### ISSUE TITLE
[BUG] Entity: Releases

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#100]
Browser: Firefox

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/76303865-548a2480-62ba-11ea-975a-b8fca5641ea5.png)

**Comment by lorenzobruni** [comment]
@liamie 
This Warning is generated by an unusual Bootstrap CSS property.
As part of this Issue, Bootstrap has been upgraded to v4.5.2
The warning persist despite the upgrade.

Can you please run an overall check to verify the upgraded version of Bootstrap is not causing issues.

Thanks

**Comment by lorenzobruni** [comment]
@damienderoistecso and @CHanamy57 
FYI, we are now targeting **Bootstrap 4.5.2**
