### ISSUE TITLE
[BUG] "Exceptional" in comparison report appearing incorrectly in chrome

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#103]
Go to release and comparison report on the left hand column.

How it appears in chrome (lowercase and brackets)
![image](https://user-images.githubusercontent.com/55874862/76418923-655c9800-6397-11ea-90a3-29593a68e1ca.png)

Appears correct I believe in firefox
![image](https://user-images.githubusercontent.com/55874862/76419006-8ae9a180-6397-11ea-8d25-d5d0e5523809.png)

**Comment by liamie** [comment]
Similar in Add Request Screen
Chrome
![image](https://user-images.githubusercontent.com/55874862/76439724-baf36d80-63b4-11ea-8ba2-c49123304833.png)

Firefox seems ok
![image](https://user-images.githubusercontent.com/55874862/76439800-d9596900-63b4-11ea-9a67-7a2f97043204.png)

**Comment by damienderoistecso** [comment]
This was a caching issue. As the labels come from the language dictionary and this is a JSON file, it gets cached by the browser. Can you re-test in Chrome but after doing a hard re-load of the page first. 

@liamie ready for testing
