### ISSUE TITLE
[BUG] Safari on load of live

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#105]
Having a bit of trouble getting screenshots on the mac with the windows keyboard i'll add as I work out.
This is the first error of 2 when loading live on safari

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (app.bootstrap.guideline.css.map, line 0)

**Comment by liamie** [comment]
/Users/formsdev/Desktop/Screen Shot 2020-03-19 at 11.28.43 a.m..png

**Comment by lorenzobruni** [comment]
Apparently `app.bootstrap.guideline.css.map` is an optional file required for debugging purpose.
@damienderoistecso can you please import the .map file from the **CSOIreland/Client-API-Library** project?
https://github.com/CSOIreland/Client-API-Library/blob/master/bootstrap/4.3.1/scss/app.bootstrap.guideline.css.map

**Comment by lorenzobruni** [comment]
@liamie 
Ready to test, the warning message should be gone away :-)

**Comment by liamie** [comment]
@lorenzobruni tested with chrome Yup message cleared from Dev now. 

Still on live but I take it will change with next release.
![image](https://user-images.githubusercontent.com/55874862/77738524-e65a9700-7007-11ea-8619-55159e4aae3f.png)
