### ISSUE TITLE
[BUG] share this warning

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#107]
![image](https://user-images.githubusercontent.com/55874862/77077035-94ed4f00-69ec-11ea-93cc-4fe31aaaf54e.png)

Warning for share this in chrome

Occurs on opening main data screen in Live and Dev

**Comment by lorenzobruni** [comment]
@liamie 
We have recently reviewed the whole Cookie consent affecting the ShareThis plugin too.
The specific Warning was coming because of Cross-sire resources from ShareThis that apparently have bene fixed?

Can you Please confirm if this does not happen anylonger? Thanks

**Comment by lorenzobruni** [comment]
> @liamie
> We have recently reviewed the whole Cookie consent affecting the ShareThis plugin too.
> The specific Warning was coming because of Cross-sire resources from ShareThis that apparently have bene fixed?
> 
> Can you Please confirm if this does not happen anylonger? Thanks

This was under the Issue #222

**Comment by liamie** [comment]
This warning appears to have been cleared
