### ISSUE TITLE
[BUG] Clicking on any breadcrumb returns you to a page breadcrumbed with home only

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#109]
**Describe the bug**
On live clicking on any breadcrumb returns to a page bread crumbed with home only.

Breadcrumb end points links return to pages that are not consistently bread-crumbed.

Should it be only clicking "Home" returns to home other points should goto/stay on those screens.  

eg
Home - clicking here returns home
Census 2016 - unclickable
Profile 2 - Population Distribution and Movements - clicking here also returns home

As per WCAG the navigation breadcrumb should reflect the current location

**Comment by lorenzobruni** [comment]
@damienderoistecso 
FYI, this is the known & missing feature for having the breadcrumb for Products.

**Comment by damienderoistecso** [comment]
Fixed in Dev

@liamie can you test

**Comment by liamie** [comment]
The clicking on breadcrumb seems to have been resolved and does not return to home.
Some of the breadcrumbs still inconsistent with  their menu locations as per issue #141
