### ISSUE TITLE
[BUG]Safari "No Results" on every filter in a data table

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#112]
In Safari on Live
All the filters lists of statistic, year and classifications etc. have "No Results" at the top of the list in addition to the actual data for the filters as appears in chrome.

here's how they appear in Chrome
![image](https://user-images.githubusercontent.com/55874862/77411930-11997800-6db5-11ea-8623-13aa4402c576.png)
but in Safari "No Results" is at the top of each list also

**Comment by damienderoistecso** [comment]
Tested by @lorenzobruni on safari. Test passed.
