### ISSUE TITLE
[ENHANCEMENT] Implement new query schema for ReadDataset and ReadPreDataset

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#113]
A query schema has been created for querying and data. This must be implemented in the client and server and fully documented

**Comment by damienderoistecso** [comment]
Updated client side to send new query schema

@JohnPCarroll @liamie ready for testing

**Comment by neilfromcork** [comment]
Updated server side

**Comment by lorenzobruni** [comment]
@liamie and @JohnPCarroll please test liaising with @damienderoistecso .

**Comment by liamie** [comment]
Data locations in data and release tables seem to be correct.
