### ISSUE TITLE
[BUG] Sync validation for build/create between server and client

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#115]
**Describe the bug**
Some things that were being validated on the server we not being validated on the client

STATISTIC (code) , Classification Code and Frequency code can't be the same because there are columns in the csv that only contain those as headings

These items can't be called "value" or "unit" for the same reason as above.

Above rules implemented on the client side.

Classification variable order must be the same for all languages. Implemented on the client side.

**Additional context**
@JohnPCarroll @liamie When testing, try and enter a classification with a code of "UNIT", or "CODE", or "VALUE". You should get an error.

 Try to create a classification across two languages where the variables are the same, but the order is different. This should produce an error.

**Comment by liamie** [comment]
@damienderoistecso In build when entering classification code of "UNIT", "unit", "CODE", "code", "VALUE" or "value" they can be entered in the add classifications section the validation test only seems to be done when the "Create" button is pressed further down, is this correct?

**Comment by liamie** [comment]
@damienderoistecso 
![image](https://user-images.githubusercontent.com/55874862/77890588-a2fe6380-7267-11ea-9fa6-5464be61d0be.png)

Classification Code seems to be detecting against STATISTIC LABEL in properties of build not STATISTIC CODE in Statistic section is this correct.

**Comment by liamie** [comment]
@damienderoistecso
Allows different order for variables no error created for below.
english
![image](https://user-images.githubusercontent.com/55874862/77895212-58ccb080-726e-11ea-89c8-90b5165d48f3.png)
irish
![image](https://user-images.githubusercontent.com/55874862/77895506-cd075400-726e-11ea-98bf-b75e90d47129.png)

**Comment by neilfromcork** [comment]
Classification / variable order should be ok now - retest

**Comment by damienderoistecso** [comment]
@JohnPCarroll @liamie committed and ready for testing

**Comment by liamie** [comment]
Variable order now detecting correctly

**Comment by liamie** [comment]
@damienderoistecso Classification Code seems to be detecting against STATISTIC LABEL in properties of build not STATISTIC CODE in Statistic section is this correct?
Currently you can still have a Classification Code equal to Statistic Code. eg matrix 

Also you can still create a classification with "CODE" should this not produce error like "VALUE" and "UNIT"

**Comment by neilfromcork** [comment]
@liamie, @damienderoistecso   So, if you have, for example two statistics - S01 and S02,  it should not be a problem for either of those to be the same as a classification code because they exist at different levels. It would be a problem if any of the dimension codes or values were the same, or if any of the item values/codes were the same in a given dimension. Also, the VALUE/UNIT thing is to avoid conflicting headers in CSV files. CODE does not cause a problem.

**Comment by liamie** [comment]
@damienderoistecso, @neilfromcork Then in light of neils clarification build/create seems to be correct.
