### ISSUE TITLE
[BUG] Code Toggle cannot be tabbed to or adjusted with Keyboard

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#116]
Tabbing seems to skip by this element in general and even after using it with mouse doesn't seem to be functional with keyboard

![image](https://user-images.githubusercontent.com/55874862/77649958-9d043c00-6f62-11ea-9a5f-a38f780e6917.png)

**Additional context**
This keyboard functionality is a requirement for Accessibility

**Comment by liamie** [comment]
Similar for official statistics toggle in build
![image](https://user-images.githubusercontent.com/55874862/77664911-c75ff480-6f76-11ea-95cb-6aa77bdb768e.png)

**Comment by liamie** [comment]
Similar in release workflow
![image](https://user-images.githubusercontent.com/55874862/77739732-ee1b3b00-7009-11ea-8a4f-0c96d722926c.png)

**Comment by liamie** [comment]
also seems to lead to ambiguity and obfuscation when trying to print this type of toggle
![image](https://user-images.githubusercontent.com/55874862/78664554-29502080-78cc-11ea-974f-6fe6301485cd.png)

**Comment by liamie** [comment]
These toggles are prolific in the charts section also. This makes keyboard tabbing for options in charts impossible, mouse only access for options.
![image](https://user-images.githubusercontent.com/55874862/89395310-0fe9a480-d705-11ea-9142-b991a1aa933d.png)

**Comment by lorenzobruni** [comment]
@liamie 
The fix to this issue has been already posted into the original GitHub project.
I have asked to commit and issue a new release for this fix... let's see.
https://github.com/minhur/bootstrap-toggle/issues/125

If not committed shortly we will have to fork the project ourself.
We stay tuned.
Cheers

**Comment by lorenzobruni** [comment]
I have forked the https://github.com/CSOIreland/bootstrap-toggle repository to implement this fix.

The tootles are now working with tab-keys and they can also be toggles with space/enter keys.
Can you please retest?

Thanks

**Comment by lorenzobruni** [comment]
FYI @liamie

**Comment by liamie** [comment]
This issue is mostly fixed now. 
Tabbing can pick up the toggle option and space can change the toggle value.
Printing displays the option chosen. 
However currently Analytical choice produces a success Modal which disrupts the focus. Can the focus be returned to the toggle on close of the success modal?
Also can there be a distinctive highlight around the toggle when selected it's currently hard to tell when you are on it.

**Comment by lorenzobruni** [comment]
> Also can there be a distinctive highlight around the toggle when selected it's currently hard to tell when you are on it.

This is there already... but the button is surrounded by the toggle frame, hence is not very visible... an example below.
![image](https://user-images.githubusercontent.com/53212047/95751792-0184af80-0c97-11eb-8e1b-c4aa624e97fd.png)
![image](https://user-images.githubusercontent.com/53212047/95751844-119c8f00-0c97-11eb-9e9c-f73b887c4850.png)

> However currently Analytical choice produces a success Modal which disrupts the focus. Can the focus be returned to the toggle on close of the success modal?

Sorry I didn't get this one... can you attach a screenshot or rephrase? Thanks

**Comment by liamie** [comment]
> > Also can there be a distinctive highlight around the toggle when selected it's currently hard to tell when you are on it.
> 
> This is there already... but the button is surrounded by the toggle frame, hence is not very visible... an example below.
> ![image](https://user-images.githubusercontent.com/53212047/95751792-0184af80-0c97-11eb-8e1b-c4aa624e97fd.png)
> ![image](https://user-images.githubusercontent.com/53212047/95751844-119c8f00-0c97-11eb-9e9c-f73b887c4850.png)
> 
Ok if the toggle cant be made more distinctive, like group below in the images, because of nesting in the frame can the text of the toggle be emphasised or something similar to provide a visual cue.
This is group selected not toggle
![image](https://user-images.githubusercontent.com/55874862/95754647-401c6900-0c9b-11eb-9329-d52f03c51123.png)
This is toggle selected
![image](https://user-images.githubusercontent.com/55874862/95754980-b4570c80-0c9b-11eb-82d3-9a75c0484875.png)

 
> > However currently Analytical choice produces a success Modal which disrupts the focus. Can the focus be returned to the toggle on close of the success modal?
> 
> Sorry I didn't get this one... can you attach a screenshot or rephrase? Thanks
When Analytical toggle selection is switched
![image](https://user-images.githubusercontent.com/55874862/95753844-17e03a80-0c9a-11eb-8bdf-94774226ef6c.png)
appears but when this is closed the focus doesn't return to the toggle to proceed from there.
This may be separate issue of returning focus to where dialog screens are launched from once closed unless there is an action resulting from the choice/close in the dialog.

**Comment by lorenzobruni** [comment]
@liamie , thanks!
I agree we should address how the focus look because is almost imperceptible. 
I will look into the return of the focus...

@damienderoistecso,
can you please inspect the CSS have have a look to how we can improve the visual effect of a focused toggle?
Thanks

**Comment by damienderoistecso** [comment]
@lorenzobruni possible issue with forked library. When we toggle now, error in console

![image](https://user-images.githubusercontent.com/53211688/95888053-84ca0200-0d78-11eb-9c68-744f8264928d.png)

**Comment by lorenzobruni** [comment]
I have issued a new release of the bootstrap-toggle with both the console error fixed and the focus/blur enhanced.
The slider changes color then on focus/blur.
![image](https://user-images.githubusercontent.com/53212047/95922355-0470c480-0dab-11eb-811c-b7fcfb34b29c.png)
![image](https://user-images.githubusercontent.com/53212047/95922376-0dfa2c80-0dab-11eb-96b7-d2da7dd7b40a.png)

Unfortunately the success modal has no callback function (currently) so we cannot bring the focus back to anything.
Perhaps something to consider in the future?
Do you want to create an enhancement under the Client API repo to implement a callback function for the api.modal.success ?

Please test and let me know if the 2 items above are fixed.

Thanks!
