### ISSUE TITLE
[ENHANCEMENT] Validation to limit the number of datapoints in build (create/update) and upload

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#117]
Allow the system to configure a maximum number of datapoints allowed in a dataset

**Comment by neilfromcork** [comment]
Ready for test. Limit set to 1000 for test purposes only

**Comment by damienderoistecso** [comment]
Applied to client side for both create and update

**Comment by damienderoistecso** [comment]
@liamie @JohnPCarroll committed and ready for testing

**Comment by neilfromcork** [comment]
Message adjusted to return (a) the number of cells the user is trying to upload and (b) the current maximum number of cells allowed. @damienderoistecso

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/78342246-e111c500-7590-11ea-81c2-3883cf23b8bc.png)

is the error I get on build>create when trying to add a file with over 1000 data points

**Comment by damienderoistecso** [comment]
@liamie can you do a final check on this from your side and mark tested if it is OK. Thanks

**Comment by liamie** [comment]
This seems correct now.
