### ISSUE TITLE
[BUG] The Update feature of Build times-out if I try to add any large files.

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#118]
The Update feature of Build times-out if I try to add any large files. @lorenzobruni 

As the files are large, they take some time, but the system times-out after three minutes.
I brought the px file into update. I then selected Update > PX 2013.
After three minutes I received a Network Error pop-up message.

**Comment by lorenzobruni** [comment]
@colmanflynn this is now fixed.
The default timeout of 3 minutes was incorrectly applied instead of the `app.config.upload.timeout`.
It will be available across all environments form next release.

**Comment by lorenzobruni** [comment]
Test passed with @colmanflynn
