### ISSUE TITLE
[ENHANCEMENT]  XLSX default display settings

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#119]
Amend XLSX output as follows:
1. Sheets are defaulted to landscape view
2. Data sheet column widths are preset to fit the length of the text in the cell

**Comment by lorenzobruni** [comment]
@JohnPCarroll I take this testing

**Comment by lorenzobruni** [comment]
[FAA01.20200409T120431.xlsx](https://github.com/CSOIreland/PxStat/files/4455987/FAA01.20200409T120431.xlsx)
XLSX file for reference.
No borders for any cell except the headings.
No referencing extra cells outside of the context.

**Comment by neilfromcork** [comment]
Completed in DEV - for test

**Comment by lorenzobruni** [comment]
@neilfromcork the print works fine now with the non-relevant cells not set, thanks.

By the way, is it possible to apply the same heading style to the adjacent cell-column and to bold the heading to the below cell-rows?

Thanks

![image](https://user-images.githubusercontent.com/53212047/79201736-6a968200-7e30-11ea-8159-6182d40f272e.png)

**Comment by neilfromcork** [comment]
Style settings as outlined in previous comment implemented

**Comment by lorenzobruni** [comment]
Test passed
