### ISSUE TITLE
[ENHANCEMENT] Move API result messaging from server to client

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#121]
**Describe the solution you'd like**
Results from the server that contain a message are not displayed by the client. Instead, a result keyword is agreed and the messaging is defined in the client and is language specific

Example of this is response from "PxStat.Data.Matrix_API.Create"

**Comment by lorenzobruni** [comment]
Server side messaging is dynamically built and therefore too complex or not relevant for the Client side to emulate the same.
