### ISSUE TITLE
[ENHANCEMENT] Allow power users and admins to have a 1 step workflow

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#122]
**Describe the solution you'd like**
Give power users and admins the ability to have a one step workflow where a WIP matrix and be signed off without the need for a request and response.

**Comment by neilfromcork** [comment]
Server side work complete and tested. Will eventually move configuration to line up with #123

**Comment by damienderoistecso** [comment]
@neilfromcork As discussed, can you implement the logic that if a moderator with approval access initiates a request, then this request goes straight for sign-off with auto-response. I will implement on client side

**Comment by neilfromcork** [comment]
Server side changes published. Includes _:"if a moderator with approval access initiates a request, then this request goes straight for sign-off with auto-response. I will implement on client side"_ . Ready for test

**Comment by damienderoistecso** [comment]
Client side changes committed 

@JohnPCarroll @liamie ready for **### TESTING**

**Comment by damienderoistecso** [comment]
**Test 1: No permissions for any user type.** 

Request Step
Moderator - Editor
Expected result: Move to awaiting response

- Publish
- Update properties
- Rollback
- Delete

Moderator - Approver
Expected result: Move to awaiting sign-off

- Publish
- Update properties
- Rollback
- Delete

Power User
Expected result: Move to awaiting response

- Publish
- Update properties
- Rollback
- Delete

Administrator
Expected result: Move to awaiting response

- Publish
- Update properties
- Rollback
- Delete


Response Step

Moderator - Editor
Expected result: n/a

- Publish
- Update properties
- Rollback
- Delete

Moderator - Approver
Expected result: Move to awaiting sign-off

- Publish
- Update properties
- Rollback
- Delete

Power User
Expected result: move to awaiting sign-off

- Publish
- Update properties
- Rollback
- Delete

Administrator
Expected result: move to awaiting sign-off

- Publish
- Update properties
- Rollback
- Delete

**Comment by liamie** [comment]
As Admin user the request publish step is going straight to approved signoff and publishing
![image](https://user-images.githubusercontent.com/55874862/80350462-aab22780-8868-11ea-9542-f386d47950ee.png)
under current configuration this is incorrect I believe

**Comment by damienderoistecso** [comment]
@liamie Changes to global config got overwritten by server publish. I have updated the global config again and ran the reload method so you should be able to run test 1 again now.

**Comment by liamie** [comment]
Have run test one again for admin after updating client again.
https://dev-data.cso.ie/millarl/2.3.0/#

Still forcing one step publishing not going through the steps as implied by current expected results

**Comment by JohnPCarroll** [comment]
I imported a PX File and updated the navigation as required. I went to Publish and approved. This step goes directly to sign off and the table is Pending Live E1002.  As an Administrator Test 1 should not have let me do this. Am i correct or not ? Please note the First message the sentence is duplicated.

**Comment by damienderoistecso** [comment]
Removed duplicate auto response warning

**Comment by liamie** [comment]
Same occurring as power user straight to publish/pending publish
![image](https://user-images.githubusercontent.com/55874862/80358801-de934a00-8874-11ea-8c54-09a1fa9608ed.png)

**Comment by neilfromcork** [comment]
Fix put in place - config files need to exist independently of IIS while still being readable by IIS. Ready for retest @damienderoistecso @JohnPCarroll @liamie

**Comment by JohnPCarroll** [comment]
loaded new table E1003 as administrator and selected publish. Selected Add Button and the following error occurred -->An unexpected error has occurred. Please seek technical support.

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/80385985-aef93780-889e-11ea-9fcc-d4fa1714dc9e.png)
 occurs now after updating.
Also message still said it would bypass response and sign-off in the request window surely it should only say this if in deed it is going to be bypassed and so not for current scenario.

**Comment by neilfromcork** [comment]
Unexpected error problem fixed. Ready for test. @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Power user issue. Table E1002 live version. Added another version and proceeded testing the delete option. At sign off stage it deleted the new version but made the live version historical.

**Comment by neilfromcork** [comment]
@JohnPCarroll - As far as I understand, that is what is supposed to happen with a delete. Otherwise you would use a rollback.

**Comment by JohnPCarroll** [comment]
this is what happens with power user.. Version 1.1 is deleted correctly and version 1.0 is made historical incorrectly. It should remain live
![image](https://user-images.githubusercontent.com/44975474/80468741-7f4a3e00-8937-11ea-9e9b-1dc7e69fa767.png)

**Comment by liamie** [comment]
I found the steps went through correctly for power user response sign off etc. Should any Issues with how rollback/live etc. is handled as a result not be a separate issue otherwise we are going to snowball.

**Comment by neilfromcork** [comment]
Problem with DELETE resolved. Ready for retest. @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Power user issue with rollback. I had version 2.0. live and 1.0 historical.  Rollback 2.0 and 1.0 is now live correctly. But version 2.0 is now 1.1 Work in progress and you cannot select any workflow request. It is not on the Work in Progress to the right. Should it be displayed as per screen shot ?
![image](https://user-images.githubusercontent.com/44975474/80476890-f1745000-8942-11ea-9efd-ff31ec5c9456.png)

**Comment by liamie** [comment]
> Power user issue with rollback. I had version 2.0. live and 1.0 historical. Rollback 2.0 and 1.0 is now live correctly. But version 2.0 is now 1.1 Work in progress and you cannot select any workflow request. It is not on the Work in Progress to the right. Should it be displayed as per screen shot ?
> ![image](https://user-images.githubusercontent.com/44975474/80476890-f1745000-8942-11ea-9efd-ff31ec5c9456.png)

this is the same as I raised  issue #125 so if when resolved can be closed

**Comment by JohnPCarroll** [comment]
We appear to have reverted to auto response and sign off options for power user. Plese revert
![image](https://user-images.githubusercontent.com/44975474/80481174-dbb65900-8949-11ea-92a7-2032defd0c52.png)

**Comment by JohnPCarroll** [comment]
Power user. All Delete and Rollback issues resolved. Others options work correctly

**Comment by damienderoistecso** [comment]
- [ ] test

**Comment by JohnPCarroll** [comment]
Moderator - Editor  and approver both work for Relevant options - Publish, Delete, Update Properties and Rollback

**Comment by liamie** [comment]
Moderator - Editor and approver seem correct for - Publish, Delete, Update Properties and Rollback at both stages.

**Comment by damienderoistecso** [comment]
Test 1 passed

**Comment by damienderoistecso** [comment]
[Test2ModeratorApproverGrainne.docx](https://github.com/CSOIreland/PxStat/files/4552036/Test2ModeratorApproverGrainne.docx)
[Test2ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4552037/Test2ModeratorEditorConal.docx)
[Test2PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4552038/Test2PowerUserLiam.docx)
[Test2AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4552039/Test2AdministratorJohn.docx)

Global config updated to 

```json 
"permission": {
    "workflow": {
      "autoResponse": ["MODERATOR"],
      "autoSignoff": ["MODERATOR"]
    }
  }
```

Ready for testing

**Comment by CHanamy57** [comment]
@neilfromcork Moderator Editor request for publish received the following error 
"Invalid authentication. Access denied."

**Comment by damienderoistecso** [comment]
> @neilfromcork Moderator Editor request for publish received the following error
> "Invalid authentication. Access denied."

This only happens for Moderator Editor. Moderator approver works as expected

**Comment by JohnPCarroll** [comment]
Administrator Passed. Question  - Once a Live Release is deleted it becomes Historical ?

**Comment by liamie** [comment]
Power user steps passed correctly
I too am a bit confused about rollback being a revert rather than republish

**Comment by neilfromcork** [comment]
[Signoff Business rules.txt](https://github.com/CSOIreland/PxStat/files/4552744/Signoff.Business.rules.txt)

**Comment by damienderoistecso** [comment]
Following initial testing, new configuration rules required. Server and client both re-factored and deployed now. Will re-start testing at new Test 1. Will create Test 1 soon and make available.

**Comment by damienderoistecso** [comment]
New Test 1: No fast tracking of workflow

Moderators can no longer be allowed fast track beyond the response step. 

[Test1PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4557963/Test1PowerUserLiam.docx)
[Test1AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4557964/Test1AdministratorJohn.docx)
[Test1ModeratorApproverGrainne.docx](https://github.com/CSOIreland/PxStat/files/4557965/Test1ModeratorApproverGrainne.docx)
[Test1ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4557967/Test1ModeratorEditorConal.docx)

```json 
"fastrack": {
      "response": {
        "approver": false,
        "poweruser": false,
        "administrator": false
      },

      "signoff": {
        "poweruser": false,
        "administrator": false
      }
    }
```

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/80709325-04268a80-8ae5-11ea-937a-2bc1600239a8.png)

getting this when try to publish

**Comment by neilfromcork** [comment]
@liamie - problem found and fixed. Can you try again?

**Comment by liamie** [comment]
> > ![image](https://user-images.githubusercontent.com/55874862/80709325-04268a80-8ae5-11ea-937a-2bc1600239a8.png)
> > getting this when try to publish
> 
> At which step did this happen Liam?

when try to publish or delete after clicking add on the request screen

**Comment by neilfromcork** [comment]
@liamie - problem found and fixed. Can you try again?

**Comment by JohnPCarroll** [comment]
Administrator Passed for Test 1
[Test1AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4558631/Test1AdministratorJohn.docx)

**Comment by liamie** [comment]
Power User Passed for Test 1
[Test1PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4558732/Test1PowerUserLiam.docx)

**Comment by grainnemooney** [comment]
Moderator Approver passed for Test 1
Typo in Rollback request message
[Test1ModeratorApproverGrainne.docx](https://github.com/CSOIreland/PxStat/files/4558826/Test1ModeratorApproverGrainne.docx)

**Comment by CHanamy57** [comment]
Moderator Editor passed for Test 1
[Test1ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4563155/Test1ModeratorEditorConal.docx)

**Comment by damienderoistecso** [comment]
Test 2

All users given permission for fastrack response, except moderator-editor who is Conal

[Test2PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4563150/Test2PowerUserLiam.docx)
[Test2AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4563151/Test2AdministratorJohn.docx)
[Test2ModeratorApproverGrainne.docx](https://github.com/CSOIreland/PxStat/files/4563152/Test2ModeratorApproverGrainne.docx)
[Test2ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4563153/Test2ModeratorEditorConal.docx)

```json 
"fastrack": {
      "response": {
        "approver": true,
        "poweruser": true,
        "administrator": true
      },

      "signoff": {
        "poweruser": false,
        "administrator": false
      }
    }
```

**Comment by liamie** [comment]
Power user getting this message at request all actions 
![image](https://user-images.githubusercontent.com/55874862/80799007-9db17300-8b9d-11ea-8594-a5927c33afae.png)
should be the response auto approve message. Action occurs correctly though still goes to awaiting sign off

**Comment by grainnemooney** [comment]
moderator getting same message
![image](https://user-images.githubusercontent.com/51713130/80800877-9476d500-8ba2-11ea-9b2c-bf00e80a7ca3.png)

**Comment by grainnemooney** [comment]
I found the error damien
![image](https://user-images.githubusercontent.com/51713130/80808055-95196680-8bb6-11ea-97bd-d1c07fc8786c.png)

**Comment by CHanamy57** [comment]
Moderator Editor passed for Test 2
- no modal error
[Test2ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4564313/Test2ModeratorEditorConal.docx)

**Comment by damienderoistecso** [comment]
> I found the error damien
> ![image](https://user-images.githubusercontent.com/51713130/80808055-95196680-8bb6-11ea-97bd-d1c07fc8786c.png)

Updated in client now and committed

**Comment by damienderoistecso** [comment]
> moderator getting same message
> ![image](https://user-images.githubusercontent.com/51713130/80800877-9476d500-8ba2-11ea-9b2c-bf00e80a7ca3.png)

Fixed in client and committed

**Comment by grainnemooney** [comment]
Moderator Approver passed for test 2
[Test2ModeratorApproverGrainne (1).docx](https://github.com/CSOIreland/PxStat/files/4564798/Test2ModeratorApproverGrainne.1.docx)

**Comment by liamie** [comment]
Power user tests passed correctly test 2
[Test2PowerUserLiam (1).docx](https://github.com/CSOIreland/PxStat/files/4564809/Test2PowerUserLiam.1.docx)

**Comment by liamie** [comment]
Admin tests passed correctly test 2

**Comment by damienderoistecso** [comment]
All Test 2 completed successfully. Will prepare Test 3 next

**Comment by damienderoistecso** [comment]
Test 3
[Test3PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4579769/Test3PowerUserLiam.docx)
[Test3AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4579770/Test3AdministratorJohn.docx)
[Test2ModeratorApproverGrainne.docx](https://github.com/CSOIreland/PxStat/files/4579771/Test2ModeratorApproverGrainne.docx)
[Test3ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4579772/Test3ModeratorEditorConal.docx)

```json 
"fastrack": {
            "response": {
                "approver": false,
                "poweruser": false,
                "administrator": false
            },
            "signoff": {
                "poweruser": true,
                "administrator": true
            }
        }
```

Test 3 ready. Don't forget to hard re-load browser. No need to update SVN

**Comment by JohnPCarroll** [comment]
Went to approve response for B0105GM and the following message appeared
![image](https://user-images.githubusercontent.com/44975474/81052105-ca75cb00-8eba-11ea-9687-fb27a3a59cdd.png)

**Comment by CHanamy57** [comment]
Moderator Editor passed for test 3
[Test3ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4580903/Test3ModeratorEditorConal.docx)

**Comment by JohnPCarroll** [comment]
Administrator test 3. Part 1 loaded up table  A0201 and set navigation. Auto sign off failed 
![image](https://user-images.githubusercontent.com/44975474/81075931-e8efbc80-8ee2-11ea-9382-a77fac499ac4.png)

**Comment by grainnemooney** [comment]
Moderator Approver Test 3
Published workflow request successfully approved by administrator however bypassed Awaiting Sign Off/Reject step straight to live

**Comment by neilfromcork** [comment]
@JohnPCarroll - Issue found. Please retest.

**Comment by liamie** [comment]
Test 3 When a Power User does a request the message is 
![image](https://user-images.githubusercontent.com/55874862/81159546-f8bdde00-8f80-11ea-8b42-a9b6c5f4993d.png)
I think there should be no message at the request step as we do not know if the same user is going to be doing the response and so we don't know if whoever is doing it will have auto sign off privilege. I think this message should only appear in request if the user also has auto response privilege and so all steps will actually be skipped.

**Comment by grainnemooney** [comment]
Test 3 When Moderator Approver adds a publishing request message says 
![image](https://user-images.githubusercontent.com/51713130/81162013-6ddee280-8f84-11ea-83dd-44b1ca11bd9b.png)

**Comment by liamie** [comment]
Delete of a pending live causes loading hang after sign off step.
![image](https://user-images.githubusercontent.com/55874862/81167792-bea70900-8f8d-11ea-9ea9-2b9b9290fd15.png)
When I delete a pending live the screen switches and stays on loading as if it doesn't know where to default back to.

**Comment by grainnemooney** [comment]
Moderator Approver passed for test 3
[Test3ModeratorApproverGrainne (3).docx](https://github.com/CSOIreland/PxStat/files/4586290/Test3ModeratorApproverGrainne.3.docx)

**Comment by JohnPCarroll** [comment]
Administrator restarted but still not correct based on messages. I loaded tables and tested the Publish and delete options.
1. Publish
![image](https://user-images.githubusercontent.com/44975474/81174978-af7a8800-8f9a-11ea-89bb-52586b3470a6.png)

The message on screen for Add Request is not reflected in the process as it goes to awaiting response

2. Delete 

![image](https://user-images.githubusercontent.com/44975474/81175137-e94b8e80-8f9a-11ea-8687-babf5e4ac268.png)

The message on screen for Add Request is not reflected in the process as it goes to awaiting response.
Hangs when approved in Awaiting response

**Comment by JohnPCarroll** [comment]
Administrator restarted but still not correct based on messages. I loaded tables and tested the Update Properties and Rollback options. The same issues exist as with the Publish and delete options
![image](https://user-images.githubusercontent.com/44975474/81185662-c5dc1000-8fa9-11ea-8618-8583b670a0f9.png)

Rollback Option
Workflow request -  goes to awaiting response

![image](https://user-images.githubusercontent.com/44975474/81185816-f91e9f00-8fa9-11ea-8c6d-d8447d588641.png)

![image](https://user-images.githubusercontent.com/44975474/81185882-0b004200-8faa-11ea-8032-d96d3ecc899e.png)

**Comment by JohnPCarroll** [comment]
Test 3 for the Administrator is a failure. The process and the messages on the pages do not match. Please see attached completed test plan
[Test3AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4587212/Test3AdministratorJohn.docx)

**Comment by liamie** [comment]
Power User  Test 3 Failed completed test plan attached
[Test3PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4592170/Test3PowerUserLiam.docx)

**Comment by damienderoistecso** [comment]
Updated client to sort messages. Re-test of test 3 required by all user types

**Comment by JohnPCarroll** [comment]
Administrator Testing. An issue exists when you delete or rollback. The Application hangs.
[Test3AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4593100/Test3AdministratorJohn.docx)

**Comment by grainnemooney** [comment]
Moderator Approver passed Test 3 retest
[Test3ModeratorApproverGrainne (3).docx](https://github.com/CSOIreland/PxStat/files/4593165/Test3ModeratorApproverGrainne.3.docx)

**Comment by neilfromcork** [comment]
I can't replicate the hang issue on Delete, either on the back-end or the client.

**Comment by CHanamy57** [comment]
Moderator Editor passed for Test 3 Retest
[Test3ModeratorEditorConal - retest.docx](https://github.com/CSOIreland/PxStat/files/4593318/Test3ModeratorEditorConal.-.retest.docx)

**Comment by JohnPCarroll** [comment]
Administrator test 3 Delete  hanging. 
This is what happens
1. Select Approve in Workflow Response 
2, Success message appears. Close message
3. Now the screen hangs as it is unable to refresh 
Sorry about any confusion.

The same happens for rollback

**Comment by liamie** [comment]
> Delete of a pending live causes loading hang after sign off step.
> ![image](https://user-images.githubusercontent.com/55874862/81167792-bea70900-8f8d-11ea-9ea9-2b9b9290fd15.png)
> When I delete a pending live the screen switches and stays on loading as if it doesn't know where to default back to.

Trying to rollback hangs in a similar manner.

Also when try a rollback of a live with a pending live in the queue the roll back request goes through but the option is still available to make a request not response however this second request if try again produces the following error
![image](https://user-images.githubusercontent.com/55874862/81309377-c8f30100-907a-11ea-9cbc-00a37f71b33d.png)
[Test3PowerUserLiam (2).docx](https://github.com/CSOIreland/PxStat/files/4593714/Test3PowerUserLiam.2.docx)


Test3Power User Fail under certain conditions as described above

**Comment by damienderoistecso** [comment]
[Test4ModeratorApproverGrainne.docx](https://github.com/CSOIreland/PxStat/files/4599061/Test4ModeratorApproverGrainne.docx)
[Test4ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4599062/Test4ModeratorEditorConal.docx)
[Test4PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4599063/Test4PowerUserLiam.docx)
[Test4AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4599064/Test4AdministratorJohn.docx)

```json 
"fastrack": {
            "response": {
                "approver": true,
                "poweruser": true,
                "administrator": true
            },
            "signoff": {
                "poweruser": true,
                "administrator": true
            }
        }
```

**Comment by liamie** [comment]
Still hangs on Rollback in general and Delete of pending live but ignored as per instructed previous test 3.
The other test 3 issue of rollback of current live with a Pending live in queue is eliminated in this test by both the pending live and the current live seeming to be rolledback/removed automatically

Power User Test 4 Fail in scenarios listed above
[Test4PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4599299/Test4PowerUserLiam.docx)

**Comment by grainnemooney** [comment]
Moderator Approver passed for Test 4
[Test4ModeratorApproverGrainne.docx](https://github.com/CSOIreland/PxStat/files/4599493/Test4ModeratorApproverGrainne.docx)

**Comment by CHanamy57** [comment]
Moderator Editor passed for Test  4 
[Test4ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4599627/Test4ModeratorEditorConal.docx)

**Comment by liamie** [comment]
Return to Test 3 
The main rollback and delete issues that were resulting in hanging now return
![image](https://user-images.githubusercontent.com/55874862/81559677-be40b080-9387-11ea-9510-2c6a5b94382d.png)
which seems appropriate
However the other error of the workflow being disrupted if try to rollback a live with a pending live queued is still occurring. Not going to response and if try to redo error says a request already exists
![image](https://user-images.githubusercontent.com/55874862/81559922-42933380-9388-11ea-9ab7-1a2f0651613f.png)

**Comment by liamie** [comment]
Test 3 PowerUser All passed correct now issues cleared.

**Comment by JohnPCarroll** [comment]
Administrator Tests 4. Tested Response step. Other steps not requested for testing but are available as tables exist in awaiting response and sign off areas. 
Only one issue in relation to deletion and rollback. The following message appears. is this correct ?
![image](https://user-images.githubusercontent.com/44975474/81666474-fd2f3e80-9439-11ea-9adc-bfd12e452e48.png)

Test results
[Test4AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4614586/Test4AdministratorJohn.docx)

**Comment by damienderoistecso** [comment]
> Administrator Tests 4. Tested Response step. Other steps not requested for testing but are available as tables exist in awaiting response and sign off areas.
> Only one issue in relation to deletion and rollback. The following message appears. is this correct ?
> ![image](https://user-images.githubusercontent.com/44975474/81666474-fd2f3e80-9439-11ea-9adc-bfd12e452e48.png)
> 
> Test results
> [Test4AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4614586/Test4AdministratorJohn.docx)

Yes, this is correct as the release has been deleted as it was a WIP

**Comment by damienderoistecso** [comment]
Test 5 ready

[Test5ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4614688/Test5ModeratorEditorConal.docx)
[Test5PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4614689/Test5PowerUserLiam.docx)
[Test5AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4614690/Test5AdministratorJohn.docx)
[Test5ModeratorApproverGrainne.docx](https://github.com/CSOIreland/PxStat/files/4614691/Test5ModeratorApproverGrainne.docx)
```json 
"fastrack": {
            "response": {
                "approver": true,
                "poweruser": true,
                "administrator": false
            },
            "signoff": {
                "poweruser": true,
                "administrator": false
            }
        }
```

**Comment by liamie** [comment]
Test 5 passed for PowerUser no issues
[Test5PowerUserLiam.docx](https://github.com/CSOIreland/PxStat/files/4614938/Test5PowerUserLiam.docx)

**Comment by grainnemooney** [comment]
Test 5 passed for Moderator Approver
[Test5ModeratorApproverGrainne (1).docx](https://github.com/CSOIreland/PxStat/files/4615067/Test5ModeratorApproverGrainne.1.docx)

**Comment by CHanamy57** [comment]
Test 5 passed for Moderator Editor.
[Test5ModeratorEditorConal.docx](https://github.com/CSOIreland/PxStat/files/4615141/Test5ModeratorEditorConal.docx)

**Comment by JohnPCarroll** [comment]
Test 5 passed for Administrator
[Test5AdministratorJohn.docx](https://github.com/CSOIreland/PxStat/files/4615324/Test5AdministratorJohn.docx)
