### ISSUE TITLE
[ENHANCEMENT] Add Manage - Configuration interface

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#123]
**Describe the solution you'd like**
Build a client side interface to allow admins to update the config file which will be stored on the server.

**Comment by lorenzobruni** [comment]
> **Describe the solution you'd like**
> Build a client side interface to allow admins to update the config file which will be stored on the server.

This issue covers the implementation of the required Server side APIs

**Comment by lorenzobruni** [comment]
@damienderoistecso 
Start mocking up the Manage - Configuration entity interface
@neilfromcork 
Start R&D on managing JSON configuration as a static property

**Comment by lorenzobruni** [comment]
**IMPORTANT**: Do not commit this under Milestone 2.2.0
Only into next iteration.

**Comment by lorenzobruni** [comment]
Notes about required APIs:

* Read, to return the JSON configuration
* Update, to amend the JSON configuration

By Admin privilege only

**Comment by neilfromcork** [comment]
Configuration refactored on the server. New config files config.server.json and config.global.json. New Refresh API to allow changes in files to be implemented on the server.

**Comment by CHanamy57** [comment]
Reload button added. Config API Refresh integrated. Successful reload modal added.

**Comment by damienderoistecso** [comment]
Updated search dropdown to translate client. global & server strings

@JohnPCarroll @liamie ready for test

**Comment by damienderoistecso** [comment]
I have added another property to the global config to control access to the build for moderators


```json 
"build": {
        "create": {
            "moderator": false
        },
        "update": {
            "moderator": true
        },
        "import": {
            "moderator": true
        }
    }
```

@neilfromcork for the following API's can you first check if the user has access based on the above settings

"PxStat.Build.Build_API.Create"
"PxStat.Build.Build_API.Update"
"PxStat.Data.Matrix_API.Create"

**Comment by neilfromcork** [comment]
Global config change complete - ready for test @damienderoistecso

**Comment by damienderoistecso** [comment]
@grainnemooney @CHanamy57 @liamie @JohnPCarroll 
Ready for testing

**Comment by damienderoistecso** [comment]
@CHanamy57 Can you make some small changes to this entity.

In the search modal, put source before type in the order of rows

For the reload button, use the confirm method to ask the user to confirm that they wish to reload the config. If they confirm, call the reload API and then re-load the entire application in the browser to get the latest config

**Comment by CHanamy57** [comment]
Source put before Type in Search modal.
Confirm method & modal added to reload button. 
Reload API call on Confirm & application reload added to Hide event on reload Success modal.

**Comment by liamie** [comment]
Seems correct as described

**Comment by JohnPCarroll** [comment]
Appears to do as described
