### ISSUE TITLE
[BUG] [uploaded-by] looks out of place

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#124]
In Release> Source section the "uploaded-by" is appearing with square brackets around it [ ] as per image
![image](https://user-images.githubusercontent.com/55874862/80462323-7143ef80-892e-11ea-9f07-367748b890fd.png)

Should this be appearing as a more readable string like the rest of the emboldened keywords?

**Comment by damienderoistecso** [comment]
Updated to 'Imported by'
