### ISSUE TITLE
[BUG] Rollback creates orphaned work in progress file

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#125]
if there is a version 1.0 and 2.0 and work in progress 2.1 of a live table

then 2.0 is rollback to version 1.0

the work in progress 2.1 becomes 1.1 but cannot be deleted or published no request option available

Subsequent imports do not overwrite the work in progress 1.1 instead they start an additional 1.2 and these can be progressed but 1.1 remains

![image](https://user-images.githubusercontent.com/55874862/80473195-b28fcb80-893d-11ea-8b81-34bbb02d9017.png)

![image](https://user-images.githubusercontent.com/55874862/80473507-26ca6f00-893e-11ea-8514-36277e6700bc.png)

tested with power user

**Comment by damienderoistecso** [comment]
@neilfromcork Can you see if this is still the case

**Comment by damienderoistecso** [comment]
@liamie ready for re-testing

**Comment by liamie** [comment]
The work in progress is now also deleted as part of the rollback this has resolved the orphan situation so test passed.
