### ISSUE TITLE
[BUG] Issue displaying with Pending live Tables - Multiple entries exist if many changes made

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#126]
**Describe the bug**
When I made a number of changes to the Update properties the pending live shows the sme table a number of times on the RHS of the Releases page.

**Expected behavior**
The table code should only appear once

**Screenshots**
![image](https://user-images.githubusercontent.com/44975474/81153482-e0e35b80-8f7a-11ea-8a55-ad987c1497fd.png)

![image](https://user-images.githubusercontent.com/44975474/81153567-f22c6800-8f7a-11ea-9cd5-2e10abca59e9.png)

**Comment by neilfromcork** [comment]
Issue fixed. Only displays the workflow data for the actual pending live request (though this change makes the Request heading in the Pending live table a bit pointless - it will always be PUBLISH) @JohnPCarroll  for retest

**Comment by JohnPCarroll** [comment]
Test successful
