### ISSUE TITLE
[ENHANCEMENT] Create generic version of Excel functionality to allow re-use on other projects etc

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#128]
Currently the XLSX functionality is embedded in the PxStat code. This enhancement separates Excel into its own classes, to allow a small but simple list of core excel functions, e.g. creating worksheets, adding data, images, serializing etc.

**Comment by damienderoistecso** [comment]
@neilfromcork Can you confirm if this is completed.

**Comment by neilfromcork** [comment]
This is complete - ready for test

**Comment by liamie** [comment]
XLXS download appears to be unaffected by these alterations
