### ISSUE TITLE
[BUG] No text wrap on browse subject text

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#129]
**Describe the bug**
Long subjects in the browse navigation do not wrap
![image](https://user-images.githubusercontent.com/53211688/81698977-a6882b80-945e-11ea-9ec6-dd2ac2c01ec9.png)

**Comment by damienderoistecso** [comment]
Fixed in dev

@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test passed.
