### ISSUE TITLE
Data page Navigation tree overlaying Latest Releases[BUG] 

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#130]
I had PXstat open in Chrome on the Data page. I shrunk the Chrome window and the Navigation tree on the right under Browse didn't resize and overlayed the Latest Releases.
Screenshot attached
![PXStat Bug](https://user-images.githubusercontent.com/59689411/81808235-5325e400-9517-11ea-951c-7f1c59f71b47.PNG)

**Comment by damienderoistecso** [comment]
Duplicate of #129
