### ISSUE TITLE
[ENHANCEMENT] Replace our custom extra large modal with bootstrap extra large modal

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#131]
*Describe the solution you'd like**
Extra large modal now available in Bootstrap 4.3. We no longer need our custom extra large modal and can use native bootstrap one instead

Search everywhere for "modal-full" to find where we use it. Then re-factor these modals to use bootstrap extra large modal option https://getbootstrap.com/docs/4.3/components/modal/#optional-sizes

Remove custom css from app.library.css

**Comment by CHanamy57** [comment]
Custom CSS extra large Modals replaced with native Bootstrap Extra Large Modals

**Comment by JohnPCarroll** [comment]
Tested. Everything appears to be ok
