### ISSUE TITLE
[BUG] Possibility of silent failure during data load 

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#132]
Because the loading of data tables from px runs on an independent thread, any failure during this process could occur without the main application being aware of it.

**Comment by neilfromcork** [comment]
@JohnPCarroll - fix in place for this. To test this fix, just do a load of both a small and a large dataset

**Comment by neilfromcork** [comment]
@JohnPCarroll  - when testing this, make sure to check if the data has loaded actual values and not blanks

**Comment by JohnPCarroll** [comment]
Test passed. Tested Tables A0603, TEA16 and CPM13. Data appears to be correct for all. No blanks exist
