### ISSUE TITLE
[BUG] Scroll to not working on some screens

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#133]
**Describe the bug**
Scroll to does not work correctly in some environments. e.g. mobile

Investigate alternatives to $('html, body').animate({ scrollTop:

Maybe a jQuery library

https://github.com/flesler/jquery.scrollTo

**Comment by CHanamy57** [comment]
**Bug Identified**
Issue with scrollTop on mobile devices - mobile ios cannot read $('html, body') as 'html' is not treated as a DOM node in mobile browsers.

ScrollTo jQuery library seems to work well on initial tests.

**Comment by lorenzobruni** [comment]
> **Bug Identified**
> Issue with scrollTop on mobile devices - mobile ios cannot read $('html, body') as 'html' is not treated as a DOM node in mobile browsers.
> 
> ScrollTo jQuery library seems to work well on initial tests.

Unfortunately the `window.scrollto` does not provide any animation, jumping instead to the target element. This may confuse the user experience/interaction especially following the Accessibility directives. 
In this case is preferable to avoid any "hard-jump" in the page for those devices not supporting the `$('html, body')` selector.

**Comment by lorenzobruni** [comment]
The scrolling was anyway behaving incorrectly when in **Modal**.

This has been fixed by using the relative scrolling `+=` rather then scrolling to a fixed position.
Example below:

```javascript
$('modal-selector').animate({
  scrollTop:'+=' + $('selector-to-scroll-to')[0].getBoundingClientRect().top
}, 1000);
```

@damienderoistecso please catch up on this one :-)

**Comment by lorenzobruni** [comment]
Test passed

**Comment by lorenzobruni** [comment]
P.S. Apparently https://github.com/flesler/jquery.scrollTo has the same issue... https://github.com/flesler/jquery.scrollTo/issues/178
