### ISSUE TITLE
[BUG] PREVIOUS/NEXT expands beyond bounds with additional pages 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#134]
Discovered on release screen but maybe other locations also.
In the panels on the right-hand side. if the number of pages expand the Previous/Next can be pushed outside the bounds of the panel. 
![image](https://user-images.githubusercontent.com/55874862/82320893-e8b7ec80-99cb-11ea-85f1-abed26069f55.png)

**Comment by lorenzobruni** [comment]
@liamie 
I looked into it but I couldn't find a solution.. .there are simply too many rows to paginate... I'm afraid I must close this as "wont fix".. .GULP!
