### ISSUE TITLE
[BUG] Issue in release page view data option - page not fully shown only part of  

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#135]
**Describe the bug**
When you enter the Releases page for the first time, select a px file. You then select the view data option and an incorrect page heading only is displayed, The correct heading and data is then displayed. If you repeat without leaving the Releases page , the correct heading is displayed only and then the data.

**To Reproduce**
1. Go to Releases
2. Click on a px table
3. Select View data
4. See error on screen
5, Repeat to see second issue 

**Expected behavior**
Correct page heading and data to appear as one. No screen flicking

**Screenshots**

![image](https://user-images.githubusercontent.com/44975474/82430547-5c6a0000-9a85-11ea-8a2d-e99ffeb25a66.png)

**Comment by lorenzobruni** [comment]
Fixed
@JohnPCarroll can you please test, thanks

**Comment by JohnPCarroll** [comment]
Test passed
