### ISSUE TITLE
[BUG] Update report hanging

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#137]
**Describe the bug**
When you have no records in the 'Records to be updated', the table doesn't render correctly and the page hangs for the user.

**Expected behavior**
Empty datatable for 'Records to be updated' is displayed

**Comment by damienderoistecso** [comment]
Ready for testing. Test by trying to update a px file with a csv file where every record is incorrect

**Comment by JohnPCarroll** [comment]
I tried to B0103 using the CSV file from A0101 and the following error was displayed
![image](https://user-images.githubusercontent.com/44975474/82554785-7fb4ae00-9b5e-11ea-9588-dd28042ae0fb.png)
I am taking this as correct

**Comment by liamie** [comment]
It appeared correct for me when I downloaded the csv of a file changed all the entries in statistic column to something different and tried update a full table in Records to be Ignored and an empty table in 'Records to be updated'

**Comment by JohnPCarroll** [comment]
I tried to update SFA09 and it appeared to have updated incorrectly. See csv file used
I added a new time period for 2011 and then amended the csv file for loading as attached 
[SFA09.20200521T120551.data.txt](https://github.com/CSOIreland/PxStat/files/4662246/SFA09.20200521T120551.data.txt)

**Comment by JohnPCarroll** [comment]
My reflection test passed
