### ISSUE TITLE
[ENHANCEMENT] Add "Daily" as a frequency option

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#139]
*Describe the solution you'd like**
Ability to create, update and import datasets with a frequency of "Daily"

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Issues with Create
TList Should be in capitals like the other Frequency Codes
![image](https://user-images.githubusercontent.com/44975474/82993112-00a8f500-9ff8-11ea-86be-5e1bf97077db.png)

When I try to create a px file the following error occurs
![image](https://user-images.githubusercontent.com/44975474/82993428-70b77b00-9ff8-11ea-9e94-89fa7bd4ba44.png)

**Comment by damienderoistecso** [comment]
Both issues fixed

@JohnPCarroll ready for testing again

**Comment by JohnPCarroll** [comment]
Test passed. For Build Create. Update and Import options
