### ISSUE TITLE
[ENHANCEMENT] Match breadcrumbs and menus

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#141]
In general the breadcrumbs match the menu options but a few of the manage and system/configuration breadcrumbs are now at odds with their menu location. For clarity and navigation I think these should match.
Ones at odds
In Menu : Manage> Reasons
Breadcrumb: Configuration/Reasons

In Menu : Build> Import
Breadcrumb: Import 
(other build options have build in the breadcrumb)

In Menu : System>Languages
Breadcrumb: Configuration/Languages

In Menu : System>Formats
Breadcrumb: Configuration/Formats

In Menu : System>Tracing
Breadcrumb: Manage/Tracing

In Menu : System>Logging
Breadcrumb: Manage/Logging

**Comment by lorenzobruni** [comment]
@damienderoistecso 
Can we address this one together with fixing the breadcrumb for Products.

**Comment by liamie** [comment]
Breadcrumbs and menus matching.
Separate from the menus
Only things slightly out and a little confusing is the product breadcrumb being used for both individual tables and the product group page.
Since its the path to rather than the path of I'll still mark as tested as bit of a choice thing.
Should we have the individual table names as part of the breadcrumb.
