### ISSUE TITLE
[ENHANCEMENT] Investigate speeding up search 

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#142]
Currently  one subquery is currently taking 80% of the time. Investigate speeding up the search.

**Comment by JohnPCarroll** [comment]
Test passed. Search on data page much quicker to return results

**Comment by neilfromcork** [comment]
Can I warn everybody that this was a significant rewrite of the search stored procedure? We probably need to test all cases, not just speed of response. Also, when testing, watch out for cached data, so try to ensure that all searches are new.

**Comment by liamie** [comment]
If it is not to taxing on the system I think there should be some form of weighting to place exact matches on the search higher than the synonyms. Currently 'capital' has a synonym 'great' so when you search for 'capital' you get any table with 'Great Britain' also, These tables not mentioning capital just 'Great Britain' can be ranked higher than any of the financial tables that mention capital. I think we currently list by publication date (Oldest to Newest) but I could be corrected on this.

**Comment by neilfromcork** [comment]
Higher weighting now given to the search term (plus its plurals, singulars) than the synonym @liamie

**Comment by liamie** [comment]
Search coming back quickly.
If full matrix name used exact match returned correctly.
If a word is used there seems to be a direct connection with the first page results at least of matrix returned.
Without a hierarchy of importance between title, classification, period etc. it is impossible to establish which matrices should be listed higher and this would change with intent anyhow on more general terms. So will keep an eye out for strange behavior with specific terms.
