### ISSUE TITLE
[BUG] Fadas are incorrectly displaying in CSV files

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#144]
Fadas are incorrectly displaying in CSV files... but I can see they are correctly working everywhere else. (Check EY004 from Live)

**Comment by JohnPCarroll** [comment]
Test passed

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. EY004 has been replicated in DEV.

**Comment by neilfromcork** [comment]
Can I warn everybody that this was a significant rewrite of the search stored procedure? We probably need to test all cases, not just speed of response. Also, when testing, watch out for cached data, so try to ensure that all searches are new.

**Comment by neilfromcork** [comment]
Last comment deleted - wrong issue!
