### ISSUE TITLE
[BUG] Table gone live today on data.cso.ie is not on latest updated tables or on theme 

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#145]
**Describe the bug**
Table MSA02 went live today at 11 am. It does not appear on the Latest Update Tables list or the theme it is associated with that is Services/Services Index. The total number on the Services Index is 4 but yet only details for 3 tables appear. 

**Expected behavior**
Once a table goes live it should appear on all relevant pages

**Comment by neilfromcork** [comment]
This is caused by a mismatch between the Collection/Navigation and the relevant caches. Currently under review.

**Comment by colmanflynn** [comment]
MSI02, MSA02 & MSQ02 went live at 11am today are not appearing in the Last Updated Tables on the Beta.
They do appear on the Product page in the Navigation: Services > Services Index.
Only when I select todays date from the drop-down calendar will they appear.

The same is true on the Test.
External Trade tables: TSM01 - TSM10 & TSM13 went live toady at 11am and are not appearing in Last Updated Tables but do appear when you browse in External Trade or select todays date.

![Beta 145](https://user-images.githubusercontent.com/59689411/86461913-a4d23a00-bd22-11ea-9d57-4280f193b0a7.PNG)
![Test 145](https://user-images.githubusercontent.com/59689411/86461958-b3205600-bd22-11ea-812a-f4189d7c5f24.PNG)

**Comment by lorenzobruni** [comment]
@colmanflynn this hasn't been released yet.
You will see the fix once the label `RELEASED` will be attached.

Thanks
