### ISSUE TITLE
[ENHANCEMENT] Search enhancements for empty search string and cache key

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#146]
[ENHANCEMENT] Amend search to (a) ensure an empty search string brings back nothing and (b) ensure the search terms are ordered and lowercase before being used as a cache identifier.

**Comment by neilfromcork** [comment]
Completed - ready for test

**Comment by damienderoistecso** [comment]
Client side updated to handle empty search input

@JohnPCarroll ready for test

**Comment by liamie** [comment]
Empty search seems to retain the search of previous term. Not bring back nothing the search doesn't update.

**Comment by neilfromcork** [comment]
@damienderoistecso - front end issue, I think..

**Comment by JohnPCarroll** [comment]
Search failing on data page. Table E0109 is not found but is a live table

**Comment by neilfromcork** [comment]
There is no E0109 table in DEV @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Should be A0109. It looks like this table was a test table in Late April that should be gone but is not.  Nothing to worry about

**Comment by damienderoistecso** [comment]
> Empty search seems to retain the search of previous term. Not bring back nothing the search doesn't update.

If you have nothing in the search input, then the client doesn't call the search API method. Whatever was on the screen previous to attempting a search remains there until a valid action is performed.
