### ISSUE TITLE
[ENHANCEMENT] Inherit Public Comment in Releases

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#147]
**Is your feature request related to a problem? Please describe.**
Make the **Public Comment** under Releases `RLS_CMM_ID` inheritable on upload of a new Work In Progress release.
Logged on behalf of _Digital Communication @ CSO . ie_

**Describe the solution you'd like**
DO NOT use the same `RLS_CMM_ID `because otherwise the same reference will be shared with the previous release(s) creating issue on Update/Delete.
**N.B.1** If `RLS_CMM_ID `not NULL then the comment must be duplicated and a new `CMM_ID ` linked to `RLS_CMM_ID`.

@neilfromcork please get in touch for details if needed.

![image](https://user-images.githubusercontent.com/53212047/84238076-5ef2cf00-aaf2-11ea-8631-68ee4051672c.png)

**How to Test**
1. Create a Public Comment to an existing Release (i.e. _Version 1.0_)
2. Upload a new Release (i.e. _Version 1.1_)
3. Check the Public Comment has been inherited.
4. Update or delete the Public Comment form the previous release  (i.e. _Version 1.0_)
5. Check the Public Comment has NOT been affected in the new Release (i.e. _Version 1.1_)
6. Repeat the operation for different Release statuses (Live, WIP, Pending Live, Historical) to verify the "cloning" process works correctly.

**Comment by JohnPCarroll** [comment]
Used A0201 for testing. 
Released live with comment version 1.0  and Released live version 2.0. Comment was included. OK
Updated comment on version 2.0 and appeared on data page. No approval required. 
Deleted comment on version 2.0 and it still appears on data page. No approval required. Incorrect

**Comment by liamie** [comment]
Update only seems to work on current live. If the new work in progress version has its comment updated to something different before going live it still does not supersede the public note of the previous live until update button is clicked again after going live. I understand work in progress shouldn't update the current live but on publish should the new versions public note not be published also. This occurs in reverse on rollbacks the rolled-back version of the public note remains until update done again in releases.

**Comment by neilfromcork** [comment]
Fixed in DEV- for test @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Failed updated comment test' used A0108 
Steps followed 
1. Added comment and went live.
2. Loaded table again and updated comment.
3. Released live but old comment displayed. This is incorrect

**Comment by neilfromcork** [comment]
@JohnPCarroll @lorenzobruni - This requirement needs more detail as to how it should behave across releases. Can you explain please?

**Comment by neilfromcork** [comment]
Fixed in DEV. Currently cloning comments on the same basis that releases are cloned. Cloning only occurs when we create a new release i.e. when we  create a WIP after a current live release.

**Comment by colmanflynn** [comment]
Comment added but not appearing on -
PEH12
QEA01
LFBA5
PSQ01
LRM05
I can't see any reason for them not to appear. They were added in exactly the same manner as all of the others.
Copy in the text "For more information, please go to the statistical release page on our website." and add a link to the words "...statistical release page...". 
![LRM05](https://user-images.githubusercontent.com/59689411/85145216-26ff3080-b244-11ea-9ba8-2e0062e42e7f.PNG)
![PSQ01](https://user-images.githubusercontent.com/59689411/85145234-2ebed500-b244-11ea-904b-5cfd638478e5.PNG)

**Comment by liamie** [comment]
Public comment is appearing the same for multiple language versions. If the public comment is updated in either language release it is applied to both. Should this not be updated separately for each language the same as a footnotes as the message could have different text for Irish and English.

**Comment by neilfromcork** [comment]
Currently, the comment is cloned when we change the version, i.e. at the same time as the release is cloned. 
Releases are not language specific and, since comments are related to releases, it is not possible in the current data model to relate a comment to a language version of a matrix. In practice, it would be considered unlikely that a user would take the trouble to write a comment for all available language versions.
