### ISSUE TITLE
[BUG] Datatable warning when trying to read users when one of the Users doesn't have an "Name " or "Email" value

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#148]
Datatable warning when trying to read users when one of the Users doesn't have an "Name " or "Email" value

**Comment by damienderoistecso** [comment]
Server side: Always return fully formed object for each user in "PxStat.Security.Account_API.Read". If no user found in active directory, return null for "CcnEmail" and "CcnName". 

Client side: In Users table, add a column called "Valid". For each user, check if either "CcnEmail" or "CcnName" is null and display relevant icon in column.

**Comment by damienderoistecso** [comment]
Client side updated. New column called "Valid" added to users table. Any user without email or name will be displayed as invalid and an appropriate action can be taken.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test @damienderoistecso

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for test. If you open manage users in test you will see the problem. New column in Dev to highlight users no longer in active directory

**Comment by JohnPCarroll** [comment]
Test passed. Removed invalid user. Unable to locate another user to add on
