### ISSUE TITLE
[ENHANCEMENT]  Change href in JSON-stat output to point to RESTful APIs as data resources

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#150]
Currently the JSON-stat output shows hrefs as follows:
{
                    "type": "application/json",
                    "href": "https://dev-data.cso.ie/release/45"
                },
                {
                    "type": "plain/px",
                    "href": "https://dev-data.cso.ie/release/45"
                },
                {
                    "type": "text/csv",
                    "href": "https://dev-data.cso.ie/release/45"
                }

These hrefs need to be changed to the relevant RESTful APIs. Also, change px mimetime to correct version and add xlsx mime type.

**Comment by neilfromcork** [comment]
Completed in DEV. RESTful APIs now available for ReadDataset, ReadCollection and ReadMetadata. Ready for test. @JohnPCarroll

**Comment by damienderoistecso** [comment]
tested. Works correctly
