### ISSUE TITLE
[BUG]  imported by appearing in correct on dashboard for work in progress

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#151]
On the dashboard page, work in progress panel : imported by is appearing with brackets
![image](https://user-images.githubusercontent.com/55874862/84762175-63235e80-afc2-11ea-9107-dfc1ea1e57b0.png)

**Comment by damienderoistecso** [comment]
Fixed typo

@liamie ready for test

**Comment by liamie** [comment]
Tested, looks correct now.
