### ISSUE TITLE
Unexpected Error occurs when uploading 2 language file[BUG] 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#152]
Unexpected error occurs importing a file with 2 languages
Validated correctly but error appeared when import button pressed.
Had prompted for frequency also.
![image](https://user-images.githubusercontent.com/55874862/85575460-7ae88b80-b62f-11ea-8824-0de6aaf07807.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Front page not loading for me now. Tried clear cache, updated the client. Restarted browser and pc. Hangs on greyed out front screen with the load bars cyclying.

**Comment by damienderoistecso** [comment]
> Front page not loading for me now. Tried clear cache, updated the client. Restarted browser and pc. Hangs on greyed out front screen with the load bars cyclying.

This is an unrelated issue to this bug. It is a side affect of #149 which we are still developing so it can be ignored for now.

**Comment by damienderoistecso** [comment]
@liamie Application should load eventually if you refresh a few times

**Comment by liamie** [comment]
Files uploading now
