### ISSUE TITLE
[BUG] Build update doesn't progress with a very big file

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#154]
Very large NISRA census file fails to update. API hangs.

**Comment by neilfromcork** [comment]
Fixed. Comprehensive re-write of the Build Update. Note rules:
- Any invalid data supplied for update will be ignored
- Duplicate values will be ignored.
- Values that are and are not updated will be listed as usual on the client before the PX file is downloaded.

**Comment by damienderoistecso** [comment]
@neilfromcork do you still have the NISRA file? Can you send to @liamie so he can test and we can get this signed off? Thanks

**Comment by liamie** [comment]
when tried download csv the progress bar advanced at a consistent pace
then stayed at 99% for about 3 minutes and gave the error below
![image](https://user-images.githubusercontent.com/55874862/88184758-02bfb680-cc2b-11ea-8154-63906a2a6981.png)

**Comment by damienderoistecso** [comment]
> when tried download csv for existing periods the progress bar advanced at a consistent pace
> then stayed at 99% for about 3 minutes and gave the error below
> ![image](https://user-images.githubusercontent.com/55874862/88184758-02bfb680-cc2b-11ea-8154-63906a2a6981.png)

@neilfromcork is this just a case of timing out due to size?

**Comment by neilfromcork** [comment]
Yes, I think so. The API has finished processing at this point.

**Comment by liamie** [comment]
When try upload the csv file provided of data it gets to confirmation screen but if try to download the csv of either the ignored or rows to be updated it times out again.

**Comment by neilfromcork** [comment]
According to the logs, the server will eventually create the very large csv file. However, a network error seems to occur before this happens. Possible timeout limit on IIS? Also maybe check file download size limit. @lorenzobruni

**Comment by neilfromcork** [comment]
Timeout amended. Ready for test.

**Comment by lorenzobruni** [comment]
Timeout test with manual by-pass of client code.
This bug is FIXED, but it requires the BUG #169 to be implemented on the Client code.
