### ISSUE TITLE
[BUG] view data hanging in releases in progress screen

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#156]
when trying to view data in the releases (work in progress)
1. go to the work in progress page of a release
2. click on 'view data' button

rather than displaying data hangs on this screen

![image](https://user-images.githubusercontent.com/55874862/86473351-a9a1e880-bd38-11ea-9c9d-e2c0a8b0fc85.png)

**Comment by neilfromcork** [comment]
Seems ok in 2.3 - front end needs to be checked. @damienderoistecso

**Comment by damienderoistecso** [comment]
Side affect of #149

**Comment by damienderoistecso** [comment]
Duplicate of #165

**Comment by damienderoistecso** [comment]
Duplicate of #165
