### ISSUE TITLE
Validation Error Message when browsing subjects and products[BUG] 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#157]
When browsing the subject/products using the panel on left hand side of Data page
![image](https://user-images.githubusercontent.com/55874862/86476424-69ddff80-bd3e-11ea-8220-458652cf50f7.png)

When you choose a product the following error screen appears as if trying to validate 

![image](https://user-images.githubusercontent.com/55874862/86476193-f9cf7980-bd3d-11ea-89d2-47b3d3627846.png)

**Comment by neilfromcork** [comment]
Fixed in DEV -please retest.

**Comment by liamie** [comment]
This is correct now
