### ISSUE TITLE
Build - add ability to download classification from .px file   [ENHANCEMENT] 

### ISSUE THREAD

**Issue by Elainehoward** [CSOIreland/PxStat#159]
Hi guys,

As discussed - under the build option in PxStat could we get the option to download the classification from the .px file?

Thanks,
Elaine

**Comment by damienderoistecso** [comment]
Added "Download as CSV" to modal footer create when you click on classification to view it's variables.

**Comment by damienderoistecso** [comment]
ready for test

**Comment by JohnPCarroll** [comment]
Classification Download Working
