### ISSUE TITLE
Build - add the ability to download all the periods from .px file [ENHANCEMENT] 

### ISSUE THREAD

**Issue by Elainehoward** [CSOIreland/PxStat#160]
Hi,

As discussed - in the Build, could we get the ability to download all the periods from the .px file?

Thanks
Elaine

**Comment by damienderoistecso** [comment]
Download periods button added to Build/create

**Comment by damienderoistecso** [comment]
Ready for test

**Comment by JohnPCarroll** [comment]
Test successful

**Comment by liamie** [comment]
Periods download successful. Note you can download a blank file if there is no periods listed. Button is not disabled.
