### ISSUE TITLE
[BUG] Update Data CSV Download is changing data order

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#161]
The csv download from update data seems to be changing the order of data on some files.

If the csv is then used to reupdate  the file the figures are shifted around 
Sent details to Neil

**Comment by liamie** [comment]
Order corrected for some files but Statistic and unit seems to be omitted on CSV download for some files
when using build->update 
after parsing the px file
![image](https://user-images.githubusercontent.com/55874862/87132418-bd47d480-c28d-11ea-8961-944d2717565d.png)
for existing period

The entries in the CSV columns for statistic and unit are blank and so give the following error if try to reupdate using these files as they don't match their px layout
![image](https://user-images.githubusercontent.com/55874862/87131857-f0d62f00-c28c-11ea-95f7-2b92e08b9c0c.png)

Sent sample file details to Neil

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Statistic and unit appearing correctly now
