### ISSUE TITLE
[ENHANCEMENT] Create JSON-stat version1.0 output for backward compatibility

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#162]
Statbank uses JSON-stat 1.0 for output. Therefore we need a backward-compatible version of ReadDataset for any existing JSON-stat users

**Comment by neilfromcork** [comment]
Implemented in DEV- ready for test.
Notes for testing:
It's unlikely that this will ever be implemented in the PxStat client. You can test it however by reading a dataset directly from a browser, e.g. as https://dev-ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/LIAMTESTPEC18/JSON-stat/1.0/en
You may change the JSON-stat version by changing the second last item in the url, e.g. from 1.0 to 2.0
Unfortunately there is no defined spec for JSON-stat 1.0. The best you can do is to ensure that the output is structurally similar to an equivalent output from the Statbank API - Go to https://statbank.cso.ie/webserviceclient/DatasetListing.aspx

**Comment by liamie** [comment]
Tested and confirmed corrected format with Neil
