### ISSUE TITLE
[BUG] A ReadDataset query containing a dimension with all its items invalid will return malformed JSON-stat

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#163]
If any dimension in a JSON-stat query has only got invalid dimension items, the dimension filtering is ignored (correctly) but the metadata will be empty for that dimension.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test.
Some testing notes:
This can't be replicated by the front-end. In order to test this you would need to either make a call to the API via Postman or else as a GET request on a browser. An example of the browser request url is shown below:
https://dev-ws.cso.ie/public/API.JSONRPC/?data={"jsonrpc":"2.0","method":"PxStat.Data.Cube_API.ReadDataset","params":{"class":"query","id":["TLIST(A1)","C02405V02899","C02404V02898"],"dimension":{"TLIST(A1)":{"category":{"index":["2016","2014"]}},"C02405V02899":{"category":{"index":["016","01601","01602"]}},"C02404V02898":{"category":{"index":["-","01"]}}},"extension":{"language":{"code":"en"},"format":{"type":"JSON-stat","version":"2.0"},"matrix":"SEI06"},"version":"2.0"}}

The bug would have occurred where, for example, instead of:
 category":{"index":["016","01601","01602"]}
you had:
category":{"index":["016xxx","01601xxx","01602xxxx"]}, i.e. classification with a full load of invalid variables

**Comment by liamie** [comment]
If all dimensions are invalid it now returns all dimensions as if no dimensions filtering.
If any dimensions are valid it is filtered to those dimensions
