### ISSUE TITLE
[BUG] Build update generating multiple languages and failing to validate update 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#164]
Build update seems to be generating multiple English language tabs for a single language file with multiple statistics.

![image](https://user-images.githubusercontent.com/55874862/87669852-97776f80-c766-11ea-95ab-581d685a2f08.png)
![image](https://user-images.githubusercontent.com/55874862/87670012-ede4ae00-c766-11ea-82f4-5e6cc5ca8f07.png)

and then when try to update the file the following error is given

![image](https://user-images.githubusercontent.com/55874862/87670102-18cf0200-c767-11ea-8d04-5e3899a6e1a4.png)

**Comment by neilfromcork** [comment]
Doesn't replicate on Postman to server test, at least for the initial Read stage.

**Comment by damienderoistecso** [comment]
@liamie cannot reproduce. Can you see if you can generate this again?

**Comment by damienderoistecso** [comment]
Issue occurs when you drop multiple px files into "Upload Source File" in sequence.

**Comment by damienderoistecso** [comment]
Reset language array each time a new file is dropped uploaded

**Comment by damienderoistecso** [comment]
@liamie ready for test

**Comment by liamie** [comment]
This problem is still occurring. As re-framed it seems to be occurring as multiple files can be parsed in sequence. The newly parsed file is amended to the stored copy of previously parsed files until the reset button is pressed.
I think it may be resolved by disabling the upload file box as well as the parse button after the first successful file is parsed until the reset is pressed again. Similar to the properties section in the Create option once Build Dimensions is successful. Currently using the upload file box re-enables the parse button without a reset.

**Comment by damienderoistecso** [comment]
@liamie can you re-test please. Now emptying any previous JSONstat data

**Comment by liamie** [comment]
This seems to be corrected now
