### ISSUE TITLE
[BUG] jQuery .once error 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#165]
Incompatibility between out jQuery .once plugin function and widget jQuery 

**To Reproduce**
Intermittent occurrence at run time 

**Expected behavior**
.once function loads along with widget jQuery

**Screenshots**
![image](https://user-images.githubusercontent.com/53211688/87921695-d8c39400-ca72-11ea-8059-6271e01e1fdd.png)

**Comment by lorenzobruni** [comment]
Issue resolved with @damienderoistecso via loading the **pxWidget** `ISOGRAM `on demand when the Chat tab is clicked rather than sequentially onload.

This can be tested on the long run, by verifying that the `$(...).once` error in the console won't show up.

Thanks

**Comment by lorenzobruni** [comment]
Closing this bug as it did not occurred again over the past days.
