### ISSUE TITLE
[ENHANCEMENT] Implement widget tables in data entity

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#166]
Extend the widget plugin to enable embedding of table widgets

**Comment by lorenzobruni** [comment]
Implemented.
@JohnPCarroll can you please test as following:

1. Make a Table selection and view the results.
2. Scroll to the **Widget** accordion.
3. Copy the Snippet code and paste it into a brand new `index.html` file anywhere on your computer.
4. Open the index.html file with a browser (i.e. Chrome)

Repeat steps 3 and 4 by changing the Options in the Widget

![image](https://user-images.githubusercontent.com/53212047/88715258-afab9f00-d115-11ea-8320-360c1f2856fb.png)

**Comment by JohnPCarroll** [comment]
Test Passed
