### ISSUE TITLE
displaying pill details for matrix using multiple languages

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#17]
If a Matrix is in multiple languages the Pills in all languages are displayed together eg Matrix FINA

**To Reproduce**
1. Go to Data  
2. Click on Search
3. Scroll down to Matrix FINA

**Expected behavior**
Only display the Pills associated with the relevant language

**Comment by damienderoistecso** [comment]
Bug with "PxStat.System.Navigation.Navigation_API.Search"

Array of classifications is returning all languages

**Comment by neilfromcork** [comment]
Fix deployed in dev. Ready for retest
