### ISSUE TITLE
[ENHANCEMENT] Implement a PxAPIv1 interface based on Statistics Sweden

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#170]
Enable to user to view data by emulating the Statistics Sweden interface at https://www.scb.se/en/services/oppna-data/api-for-the-statistical-database/

For testing, please use the documentation at https://github.com/CSOIreland/PxStat/wiki/API-Cube-PxAPIv1

**Comment by neilfromcork** [comment]
Ready for test

**Comment by liamie** [comment]
The Read Collection for Product is not being limited by the subject and therefore you can use a product code with a subject that it is not a member off which gives a collection that has no relevance to the subject

**Comment by neilfromcork** [comment]
This issue is now fixed in DEV. I've also applied the rule to the data and metadata RESTful queries, i.e. even if the matrix code is valid, you will not get a result unless the subject and product codes are correct.
