### ISSUE TITLE
[ENHANCEMENT] Normalize Excel library for handling XLSX file creation

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#171]
Create API library for Excel creation

**Comment by lorenzobruni** [comment]
@neilfromcork 
This one was incorrectly created under the wrong repo `Server-API-Library`.
I transfer it here.

If I remember well this was already implemented and tested, correct? 
Thanks

**Comment by neilfromcork** [comment]
Yes. This seems to be a duplicate of #128

**Comment by lorenzobruni** [comment]
Perfect, thanks!
Duplicate of #128
