### ISSUE TITLE
[BUG] Build Update - SortId returned in API response

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#172]
**Describe the bug**
The `SortId` is incorrectly returned in the **Build Update** report.

**To Reproduce**
1. Go to Build Update
2. Import a PX file and add some CSV data'
3. Click on Update
4. See issue as per screenshot

**Expected behavior**
Is it possible to strip the SortId before returning the API response to the client?

**Screenshots**
![image](https://user-images.githubusercontent.com/53212047/88596258-9db9f580-d05c-11ea-9bb8-2f69013f157c.png)

**Comment by neilfromcork** [comment]
Fixed. Ready for test

**Comment by lorenzobruni** [comment]
Test passed, brilliant! :-)
