### ISSUE TITLE
[BUG] Can't see new periods in new version update

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#173]
Table RSM05

1. Imported RSM05_1_0... and published.
2. Then I selected data for month 2020M02  for 3 nace groups and all indicators. and widget code
3. Imported RSM05_2_0... and published
4. This px file contains data to 2020M05 but you can only select to 2020M02 ? 
5. If you select no months 2020M03 to 2020M05 are displayed in the Results

Table RSM07

1. Imported RSM07_1_0.. and published
2. Imported RSM07_2_0... and published
3. The data selection is correct. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by neilfromcork** [comment]
Fixed - ready for test

**Comment by JohnPCarroll** [comment]
Test Passed
