### ISSUE TITLE
[BUG] Chart Link incorrect

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#174]
**Describe the bug**
Accessed date.cso.ie
The link on the chart refers to dev-data.cso.ie and not data.cso.ie

**To Reproduce**
Create a bar chart using any table

**Expected behavior**
link should be to correct environment not https://dev-data.cso.ie/table/CBM03

**Screenshots**
![image](https://user-images.githubusercontent.com/44975474/89285881-1581b480-d649-11ea-89d4-a04559441365.png)

**Comment by liamie** [comment]
This incorrect link issue also applicable to the share this link section for email and social media
![image](https://user-images.githubusercontent.com/55874862/89400276-943f2600-d70b-11ea-9e95-b8fd4c88fc0e.png)

**Comment by lorenzobruni** [comment]
Thanks @JohnPCarroll 
Both should be fixed.

![image](https://user-images.githubusercontent.com/53212047/94620825-28121600-02a7-11eb-8071-466824c0f77c.png)

**Comment by liamie** [comment]
Seems to be correct on live for both share link and chart link now
