### ISSUE TITLE
[BUG]  Build/Update option. Title updated but not fully reflected in updated Px file

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#175]
**Describe the bug**
The CONTENTS details are not updated in the px file but the DESCRIPTION and TITLE are. 

**To Reproduce**
1. Uploaded the PX file E9010.
2. Amended title
3. Downloaded updated version
4. Imported the updated PX file and the Title was not changed on screen. It Appears to use the CONTENTS from the PX file

**Expected behavior**
The DESCRIPTION, TITLE AND CONTENTS should all update

**Screenshots**
PX file pre update
[E9010.20200804T140806.txt](https://github.com/CSOIreland/PxStat/files/5022611/E9010.20200804T140806.txt)

PX file post update
[E9010.20200804T140854.txt](https://github.com/CSOIreland/PxStat/files/5022617/E9010.20200804T140854.txt)

**Additional context**

**Comment by neilfromcork** [comment]
Fixed - ready for test
