### ISSUE TITLE
[BUG] title in config.json duplicated on Client side

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#176]
**Describe the bug**
the `title `property of the config.json is correctly placed on the config.global.json on the Server side but is duplicated inclorrectly also on the client side.

Please remove the `title `property form the Client side **config.json**

**Comment by damienderoistecso** [comment]
removed title in client config

@JohnPCarroll ready for test. To test, check that the title is appearing correctly in the header

**Comment by damienderoistecso** [comment]
Test passed
