### ISSUE TITLE
[BUG] JSON-stat 1.0 missing

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#177]
**Describe the bug**
JSON-stat version 1.0 is missing.
Probably is because the script to add the relative DOWNLOAD format in the DB was missing during the last release.
Please post here the SQL script and I will create a **hot live fix** under **2.4.1** version.

Thanks

**Comment by lorenzobruni** [comment]
@neilfromcork can you please handover the fix to @liamie as part of the training?
Take it as an opportunity to explain why & how doing it.

Thanks

**Comment by neilfromcork** [comment]
Assigned to Liam

**Comment by liamie** [comment]
Script required

INSERT [dbo].[TS_FORMAT] ([FRM_ID], [FRM_TYPE], [FRM_VERSION], [FRM_DIRECTION]) VALUES (6, N'JSON-stat', N'1.0', 'DOWNLOAD')
