### ISSUE TITLE
[ENHANCEMENT] remove redundant range is 1 time point only is present

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#178]
**Is your feature request related to a problem? Please describe.**
Some tables have only 1 timepoint but the pill shows a range with the same value.

**Describe the solution you'd like**
If only 1 timepoint exists, can the range be replaced by the single timepoint value?
It is a bit confusing otherwise, thanks

![image](https://user-images.githubusercontent.com/53212047/89872984-a8729f80-dbb1-11ea-95b0-4dbcd41d2546.png)

**Comment by damienderoistecso** [comment]
Removed span if only one variable in time dimension. Also removed redundant square brackets.

Last updated tables changed, search results changes and view data changed.

@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
One variable now displayed for time dimension. But the Last updated page now displays incorrectly. The title now runs over many more lines than before. as the Language and Last Updated have moved left.

**Comment by damienderoistecso** [comment]
> One variable now displayed for time dimension. But the Last updated page now displays incorrectly. The title now runs over many more lines than before. as the Language and Last Updated have moved left.

Should be fixed now

@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Test passed
