### ISSUE TITLE
[BUG] Update px file with map url not working

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#179]
**Describe the bug**
Update a px file and attach a map url to a classification

**To Reproduce**
Try and update a px file and add a map url to a classification. Updated px file contains no reference to the map url. 

**Expected behavior**
Map value gets inserted into px file

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test @damienderoistecso

**Comment by damienderoistecso** [comment]
Test passecd
