### ISSUE TITLE
[ENHANCEMENT] Upload - List the group in alphabetical order 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#18]
**Is your feature request related to a problem? Please describe.**
List groups in the upload screen are not sorted alphabetically 

**Describe the solution you'd like**
List groups alphabetically 

![image](https://user-images.githubusercontent.com/53211688/71734222-56abaf00-2e43-11ea-81a7-8a0bbef7e44f.png)

**Comment by neilfromcork** [comment]
Changed to return data alphabetically by GRP code.
