### ISSUE TITLE
[ENHANCEMENT] Remove highcharts and google charts from analytics entity and replace with chart js

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#181]
**Describe the solution you'd like**
Remove highcharts as this is a licenced product. Use chart js which is full open source and free to use

**Additional context**
Also remove google chart and no need for two free charting libraries.

**Comment by damienderoistecso** [comment]
Updated, chartjs now the only library for used for analytics.

@JohnPCarroll ready for test. Analytics should be more or less the same as it was when using highcharts/gogole charts as it is now using chartJs except for some minor aesthetical differences

**Comment by JohnPCarroll** [comment]
Test Failed.
To do this select subject and submit. The Referrer hits loses some columns and then they reappear depending where you are on the chart.

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for re-test

**Comment by JohnPCarroll** [comment]
Test failed. Individual hits for a table not shown when selected

**Comment by damienderoistecso** [comment]
@JohnPCarroll fixed ready for re-test

**Comment by JohnPCarroll** [comment]
Test failed. on the individual hits for a table the hits over time appears to be correct but all remaining charts show the overall values for all tables combined

**Comment by damienderoistecso** [comment]
> Test failed. on the individual hits for a table the hits over time appears to be correct but all remaining charts show the overall values for all tables combined

@neilfromcork Can you take a look at this. It appears that the same result is coming back whether or not you pass the parameter "MtrCode" or not. Method I tested is "PxStat.Security.Analytic_API.ReadBrowser" but I think it is happening for other analytic methods also.

**Comment by neilfromcork** [comment]
Issue with MtrCode fixed for all Analytics. Ready for test

**Comment by JohnPCarroll** [comment]
Test Failed. Formats chart for an individual still contains an overall total

**Comment by neilfromcork** [comment]
@JohnPCarroll  - can you advise, which analytic item and which matrix code were used in the test?

**Comment by JohnPCarroll** [comment]
If you use CBM03, A0103 or any Matrix the formats chart appears to be an overall total

**Comment by damienderoistecso** [comment]
@JohnPCarroll format pie chart fixed

@neilfromcork can you check that we don't have any issue with what's returned i.e. Formats. Seems to always only be JSONstat 2.0 and csv

**Comment by JohnPCarroll** [comment]
Test passed for individual format pie chart
