### ISSUE TITLE
[BUG] Dimension pills not displaying in view data sceen

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#182]
**Describe the bug**
Dimension pills are not displaying in view data screen

**Screenshots**
![image](https://user-images.githubusercontent.com/53211688/90259741-7035c000-de42-11ea-9f4e-63f4fa5ef68a.png)

**Comment by damienderoistecso** [comment]
Fixed in dev

@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Test passed
