### ISSUE TITLE
[ENHANCEMENT] Data chart widget enhancements

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#184]
**Describe the solution you'd like**
A number of features to enhance the chart widgets

- Allow user to insert optional axis labels

- Allow users to include optional max number of steps for the xAxis

- Remove vertical grid lines

**Comment by damienderoistecso** [comment]
@JohnPCarroll @liamie ready for testing.

**Comment by liamie** [comment]
max number of steps for x-axis allows negative number you can use -20

**Comment by damienderoistecso** [comment]
> max number of steps for x-axis allows negative number you can use -20

Negative values no longer accepted

**Comment by liamie** [comment]
xAxis Label and yAxis Label not reset with reset button
these labels still remain filled in even if bar chart type changed.

**Comment by damienderoistecso** [comment]
> xAxis Label and yAxis Label not reset with reset button
> these labels still remain filled in even if chart type changed.

@liamie should be resolved now

**Comment by damienderoistecso** [comment]
If type is "Bar", change the description of the axes labels

**Comment by damienderoistecso** [comment]
> If type is "Bar", change the description of the axes labels

@liamie should be resolved now

**Comment by liamie** [comment]
In charts if there is a large disproportion between figures it can be difficult to hover over to display the exact figure of small amounts. Is there alternative ways to display these amounts by tabbing between columns/bars, using the label or toggling values on/off.
![image](https://user-images.githubusercontent.com/55874862/91431141-de717e00-e857-11ea-9f1d-7569f6c16ecf.png)

**Comment by damienderoistecso** [comment]
> In charts if there is a large disproportion between figures it can be difficult to hover over to display the exact figure of small amounts. Is there alternative ways to display these amounts by tabbing between columns/bars, using the label or toggling values on/off.
> ![image](https://user-images.githubusercontent.com/55874862/91431141-de717e00-e857-11ea-9f1d-7569f6c16ecf.png)

@liamie if you toggle the auto-scale in the options for this selection does it improve the chart?

**Comment by liamie** [comment]
> > In charts if there is a large disproportion between figures it can be difficult to hover over to display the exact figure of small amounts. Is there alternative ways to display these amounts by tabbing between columns/bars, using the label or toggling values on/off.
> > ![image](https://user-images.githubusercontent.com/55874862/91431141-de717e00-e857-11ea-9f1d-7569f6c16ecf.png)
> 
> @liamie if you toggle the auto-scale in the options for this selection does it improve the chart?

@damienderoistecso toggle auto-scale offers little to no difference in this case as high and low numbers are far apart but in others where numbers are closer together it would improve a bit. A similar solution to Analytics enhancements
#186 with tooltip may partially address for bar/column charts.

**Comment by damienderoistecso** [comment]
@liamie can you confirm that there are no further issues with this and mark as tested please. Thanks
