### ISSUE TITLE
[BUG] Invalid daily time range displayed  in pill when Search or listing page used

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#185]
**Describe the bug**
The incorrect daily time range is displayed for a table when the listing page or search option is used

**To Reproduce**
Searched for table CBM03 or selected from BERD Region listing

**Expected behavior**
Correct date should appear in the pill

**Screenshots**
Correct details taken form Last Updated page
![image](https://user-images.githubusercontent.com/44975474/90775698-0cebd800-e2f1-11ea-8f4b-3cc1ec3c7eb3.png)

Incorrect details taken form search or listing page option
![image](https://user-images.githubusercontent.com/44975474/90775825-3b69b300-e2f1-11ea-9138-801bdb53c77a.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Please note that the periods may still be out of sync if (a) the search has already been cached or (b) the periods were inserted in non ascending order to begin with (e.g. SAPTHM4TBL6)

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Test passed. Latest matrix for CBM03 is correct

**Comment by neilfromcork** [comment]
tested but not committed

**Comment by lorenzobruni** [comment]
Ready to redeploy.
