### ISSUE TITLE
[ENHANCEMENT] Analytics enhancements

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#186]
**Describe the solution you'd like**

- Review thresholds on read methods e.g. Increase thresholds on number of referrers and browsers. Review all methods for these thresholds

- Create a new method for User language to read the culture of the end user. Create new column chart on front end to display results

- Pass language in all methods so description can be translated where necessary e.g, "Other"

**Comment by neilfromcork** [comment]
Server side complete. To read data for the language environment, see example API call below:
{
	"jsonrpc": "2.0",
	"method": "PxStat.Security.Analytic_API.ReadEnvironmentLanguage",
	"params": {
    "DateFrom":"2020-07-27",
    "DateTo":"2020-08-25",
	"LngIsoCode":"en"
}

}

**Comment by damienderoistecso** [comment]
@JohnPCarroll @liamie ready for test

**Comment by liamie** [comment]
If the number of a language is very small its impossible to find out its figure by hovering over. as per example below there are two English also (found out by using api) this may also apply to other charts with disproportionate figures. Is there anyway to use the label also as a means of showing the figure?

![image](https://user-images.githubusercontent.com/55874862/91426084-ed563180-e853-11ea-9ca8-7ae421049c86.png)

**Comment by damienderoistecso** [comment]
Tooltip now displays even if you hover above the column
@liamie ready for test

**Comment by damienderoistecso** [comment]
@liamie Can you confirm that there are no further issue with this and mark as tested plaese. Assign to Lorenxo then please

**Comment by liamie** [comment]
Yes this displays values when hover over now even on small numbers

**Comment by damienderoistecso** [comment]
Fixed issue with analytics not displaying from dashboard
