### ISSUE TITLE
[ENHANCEMENT] Ensure all urls are blank for pre-release datasets

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#187]
Any format that contains a url to the dataset should be blank if the datset is pre-release (JSON-stat, XLSX)

**Comment by damienderoistecso** [comment]
@liamie Can you test this in John's absence

**Comment by liamie** [comment]
Work in progress seems fine,
Pending live has the url present

**Comment by neilfromcork** [comment]
Pending live should be ok now too.

**Comment by liamie** [comment]
This seems to be correct now.
