### ISSUE TITLE
[ENHANCEMENT]  Create API to manage cache

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#188]
Create an API to:

- Flush the cache
- Return cache details

**Comment by damienderoistecso** [comment]
@CHanamy57 We need to create a new front end entity for these API's. It will be at system/cache and me very similar to system/configuration in terms of access

**Comment by damienderoistecso** [comment]
@neilfromcork @liamie Some changes required on the server side following front end review

- Rename "PxStat.Security.Cache_API.Refresh" to "PxStat.Security.Cache_API.FlushAll"

- Create a new API for flushing CAS caches called "PxStat.Security.Cache_API.FlushCAS" This will take an input parameter of CAS type 

- Create a new API for returning the CAS types called "PxStat.Security.Cache_API.ReadCAS"

**Comment by liamie** [comment]
Rename "PxStat.Security.Cache_API.Refresh" to "PxStat.Security.Cache_API.FlushAll"
done ready for testing

**Comment by lorenzobruni** [comment]
@CHanamy57, once testing has passed, can you please raise an enhancement for building the relative Client interface?
Thanks

**Comment by CHanamy57** [comment]
@liamie Cache front end entity at system/cache ready for testing.

**Comment by damienderoistecso** [comment]
> @liamie Cache front end entity at system/cache ready for testing.

@liamie Can you hold off on this please. I have some changes to talk to @CHanamy57 about

**Comment by liamie** [comment]
Okay. But note I have already cleared cache with button to test.

**Comment by damienderoistecso** [comment]
> Okay. But note I have already cleared cache with button to test.

No problem. It's just visual changes.

**Comment by CHanamy57** [comment]
@liamie Changes finished, ready for testing

**Comment by liamie** [comment]
This seems to be correct and reflects the data in the API
