### ISSUE TITLE
[BUG] Build message displayed with non matching period codes

### ISSUE THREAD

**Issue by grainnemooney** [CSOIreland/PxStat#19]
**Describe the bug**
If there is no matching period codes the error message contains the word NULL instead of Irish while the default language ENGLISH is displayed

**Comment by damienderoistecso** [comment]
Fixed code. Was reading incorrect object property.

**Comment by damienderoistecso** [comment]
Also fixed bug with confirm delete period message displaying blank message.

**Comment by lorenzobruni** [comment]
General enhancements for Internationalization have been applied
