### ISSUE TITLE
[ENHANCEMENT] Remove update property from "PxStat.Data.Cube_API.ReadPreMetadata" and "PxStat.Data.Cube_API.ReadPreDataset"

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#191]
**Is your feature request related to a problem? Please describe.**
Remove "updated" from JSON-stat response for pre-release data

In px files, remove "CREATION-DATE" in all cases, and use "LAST-UPDATED" for live data. Use same logic for Excel

Update widgets that if no updated property, don't display any date

**Comment by neilfromcork** [comment]
Implemented for in API for PX, XLSX, JSON-stat 1.1, JSON-stat 2.0. If this is a live dataset and there is a Release start date, display the date as "updated" in JSON-stat, "Last Updated" in XLSX and LAST-UPDATED in PX.  Ready for test. @damienderoistecso

**Comment by damienderoistecso** [comment]
Fixed in widget. Date is now not rendered for snippets for pre-release data

**Comment by damienderoistecso** [comment]
Tested in T4, works correctly
