### ISSUE TITLE
[ENHANCEMENT] Extend the matrix cache to the upload process

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#194]
Extend the matrix cache to the upload process

Because a matrix is created when we validate, we have the opportunity to save time by cacheing it at validation time and using this cache when we upload, rather than creating the matrix all over again.

**Comment by neilfromcork** [comment]
Ready for test

**Comment by damienderoistecso** [comment]
@liamie When testing this can you try and import px files using the following scenarios

 

- A regular import of a new px file

- An import of a matrix that is already a work in progress. You should receive a confirm modal.

- An import of a px file without a timeval. You should be prompted to confirm which dimension is frequency

**Comment by liamie** [comment]
Regular import of new px file correct
Import of already work in progress correct 
Import of px file without a time val correct for single en language. Problem with dual/ga language as in #198
