### ISSUE TITLE
[ENHANCEMENT] Stop confirm modal and update report modals closing when you click outside the modal

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#195]
**Describe the solution you'd like**
When you click outside confirm modal and update report modals, the modal does not close

**Comment by damienderoistecso** [comment]
Added data-backdrop="static" to modals

**Comment by liamie** [comment]
@damienderoistecso This is still occurring for add language
![image](https://user-images.githubusercontent.com/55874862/91716792-35dd5a00-eb88-11ea-91d0-b72720950337.png)

**Comment by damienderoistecso** [comment]
> @damienderoistecso This is still occurring for add language
> ![image](https://user-images.githubusercontent.com/55874862/91716792-35dd5a00-eb88-11ea-91d0-b72720950337.png)

@liamie We only want this new action for the update report and confirm modals.
