### ISSUE TITLE
View data not working in Keyword\ Releases option[BUG] 

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#197]
**Describe the bug**
When you select the View Data button the page goes into an endless loop. 

**To Reproduce**
1. Go to the KeyWords\ Releases option
2. Select a table
3. Select any release number and the select the View Data Button

**Expected behavior**
The data should appear allowing you to select the relevant details required.

**Screenshots**
![image](https://user-images.githubusercontent.com/44975474/91728897-a93c9700-eb9b-11ea-8920-2bd6c8e462c4.png)

**Comment by neilfromcork** [comment]
No obvious problem on the server side or server side logs. Need to test with client side - @damienderoistecso

**Comment by damienderoistecso** [comment]
@JohnPCarroll fixed in dev, ready for test

**Comment by JohnPCarroll** [comment]
Test passed
