### ISSUE TITLE
[BUG] Error on validation with multilingual px files with no timeval

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#198]
Error occurs when you try to validate a multilingual px file with no timeval

**Comment by neilfromcork** [comment]
Fix complete - ready for test

**Comment by liamie** [comment]
This seems to be correct now tested with E4081.px

**Comment by liamie** [comment]
Doesn't matter what option chosen in the Irish section modal keeps reappearing
when you set the language to Irish
![image](https://user-images.githubusercontent.com/55874862/92254442-d0130a00-eec8-11ea-9d9e-c8daf90356b1.png)

using Build Import on a dual language file all of the options just return back to the same modal
![image](https://user-images.githubusercontent.com/55874862/92254295-95a96d00-eec8-11ea-840d-cdcb4019a0ef.png)
doesn't progress and no error

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Not committed to release 2.5

**Comment by liamie** [comment]
This seems to be correct now tested with E1071
