### ISSUE TITLE
[BUG] Analytics - Missing Hits

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#2]
**Describe the bug**
The Analytics card (see screenshot) does not get refreshed with recent hits

**To Reproduce**
1. Read a live dataset
2. Go to Analytics and check if the counter of hits increased

**Expected behavior**
The number of hits must increase for each read of datasets

**Screenshots**
![image](https://user-images.githubusercontent.com/53212047/71106810-dab13600-21b7-11ea-9eb8-5a7545d05193.png)

**Additional context**
n/a

**Comment by JohnPCarroll** [comment]
Read Live Dataset and Count Increased

**Comment by lorenzobruni** [comment]
Pending release
