### ISSUE TITLE
[ENHANCEMENT] Auto update of the spinner colours

### ISSUE THREAD

**Issue by Chriz-ONeill** [CSOIreland/PxStat#200]
Update the Spinner to use the Bootstrap colours rather than custom one allowing the spinner colours to match the organisational colours requited.

**Comment by lorenzobruni** [comment]
Hi, I'm taking this request in for the next milestone possibly.

Things to do:
1. Amend the **Spinner Plugin** in the [Client-API-Library](https://github.com/CSOIreland/Client-API-Library) to support the Bootstrap background colors
2. Synch the changes in the PxStat project.

**Comment by Chriz-ONeill** [comment]
Hi Lorenzo,

Thanks for that. Just glad I posted that OK!

Chris

**Comment by lorenzobruni** [comment]
Change implemented by using the standard Bootstrap functional colors:
* bg-warning (for highlight purpose)
* bg-danger (for highlight purpose)
* bg-primary (to reflect branding colors)
* bg-secondary (to reflect branding colors)
* bg-tertiary (to reflect branding colors)

**Comment by lorenzobruni** [comment]
Test passed
