### ISSUE TITLE
[BUG] Static label [upload-frequency-detected] went lost

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#201]
The static label `[upload-frequency-detected]` went lost somehow.
It was there previously, please diff the internationalization files and restore the missing entry.

![image](https://user-images.githubusercontent.com/53212047/92103093-61a24f00-edd7-11ea-84d0-a776fc1134d4.png)

**Comment by liamie** [comment]
This is now appearing correctly on build options
