### ISSUE TITLE
View Data - Charts not working in Keyword/Release option[BUG] 

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#202]
**Describe the bug**
Development environment. The first time in  the chart is displayed but if you hover no information is provided. The link is missing the Matrix Code. the second time no chart appears

**To Reproduce**
1. Go to Keyword/Releases and select Matrix A0102.
2. Click on View Data within this and select chart tab
3. Select Bar chart and create 2 series
4. nothing happens when you hover on chart. 
5. The Select Reset and Repeat the process and no chart is created.
6. Please note link is missing the Matrix Table

**Expected behavior**
Charts should be displayed and information provided when you hover over them

**Screenshots**
1st time in- no details when you hove over chart
![image](https://user-images.githubusercontent.com/44975474/92107389-99ac9080-eddd-11ea-8229-6515f337c779.png)

2nd time in - No chart appears
![image](https://user-images.githubusercontent.com/44975474/92107482-c82a6b80-eddd-11ea-8864-7fa03e0bfa24.png)

**Additional context**

**Comment by damienderoistecso** [comment]
Issue with incorrect link fixed

**Comment by JohnPCarroll** [comment]
Line charts look correct. The BAR and Column charts fail.  The following steps will create an error using Matrix A0102
First run
1. Selected Year 1996 and 1991
2. Series 1 contains Both sexes and State
3. Series 2 Contains Both sexes and Leinster 
4. Chart is displayed
5. Select Reset button and the BAR chart
Second Run
1. Selected Year 1986 and 1981
2. Series 1 contains Both sexes and State
3. Series 2 Contains Both sexes and Leinster 
4. Chart is not displayed

Other chart types may fail also

**Comment by damienderoistecso** [comment]
> Line charts look correct. The BAR and Column charts fail. The following steps will create an error using Matrix A0102
> First run
> 
> 1. Selected Year 1996 and 1991
> 2. Series 1 contains Both sexes and State
> 3. Series 2 Contains Both sexes and Leinster
> 4. Chart is displayed
> 5. Select Reset button and the BAR chart
>    Second Run
> 6. Selected Year 1986 and 1981
> 7. Series 1 contains Both sexes and State
> 8. Series 2 Contains Both sexes and Leinster
> 9. Chart is not displayed
> 
> Other chart types may fail also

This was because @JohnPCarroll was pointing to the live widget library instead of dev. When pointing to dev widget code, chart rendered correctly

**Comment by damienderoistecso** [comment]
I have also fixed an issue with the formatting of the axis for years

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for test. Please do a hard re-load

**Comment by JohnPCarroll** [comment]
Test passed for Bar and charts following hard reload.
