### ISSUE TITLE
[BUG] Other language options for Frequency appearing in Update and Create

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#203]
**Describe the bug**
Other language options for Frequency appearing in Update and Create 
![image](https://user-images.githubusercontent.com/55874862/92125524-097b4500-edf7-11ea-998a-30d0e3bfe922.png)

**To Reproduce**
1. Go to 'Build > Create
2. Click on Import 
Import a multi language file
or 
1. Go to 'Build > Update
2. Upload a multi language file
2. Click on Parse

**Expected behavior**
Expect same behavior as Build > Import only one set of options to appear
![image](https://user-images.githubusercontent.com/55874862/92126618-514e9c00-edf8-11ea-9225-358262df5872.png)

**Comment by damienderoistecso** [comment]
@neilfromcork I suspect this might be a server side issue.

**Comment by neilfromcork** [comment]
Fixed - ready for test

**Comment by liamie** [comment]
This is now appearing correctly on build options
