### ISSUE TITLE
[ENHANCEMENT] Build/Update Allow users download custom csv data based on time dimension

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#204]
**Describe the solution you'd like**
When a user uploads a px file and then requests the csv template for this file, allow them to make a selection of data based on one or more timepoints. This is to accommodate extra large files.

Client side: Remove existing dropdown of options and replace with a button which opens a modal. This modal will present the user with a multiselect of timepoints which they can chose from with the option to select all. They will also have the option to toggle labels on/off in the csv file. We will need to configure a soft/hard threshold as we do for viewing data.

Server side: Allow users to view CSV Build data based on:

- One period

- Several periods

- All periods

Also allow users to choose whether or not labels are to be shown in the CSV output

**Comment by neilfromcork** [comment]
Server side complete - PxStat.Build.Build_API.ReadDataset

**Comment by CHanamy57** [comment]
@neilfromcork Bug when you call with "labels, false" - removes header row instead of removing label column.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by CHanamy57** [comment]
Fixed in Dev, ready for test @JohnPCarroll @liamie

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/94901468-9b29b100-048e-11eb-91eb-463e24f208b5.png)

If new periods are added they appear in the Modal but are not included in the csv download even if selected or all periods are chosen.

**Comment by damienderoistecso** [comment]
@neilfromcork Can you look at this on the server side. It look like we are sending the new periods but they are not included in the csv

@CHanamy57 Can you close the modal after a successful ajax call.  $('#build-update-download-csv-file').modal("hide") in the ajax call back should do the trick;

**Comment by damienderoistecso** [comment]
@neilfromcork Small issue with "PxStat.Build.Build_API.ReadDataset"

Result is sending back null for MtrCode

![image](https://user-images.githubusercontent.com/53211688/95094651-0939d680-0722-11eb-9aa3-c45c675a75de.png)

**Comment by neilfromcork** [comment]
@damienderoistecso - should be ok now

**Comment by damienderoistecso** [comment]
> ![image](https://user-images.githubusercontent.com/55874862/94901468-9b29b100-048e-11eb-91eb-463e24f208b5.png)
> 
> If new periods are added they appear in the Modal but are not included in the csv download even if selected or all periods are chosen.

@neilfromcork This is working now and also the updated px file includes any new periods added

**Comment by JohnPCarroll** [comment]
When I added a new time period and selected the download CSV data for that period only, it downloaded with values assigned to other time periods. It should contain no values

**Comment by liamie** [comment]
I agree when I add time periods now the CSV Metadata columns include the new time periods grouped with existing periods by classification but all the values for the new periods appear at the end of the Value column.

**Comment by damienderoistecso** [comment]
@neilfromcork if labels are false, can you remove unit column also

@CHanamy57 Can you rename "Labels" toggle on "Labels and Unit" in modal

**Comment by liamie** [comment]
Added two periods to a file in upload, downloaded csv for all periods some of new periods contained figure data from existing periods and some of the existing periods contained default data fields where they had figures before.

Also when downloaded csv with just the new periods they contained data figures.

**Comment by neilfromcork** [comment]
Fixed in DEV- ready for test @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Test passed. Used monthly, Quarterly and yearly tables. Added new time periods.  inserted data for new time periods and updated old data for current periods
