### ISSUE TITLE
[ENHANCEMENT] Update - handle invalid data csv with an error

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#206]
*Describe the solution you'd like**
If you try and update a px file with a data csv file that has no valid records, display an error modal instead of the report modal.

This will make it more obvious to people if they have an invalid data csv file

**Comment by damienderoistecso** [comment]
@liamie ready for test

**Comment by liamie** [comment]
This is inconsistent.. 
A file with just headings and no data so therefore no valid  seems to pass correctly to produce an updated px file report

A file with a line containing all "1" for data produced the error message about invalid data
![image](https://user-images.githubusercontent.com/55874862/92384264-aeec2c80-f107-11ea-9e40-60fe652661eb.png)

However after this if you do a reset in the data section the just headings file csv file then produces the same error message.

Also is if a file that contains all existing data is used this passes fine to report as expected but if you do a data section reset you can then use the all "1" data set to produce a px file with the report not an error message.

I think it seems to be holding that a file with just headings passes through without fail or success. An error stays an error once triggered the first time until a successful test is passed and if a successful test is passed it stays that way despite data resets.

**Comment by damienderoistecso** [comment]
@liamie ready for re-test

**Comment by liamie** [comment]
This seems to be correct now.
File with just correct headers produced error
File with correct headers and lines of data but all incorrect produced error
File with correct header data and some lines correct and incorrect produced report 
And all seemed to be acting independently with data resets.
