### ISSUE TITLE
[BUG] Last updated tables inconsistent 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#207]
In the Irish the table seems to be listed twice 
![image](https://user-images.githubusercontent.com/55874862/92391406-8b7bae80-f114-11ea-878a-acadc55a9b87.png)

In the English only once in the list
![image](https://user-images.githubusercontent.com/55874862/92391652-f927da80-f114-11ea-8fc9-285c2903b8d4.png)

**Comment by neilfromcork** [comment]
Fixed - data issue. Ready for test

**Comment by liamie** [comment]
This appears correct now

**Comment by neilfromcork** [comment]
Change also done on sp
