### ISSUE TITLE
[BUG] Wrong data shown in updated px file in Build

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#208]
If a dataset is undergoing build and the associated csv data is invalid, the build proceeds anyway but with wrong data.

**Comment by neilfromcork** [comment]
Ready for test

**Comment by liamie** [comment]
first used of update data with new data resulted in an error which didn't appear when update pressed a second time with same data

**Comment by neilfromcork** [comment]
Issue temporarily fixed by replacing multithreaded function with serial versions

**Comment by lorenzobruni** [comment]
@neilfromcork 
can you please confirm if the parallel multi-threaded process has been re-instated by using a struct/object rather than a Dictionary based implementation?
Thanks

**Comment by lorenzobruni** [comment]
@neilfromcork 
can I mark it tested?
