### ISSUE TITLE
Moderator Sign off

### ISSUE THREAD

**Issue by Chriz-ONeill** [CSOIreland/PxStat#210]
Option to allow moderators with approval status to be able to sign off a publication rather than only power users and admin, so all 3. The ability for moderators to be able to assign the navigation and to be able to use the toggles (Analytical/Dependency).

**Comment by lorenzobruni** [comment]
Hi @Chriz-ONeill, 
Regarding the first query, this is already possible :-)
Please see all details under this post https://github.com/CSOIreland/PxStat/issues/122

To put it simple, this feature is called "fast-track" and it allows you to configure any type of 1, 2 or 3 step workflow agaisnt each role... a lot of combinations!

You can choose the settings under the `/Resources/Config/config.blobal.json` file in the Server Side code.
![image](https://user-images.githubusercontent.com/53212047/93144356-c156ff00-f6e1-11ea-81ea-ccd0f69b7aa7.png)

By setting the properties to true you will allow fast-tracking either the Workflow Response and / or Sign-off for each role.
In the example ABOVE all roles will fast-track... but usually we suggest to keep Administrators outside of the fast-tracking in order not to interfere with business rules, like in the case BELOW.

![image](https://user-images.githubusercontent.com/53212047/93144627-58bc5200-f6e2-11ea-9bfd-e4ca17c72f9f.png)

All combinations are possible.
Remember, to refresh the configuration via the appropriate interface when making changes to the files.

![image](https://user-images.githubusercontent.com/53212047/93144718-8c977780-f6e2-11ea-902d-3b6d5bce733a.png)

**Comment by lorenzobruni** [comment]
Regarding the Analytics/Dependency flag, we may discuss their actual need to exist... because apparently they aren't used as originally intended... 
I leave this topic opened and get back to you as soon as possible.

Cheers

**Comment by lorenzobruni** [comment]
@Chriz-ONeill the `Dependency Flag` has been removed in this Issue #227 
We are going to keep the Analytics for longer to see how it works out.
Cheers
