### ISSUE TITLE
[BUG] [uploaded by] label not correct in comparison report modal

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#215]
**Describe the bug**
[uploaded by] label not correct in source section of comparison report modal

Go to a release with a live to compare to
Click Compare Release Button

![image](https://user-images.githubusercontent.com/55874862/93312222-dd9c8e00-f7fe-11ea-858a-80cacb1a1e5f.png)

**Comment by damienderoistecso** [comment]
Fixed in Dev

@liamie ready for test

**Comment by liamie** [comment]
This is correct now.
