### ISSUE TITLE
[ENHANCEMENT] Implement PxAPIv1 as a RESTful API

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#217]
Implement PxAPIv1 as a RESTful API similar to https://www.scb.se/en/services/oppna-data/api-for-the-statistical-database/ on the front end

**Comment by neilfromcork** [comment]
Backend completed and tested e.g. https://dev-ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.PxAPIv1/en/SBJ01/PRD01/HPM01

**Comment by damienderoistecso** [comment]
Refactored client side config to separate jsonrpc and restful api url's

**Comment by damienderoistecso** [comment]
Implemented on client

@liamie @JohnPCarroll ready for test

**Comment by damienderoistecso** [comment]
![image](https://user-images.githubusercontent.com/53211688/93753150-985dcf00-fbf7-11ea-89d9-35313888ed5c.png)

**Comment by damienderoistecso** [comment]
Added feature to disable json-stat 1.1 format if in pxapi v1 tab as this format is not supported in the API

**Comment by liamie** [comment]
Format is listed in dropdown on pxapi v1tap but is disabled for selection as required
