### ISSUE TITLE
[BUG] Build Upload - Choose a px file or drag it here

### ISSUE THREAD

**Issue by grainnemooney** [CSOIreland/PxStat#22]
**Describe the bug**
After using browse tool to load a file, if you browse again the original file name remains but if validate it shows mandatory even though name is still there.

**Comment by lorenzobruni** [comment]
Fixed. The Cancel button of the default browser file picker will trigger the clear upload.

**Comment by lorenzobruni** [comment]
@damienderoistecso please review all other upload drag&drop features in the application

**Comment by damienderoistecso** [comment]
Removed file input from validation. Validation button disabled until valid file uploaded
