### ISSUE TITLE
Browse menu toggle on search

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#220]
**Describe the bug**
When you search for something the browse menu hides by a toggle. When you perform a second search, the menu re-opens because we use a toggle instead of hide 

**Expected behavior**
Menu should always hide when display search results

**Comment by damienderoistecso** [comment]
Fixed in Dev

@liamie @JohnPCarroll ready for test

**Comment by damienderoistecso** [comment]
Re-opened as menus is still expanded when you click from a search result to the table selection page

**Comment by damienderoistecso** [comment]
Fixed in dev

@liamie ready for test

**Comment by liamie** [comment]
Hides now/ Remains hidden when selecting a table also.
