### ISSUE TITLE
Product Listing Results - Define logic to order

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#221]
**Describe the solution you'd like**
Define a logic to order the results from a product search results

**Comment by damienderoistecso** [comment]
@neilfromcork Currently when you return data from "PxStat.System.Navigation.Navigation_API.Search" based on a product search, each item has a score of 0. Once we agree a logical score of products, the score should reflect this.

**Comment by damienderoistecso** [comment]
@neilfromcork  Order the results with the following logic

- First rank by non-archived and then archived
- Next by date last updated (newest first)
- Next by alphabetical (a-z)

**Comment by damienderoistecso** [comment]
Following review of product listing the following was decided.

- For both search and product navigation, add an alpha sorting option based on table code

- For search, set the default sorting to relevance

- For product search, disable/remove relevance sorting option 

- Set default sorting for product navigation to Newest first

- Reverse order of Table Title and Table ID on both search results page and data view page

- Move indicators after table ID on both search results page and data view page

**Comment by damienderoistecso** [comment]
Fixed in client

@liamie @JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test Passed

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/95093090-47ce9180-0720-11eb-9379-777115c3d0d7.png)

PCA18 not appearing in a search by table name seems to be ok for other tables maybe related to #223 either

**Comment by liamie** [comment]
Issue with PCA18 seems to resolved now. Test passed
