### ISSUE TITLE
[ENHANCEMENT]Review cookie consent banner for share this feature

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#222]
**Describe the solution you'd like**
Find a better way to show the share this feature based on accept/reject non-essential cookies

**Comment by lorenzobruni** [comment]
Cookie Notice implemented according to ePD and new coming ePR.

**Comment by lorenzobruni** [comment]
@damienderoistecso please test? Thanks

**Comment by damienderoistecso** [comment]
Works. Only consideration would be that if you are viewing a table and have not given consent, share this is not displayed which is correct. If you then give consent while still viewing the table, the share this feature remains disabled. Should we run the share this render function if you give consent as you are viewing a table @lorenzobruni What do you think?

**Comment by damienderoistecso** [comment]
If you toggle cookie consent to allow and you have a table open in the background, the share this feature gets drawn 

@liamie ready for test

**Comment by damienderoistecso** [comment]
@liamie updated to also handle a users accepting cookies through the cookie banner accept button. If you accept cookies through the banner while viewing a table, the share this icons get drawn.

**Comment by liamie** [comment]
Works as intended when toggled to on.

Note: if consent is removed it boots back to the home page doesn't just undraw/redraw share this, but passed as that may be design choice.

**Comment by damienderoistecso** [comment]
> Works as intended when toggled to on.
> 
> Note: if consent is removed it boots back to the home page doesn't just undraw/redraw share this, but passed as that may be design choice.

Yes, if consent is withdrawn, we reload the application to run again with non-essential cookies fully removed
