### ISSUE TITLE
[BUG] Filter search not working for products for prodcom sales tables 

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#223]
**Describe the bug**
The filter search fails when searching on the product. No results returned. Tables affected PCA18, PCA17 and PCA16

**To Reproduce**
1. Go to Table PCA18
2. on Product enter "ores"
3. Nothing returned 

**Expected behavior**
Product listing containing ores should be returned.

**Comment by damienderoistecso** [comment]
Fixed in dev

@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Test Passed
