### ISSUE TITLE
[ENHANCEMENT] Speed up search by keying on sorted search terms and storing formatted output

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#224]
Speed up search by keying on sorted search terms and storing formatted output

Currently the raw output from the database read is the cached value. This should be changed to the formatted output in order to reduce the amount of work to be done at each read.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test.

**Comment by liamie** [comment]
Search on Dev does appear to be quicker than live especially on previously searched terms but I am unsure if this is just a volume difference
