### ISSUE TITLE
[ENHANCEMENT] Re-order LHS of data view page

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#226]
**Describe the solution you'd like**
In the data view page order the LHS as follows

- Note

- Reasons

- Download

- Share

- Contact

**Comment by damienderoistecso** [comment]
fixed in dev

@JohnPCarroll @liamie ready for test

**Comment by damienderoistecso** [comment]
fixed in dev

@JohnPCarroll @liamie ready for test

**Comment by liamie** [comment]
They now appear in that order. 
Browse appears above those listed. Note and Reasons only appear if value present.
