### ISSUE TITLE
[ENHANCEMENT] Remove dependency flag

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#227]
**Describe the solution you'd like**
Remove dependency flag from entire project. Redundant feature

**Comment by neilfromcork** [comment]
Completed on server side. - Requires extensive regression testing

**Comment by liamie** [comment]
Option no longer available on reasons screens any stage

**Comment by JohnPCarroll** [comment]
I have added, deleted, made historical and updated tables as well as the properties of tables and all appears to be correct. I turned off and on the various flags and everything passed. All appears to be correct no matter what page I view.
