### ISSUE TITLE
[ENHANCEMENT] Inform Internet Explorer users/other browsers unsupported

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#230]
Some information message for unsupported browsers users of how to get or what supported browsers rather than blank screen.

![image](https://user-images.githubusercontent.com/55874862/94668761-5411b380-0308-11eb-89c0-e6d68bc8344a.png)

**Comment by damienderoistecso** [comment]
@CHanamy57 Can you do some research on this. Maybe some javascript/jQuery to detect browser type and a switch statement to handle messages depending on browser type/version. You can use a simple HTML page outside of pxStat for the purposes of research.

**Comment by lorenzobruni** [comment]
@CHanamy57 
I'm taking this one, cheers

**Comment by lorenzobruni** [comment]
Sample of message:

> **IE (Internet Explorer)** browser is deprecated and no longer supported.
> Please upgrade to a **current browser** to use the application.

**Comment by lorenzobruni** [comment]
The modal has been tailored to disallow closing it.
This applies to every IE versions, considering the the shut down of support will start progressively from the 30th of November 2020.
![image](https://user-images.githubusercontent.com/53212047/99103209-268e7a00-25d7-11eb-9338-3f86e3d07956.png)

@liamie ready for testing.
