### ISSUE TITLE
[BUG] Build update fails to add new data

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#231]
For a dataset where the number of added periods greatly exceeds the number of existing periods, PxStat is refusing to update some of those entries

**Comment by neilfromcork** [comment]
Fixed - ready for test. Example files attached. Files are suffixed with ".txt" to enable insertion into github
[TSM02_5_2_20200929T170933 (1) - Copy.px.txt](https://github.com/CSOIreland/PxStat/files/5310078/TSM02_5_2_20200929T170933.1.-.Copy.px.txt)
[tsm02_tsm23_1970_2020_v2 - Copy.csv.txt](https://github.com/CSOIreland/PxStat/files/5310086/tsm02_tsm23_1970_2020_v2.-.Copy.csv.txt)
[dates_from_1990 - Copy.csv.txt](https://github.com/CSOIreland/PxStat/files/5310089/dates_from_1990.-.Copy.csv.txt)

**Comment by JohnPCarroll** [comment]
Test passed. Used test files supplied
