### ISSUE TITLE
[BUG] HREF swapped in ReadCollection API result

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#232]
**Describe the bug**
The href in the ReadCollection output points to Json-stat 1.1 instead of 2.0
This is swapped with the alternate link.

![image](https://user-images.githubusercontent.com/53212047/94797449-082e3f80-03d8-11eb-94ad-c4fe61f90657.png)

**Comment by neilfromcork** [comment]
Fixed in DEV. Ready for test. Note - watch out for cached data.

**Comment by liamie** [comment]
JSON-stat/2.0 is now primary link
order of alternatives 
CSV/1.0
JSON-stat/1.1
PX/2013
XLSX/2007

test passed
