### ISSUE TITLE
[BUG] In development environment new tables added not appearing in relevant product listings etc

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#235]
**Describe the bug**
Tables added not shown and counts incorrect bar initial menu
**To Reproduce**
1. Added 2 tables and released live
2. Tables are on Last Updated tables.
3. Counted in Listing 
4. Do not appear in table listing or included in other counts

**Expected behavior**
When the tables go live they should appear on relevant pages and be included in all counts.

**Comment by damienderoistecso** [comment]
@neilfromcork appears to be an issue with "PxStat.System.Navigation.Navigation_API.Search". New tables appearing in ReadCollection but not through the search

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by damienderoistecso** [comment]
@JohnPCarroll @liamie ready for test

**Comment by JohnPCarroll** [comment]
test passed
