### ISSUE TITLE
[BUG] Newline character in the middle of VALUES in a px file causes validate problems

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#236]
If VALUES fields in a px file are long, and contain a newline character, the newline is carried into the process and validation fails

Example file:
[NQQ46.20201005T131012.px.txt](https://github.com/CSOIreland/PxStat/files/5332066/NQQ46.20201005T131012.px.txt)

**Comment by neilfromcork** [comment]
Fixed in DEV, ready for test

**Comment by JohnPCarroll** [comment]
Test passed. Used file NQQ34 for testing
[NQQ34.px.txt](https://github.com/CSOIreland/PxStat/files/5332338/NQQ34.px.txt)
