### ISSUE TITLE
[BUG] Charts not correctly displayed for some tables eg HS119

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#238]
**Describe the bug**
Incorrect details displayed. Two series requested but only one is shown for column and bar charts. Charts created for most other tables appear to be correct.

**To Reproduce**
1. Select Year
2. For Series 1 select "All social groups" and for series 2 select "2" along with the one statistic
3. All series not shown and chart contains duplicate values

**Expected behavior**
both series displayed correctly and chart does not contain duplicate values on y-axis

**Screenshots**
![image](https://user-images.githubusercontent.com/44975474/95200082-b4579800-07d5-11eb-8a08-9c7cb1aa8742.png)

**Additional context**

**Comment by damienderoistecso** [comment]
@JohnPCarroll There is no bug here. The reason you cant see Series 2 is that the value of series 2 is 50.7. The y-axis start at 50.0 so you can't see the bar with the naked eye. If you expand options and set Auto-scale to false, you can then see both series. Unfortunately we can't know whether to set auto-scale to true or false on a chart by chart basis. It probably works better overall if auto-scale is set to true by default
