### ISSUE TITLE
[ENHANCEMENT] Update colours of cards in build/update report modal

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#244]
*Describe the solution you'd like**
Change colours to better highlight valid and invalid reports so help user differentiate between both reports

**Comment by damienderoistecso** [comment]
@CHanamy57 Can you make sure that this change passes accessibility. Go to build/update, update a px file with some csv data to generate the report modal

**Comment by CHanamy57** [comment]
Preview report modal passes Accessibility requirement
