### ISSUE TITLE
[BUG] Reference period shown on Last Updated Tables on the Beta & Test is incorrect

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#245]
As the title says, go to the Last Updated Tables on the Data page. The reference periods for each table do not match with what you see when you click on the table.
![Incorrectly displayed reference periods](https://user-images.githubusercontent.com/59689411/96256674-ff7d6200-0fb0-11eb-802e-8ab1c6a6b539.PNG)

**Comment by damienderoistecso** [comment]
@neilfromcork order of time variables in "PxStat.Data.Cube_API.ReadCollection" is different from "PxStat.Data.Cube_API.ReadMetadata" and "PxStat.System.Navigation.Navigation_API.Search"

**Comment by damienderoistecso** [comment]
might be linked to #185

**Comment by lorenzobruni** [comment]
@neilfromcork 
I'm going ahead with the release 2.6.0 Beta anyway, but can you fix this one in Trunk once I complete the release?
So we can make an emergency release 2.6.1 with only this Issue fixed considering the importance.

Thanks

**Comment by neilfromcork** [comment]
@damienderoistecso  - needs to be tested asap

**Comment by damienderoistecso** [comment]
Time variables order is correct in Dev 2.6.0 in Last Updated Tables
