### ISSUE TITLE
[BUG] Can not fetch table metadata

### ISSUE THREAD

**Issue by likp** [CSOIreland/PxStat#247]
**Describe the bug**
I get HTTP 500 internal server error when trying to fetch the table metadata when using Postman or from C# code. Pasting it in e.g. Chrome works fine.

**To Reproduce**
Use postman to do a HTTP GET on the following url
https://ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.PxAPIv1/en/30/GEI/TSA05

**Expected behavior**
I JSON result with the metadata for that table. See chapter 4.3 Table metadata result in https://www.scb.se/contentassets/79c32c72783a4f67b202ad3189f921b9/api-description.pdf

**Comment by lorenzobruni** [comment]
@likp 
Thanks for that, can you please provide the GET URL you tried?
Because I think the wrong one got pasted into the issue above.

Thanks!

**Comment by likp** [comment]
Just updated the issue, while doing so I discovered that the problem occurred in Postman and worked fine i Chrome. Maybe I missing some headers?

**Comment by neilfromcork** [comment]
No special headers are required. If you're doing a GET request for a RESTFUL service in Postman, you just paste the url into the bar.

**Comment by neilfromcork** [comment]
@likp we've managed to reproduce the problem - we will get back to you on this.

**Comment by lorenzobruni** [comment]
@likp 
Just for clarity. The issue we have identified is happening when making a Data Query via POST.
Requesting Metadata only looks good to us, see below.

Please find below a screenshot of Postman, where you can see the GET or POST method, the URL, the empty BODY (for the POST) and the list of default Headers. 

**N.B.** Please note these are the default Postman headers... are they any different to your default one?

Can you please confirm that fetching the Metadata is now working in Postman for you as well? 
Thanks :-)

![image](https://user-images.githubusercontent.com/53212047/96513108-7fc5f080-1259-11eb-830e-cdfc2480f958.png)

**Comment by likp** [comment]
My bad, if found the problem. I had some rubbish i the body that caused the 500 message.
