### ISSUE TITLE
[ENHANCEMENT] Show users duplicate data in update CSV file

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#248]
**Describe the solution you'd like**
If a user has duplicate row in their data CSV  for update, display this clearly for the user in the update report

**Comment by damienderoistecso** [comment]
@neilfromcork In the API "PxStat.Build.Build_API.Update", in the report array, for each item can you include a property called "duplicate" which would be true or false

**Comment by damienderoistecso** [comment]
@CHanamy57 On the client side we will have to amment the datatable for "Invalid records to be ignored" to highlight any duplicate records

**Comment by neilfromcork** [comment]
Completed on server side. Report now returns "duplicate" true or false

**Comment by CHanamy57** [comment]
![image](https://user-images.githubusercontent.com/55976631/98263403-b0f33000-1f7e-11eb-8f9f-6d468b229703.png)

@neilfromcork Invalid records in report don't contain "duplicate" property.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Note that if a record is invalid, it will not be checked for duplicity and "duplicate" will always show false.

**Comment by CHanamy57** [comment]
Front end fixed in Dev - ready for test @JohnPCarroll

**Comment by liamie** [comment]
Seems to work as intended.
Duplicate records are appearing with a duplicate tick in "Invalid records to be ignored" unless another reason to invalidate is found first then also listed in "Invalid records to be ignored" but not marked as duplicate.
