### ISSUE TITLE
[BUG] Dimension and time pills missing from table details in view data from release and keywords 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#249]
**Describe the bug**
Dimension and time pills missing from table details in view data from release and keywords 

![image](https://user-images.githubusercontent.com/53211688/96459155-afed9f00-1219-11eb-8f4e-5ae087c5078b.png)

**Comment by damienderoistecso** [comment]
Fixed in Dev

@liamie ready for test

**Comment by liamie** [comment]
Dimension and Time pills now appearing on the view data for release and keyword(release)
