### ISSUE TITLE
[ENHANCEMENT] Extend PxAPIv1 to support both JSON-stat 1.x and JSON-stat 2.x

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#250]
Extend the API `format` parameter to allow the `json-stat2` value when requesting an output in **JSON-stat 2.x**
The existing `json-stat` value should return instead an output in **JSON-stat 1.x**

**Comment by lorenzobruni** [comment]
Query to update the official PxAPI documentation logged with Statistics Sweden.
FYI https://github.com/statisticssweden/PxWeb/issues/54

**Comment by neilfromcork** [comment]
@lorenzobruni - a problem with the httpPOST member. If you change the body (for example change the format) of the PxApiV1 POST request, the change is not picked up unless you restart the application

**Comment by lorenzobruni** [comment]
> @lorenzobruni - a problem with the httpPOST member. If you change the body (for example change the format) of the PxApiV1 POST request, the change is not picked up unless you restart the application.
> This problem also exists for JSON-rpc requests

Fixed at the Server API Library under version 4.2.0

**Comment by damienderoistecso** [comment]
Client updated to allow JSON-stat 2.0 and JSON-stat 1.1

**Comment by neilfromcork** [comment]
Server updated

**Comment by damienderoistecso** [comment]
Tested in browser for both JSON-stat 2.0 and JSON-stat 1.1

Correct results are returned
