### ISSUE TITLE
[ENHANCEMENT] Enable data to be downloaded already pivoted by any single dimension

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#252]
The server should be able to deliver data pivoted by a choice of dimensions. Therefore the user should be able to choose a single pivot dimension and the data should be delivered pivoted by that dimension.

**Comment by neilfromcork** [comment]
Completed on server

**Comment by damienderoistecso** [comment]
@neilfromcork Can you extend the full pivoting to PxAPIv1 also

**Comment by damienderoistecso** [comment]
client updated

@JohnPCarroll ready for testing

**Comment by lorenzobruni** [comment]
@Killian-Carroll
This is the enhancement to allow downloading the data pivoted on screen.
It's planned to be released next, 2.7.0

**Comment by lorenzobruni** [comment]
Test passed
