### ISSUE TITLE
[ENHANCEMENT] Create new entity and API for monitoring server performance

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#254]
**Describe the solution you'd like**
Create new API to read server performance.

Display details on client in new entity called "Server" under the System tab

**Comment by liamie** [comment]
Committed on DB/Server side

**Comment by damienderoistecso** [comment]
@CHanamy57 You can start looking at using these API in the new performance entity but don't commit in 2.7.0

Example API calls

"method": "PxStat.Entities.Security.Performance.Performance_API.ReadPrfProcessorPercentage",
    "params": {
    "PrfDatetimeStart":"2020-11-05T15:36:00.00",
    "PrfDatetimeEnd":"2020-11-05T15:38:00.00"
}
    "method": "PxStat.Entities.Security.Performance.Performance_API.ReadPrfMemoryAvailable",
    "params": {
    "PrfDatetimeStart":"2020-11-05T15:36:00.00",
    "PrfDatetimeEnd":"2020-11-05T15:38:00.00"
}
    "method": "PxStat.Entities.Security.Performance.Performance_API.ReadPrfRequestQueue",
    "params": {
    "PrfDatetimeStart":"2020-11-05T15:36:00.00",
    "PrfDatetimeEnd":"2020-11-05T15:38:00.00"
}
    "method": "PxStat.Entities.Security.Performance.Performance_API.ReadPrfRequestPerSecond",
    "params": {
    "PrfDatetimeStart":"2020-11-05T15:36:00.00",
    "PrfDatetimeEnd":"2020-11-05T15:38:00.00"
}


    "method": "PxStat.Entities.Security.Performance.Performance_API.Delete",
    "params": {
//None required if your admin you get to delete
}

**Comment by lorenzobruni** [comment]
Server Side API completed, pending Client Side implementation under issue #294
