### ISSUE TITLE
[ENHANCEMENT] Better displaying of search/product results

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#256]
**Describe the solution you'd like**
Re-factor search and product page to enhance user experience.

**Comment by damienderoistecso** [comment]
@neilfromcork for "PxStat.System.Navigation.Navigation_API.Search", if it's called with a "PrcCode", can the results be default sorted alphabetically  and if it's called with "Search" can the results be default sorted by "Score"

**Comment by neilfromcork** [comment]
Completed in DEV - ready for test

**Comment by damienderoistecso** [comment]
@neilfromcork As discussed, if it's called with "Search" can the results be default sorted by "Score", then date last updated and then alphabetical

**Comment by neilfromcork** [comment]
Completed in DEV - ready for test. I'm presuming that the more recent updated dates are shown first.

**Comment by JohnPCarroll** [comment]
Test Passed
