### ISSUE TITLE
[BUG] Handle user verification when connection to active Directory fails

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#257]
**Describe the bug**
When connection to active directory fails, do not cache this result. Only cache the result on a successful call to AD

![image](https://user-images.githubusercontent.com/53211688/96589103-58fcce00-12dc-11eb-93a1-047b8118bf54.png)

**Comment by lorenzobruni** [comment]
Fixed under the Server API Library, Release 4.1.3 https://github.com/CSOIreland/Server-API-Library/releases/tag/4.1.3
