### ISSUE TITLE
[BUG] Backward compatible JSON-stat outputs need to be based on version 1.0, not on 1.1

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#259]
We need to be able to provide an output format for data that is compatible with Statbank. This must be based on JSON-stat 1.0, and not on version 1.1

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by lorenzobruni** [comment]
Fixed on client side too.

**Comment by neilfromcork** [comment]
@damienderoistecso - Damien, can you check the front-end to make sure all is ok?

**Comment by damienderoistecso** [comment]
> @damienderoistecso - Damien, can you check the front-end to make sure all is ok?

Updated client and all working OK

**Comment by JohnPCarroll** [comment]
Test passed

**Comment by lorenzobruni** [comment]
@John,
you missed to check the Unit :-)

@neilfromcork 
The "base" must contain the unit, like "%", "Kg" etc...
The parent of the "base" must contain the Code, not the Label.

Wrong from PxStat
![image](https://user-images.githubusercontent.com/53212047/96775793-f4c33280-13df-11eb-8502-d7466e5ca24a.png)

Correct from Statbank
![image](https://user-images.githubusercontent.com/53212047/96775979-3d7aeb80-13e0-11eb-9fba-8c78d04fcd1d.png)

**Comment by lorenzobruni** [comment]
@neilfromcork 
Please text me on mobile once done as I will be at the conference.

**Comment by lorenzobruni** [comment]
> @JohnPCarroll ,
> you missed to check the Unit :-)
> 
> @neilfromcork
> The "base" must contain the unit, like "%", "Kg" etc...
> The parent of the "base" must contain the Code, not the Label.
> 
> Wrong from PxStat
> ![image](https://user-images.githubusercontent.com/53212047/96775793-f4c33280-13df-11eb-8502-d7466e5ca24a.png)
> 
> Correct from Statbank
> ![image](https://user-images.githubusercontent.com/53212047/96775979-3d7aeb80-13e0-11eb-9fba-8c78d04fcd1d.png)

This one is fixed 👍

**Comment by lorenzobruni** [comment]
@neilfromcork 
Just another tiny one...

The "role" time should have the reference to the Code as well, not the Label.
![image](https://user-images.githubusercontent.com/53212047/96788262-1d045e80-13eb-11eb-8424-3a419e0adedc.png)

**Comment by neilfromcork** [comment]
Role discrepancy fixed. Published in DEV and committed.

**Comment by lorenzobruni** [comment]
Test passed
