### ISSUE TITLE
[BUG] Editing Note does not save to the px file in update

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#262]
**Describe the bug**
When you add or edit a note in "PxStat.Build.Build_API.Update" it is not included in the updated px file

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
Test failed. I used Table FSA26. It contained no note so I added it. The new Px file generated contained NOTEX and NOTE.  This is incorrect and when the px file is imported no footnote appears. See files attached for before and after updates
[FSA26.20201023T121032preupdate.txt](https://github.com/CSOIreland/PxStat/files/5429084/FSA26.20201023T121032preupdate.txt)
[FSA26.20201023T121033postupdate.txt](https://github.com/CSOIreland/PxStat/files/5429085/FSA26.20201023T121033postupdate.txt)

**Comment by neilfromcork** [comment]
Issue resolved in DEV - ready for test

**Comment by liamie** [comment]
In Build update when alter note 
It reads in the Notex but saves as Note when updating
![image](https://user-images.githubusercontent.com/55874862/97574600-648a7c00-19e3-11eb-9809-501340dceeb7.png)


section in resulting updated px that is incorrect

![image](https://user-images.githubusercontent.com/55874862/97574858-c1863200-19e3-11eb-99bc-cd30d58a684e.png)

**Comment by neilfromcork** [comment]
I'm proposing to merge this with #264

**Comment by neilfromcork** [comment]
Merged with #264 - completed in DEV

**Comment by JohnPCarroll** [comment]
Test passed. NOTEX set to NOTE
