### ISSUE TITLE
[ENHANCEMENT] Concatenate NOTEX, NOTE, INFOFILE in NOTES

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#264]
Concatenate NOTEX, NOTE, INFOFILE in NOTES. Infofile must be validated as a url

**Comment by neilfromcork** [comment]
Completed in DEV - restest in update and build. Use files with and without notes, notex, infofile etc

**Comment by liamie** [comment]
With a file with no note originally
added note in update
![image](https://user-images.githubusercontent.com/55874862/97997111-88353400-1de0-11eb-8c05-0bebe78e0b6c.png)

but in saved/updated file note keyword section appears but does not contain the notes content
![image](https://user-images.githubusercontent.com/55874862/97997534-f679f680-1de0-11eb-9b56-5e4d1db169c0.png)

**Comment by liamie** [comment]
With a file with an existing notex or note the updated file section is changed to note
![image](https://user-images.githubusercontent.com/55874862/97998749-6937a180-1de2-11eb-8eb0-025b70aa1ee6.png)

however no alterations to the contents note are made in the updated file if altered or added to in the note box on screen

**Comment by neilfromcork** [comment]
Fixed in dev - ready for test

**Comment by JohnPCarroll** [comment]
INFOFILE currently dropped in Create and update option if imported in a file. Not added to Note.

**Comment by neilfromcork** [comment]
INFOFILE is only appended if it's a valid url.

**Comment by JohnPCarroll** [comment]
Valid url added eg https://www.cso.ie/en/databases/

**Comment by JohnPCarroll** [comment]
Test Passed
