### ISSUE TITLE
[BUG] Workflow History - Signoff Approve tooltip not working

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#265]
The tooltip over the Approved icon is not working.
It should display "Published" instead.

![image](https://user-images.githubusercontent.com/53212047/97865270-da535800-1d01-11eb-8b68-64835fac9395.png)

**Comment by lorenzobruni** [comment]
Fixed
![image](https://user-images.githubusercontent.com/53212047/97865396-07076f80-1d02-11eb-8599-1c7bedb4430f.png)

@JohnPCarroll 
can you please test? Thanks

**Comment by JohnPCarroll** [comment]
Test passed when table sign off completed
