### ISSUE TITLE
[BUG] Build Update - Loading a csv file where timeperiod does not exist on px file

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#266]
**Describe the bug**
Loaded a csv file containing with a timeperiod which is not on the px file. I did not add it as a new time period either.

**To Reproduce**
Loaded a px file called AKM01 with max TLIST(M1) 202008. Loaded a csv file with max TLIST(M1) 202009

**Expected behavior**
This type of  error message should not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/44975474/97981188-cffc9100-1dc9-11eb-8ed2-f87034b6a04a.png)

**Additional context**

**Comment by neilfromcork** [comment]
Appears to work ok from a server point of view. Superfluous data is on the ignore list. The warning seems to be brought up by the client.

**Comment by damienderoistecso** [comment]
This is a result of development on #248
