### ISSUE TITLE
[BUG] Spaces allowed in codes for statistics, classification and timeperiods

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#267]
**Describe the bug**
Spaces are accepted for Statistical Codes, Classifications and Timeperiods in the Build create and update option. This should not be allowed.

**To Reproduce**
1. Statistics. - The Code should not contain spaces eg CPM 01C1 is incorrect
2. Classifications. - The code itself should not contain spaces eg C02064 V02491 is incorrect
3. Classification Variables - The Code should not contain spaces eg 0 1  is incorrect
4. Time Periods - The code or Values should not contain spaces.  eg 2020 09 2020 M09 are incorrect.

**Expected behavior**
Codes should not contain spaces. The time period values should not contain spaces.

**Additional context**
There is code used elsewhere which removes spaces automatically.

**Comment by lorenzobruni** [comment]
@neilfromcork & @damienderoistecso 

Please ensure that the validation on the Client will be reflected by the one on the Server.
Thanks

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
Test failed. Time Periods containing spaces still allowed in create and update.

**Comment by damienderoistecso** [comment]
> Test failed. Time Periods containing spaces still allowed in create and update.

@JohnPCarroll client side not yet updated.

**Comment by neilfromcork** [comment]
Validation amended. Should be ok now.

**Comment by damienderoistecso** [comment]
Fixed in client

@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test failed for time Periods Values. Spaces still permitted whether you add in manually or upload a fil. Code get spaces auto removed.
![image](https://user-images.githubusercontent.com/44975474/99080983-fbe1f880-25b9-11eb-903a-fb61883755ae.png)

**Comment by JohnPCarroll** [comment]
Test passed on further review
