### ISSUE TITLE
[BUG] Build Update and Create UNITS on the px file

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#269]
**Describe the bug**
The UNITS are defaulted to a "-" no matter what is entered in the Unit for the statistic.

**To Reproduce**
The create option
1. Create a new table or import an existing px file.
2. Select the Create button and view the output 

The Update option
1. Select a px file and Parse.
2. Select the Update button and view the output

**Expected behavior**
In create it should default to a Statistical unit. 
In update it should remain the same as the file selected 

**Screenshots**
Before update
![image](https://user-images.githubusercontent.com/44975474/98232142-35c95400-1f55-11eb-8396-5f8743f8d61a.png)

Post Update
![image](https://user-images.githubusercontent.com/44975474/98232261-5a253080-1f55-11eb-819d-63a5f2892bb6.png)

The same happens when you create a px file

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
Failed in Build Create.
I imported a file and changed the Matrix code. I Selected the Create button and viewed the output. The UNITS= "Thousand" is missing. 
![image](https://user-images.githubusercontent.com/44975474/98264712-185daf80-1f80-11eb-987b-3738abbf5769.png)

This means that the px file created cannot be opened using PXWin.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
Test Passed
