### ISSUE TITLE
[BUG] Embargo Days not filtered

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#27]
**Describe the bug**
The setting `embargo.day` in the `config.json` do not filter the list of available dates in the Publish workflow for non-emergency releases.

**To Reproduce**
1. Go to Releases and attempt a Publish workflow

**Expected behavior**
The Publish date picker should disable the days that are not in the `embargo.day` setting

**Comment by lorenzobruni** [comment]
Issue fixed.
See screenshot with the `embargo.day` set to [1,2,3,4,5] which means Monday, Tuesday, Wednesday, Thursday, Friday on.
![image](https://user-images.githubusercontent.com/53212047/71893586-020a7b80-3144-11ea-9d4a-141b9513048e.png)

**Comment by lorenzobruni** [comment]
Neil, can you please implement the Server Side validation, by adding the Static config APP_EMBARGO_TIME = "11:00:00" and the APP_EMBARGO_DAY = "1,2,3,4,5" when the Emergency option is NOT selected.

**Comment by neilfromcork** [comment]
API validation created. For retest.
