### ISSUE TITLE
[BUG] Build Update Dual language Data issue

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#270]
**Describe the bug**
The DATA is not returned when the px file is updated 

**To Reproduce**
1. Select a Duel Language px file and parse in the Build update option
2. Click on the Update option
3. View the updated px file in notepad and the DATA is missing
4. You are unable to open this px file using PX-Win

**Expected behavior**
DATA to be retained

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
Test passed Data retained
