### ISSUE TITLE
[ENHANCEMENT] Create a new Flag for Frontier Releases

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#271]
**Describe the solution you'd like**
Create a new flag in the database called "experimental" to be labeled as "Frontier Series" on the client interface

@neilfromcork From a server perspective, this is an exact replica of the "Archived" flag in terms of workflow, privileges, API's etc

@damienderoistecso Add all necessary features on the client side to show/update this new flag

**Comment by neilfromcork** [comment]
Completed in DEV - Flag name for Release is RlsExperimentalFlag, for Worflow Request it's WrqReleaseFlag

**Comment by damienderoistecso** [comment]
@neilfromcork Can you look at "PxStat.Workflow.Workflow_API.Read" I don't think "WrqExperimentalFlag" is returned in this API

**Comment by neilfromcork** [comment]
Should be ok now - can you recheck?

**Comment by damienderoistecso** [comment]
@neilfromcork  Can you check "PxStat.Workflow.Workflow_API.ReadHistory" also for "WrqExperimentalFlag"

**Comment by neilfromcork** [comment]
Ok, that's changed - should be visible now

**Comment by damienderoistecso** [comment]
@neilfromcork  Can you add "RlsExperimentalFlag" to "PxStat.Workflow.Workflow_API.ReadLive"

**Comment by neilfromcork** [comment]
RlsExperimentalFlag now on PxStat.Workflow.Workflow_API.ReadLive

**Comment by damienderoistecso** [comment]
Client side complete

@JohnPCarroll ready for testing

**Comment by liamie** [comment]
Toggle options applied to both live and wip, once sign off is approved for the update of properties.

note1: Does not change the option if work in progress is in the pending live stage

note2: once enabled links for all three options on the live data page point to the same location for explanations however only frontier series is actually mentioned on this linked page should other "More Information" links be directed to appropriate about pages or is this going to be a central information point
