### ISSUE TITLE
[ENHANCEMENT] Create new bootstrap functional colours 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#272]
**Describe the solution you'd like**
Create new functional colours in our bootstrap css for each flag that we use

We need functional colours for each of the following

- official

- exceptional

- reservation

- archive

- analytical

- experimental

**Comment by damienderoistecso** [comment]
Frontier Series colour should be matched with Frontier Series color scheme on www.cso.ie

**Comment by damienderoistecso** [comment]
@CHanamy57 Can you try "#dee2e6" as the colour for neutral and see how it works in your dev environment. Especially for the buttons in a modal footer with class "btn-neutral"

**Comment by CHanamy57** [comment]
"#dee2e6" as colour for neutral passes Accessibility Requirements in cards and for buttons in modal footers
![image](https://user-images.githubusercontent.com/55976631/99690440-14ea1e00-2a80-11eb-94e1-532352784f49.png)
![image](https://user-images.githubusercontent.com/55976631/99690656-4a8f0700-2a80-11eb-942a-998f9dcbadb0.png)

**Comment by damienderoistecso** [comment]
@CHanamy57 Can you update the experimental color to be the same colour as warning 

You can check a frontier release e.g. "IBA01" for accessibility

**Comment by CHanamy57** [comment]
@damienderoistecso Experimental colour when changed to the same colour as Warning does pass accessibility

![image](https://user-images.githubusercontent.com/55976631/99697989-2b947300-2a88-11eb-9fb7-fc83de0cabe0.png)

**Comment by CHanamy57** [comment]
Passes accessibility with text-dark

![image](https://user-images.githubusercontent.com/55976631/99699028-677c0800-2a89-11eb-858a-9f6061cc2515.png)

**Comment by damienderoistecso** [comment]
Great, can you commit both changes so

**Comment by CHanamy57** [comment]
@damienderoistecso  Committed changes:

- Neutral colour changed to "#eaecee" to pass accessibility while keeping column separators & buttons visible.

- Experimental colour changed to same colour as warning "#EBA900".

- Text for Frontier Series changed to text-dark in HTML to pass Accessibility.

**Comment by lorenzobruni** [comment]
The HTML files contained a conflict of how neutral and default colors were used. This has been harmonized, so that neutral colors wont clash over default. The SCSS bootstrap files have been re-synched as well with the latest 4.5.2 version. 
The SCSS app.bootstrap.guideline.scss has also been included in the project in order to retain the custom SCSS for the additional flags.
![image](https://user-images.githubusercontent.com/53212047/99786281-2d0c7c80-2b16-11eb-906f-fdbb7ec5b918.png)

**Comment by lorenzobruni** [comment]
Test passed.
