### ISSUE TITLE
[BUG] Build Create and Update issue with notes containing fadas etc

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#273]
**Describe the bug**
Used dev
When you enter Irish text into a note the px file created or updated contains incorrect details in the NOTE.

**To Reproduce**
1. Go to Create ot build and load a px file
2. Update note with some text eg tástáil 1 Baile Átha Cliath
3. Save and View px file in notepad 
4. See error - NOTE[ga]="t&aacute;st&aacute;il 1 Baile &Aacute;tha Cliath";

**Expected behavior**
The note should be the same as what was entered

**Screenshots**
.
[E1056.20201106T141125.px.txt](https://github.com/CSOIreland/PxStat/files/5501907/E1056.20201106T141125.px.txt)

**Comment by lorenzobruni** [comment]
Fixed. 
@JohnPCarroll ready to test :-)

**Comment by liamie** [comment]
Seems to be correct now tested on single and dual language notes in create and update
