### ISSUE TITLE
[ENHANCEMENT] Allow pivot on dimensions other than the default time dimension in PxAPIv1

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#274]
PxApiV1 pivots on the time dimension by default. Enhancement is to override this by supplying a pivot dimension in the url

**Comment by neilfromcork** [comment]
Completed in DEV on the server side

**Comment by damienderoistecso** [comment]
client updated

**Comment by damienderoistecso** [comment]
Completed in client

@JohnPCarroll ready for test

**Comment by liamie** [comment]
The URL in the API  changes to reflect the pivot changes.
However the response appears to be unchanged i.e. data order etc.
Is this something only picked up on the client side i.e. use the data provided as per URL order or should the API response also change?

**Comment by neilfromcork** [comment]
Pivot only applies to csv and xlsx outputs. Pivot appears normal on these formats.

**Comment by neilfromcork** [comment]
We need to decide how we deal with units in a pivot. 
A possible method is:
- Where we are not pivoting on Statistics, include the units a single column
- Where we are pivoting on Statistics, include the unit in the Statistic column heading

**Comment by lorenzobruni** [comment]
> We need to decide how we deal with units in a pivot. @lorenzobruni @JohnPCarroll @damienderoistecso
> A possible method is:
> 
> * Where we are not pivoting on Statistics, include the units a single column
> * Where we are pivoting on Statistics, include the unit in the Statistic column heading

Both good to me.
Damien and I reviewed the Client making the same changes.

It will look like this:

![image](https://user-images.githubusercontent.com/53212047/98677440-ecae4100-2354-11eb-938d-f2452b73ecb1.png)

**Comment by lorenzobruni** [comment]
@JohnPCarroll 
The Client has been fixed. You can test it.

Wait for @neilfromcork to check the CSV and XLSX files.

**Comment by neilfromcork** [comment]
Completed in DEV using the rules outlined above- ready for test

**Comment by lorenzobruni** [comment]
@Killian-Carroll
This might be of your interest as well.
This is to extend the same functionality to stream the pivoted data across other APIs, such as JSON-RPC, RESTful and PxAPIv1.
Planned for next release too, 2.7.0

**Comment by lorenzobruni** [comment]
@JohnPCarroll talk to @damienderoistecso to get the details on how to test

**Comment by lorenzobruni** [comment]
Test passed
