### ISSUE TITLE
[BUG] Validation on release page is giving an error

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#275]
**Describe the bug**
Validation on release page is giving an error

**To Reproduce**
1. Go to  release page workflow
2. Scroll down to 
![image](https://user-images.githubusercontent.com/55874862/98389681-4c060b80-204c-11eb-988e-295e625491f6.png)
3. Add request
4. click add on the modal (settings don't seem to matter)
4. See error as per screen shot below

**Expected behavior**
As no apparent changes has occurred expect to proceed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/98389342-d39f4a80-204b-11eb-99c0-a374f1ac243e.png)

**Additional context**
This is occurring on multiple files even those that passed an import validation only moments before

**Comment by damienderoistecso** [comment]
Issue is related to ongoing development with #271 

If you update from svn it should work now
