### ISSUE TITLE
[BUG] Update WIP properties if live release gets updated

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#276]
**Describe the bug**
@neilfromcork  Currently when you create a WIP, it inherits properties from previous live. However, if you have a WPI and the current live gets updated with new properties, the WIP doesn't get these updated properties.

If a live gets updated with new properties, and there is a WIP, updated the WIP to reflect these properties. Also, if the WIP has a workflow request started after the live gets updated, than this workflow request should also get the updated properties.

@damienderoistecso On the client side, when updating a live with new properties, if a WIP exists, alert the user to the changes that will be applied to the WIP.

@neilfromcork This change on the client will need a new API to detect if a matrix has a WIP

**Comment by neilfromcork** [comment]
Server side complete. New API is called PxStat.Data.Release_API.ReadHasWipForLive. 

RlsExperimentalFlag needs to be included in the call to PxStat.Data.WorkflowRequest_API.Create

**Comment by damienderoistecso** [comment]
Client updated

@JohnPCarroll ready for testing

**Comment by lorenzobruni** [comment]
@JohnPCarroll talk to @damienderoistecso to get the details on how to test

**Comment by liamie** [comment]
Toggle options applied to both live and wip, once sign off is approved for the update of properties.

note1: Does not change the option if work in progress is in the pending live stage

note2: once enabled links for all three options on the live data page point to the same location for explanations however only frontier series is actually mentioned on this linked page should other "More Information" links be directed to appropriate about pages or is this going to be a central information point

**Comment by damienderoistecso** [comment]
@neilfromcork Can you look at note1 from above

With regard to note2, the location for explanations is maintained in the config file. At the moment, the business area has provided one page where all explanations will eventually be explained. We have the option in the config to use different remote pages to explain the properties if we wish

**Comment by neilfromcork** [comment]
Regarding Note 1 - I can't replicate it. The only time it happened was when I ran it from Postman with the cache disabled. Otherwise it works ok either via Postman or the front end.

**Comment by liamie** [comment]
AKM01 worked fine as it is the existing pending live that was updated i.e. the only release 1.0.
Problem is occurring when a current live e.g 1.0 is updated the pending live which will be 2.0 that's in the pipeline is unaffected

**Comment by neilfromcork** [comment]
Ok, understood. Fixed in DEV - Ready for test

**Comment by liamie** [comment]
On the first pass the pending live gets changed at the completion of approval stage of the update properties in the live it does not wait for sign off. Subsequent update requests do wait for sign off.

Also at no stage does the warning message appear in the modal that the current wip will be altered if the wip is at pending live 
![image](https://user-images.githubusercontent.com/55874862/99663693-e576e980-2a5e-11eb-8eb7-a1c54a7ffafd.png)

**Comment by damienderoistecso** [comment]
@neilfromcork "PxStat.Data.Release_API.ReadHasWipForLive" returns null when there is a pending live 

Also, a new WIP doesn't seems to be inheriting the correct properties, if the previous live had it's properties updated

**Comment by lorenzobruni** [comment]
@neilfromcork 
Did you implement the clear of the caching for the child release?

And this one? Thanks
> @neilfromcork "PxStat.Data.Release_API.ReadHasWipForLive" returns null when there is a pending live
> Also, a new WIP doesn't seems to be inheriting the correct properties, if the previous live had it's properties updated

**Comment by lorenzobruni** [comment]
@liamie Fixed, can you please test again? Thanks

> On the first pass the pending live gets changed at the completion of approval stage of the update properties in the live it does not wait for sign off. Subsequent update requests do wait for sign off.
> 
> Also at no stage does the warning message appear in the modal that the current wip will be altered if the wip is at pending live
> ![image](https://user-images.githubusercontent.com/55874862/99663693-e576e980-2a5e-11eb-8eb7-a1c54a7ffafd.png)

**Comment by neilfromcork** [comment]
@lorenzobruni - child cache is now clearing. Issues are ready for test

**Comment by JohnPCarroll** [comment]
Table Used BGA02. Issue with awaiting response.
The live properties were updated to include archived in Test 2.. When you go to update the Matrix with Awaiting Response Status the ADD Response Modal displays incorrect information. The archived should be ticked as it is on the properties section of the pages
Modal
![image](https://user-images.githubusercontent.com/44975474/99787326-845f1c80-2b17-11eb-8f06-3460b8a872ac.png)

Properties Section
![image](https://user-images.githubusercontent.com/44975474/99787513-be302300-2b17-11eb-8210-8c88a42f549d.png)

**Comment by liamie** [comment]
Also is the message incorrect, inhetitate should it be inherit?
![image](https://user-images.githubusercontent.com/55874862/99794183-b07f9b00-2b21-11eb-8c21-fd026489c990.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - Ready for test. Please note that the child workflow will not be updated until the parent workflow is signed off.

**Comment by damienderoistecso** [comment]
Client updated to fix typo. Also, warning message is now displayed at each stage of the workflow instead of just the request step

@liamie @JohnPCarroll  ready for test

**Comment by JohnPCarroll** [comment]
Test passed. Message displayed at each step of update properties in live release if there is a WIP
