### ISSUE TITLE
[ENHANCEMENT] Include workflow request details in comparison modal 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#277]
@damienderoistecso in comparison modal, include a column that shows details of updated properties and 'Live From date' if the release in in a workflow.

@neilfromcork In "PxStat.Data.Release_API.Read", can you include details about a potential workflow request from this database table

 
![image](https://user-images.githubusercontent.com/53211688/98685990-f0939080-235f-11eb-9db0-5783fb152a60.png)

**Comment by damienderoistecso** [comment]
@JohnPCarroll @liamie ready for test. Comparison modal should now display  workflow request details if there is one

**Comment by lorenzobruni** [comment]
@damienderoistecso update comparison columns based on colors bg-default

**Comment by damienderoistecso** [comment]
Client updated and tested
