### ISSUE TITLE
[BUG] General fixing of Labels

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#278]
Please record under this issue any general fix of Labels, system wide

**Comment by lorenzobruni** [comment]
**CODE FREEZE** for languages until [ENHANCEMENT] Add Irish as an official language #284 completed

**Comment by lorenzobruni** [comment]
> **CODE FREEZE** for languages until [ENHANCEMENT] Add Irish as an official language #284 completed

CODE FREEZE ended.

**Comment by lorenzobruni** [comment]
TO DO: Harmonies confirm messages across the system.

**Comment by CHanamy57** [comment]
- System/Cache:
Implement async setting in API
I/O Byte chart label changes
Flush Button change Label & Icon

- System/Performance:
Add reload button to reload performance entity with chosen dates
Updated labels

**Comment by lorenzobruni** [comment]
Test passed
