### ISSUE TITLE
[BUG] Delete Group not working

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#279]
When attempting to delete a Group with either Users and tables at ZERO count, then an error is returned.
See TST group.

![image](https://user-images.githubusercontent.com/53212047/98802577-6a348880-240b-11eb-96d0-06f9b0c91ccb.png)
![image](https://user-images.githubusercontent.com/53212047/98802623-7882a480-240b-11eb-9793-f74c6b6bffb7.png)

**Comment by neilfromcork** [comment]
Can't replicate in DEV. You may not delete a group if it (a) has Releases attached to it or (b) has users in it @lorenzobruni

**Comment by lorenzobruni** [comment]
@neilfromcork 
the TST group in production has both 0 Users and 0 Releases... unless the counter in wrong?

![image](https://user-images.githubusercontent.com/53212047/98846050-7427ad00-2446-11eb-9e20-dc4d63014f44.png)

Can you try running the Delete API in Production for the TST Group only and see the result?

Thanks

**Comment by neilfromcork** [comment]
@lorenzobruni - There is a problem in Production that does not exist in DEV. If I create a new group and then immediately delete it, all works ok in DEV. When I do the same in Production, I can't delete it.
Could this be an upgrade scripting error?

**Comment by neilfromcork** [comment]
Scripting error found and corrected.

**Comment by lorenzobruni** [comment]
Test passed
