### ISSUE TITLE
[ENHANCEMENT] Implement new PxStat.Data.Matrix_API.ReadByLanguage

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#280]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by neilfromcork** [comment]
Server side completed

**Comment by damienderoistecso** [comment]
Client updated

@JohnPCarroll ready for test

**Comment by liamie** [comment]
Table count and labels are correct.
