### ISSUE TITLE
[ENHANCEMENT] Implement new PxStat.Data.Matrix_API.ReadByCopyright

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#281]
Implement the new API for reading the list of Matrix by Copyright.
See `PxStat.Data.Matrix_API.ReadByProduct `for reference.

@damienderoistecso,
Pleas implement Client changes in Copyright page as per Product page in Dev

**Comment by neilfromcork** [comment]
Server side completed

**Comment by damienderoistecso** [comment]
Client updated

@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test Passed

**Comment by liamie** [comment]
Table count and labels are correct.
