### ISSUE TITLE
[ENHANCEMENT] Implement new PxStat.Data.Matrix_API.ReadByGroup

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#282]
Implement the new API for reading the list of Matrix by Group.
See `PxStat.Data.Matrix_API.ReadByProduct `for reference.

@damienderoistecso,
Pleas implement Client changes in Product page as per Product page in Dev

**Comment by neilfromcork** [comment]
Server side completed

**Comment by damienderoistecso** [comment]
Client updated. You can now view a list of tables attached to each group and go straight to the release page for that table

![image](https://user-images.githubusercontent.com/53211688/98961124-1efaa280-24fd-11eb-9170-0764e449f654.png)

![image](https://user-images.githubusercontent.com/53211688/98961175-2d48be80-24fd-11eb-870e-4b254eb4e3f0.png)


@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test Passed

**Comment by liamie** [comment]
Table count and labels are correct.
