### ISSUE TITLE
[ENHANCEMENT] Harmonize the context of Release Count and Matrix Count

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#283]
Review the following APIs to return the context of the Release Count and Matrix Count.

Matrix Context:
* **PxStat.System.Settings.Language_API.Read** `RlsCount` to `MtrCount`
* **PxStat.System.Settings.Copyright_API.Read** `RlsCount` to `MtrCount`

Release Context:
* **PxStat.Security.Group_API.Read** `GrpReleaseCount` to `RlsLiveCount` and `MtrCount` and  `CcnCount`
* **PxStat.System.Navigation.Product_API.Read** `PrcReleaseCount` to `RlsLiveCount` and  `MtrCount`

**N.B.** This requires Client side changes, please coordinate before releasing to Test.

**Comment by lorenzobruni** [comment]
Release context reviewed with @neilfromcork and it is correct.
Matrix context to amend as described.

**Comment by lorenzobruni** [comment]
Test passed

**Comment by damienderoistecso** [comment]
Client updated

**Comment by neilfromcork** [comment]
Counts and lists lined up with each other as per our workshop - for Language, Copyright,Product, Group @lorenzobruni @damienderoistecso

**Comment by damienderoistecso** [comment]
@neilfromcork Can you review counts and list for groups, might be out of sync

![image](https://user-images.githubusercontent.com/53211688/99276936-1bc92480-2825-11eb-830f-0dc4a6f35c79.png)
![image](https://user-images.githubusercontent.com/53211688/99276985-2c799a80-2825-11eb-9e24-26ce1406d451.png)

**Comment by neilfromcork** [comment]
Fixed now -ready for test

**Comment by damienderoistecso** [comment]
@JohnPCarroll @liamie reading for testing

When viewing the group, product, copyright and language entities, you should be able to get a list of tables associated with the relevant entity. The number of tables listed in the initial view should match the number listed in the modal when you click to view tables.

**Comment by liamie** [comment]
The figures in manage (groups, product, copyright) and system (language) summary pages match the contents figures.
