### ISSUE TITLE
[ENHANCEMENT] Add Irish as an official language

### ISSUE THREAD

**Issue by CHanamy57** [CSOIreland/PxStat#284]
Create an Irish language dictionary as part of default languages - ga.json

**Comment by lorenzobruni** [comment]
@CHanamy57 
As part of the issue #290 I must commit a change to the label.

It's the new keyword `ie-notice` as per below.
![image](https://user-images.githubusercontent.com/53212047/99102219-ad425780-25d5-11eb-9485-b517f225139f.png)

I appreciate if you can acknowledge it.
Thanks

**Comment by CHanamy57** [comment]
@neilfromcork Please find attached an Excel workbook of the Server side Irish translations for your reference
[PxStat-Internationalization-GA-Server.xlsx](https://github.com/CSOIreland/PxStat/files/5559919/PxStat-Internationalization-GA-Server.xlsx)

**Comment by CHanamy57** [comment]
Client Side Dictionary committed

**Comment by neilfromcork** [comment]
Completed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
Used Table ADR04. Is in English and Irish.
When I am in Irish and on the Releases Page. The Language defaults to English in the Source Section. This means when you view the data it is in English not Irish.

![image](https://user-images.githubusercontent.com/44975474/99687886-1239f980-2a7d-11eb-9510-ebd8f9fe90e5.png)

**Comment by liamie** [comment]
For the Irish I believe the Tables label on the summary pages below should be altered to Tábla as that is what it is on the modal when you click into the links in the column
![image](https://user-images.githubusercontent.com/55874862/99692062-c50c5680-2a81-11eb-9bbc-a28e6f4db70a.png)

Groups/Grúpaí
Subjects/Ábhair
Products/Táirgí
Copyright/Cóipchirt
![image](https://user-images.githubusercontent.com/55874862/99691218-e3be1d80-2a80-11eb-9041-3c0d888f6456.png)
Languages/Teangacha
![image](https://user-images.githubusercontent.com/55874862/99690568-33501980-2a80-11eb-864b-deefab8a0363.png)

**Comment by liamie** [comment]
Several labels in the Cache section are untranslated
![image](https://user-images.githubusercontent.com/55874862/99692542-52e84180-2a82-11eb-85a3-4c3b0c327711.png)

**Comment by lorenzobruni** [comment]
@CHanamy57 please follow up for the outstanding translations and the privacy policy

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/100208381-928aaf80-2f00-11eb-98aa-7dc57c10974b.png)

need to add "frontier series" to dictionary

**Comment by neilfromcork** [comment]
Can we also get translations for:

 "account-invitation": "A PxStat account has been created for you. Please click the link below to activate",
      "account-invitation-timeout": "This invitation will remain valid until {0} ",
      "account-invitation-complete": "Please click on the link below to complete your PxStat account setup",
      "account-reset": "Your account has been reset. Please click on the link below to complete"

 "account-invitation": "Activate your new PxStat account",
      "account-invitation-complete": "Complete your PxStat account activation",
      "account-reset": "Your account has been reset"

**Comment by CHanamy57** [comment]
Privacy Statement translation implemented - ready for test @liamie 
("Allow non-essential Cookies" & "Frontier Series" among latest words awaiting translation)

**Comment by liamie** [comment]
Privacy statement translated apart from "Allow non-essential Cookies" near button as stated waiting translation.

The initial cookies banner for cookies is not translated or "Allow" Button on same
![image](https://user-images.githubusercontent.com/55874862/100432205-28eddb00-3091-11eb-8fff-30ca2eafbe2f.png)

Also don't know if you want to translate "Manage Cookies" link to the same privacy document
![image](https://user-images.githubusercontent.com/55874862/100433060-6acb5100-3092-11eb-8e21-e41e8ce3d022.png)

**Comment by lorenzobruni** [comment]
> Privacy statement translated apart from "Allow non-essential Cookies" near button as stated waiting translation.
> 
> The initial cookies banner for cookies is not translated or "Allow" Button on same (doesn't detect language change)
> ![image](https://user-images.githubusercontent.com/55874862/100432205-28eddb00-3091-11eb-8fff-30ca2eafbe2f.png)
> 
> Also don't know if you want to translate "Manage Cookies" link to the same privacy document
> ![image](https://user-images.githubusercontent.com/55874862/100433060-6acb5100-3092-11eb-8e21-e41e8ce3d022.png)

The Allow button was hardcoded and it has been fixed.
@CHanamy57 please note I added the label "**allow**" in `en` and "#**allow**" in `ga` that must be translated.

All 3 label (This website.... Manage Cookies.... Allow) are displaying in English only because the Irish translation is still missing. 
They will automatically display in Irish when available.

**Comment by lorenzobruni** [comment]
This topic will continue in #307 following the release 3.0.0

**Comment by CHanamy57** [comment]
Latest Irish Translations implemented on client side - ready for test @liamie 
Still outstanding: System/Performance - Chart names, Flush Performance confirm message, Flush Performance success message -  added to EN dictionary Friday.
