### ISSUE TITLE
[BUG] Trying to add a new copyright results in error

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#286]
**To Reproduce**
1. Go to 'Manage> Copyrights'
2. Click on 'Add Copyright'
3. Fill in modal that appears and click Add button
4. See error and no copyright added

**Expected behavior**
Copyright to be added to list

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/99247367-c1b56880-27fe-11eb-8ffa-15bfde7b4e51.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
New copyrights can be created now correctly.
