### ISSUE TITLE
[ENHANCEMENT] Add share option to product pages

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#287]
**Describe the solution you'd like**
Like the table pages, add the share card to the product listing pages to allow for easy sharing.

Move the Share Card under the browse navigation in the data view for consistency with the products page

**Comment by damienderoistecso** [comment]
Client Updated

@JohnPCarroll @liamie ready for testing

**Comment by liamie** [comment]
Share cards are located correctly.

Links work correctly in dev once allowed for personal client location so should be fine when move live.
