### ISSUE TITLE
[ENHANCEMENT] Generate CSV and XLSX with or without CODES

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#289]
Currently the system generate CSV and XLSX containing both LABELS and CODES.
The change is to allow including or excluding the CODES form the generated output.

**Server side change:**
Ass the code parameter to the APIs with values true or false to enable/disable the CODES columns on the CSV and XLSX output.

**Client side change:**
Align the Codes toggle to reflect such change.

![image](https://user-images.githubusercontent.com/53212047/99284066-ba598380-282d-11eb-8fcf-e44ba61be7c8.png)

Talk to @lorenzobruni before implementing.

**Comment by neilfromcork** [comment]
Completed on server

**Comment by damienderoistecso** [comment]
Client side updated

We not have one code toggle button for simplicity. Works for both table selection and data view. CSV and Excel downloads now have codes or not depending on the toggle. Full download on left panel always has codes. API code also updated when codes are toggled.

@neilfromcork to remove codes from CSV and excel label columns as they are redundant and may cause confusion

**Comment by neilfromcork** [comment]
Completed on server.

**Comment by JohnPCarroll** [comment]
Test Passed
