### ISSUE TITLE
[BUG] Pivoting by multiple Statistics display incorrect decimal places

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#290]
If you pivot by Statistics having different Units with different Decimals, then the values are not correctly rounded to the relevant decimal.

See HPA02 and pick 2 Statistics then try pivoting... you will notice the decimals get incorrectly displayed.

**Comment by lorenzobruni** [comment]
Fixed
@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test P@assed
