### ISSUE TITLE
[BUG] Pivot Dropdown box is incorrectly positioned in dev

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#291]
**Describe the bug**
The dropdown options box is not beside the Pivot text. Refer to  data and releases/view data page 

**Expected behavior**
Drop down box to be positioned correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/44975474/99683516-5676cb00-2a78-11eb-962f-202f9d7ad865.png)

**Comment by damienderoistecso** [comment]
Flixed in client

@JohnPCarroll ready for test
