### ISSUE TITLE
[ENHANCEMENT] Create cut-down version of ReadCollection

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#293]
Amend ReadCollection to remove:
dimension
id
role
size

Keep the old version but rename as ReadMetaCollection (available only via JSON-RPC)

RESTful version of ReadCollection will return the amended version

**Comment by lorenzobruni** [comment]
@neilfromcork 
Both APIs are working but the ReadCollection (cut down version) is missing the JSON-stat 1.0 alternate link

![image](https://user-images.githubusercontent.com/53212047/99716872-8c2faa00-2aa0-11eb-8a48-9339bf283d2e.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Code review implemented

**Comment by lorenzobruni** [comment]
Test passed
