### ISSUE TITLE
[ENHANCEMENT] Build client side entity for performance API's

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#294]
**Describe the solution you'd like**
Build client side entity for performance API's deployed under #254

**Comment by CHanamy57** [comment]
Client side committed & ready for test @liamie

**Comment by liamie** [comment]
Page not appearing when click menu drop down
getting a 404 error message in the developer tools

**Comment by CHanamy57** [comment]
Error fixed - ready for test

**Comment by liamie** [comment]
Page appears now
No option to adjust time in tool, full days only. Is this to spec?
![image](https://user-images.githubusercontent.com/55874862/100467555-8e11f280-30ca-11eb-9a36-602eebd32498.png)

**Comment by CHanamy57** [comment]
@liamie  yes, the datepicker originally included option to adjust time but was requested to remove.

**Comment by liamie** [comment]
Appears to be correct. Flush cache button also provides a warning and and confirmation does work.
