### ISSUE TITLE
[ENHANCEMENT] Update view of pre-release data in Releases entity

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#295]
**Describe the solution you'd like**
If you are viewing pre-release data in the release entity, update the API card to call the correct API 

This will also allow business areas to easily read pre-release data programmatically for checking purposes

@neilfromcork thanks for the tip on this, you should be glad of the change!

Also, show a banner to alert users they are viewing confidential data.

**Comment by damienderoistecso** [comment]
Client updated

In releases, if a table is anything but live, a warmning message should appear for each view (table, chart or map). Also, in the API accordion, if it is not live the code gets updated for preRelease data and the REASTful and PxAPIv1 tabs gets disabled

@JohnPCarroll ready for test

@neilfromcork can you take a look in terms of using the API code for pre release data

**Comment by neilfromcork** [comment]
The JSON-RPC call looks ok from a server point of view

**Comment by JohnPCarroll** [comment]
Test passed for all.
