### ISSUE TITLE
[ENHANCEMENT] Improve SEO in data entity

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#296]
**Describe the solution you'd like**
In the browse menu, add the goTo link to the href attribute for each product 

In the results list add the goTo link to the href attribute for each table

**Comment by lorenzobruni** [comment]
Also, extend the breadcrumb to include the table code and title with the relative href
See example below.

[Home](url) / Agriculture / [Agricultural Land Prices](url) / [ARA02 - Agricultural Land Sales](url)

**Comment by lorenzobruni** [comment]
Include the HTML meta description and title for both the products and tables for SEO purpose.

**Comment by lorenzobruni** [comment]
List of tasks:
* Split between `breadcrumb` method and `meta `one
* About the breadcrumb, extend to include the table code - title and implement href with goTo.
* About meta - title we have 3 scenarios:
  - Homepage, where title = data.cso.ie (come from config as currently implemented) and meta-description = create label in internationalization with sprintf from config for the organisation.
  - Product, where title = product name and and meta-description = create label in internationalization with sprintf from product name
  - Table, where title = table code - table title and meta-description = create label in internationalization with sprintf from table code - table title by list of dimension and time-range (see pills).

**Comment by damienderoistecso** [comment]
Client updated.

Breadcrumbs, titles and meta description are now all set separately 

All public entities have meta description set

all entities have title set with meta description blank

@JohnPCarroll ready for testing. Chek that breadcrumbs are correct and page title in the tab is correct

**Comment by liamie** [comment]
On Data Table pages the tab still shows product not specific table
![image](https://user-images.githubusercontent.com/55874862/100460205-b3006880-30be-11eb-8f55-5884b9e6f403.png)
![image](https://user-images.githubusercontent.com/55874862/100460402-04a8f300-30bf-11eb-86c1-3022fece675e.png)

**Comment by damienderoistecso** [comment]
> On Data Table pages the tab still shows product not specific table (it does appear to add the product code on these also unlike the product page itself)
> ![image](https://user-images.githubusercontent.com/55874862/100460205-b3006880-30be-11eb-8f55-5884b9e6f403.png)
> ![image](https://user-images.githubusercontent.com/55874862/100460402-04a8f300-30bf-11eb-86c1-3022fece675e.png)

Client updated. @liamie ready for testing

**Comment by liamie** [comment]
Breadcrumbs and page title in the tab is correct now
