### ISSUE TITLE
[QUERY] Diffence between Other Vs Unknown in Analytics for Browsers

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#297]
@neilfromcork can you please clarify the difference between Other and Unknown in the Analytics API for reading the Browser information.

Are they duplicate for the same thing? Some how when a browser is not detected?
Can we harmonize it into one, like Unknown?

![image](https://user-images.githubusercontent.com/53212047/99918465-f3eb2c80-2d0e-11eb-964c-05c48b42c97c.png)

**Comment by neilfromcork** [comment]
The difference is as follows:
- Unknown means that the system just can't figure out what browser has been used (this often happens with Postman API calls)
- Other: We have a configurable limit to the number of browsers we want to count. If this limit is exceeded then the lesser used browsers are added together and put in the category of Other. Let me know how you would like to proceed @lorenzobruni

**Comment by lorenzobruni** [comment]
Perfect thanks!
