### ISSUE TITLE
[BUG]Toggle text clipping/sizing in mobile responsive

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#299]
**Describe the bug**
Clipping and sizing of toggles in mobile browsers(tested with chrome and firefox and edge on android phone) similar can be seen using responsive tool in firefox(pc)

**To Reproduce**

Toggle text seems to center/shift right on the full width of the toggle when open. Text appears correctly when closed this only noticeable in mobile/responsive size
![image](https://user-images.githubusercontent.com/55874862/99949073-588ba300-2d72-11eb-9ee1-7a0acffb5862.png)
![image](https://user-images.githubusercontent.com/55874862/99949773-79082d00-2d73-11eb-93b3-b2f62e70737c.png)

**Expected behavior**
Display full text in each setting

**Comment by liamie** [comment]
@damienderoistecso 
I think this is occurring, in part at least, due to the section in app.bootstrap.override.css 

/* Strech Buttons to fit the -sm size */

@media (max-width: 576px) {
  button.btn {
    display: block;
    width: 100%;
    margin-bottom: 0.25rem !important;
  }

}

I think the toggle doesn't play well with the enforced width 100% on button.btn

I get it to resolve by special casing button.btn in .toggle-group

.toggle-group button.btn{
 width: 50%;
}

so whole lot is now and fixed typo in stretch comment

/* Stretch Buttons to fit the -sm size */

@media (max-width: 576px) {
  button.btn {
    display: block;
    width: 100%;
    margin-bottom: 0.25rem !important;
  }
.toggle-group button.btn{
 width: 50%;
}
}

Worked for me using Edge, Firefox and Chrome. Not sure if anything else is affected by this isolation but I don't think so.

**Comment by damienderoistecso** [comment]
fixed in dev, ready for test
