### ISSUE TITLE
[ENHANCEMENT] Add pending live releases to dashboard

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#3]
**Is your feature request related to a problem? Please describe.**
Currently we are not displaying "Pending live" releases on the dashboard

**Describe the solution you'd like**
Include an accordion showing pending live releases.

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by neilfromcork** [comment]
API complete on server side

**Comment by RoseHayes** [comment]
Ready for testing.
