### ISSUE TITLE
[BUG] Copy share button not working in data view

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#302]
**Describe the bug**
Copy share button not working in data view

**Comment by damienderoistecso** [comment]
Cannot replicate. May be intermittent issue. Will investigate over time.

**Comment by liamie** [comment]
I find this occurs on tables if use the Browse to get to a product page then choose a table on that page.
Or if you use the breadcrumb to navigate to the product page and then choose a table.
The copy share does not work on the table page that loads after coming from a product page.
It seems to work if you link directly to the table page eg. from last updated list

**Comment by damienderoistecso** [comment]
Fixed in Dev. Copy to clipboard is now set in the data.share.library.js file

@liamie ready for test

**Comment by liamie** [comment]
This seems to be working correctly now tested coming from product page to table and button copied correctly.
