### ISSUE TITLE
[BUG] Search requires review

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#306]
Review search with a view to improving accuracy

**Comment by neilfromcork** [comment]
Value ratio of words to synonyms increased from 5 to 10. Highest priority given to Subject, then Product, then Release hits. SQL amendment to prevent double hits.

**Comment by neilfromcork** [comment]
Bug found - search was returning "any valid words in a list" rather than "all vaild words in a list"

**Comment by neilfromcork** [comment]
Amended search from AND to OR. Probably more user friendly, e.g. if you search for "Population poverty indicators" instead of "Population poverty rates" it shouldn't refuse data that closely matches the search term just because one word is not found. @lorenzobruni

**Comment by neilfromcork** [comment]
Ratio of word to synonym scores changed from 10:1 to 15:1

**Comment by JohnPCarroll** [comment]
Test passed
