### ISSUE TITLE
[ENHANCEMENT] Complete Irish translation for missing keywords

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#307]
This is the natural continuation of  #284.

@CHanamy57 / @liamie 
Please continue here any following updates as the #284 is resolved within the release 3.0.0

**Comment by CHanamy57** [comment]
Missing Translations from 3.2.0 added to updated 3.3.1 GA file

**Comment by lorenzobruni** [comment]
Duplicate of 335#
