### ISSUE TITLE
[BUG]  Missing PX keyword SOURCE generates an exception

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#31]
**Describe the bug**
Missing PX keyword SOURCE generates an exception rather than a friendly error

**To Reproduce**
Upload a PX file without SOURCE keyword

**Expected behavior**
friendly error should pop up

**Comment by lorenzobruni** [comment]
@neilfromcork to test please

**Comment by neilfromcork** [comment]
Tested after code change. Testing ok.
