### ISSUE TITLE
[ENHANCEMENT] Ensure where possible that similar calls in JsonRpc, PxApiv1 and RestFul use the same cache

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#314]
Currently a separate cache is used to read the same data for JsonRpc, PxApiv1 and RestFul. These should be the same cache wherever possible.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Seems to be picking up the cache with the same hash for the different calls
Test passed
