### ISSUE TITLE
[BUG] Workflow History shows incorrect usernames

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#319]
**Describe the bug**
When you call "PxStat.Workflow.Workflow_API.Read" when a release is awaiting signoff, it displays the incorrect "RspCcnCreateUsername" and "SgnCcnCreateUsername"

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
Teat passed. The person who completed the awaiting response is the name that is shown in awaiting signoff
