### ISSUE TITLE
[BUG] Align "ReadSynonym" method with system languages

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#32]
**Describe the bug**
"PxStat.System.Navigation.Keyword_API.ReadSynonym" is returning results for languages that are not system languages

**To Reproduce**
On client, when the system has only one language, search for a synonym, the results brings back languages that are not system languages

**Expected behavior**
Only return system languages

**Screenshots**
![image](https://user-images.githubusercontent.com/53211688/72145089-a46b6e80-3391-11ea-9bc1-6ebf90c0aca8.png)

**Comment by neilfromcork** [comment]
Ready for test
