### ISSUE TITLE
[ENHANCEMENT] Excel format - numbers stored as text

### ISSUE THREAD

**Issue by xprimexinverse** [CSOIreland/PxStat#321]
**Is your feature request related to a problem? Please describe.**
After I download a selection of data from PxStat in **Excel format**, when I open Excel it tells me that the **“numbers are stored as text”**. From a user perspective, this is inconvenient.

There is a simple fix in Excel. For example, I can simply highlight the cells and select “convert to number”. That said, it would be nice not to have to do this fix each time.

Would it be possible to look into this and pass the data into Excel such that the numbers are stored as numbers and not as text? My guess is that at some stage of the process they are stored as string values. There’s probably as simple type conversion function that could be used to tidy this up.

It’s not a big issue, but it would be a nice finish to the Excel format.

**Describe the solution you'd like**
When a user downloads and opens an Excel file from PxStat, the numberic values in Excel should be stored as numbers instead of being stored as text.

**Describe alternatives you've considered**
An easy fix is to let the user highlight the numeric cells in Excel and choose "convert to numbers". However, from a user perspective this would be quite annoying and repetitive.

**Additional context**
Please see the screenshot below.
![Number stored as text Excel](https://user-images.githubusercontent.com/3359065/100906628-466fda00-34c1-11eb-8c77-345b9aa0fa39.png)

**Comment by xprimexinverse** [comment]
Just to clarify. My example is from selecting a table and pivoting by quarter. That's when the numbers get stored as text. They are stored as numbers when I do not pivot before downloading the file.

**Comment by neilfromcork** [comment]
@xprimexinverse - Yes, we noticed this. This is scheduled for a fix in the next release.

**Comment by xprimexinverse** [comment]
Super! Thanks, Neil. 👍

**Comment by liamie** [comment]
Result Values no longer flagged as numbers stored as text in pivoted xlsx downloads
