### ISSUE TITLE
[ENHANCEMENT] Upgrade DeviceDetector.NET library

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#322]
Upgrade the [DeviceDetector.NET](https://www.nuget.org/packages/DeviceDetector.NET/4.2.0) library to better scan user agents.

**Comment by neilfromcork** [comment]
Fixed in DEV

**Comment by liamie** [comment]
3.11.6.0 removed 4.2.0 in DeviceDetector reference properties
