### ISSUE TITLE
[ENHANCEMENT] Open access changes

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#324]
**Describe the solution you'd like**

- Re-factor "Create User" to allow both AD and local users, e.g. tabs

- Create a public page for user to confirm email and set up 1FA password

  - Link to page by using body query string
  
  - Display full name, email and password input and repeat password
  
  - Display recaptcha

  - Send form detail (password hash sha256)  to API, on success, display message redirect to data.cso.ie

- Create a public page for use set up 2FA with QR code

  - Link to page by using body query string
  
  - Display full name, email and QR code based on secret key from server
  
  - User confirm QR scan complete, display success message and redirect to data.cso.ie

- Power user edit profile of local user to allow change 1FA 

- Power user edit profile of local user to allow change 2FA 

- Logged in User reset 2FA for all user type

- Logged in Local User reset 1FA 

- Update user list to differentiate AD user from local user

- Create login/logout button in nav bar. Read timeout cookie for this purpose

- On logout, fire API, display success and redirect to data.cso.ie

- Create login modal. 

  - Step 1: Email input, password input and recaptcha

  - Step 2: 2FA code and submit login

  - On success, redirect to data.cso.ie

   - On error, display message, reload login modal

- Implement cookie timeout with warning and expire value. run setTimeout function every second to check cookie time against current time. If we before warning, do nothing, after expire, logout and redirect, else display confirm to stay logged or logout. If stay logged in, reset cookie, else logout .

- Update client side API to update cookie timeout using .ajaxSend(). Cancel setTimeout function .ajaxComplete() run setTimeout function

- On list of users table, tables display last external login date

**Comment by damienderoistecso** [comment]
Client side code committed

@lorenzobruni client API library and constant file needs to be updated and index.html page updated to reflect new files when published

**Comment by lorenzobruni** [comment]
@JohnPCarroll @liamie @DeclanBuckley 
For testing this one you need to update the CORS policy, I can show you how to do it.

Talk to me first.

**Comment by JohnPCarroll** [comment]
User details now displayed correctly see closed bug 370

**Comment by liamie** [comment]
Getting this when going to Build>Import not every time but often enough to be noticeable can get it to occur most consistently if I add or delete a subject in manager before going to Build>Import
![image](https://user-images.githubusercontent.com/55874862/107789698-d778f200-6d49-11eb-968d-265508006e59.png)
![image](https://user-images.githubusercontent.com/55874862/107790250-7b629d80-6d4a-11eb-8a9f-b42ea3606d0d.png)

**Comment by lorenzobruni** [comment]
> Getting this when going to Build>Import not every time but often enough to be noticeable can get it to occur most consistently if I add or delete a subject in manager before going to Build>Import
> ![image](https://user-images.githubusercontent.com/55874862/107789698-d778f200-6d49-11eb-968d-265508006e59.png)
> ![image](https://user-images.githubusercontent.com/55874862/107790250-7b629d80-6d4a-11eb-8a9f-b42ea3606d0d.png)

@liamie I think that @neilfromcork has identified the issue. This was probably because of some DB transactions conflict.
Because it was happening occasionally, then it is hard to prove it 100% so I mark it as resolved but if you notice it again please reopen it immediately. Thanks a mill , GOOD SPOT!
