### ISSUE TITLE
[BUG] Last Updated Tables is not updating ***Urgent***

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#325]
The Last Updated Tables box did not update with the tables that were published this morning

Thanks

**Comment by damienderoistecso** [comment]
@neilfromcork "PxStat.Data.Cube_API.ReadMetaCollection" cache doesn't seem to be invalidating when a pending live reaches the live from time. This fix might have to be done in trunk

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Seems to be updating on emergency fine 
and seems to be flushing at sign off
have some matrix in the pending live to test

**Comment by lorenzobruni** [comment]
> Seems to be updating on emergency fine
> and seems to be flushing at sign off
> have some matrix in the pending live to test

I assume the pending will be fine as they follow the same implementation of the emergency.
I move this one to tested in order to speed up the release.
Thanks!
