### ISSUE TITLE
[BUG] The last entry of pivoted excel and csv datasets contain a duplicate of the second last line

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#327]
In some circumstances, the last entry of pivoted excel and csv datasets contain a duplicate of the second last line rather than the last data item

**Comment by JohnPCarroll** [comment]
Test passed. Used all types of Pivot dropdown options.

**Comment by liamie** [comment]
Front end pivot row counts now do not match downloaded csv/xls row count

![image](https://user-images.githubusercontent.com/55874862/101648005-4c216e80-3a31-11eb-9c1a-cc11a540f15c.png)

however the csv and xls have a row count of 96 (97-1 for title row) for the same pivot which I think is correct for the same pivot 

I think this is occurring on even numbered classifications chosen

**Comment by JohnPCarroll** [comment]
Liam,
	Is that error in Live or Dev only ?

Regards

John Carroll
Higher Executive Officer/Systems Analyst
Technology Dissemination
Email john.carroll@cso.ie
Telephone 021 4535630
Subject to the disclaimer at http://www.cso.ie/en/emaildisclaimer/ Faoi r�ir ag an s�anadh ag http://www.cso.ie/en/seanadhriomhphoist/

**Comment by lorenzobruni** [comment]
Duplicate of #328
