### ISSUE TITLE
[BUG] Front end pivot rows missing from display

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#328]
Dev and live all tables I think
Front end pivot row counts now do not match downloaded csv/xls row count

![image](https://user-images.githubusercontent.com/55874862/101648005-4c216e80-3a31-11eb-9c1a-cc11a540f15c.png)

however the csv and xls have a row count of 96 (97-1 for title row) for the same pivot which I think is correct for the same pivot 

I think this is occurring on even numbered classifications chosen not order if an odd number of classifications are chosen the row counts match in both the front end and download

_Originally posted by @liamie in https://github.com/CSOIreland/PxStat/issues/327#issuecomment-741841802_

**Comment by lorenzobruni** [comment]
@liamie 
I checked this against LRW04.
It has 9.324 rows in total.

When I pivot by Sex (3 variables) I get 9.324 / 3 = 3.108 rows.
![image](https://user-images.githubusercontent.com/53212047/102207733-67272f00-3ec6-11eb-9557-ff983d066454.png)


When I pivot by Statistics (4 variables) I get 9.324 / 4 = 2.331 rows.
![image](https://user-images.githubusercontent.com/53212047/102207632-465ed980-3ec6-11eb-8015-cc704ba6784f.png)

Same results in the CSV.

Can you please check again?
Is the issue happening with a specific table instead?

Thanks

**Comment by liamie** [comment]
> @liamie
> I checked this against LRW04.
> It has 9.324 rows in total.
> 
> When I pivot by Sex (3 variables) I get 9.324 / 3 = 3.108 rows.
> ![image](https://user-images.githubusercontent.com/53212047/102207733-67272f00-3ec6-11eb-9557-ff983d066454.png)
> 
> When I pivot by Statistics (4 variables) I get 9.324 / 4 = 2.331 rows.
> ![image](https://user-images.githubusercontent.com/53212047/102207632-465ed980-3ec6-11eb-8015-cc704ba6784f.png)
> 
> Same results in the CSV.
> 
> Can you please check again?
> Is the issue happening with a specific table instead?
> 
> Thanks

Hi Lorenzo,
Try the same pivot by sex again on the same table but only have two Nationality chosen. All the rest criteria the same.

**Comment by lorenzobruni** [comment]
Resolved by fixing the offset when splicing the reduced data

**Comment by liamie** [comment]
Row count is now consistent between pivots on download and front end
