### ISSUE TITLE
[BUG] RESTful xlsx output outputs as text rather than excel

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#329]
If you choose the XLSX output in RESTful, the encoded data is shown on the browser screen rather than downloading it as a file

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. All formats should be tested on JSON-rpc, PxAPI and RESTful

**Comment by liamie** [comment]
This now downloads a file in the XLSX format.
Works fine generally for smaller/medium file sizes but as the restful version always pulls the full data regardless of pivot or limited value selection it means that what appears to be a small datset in the front end tool and may not even prompt a large dataset warning could lead to a user attempting to download a file that exceeds the limits of XLSX(further investigating that at the moment)

**Comment by damienderoistecso** [comment]
> This now downloads a file in the XLSX format.
> Works fine generally for smaller/medium file sizes but as the restful version always pulls the full data regardless of pivot or limited value selection it means that what appears to be a small dataset in the front end tool and may not even prompt a large dataset warning could lead to a user attempting to download a file that exceeds the limits of XLSX
> Note: may also impact all Full Downloads in XLXS format current row limit 1,048576
> ![image](https://user-images.githubusercontent.com/55874862/101791396-658eed00-3afb-11eb-89f4-67da4a44b994.png)
> 
> User can download a file that exceeds limit and will only get a partial recovered file may require a soft warning as to limits and suggested formats for large datasets

This is an API interface and it can't provide other information upfront.
