### ISSUE TITLE
[ENHANCEMENT] Delete Workflow Request with no Response

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#33]
**Is your feature request related to a problem? Please describe.**
Deleting a Workflow Request created by mistake that has not been reviewed (either Approved nor Rejected) yet.

**Describe the solution you'd like**
Add a Delete button to the Workflow History to delete a Workflow Request that has not received yet a Response.

**Comment by lorenzobruni** [comment]
Feature implemented Client side.
The Button is enabled only for Workflow Requests without a Response.

@neilfromcork can you please complete the Server side change by implementing the `PxStat.Workflow.WorkflowRequest_API.Delete` with the `RlsCode` as mandatory input?

![image](https://user-images.githubusercontent.com/53212047/72158400-0b008480-33b2-11ea-9c07-1310a18155f7.png)

**Comment by neilfromcork** [comment]
Fix deployed @lorenzobruni
