### ISSUE TITLE
[ENHANCEMENT] Official Statistics icon rendering

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#330]
**Describe the solution you'd like**
If a table is marked as "Official = true", display the official icon in the search results and table view page, otherwise don't display the icon

**Comment by damienderoistecso** [comment]
Fixed in dev

@JohnPCarroll ready for test

**Comment by liamie** [comment]
Icon on official statistics : true. No Icon on statistics : false.
