### ISSUE TITLE
[BUG]download of full dataset/large files in csv format giving network error

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#331]
**Describe the bug**
Download of full dataset/large files in csv format giving network error (live and dev)

**To Reproduce**
Download full dataset in csv

**Expected behavior**
Full dataset in expected format

**Screenshots**

![image](https://user-images.githubusercontent.com/55874862/101904245-75670980-3bad-11eb-806e-1071a8802a70.png)

**Comment by lorenzobruni** [comment]
@liamie 
is this happening irrespective of the size of the table?
Can you please check how long time it takes before throwing the exception? 3 minutes perhaps?

Thanks

**Comment by lorenzobruni** [comment]
@liamie any about about the above? Thanks

**Comment by liamie** [comment]
This seems to be only very large files are timing out now. ie million+ of records had occurred on some files in 100's of thousand but these seem to be correct now. Over 10 min before exception error in some cases.

**Comment by lorenzobruni** [comment]
@liamie 
can you please inform a large table having this issue?

Thanks

**Comment by liamie** [comment]
TEM10

**Comment by liamie** [comment]
This I think has been addressed by [ENHANCEMENT] Improve CSV/XLSX max size error handling #409 
Full datasets for CSV greater than the max size cannot be downloaded directly on the front end.

**Comment by lorenzobruni** [comment]
Duplicate of #409
