### ISSUE TITLE
[ENHANCEMENT] Replace Open XML libraries with ClosedXML

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#334]
ClosedXML is a simple and flexible library for creating XLSX files ( see https://github.com/ClosedXML/ClosedXML)

- Replace the existing Open XML libraries with ClosedXML
- Replace the simple sheet view with an XLSX Table
- Always include a default pivot table, pivoted either by the requested dimension or else with no column data but easily editable to move the dimensions around.

**Comment by damienderoistecso** [comment]
@neilfromcork Can you confirm if this is fixed and ready for testing?

**Comment by neilfromcork** [comment]
Completed but needs to be deployed to dev environment for testing

**Comment by neilfromcork** [comment]
Fixed - ready for test

**Comment by damienderoistecso** [comment]
@neilfromcork Negative values seem to be excluded from Excel output

**Comment by lorenzobruni** [comment]
Test passed.
