### ISSUE TITLE
Synchronize internationalisation files between branches

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#335]
Identify all strings that need to be translated in the Irish internationalisation files  (should all be prepended with '#') and send for translation.

**Comment by liamie** [comment]
some additions from 3.4.0
Login
![image](https://user-images.githubusercontent.com/55874862/107393008-2e848a00-6af2-11eb-8927-115ed0bc04f7.png)
Logout
![image](https://user-images.githubusercontent.com/55874862/107392015-2aa43800-6af1-11eb-9d62-464e7214d7c5.png)
Verify + Translations on the text in the Logon and Verify 2FA windows
and in user
![image](https://user-images.githubusercontent.com/55874862/107392525-aef6bb00-6af1-11eb-9c91-43d53ed0957f.png)

in the confirm logout 
buttons and header is translated but not main text.
![image](https://user-images.githubusercontent.com/55874862/107392858-039a3600-6af2-11eb-8d52-fdc45150bbf5.png)

**Comment by lorenzobruni** [comment]
@CHanamy57 please forward translations for the last 3.4.0 release

**Comment by CHanamy57** [comment]
Latest 3.4.0 release translations have been forwarded.

**Comment by damienderoistecso** [comment]
@CHanamy57 Can you follow up on this with the Irish Office

**Comment by neilfromcork** [comment]
[For translation.xlsx](https://github.com/CSOIreland/PxStat/files/6335125/For.translation.xlsx)
@damienderoistecso - can these be included in a list for translations? Thanks.

**Comment by liamie** [comment]
Closed and emalgamated with #559
