### ISSUE TITLE
[BUG] Error loading releases from GoTo

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#336]
**Describe the bug**
When you load a release from a GoTo, you get an error because the TinyMCE library hasn't finished loading and the entity is trying to set TinyMCE editors. This will be resolved by hosting our own version of TinyMCE on github, thus avoiding the need to load the library dynamically with an API key https://github.com/CSOIreland/Client-API-Library/issues/2

**Comment by lorenzobruni** [comment]
Fixed and tested

**Comment by lorenzobruni** [comment]
Form validation must happen when triggering the modal on demand.
