### ISSUE TITLE
[BUG] Unable to add a new user in development environment

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#337]
**Describe the bug**
When I add a user an error message is displayed

**To Reproduce**
1. Go to Manage- Users and select Add User button
2. Select relevant user details and select Add button
3. Error message appears
![image](https://user-images.githubusercontent.com/44975474/103626506-315cef80-4f34-11eb-8a4f-f087d91c62ac.png)

**Expected behavior**
User added

There is no issue with adding users in the live environment

**Comment by damienderoistecso** [comment]
@JohnPCarroll Everything to do with Users is currently being re-factored due to #324. Please don't log any issues against the users entity until we are ready to start testing this enhancement
