### ISSUE TITLE
[BUG] Once invoked mobile view filter for product pages can persist to other pages

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#339]
**Describe the bug**

**To Reproduce**
1. Use mobile size screen
2. Go to a 'Products' listing page either via browser or breadcrumb option
2. The filters expand/collapse option should appear if screen is small enough 
![image](https://user-images.githubusercontent.com/55874862/103673682-cb915780-4f75-11eb-9632-b17ec649c086.png)
 
3. Use breadcrumb to return to home page and the filter expand/collapse
![image](https://user-images.githubusercontent.com/55874862/103673682-cb915780-4f75-11eb-9632-b17ec649c086.png) 
will remain on screen 
4. It will also appear on a table page if one is chosen from last update table at this point.
![image](https://user-images.githubusercontent.com/55874862/103674187-5eca8d00-4f76-11eb-85b7-29b6b376d1fe.png)

**Expected behavior**
Filter option to disappear on pages on which it has no functionality for.

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/103672241-f67aac00-4f73-11eb-8c30-285373d7fb8c.png)

**Additional context**
Filters themselves seem to clear on full size but the expand collapse option for mobile seems to be retained in some circumstances

**Comment by damienderoistecso** [comment]
@liamie ready for test

**Comment by liamie** [comment]
This seems to be correct now filter no longer appearing on pages without functional filter options.
