### ISSUE TITLE
[BUG] Tables appearing twice on the Pending Live List

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#341]
**Describe the bug**
Some tables are appearing twice on the Pending Live List. This occurs when the workflow history contains 2 entries. 

**To Reproduce**
1. Go to Releases and Pending Live List or DashBoard Pending Live

**Expected behavior**
Table should appear only once no matter how many entries are contained in the Workflow history

**Screenshots**
![image](https://user-images.githubusercontent.com/44975474/103751473-456e2300-5000-11eb-9d70-7bd2132b426c.png)

**Comment by lorenzobruni** [comment]
@neilfromcork to review

**Comment by neilfromcork** [comment]
Can't replicate. Possible data issue in previous release.

**Comment by JohnPCarroll** [comment]
I have recreated the issue in the Development environment using Table ELA02.
1. You reject in the Workflow Sign-Off.
2. You then approve each step of the workflow process and Approve the Sign-off. 
3. The table will appear twice in the Pending Live section.

**Comment by neilfromcork** [comment]
Thanks for that @JohnPCarroll . Fixed in DEV, ready for test now.

**Comment by JohnPCarroll** [comment]
Test Passed
