### ISSUE TITLE
[ENHANCEMENT] Improve Image quality on CSO Logo and name image

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#344]
At different size/scales image quality of CSO Logo and name image on data.cso.ie can appear blurred, still readable but lower resolution
![image](https://user-images.githubusercontent.com/55874862/103782729-b8db5900-502f-11eb-90d8-cae0989f0a4f.png) 
compared to same logo/text on main cso.ie site
![image](https://user-images.githubusercontent.com/55874862/103782527-7ade3500-502f-11eb-8c10-4aced5b20d75.png)

**Describe the solution you'd like**
Similar clarity at all sizes

**Additional context**
Most noticeable on IPad

**Comment by lorenzobruni** [comment]
@damienderoistecso please liaise with @neilfromcork  about fitting XLSX too

**Comment by damienderoistecso** [comment]
@neilfromcork Can you update the path to the logo in the global config to this url please

https://cdn.cso.ie/static/img/cso_logo_312_x_108_96dpi.png

**Comment by neilfromcork** [comment]
@damienderoistecso now on test - looks ok to me for the XLSX file

**Comment by damienderoistecso** [comment]
Client update to reflect new logo

@liamie ready for test

**Comment by liamie** [comment]
Appears to be crisper on PC in general and at smaller mobile when image is full ie text has dropped below.

![image](https://user-images.githubusercontent.com/55874862/110964175-d2a85d80-834a-11eb-8df9-8a41864e98a3.png)

Still some blurring and discoloration during middle responsive views ie when the test text on the right hand side hasn't dropped below but still better.
![image](https://user-images.githubusercontent.com/55874862/110967196-089b1100-834e-11eb-9453-a5d6f4dca798.png)

Test passed as improved but will review on IPad when live.
