### ISSUE TITLE
[ENHANCEMENT] Modularize the Search function

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#345]
Ensure that the Search works in a more modular fashion by:

- Use a number of simpler stored procedures rather than one big one
- Apply as much of the intelligence as possible to the C# code

**Comment by lorenzobruni** [comment]
@JohnPCarroll please retest the Search,  thanks

**Comment by lorenzobruni** [comment]
fixed by @neilfromcork

**Comment by lorenzobruni** [comment]
@JohnPCarroll please speak to @neilfromcork for knowing what has changed

**Comment by JohnPCarroll** [comment]
Test Passed. With using "and"  it reduces the number of tables returned which is helpful.
