### ISSUE TITLE
[BUG] Metadata not updating on client

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#347]
Outdated metadata shown on the client in some circumstances after a release

**Comment by lorenzobruni** [comment]
To be reviewed as caching for Pre-Metadata should be cleared on upload or signoff

**Comment by lorenzobruni** [comment]
@neilfromcork to test

**Comment by neilfromcork** [comment]
Fixed in DEV ready for test

**Comment by JohnPCarroll** [comment]
Test passed. 
Used One Table and all was correct
Used Two Tables associated with two Subjects and all was correct.
