### ISSUE TITLE
Ability to sort Periods/Statistics/Classifications in Create

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#349]
When you need to re-order new period/statistic/classification in the create option you currently have to delete the entire entries and re-input them in the new order.  Can we please have the ability to re-order (drag and drop) in the create.

**Comment by lorenzobruni** [comment]
@damienderoistecso to review together

**Comment by lorenzobruni** [comment]
Work on this together with #350

**Comment by lorenzobruni** [comment]
Duplicate of #350
