### ISSUE TITLE
Adding a Classification in Build-Create. Leave site pop-up appears and page reloads to Data screen [BUG] 

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#351]
I was updating a Classification for TSA09 in the Test. 
I brought the PX into the Create, deleted the old Classification and Uploaded the new one.
When I clicked on Add Classification, the Leave Site? pop-up appeared.
I clicked Cancel and tried again. A new pop-up appears with the Prevent dialogs option.
Every time I click Add Classification the pop-up appears. If I click Leave or tick the Prevent additional dialogs box, the page reloads to the Data screen.
![Test Create Add Classification error](https://user-images.githubusercontent.com/59689411/105213360-827cfe00-5b46-11eb-8a28-39d2b6c65a9b.PNG)

**Comment by damienderoistecso** [comment]
Fixed in 3.3.1  

@JohnPCarroll @liamie whoever is testing, can you make sure that the upload statistic, classification and period works correctly as I re-factored all these functions

**Comment by JohnPCarroll** [comment]
Leave Site Popup gone. There is an another issue with Validation of statistics. Will log a bug on it
