### ISSUE TITLE
Carriage returns/new lines in Footnote not rendering correctly after publish [BUG] 

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#353]
When adding or updating a Footnote ->
Download Source -> go to Build - Update - Parse
Make the changes to the footnote. Add carriage returns/new lines - Update
Then Import & Publish -> the extra lines disappear and the text appears in one block.
![Footnote vs Public Note](https://user-images.githubusercontent.com/59689411/105842068-905ed300-5fcd-11eb-9158-1cf48d36b598.PNG)

However, the source PX file retains the formatting.
![Footnote Source file](https://user-images.githubusercontent.com/59689411/105842096-98b70e00-5fcd-11eb-9ac0-80366a729fdb.PNG)

**Comment by damienderoistecso** [comment]
@neilfromcork When a footnote with line breaks is added to the px file during the update, it's passed in the api (""PxStat.Build.Build_API.Update") as follows 

![image](https://user-images.githubusercontent.com/53211688/105843876-327fba80-5fd0-11eb-80bd-3ff652a88b3b.png)

When a public footnote is added in "PxStat.Data.Release_API.UpdateComment" it's passes the same as above as follows

![image](https://user-images.githubusercontent.com/53211688/105844087-8e4a4380-5fd0-11eb-8aa8-bc1919c4a71d.png)

However, when they are output in JSON-stat they are different

![image](https://user-images.githubusercontent.com/53211688/105844215-c94c7700-5fd0-11eb-9fed-2af401e7b41e.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by lorenzobruni** [comment]
@neilfromcork please review consolidating multiple spaces into 1

**Comment by neilfromcork** [comment]
Amended to consolidate only the spaces but not the newlines

**Comment by lorenzobruni** [comment]
Test passed by @neilfromcork

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test
