### ISSUE TITLE
[BUG] Build Create download CSV file incorrect for Periods

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#354]
**Describe the bug**
The time Periods downloaded CSV file does not contain the row with the Text CODE and VALUE if no values exist.

**To Reproduce**
1. Go to Periods
2. Click on Download CSV
3. Open file and you will see no header

**Expected behavior**
The first row of the file should contain CODE in column one and VALUE in column two

**Additional context**
If details are entered in this csv file it will no load

**Comment by damienderoistecso** [comment]
Fixed in dev 3.3.1

**Comment by damienderoistecso** [comment]
@JohnPCarroll can you test this now in 3.4.0 please
