### ISSUE TITLE
Allow option to enable/disable pagination in table widgets

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#355]
**Describe the solution you'd like**
In the table widget options, allow users to toggle whether pagination is enabled or disabled in the datatable widget

**Comment by damienderoistecso** [comment]
Client update in 3.3.1

**Comment by damienderoistecso** [comment]
Applied in dev

**Comment by damienderoistecso** [comment]
Ready for testing in 3.4.0

**Comment by JohnPCarroll** [comment]
Test passed

**Comment by liamie** [comment]
Option on or off Passed, but limit on the pagination in widget.
Note: pagination dropdown does not provide a view all option in the widget/html file even with pagination enabled.

**Comment by damienderoistecso** [comment]
> Option on or off Passed, but limit on the pagination in widget.
> Note: pagination dropdown does not provide a view all option in the widget/html file even with pagination enabled.

This will be resolved by #367  when we consolidate the DataTable rendering only via the Widget.
