### ISSUE TITLE
[ENHANCEMENT] Refactor Footer Template

### ISSUE THREAD

**Issue by CHanamy57** [CSOIreland/PxStat#357]
Improve Responsive mobile functionality
Remove Sticky Footer
Include CSO Contact information
Add Social Media Links

**Comment by CHanamy57** [comment]
Committed refactored footer template
New footer.library.js file created for rendering additional links & Social Media Buttons
Update of config.json for contact details & Social Media

**Comment by damienderoistecso** [comment]
@liamie ready for testing

**Comment by liamie** [comment]
Testing in the 3.3.1 Dev.

When you click a follow us Icon the info text remains visible if you return to the pxstat page page even if that Icon is no longer highlighted. It sticks in view until something else is clicked.
Below Facebook link was clicked then went back to the pxstat page and text remained until something else was clicked.
![image](https://user-images.githubusercontent.com/55874862/106741168-3f755d00-6613-11eb-9daf-b3fb2ee3fcd4.png)
![image](https://user-images.githubusercontent.com/55874862/106741588-cd514800-6613-11eb-9f5b-da6b59c8eaa9.png)

**Comment by damienderoistecso** [comment]
Fixed in dev

@liamie ready for re-test

**Comment by liamie** [comment]
The last activated external link middle column or email link on far left. remains highlighted/grey after clicking until something else is clicked but the internal Privacy and Manage Cookies return to white once the modal is closed. Modal also breaks tabbing order and reverts to start. If possible I think this should be consistent for last clicked link either highlighted or not. Underlining for currently highlighted link is unaffected by this when using mouse.
![image](https://user-images.githubusercontent.com/55874862/106750247-7d787e00-661f-11eb-864f-0992781f98a9.png)
