### ISSUE TITLE
[ENHANCEMENT] Typo in General Privacy Terms

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#358]
responsability should be responsibility 
![image](https://user-images.githubusercontent.com/55874862/106748315-faeebf00-661c-11eb-9f13-2b9a454f4dd4.png)

**Comment by damienderoistecso** [comment]
Fixed in 3.4.0 

@liamie Ready for test

**Comment by liamie** [comment]
Correct now.
