### ISSUE TITLE
Widget Table default sort

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#359]
If table sorted by column can the widget code reflect it

**Comment by damienderoistecso** [comment]
Applied in dev. Available in next release

**Comment by damienderoistecso** [comment]
@liamie @JohnPCarroll 

This can be tested by using the new download snippet feature and when you open the HTML file you should see the new feature

**Comment by JohnPCarroll** [comment]
Test Passed

**Comment by liamie** [comment]
This works as described but is affected by the search/codes limit described in #360 so only sorts correctly if all lines are unfiltered or filtered only by labels.

**Comment by lorenzobruni** [comment]
@liamie correct, let's include this into the #367
