### ISSUE TITLE
Include default search in table widget

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#360]
If a user filters the data by using the datatable search, this search is included in the widget snippet

**Comment by damienderoistecso** [comment]
Updated in client 3.4.0

@liamie @JohnPCarroll This can be tested by using the new download snippet feature and when you open the HTML file you should see the new feature

**Comment by liamie** [comment]
Search set in the browser is presented as default in the downloaded html. This is free to be altered in the HTML file as required afterwards. Downloaded csv in the html file reflects changes also.

**Comment by liamie** [comment]
Does not work if display codes is set to true and a code or part off is used as the search criteria as even though code in widget/file is set to true code is not displayed/used so displays 0 entries in file or only those entries where search criteria is on a label also.
eg. table CCA10
with display codes set to true
in the normal search for "06" codes are picked up
![image](https://user-images.githubusercontent.com/55874862/107521964-1290ef00-6bab-11eb-9c1f-2499af00b8c9.png)
but in the downloaded widget file codes are not
![image](https://user-images.githubusercontent.com/55874862/107521698-c6de4580-6baa-11eb-9a42-cdabb2fb91d4.png)

**Comment by lorenzobruni** [comment]
@liamie good spot, we need a new enhancement for implementing the Codes in the Widget

**Comment by lorenzobruni** [comment]
Tested with the above caviat.
