### ISSUE TITLE
Chart custom JSON invalid after you reset chart

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#362]
**Describe the bug**
If you decide to "Reset" the chart, the custom JSON code box gets emptied but this causes an error to appear saying that the JSON is invalid. The custom JSON should go back to an empty JSON options object

**Comment by damienderoistecso** [comment]
@liamie ready for testing

**Comment by liamie** [comment]
{
    "options": {}
}
is now reset/retained also so error does not appear
