### ISSUE TITLE
[BUG] Single value charts showing confusing increments

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#363]
line
![image](https://user-images.githubusercontent.com/55874862/107509893-19b00100-6b9b-11eb-907c-2dbeabc58693.png)
column
![image](https://user-images.githubusercontent.com/55874862/107509536-9bebf580-6b9a-11eb-86fd-a843defa069d.png)

The value on the increments appear the same for multiple increments. Should these not be still different figures at each step or not shown at all.

**Comment by lorenzobruni** [comment]
@liamie where is this from?
How to reproduce exactly? Thanks

**Comment by liamie** [comment]
Should be similar on any chart with a single series chosen. On bar charts the multivalues are on the  x-axis.
![image](https://user-images.githubusercontent.com/55874862/108725905-c20c8080-751e-11eb-9fc1-af142ac19108.png)

**Comment by damienderoistecso** [comment]
Issue was caused by the "Auto-scale" option set to true when you only had one item on the x-axis.

Now, when you only have one variable on the x-axis, auto-scale is set to false and disabled, reset to enabled and true once more than variable  is selected for the x-axis

**Comment by damienderoistecso** [comment]
@liamie ready for test

**Comment by liamie** [comment]
Seems to be better for single variables.
However as the Auto-Scale is now forced to true even if manually set to false for multi the scaling problem still exists if the values are close together to the same figure as below 
![image](https://user-images.githubusercontent.com/55874862/110933111-3e2b0480-8324-11eb-8431-fc9e2bd4faf9.png)

**Comment by damienderoistecso** [comment]
@liamie ready for test again

**Comment by liamie** [comment]
The hard lock on Auto-Scale is now gone of multi values.
The hard lock not just default still remains on single values.

Visually I notice no difference on the Auto-Scale option set to true so a series with all similar values still provides a confused chart. 
As above image the first 2 columns have figures of 32.1 and the third has 31.9 but all the y values are labeled 32. this does seem to alleviate if there are greater variance between the values.

**Comment by liamie** [comment]
The Auto-Scale issue seems to be resolved with the use of additional decimal places to distinguish the increments.
