### ISSUE TITLE
[BUG] In Build Create Validation of Statistics not working correctly in development environment

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#364]
**Describe the bug**
The validation of statistics does not happen on the First pass but will work on the Second pass.

**To Reproduce**
1. Go to Build Create
2. Import a file
3. In the statistics section manually input or load duplicate Statistics
4. Details accepted on 1st run but not on 2nd run

**Expected behavior**
Validation should take place every time and relevant messages displayed

**Comment by damienderoistecso** [comment]
Fixed in 3.4.0

@JohnPCarroll Ready for test
