### ISSUE TITLE
[BUG] New matrix not being found in search

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#365]
need to make sure search cache only lives until next publish date ** 3.4.0 URGENT***

**Comment by lorenzobruni** [comment]
@neilfromcork Kind of urgent, thanks

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Probably caused by search for a WIP matrix code before it was published resulted in no data in the cache. Cache is now fixed to expire at the next publish date/time.

**Comment by JohnPCarroll** [comment]
Test Passed
