### ISSUE TITLE
[BUG] PxStat.Workflow.Workflow_API.ReadLive broken

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#366]
The API is broken see log below

> 
> 2021-02-10 15:55:39,776 [5] ERROR PxStat.Template.BaseTemplate_Read`2.Read:121 - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition for 'CcnDisplayName'
>    at CallSite.Target(Closure , CallSite , Object )
>    at PxStat.Security.ActiveDirectory_ADO.MergeAdToUsers(ADO_readerOutput& result) in Z:\Workbench\PxStat\branches\3.4.0\server\PxStat\Entities\Security\ActiveDirectory\ActiveDirectory_ADO.cs:line 168
>    at PxStat.Workflow.Workflow_BSO_ReadLive.Execute() in Z:\Workbench\PxStat\branches\3.4.0\server\PxStat\Entities\Workflow\Workflow\BSO\Workflow_BSO_ReadLive.cs:line 51
>    at PxStat.Template.BaseTemplate_Read`2.Read() in Z:\Workbench\PxStat\branches\3.4.0\server\PxStat\Entities\Template\BaseTemplate_Read.cs:line 121

**Comment by lorenzobruni** [comment]
@neilfromcork is this fixed? Thanks

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by lorenzobruni** [comment]
@JohnPCarroll this can be tested by opening the Dashboard and checking the content for the Live Tables.
