### ISSUE TITLE
[ENHANCEMENT] Widget Table - Include Codes 

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#367]
Extend the Widget Table to render Codes on demand via the toggle and also consolidate the DataTable rendering only via the Widget.

N.B. Please remember to resynch the Table pivoting #328

**Comment by damienderoistecso** [comment]
As per #355  ensure pagination in widget includes option to show all if pagination enabled

**Comment by liamie** [comment]
Currently codes will not be rendered to widgets
