### ISSUE TITLE
[BUG] HTML tags not being removed from px file on import

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#368]
http symbols not being removed from px file on import - e.g. in NOTES

**Comment by neilfromcork** [comment]
Fixed in DEV. Also BBCODE transform removed from JSON-stat output

**Comment by neilfromcork** [comment]
@JohnPCarroll - Script applied to DEV to convert existing notes to BBCode

**Comment by lorenzobruni** [comment]
@JohnPCarroll This can be tested by placing a valid HTML tag i.e. `<a href="something">something</a>` in the notes of a PX file when importing
