### ISSUE TITLE
[BUG] CcnDisplayName misnaned as CcnName

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#371]
### Server Side

Several APIs (and DB?) are referring to CcnName instead of CcnDisplayName following the OpenAccess enhancements #324 

### Client Side

* Rename `CcnName `to `CcnDisplayName `everywhere.

**Comment by neilfromcork** [comment]
Server side fixed

**Comment by lorenzobruni** [comment]
Test passed with @neilfromcork
