### ISSUE TITLE
[BUG] Cookie Consent Banner lost

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#373]
The Cookie Consent Banner went lost following the refactoring of the footer which is no longer sticky.
Move the Cookie Consent Banner to the top instead to avoid overlapping with the new no-sticky footer

**Comment by damienderoistecso** [comment]
Client updated

**Comment by damienderoistecso** [comment]
@liamie ready for testing ASAP please for the next release. Please delete any existing cookie for cookie consent that you may have

**Comment by lorenzobruni** [comment]
@damienderoistecso 
FYI, @liamie is off today, I mark this passed.

Cheers
