### ISSUE TITLE
[ENHANCEMENT] Implement Logarithmic scale in Analytics 

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#374]
Change the scale for the Referrer and Language bar charts to Logarithmic for better visibility.

**Comment by damienderoistecso** [comment]
@liamie As you can see on live, the y axis scale is at regular intervals and is therefore hard to compare 
![image](https://user-images.githubusercontent.com/53211688/108232418-aa0db900-713a-11eb-81eb-9d618848aeba.png)

Now, with Logarithmic, it should be easier to see all values even if one value is far higher than all the rest
