### ISSUE TITLE
[BUG]New Local or AD user gets 2FA email when setup but no token is created on the database

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#376]
New Local or AD user gets 2FA email when setup but no token is created on the database. This means that the user can't complete 2FA setup.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test.

**Comment by damienderoistecso** [comment]
@JohnPCarroll this must be tested in test-data.cso.ie

**Comment by liamie** [comment]
testing on test, but response email and link points to dev

**Comment by neilfromcork** [comment]
@liamie - error in deployment to test, can you try again?

**Comment by liamie** [comment]
This seems to be correct now. Was able to proceed through full steps for Password and 2FA setup with new user.
