### ISSUE TITLE
Analytics to be only viewable on a table that you have access to

### ISSUE THREAD

**Issue by carolfinlay** [CSOIreland/PxStat#377]
We always were of the belief that you could only see the analytics for a table that you had access to as a moderator.

After being set up as a moderator in test I was able to see the analytics for tables that I didn't have access to.  

Also I would have real concerns about people using the "Open Access" functionality having access to CSO analytics.

Can you please ensure that any moderator will only have access to the analytics of the tables that they access to

**Comment by damienderoistecso** [comment]
A few changes can be made to change how analytics are accessed. 

Only power users and admins can access the analytics entity and call the "PxStat.Security.Analytic_API.Read" to get any analytics they want. 

Moderators will only be able to access analytics from their dashboard and will only see a limited set of analytics for the tables that they have access to through their group privilege's. 

@damienderoistecso Remove moderator access to the analytics entity

@neilfromcork Remove moderator access to "PxStat.Security.Analytic_API.Read" 

@neilfromcork For the following API's, ensure the user has the right to that matrix based on their group privilege's. If it's called by a moderator, a matrix will have to be included and they must have the right to access this matrix.

- "PxStat.Security.Analytic_API.ReadBrowser"
- "PxStat.Security.Analytic_API.ReadOs"
- "PxStat.Security.Analytic_API.ReadEnvironmentLanguage"
- "PxStat.Security.Analytic_API.ReadLanguage"
- "PxStat.Security.Analytic_API.ReadTimeline"
- "PxStat.Security.Analytic_API.ReadFormat"
- "PxStat.Security.Analytic_API.ReadReferrer"

**Comment by neilfromcork** [comment]
Completed in DEV - ready for test @damienderoistecso

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for testing. Analytics entity only available to power users and admins. Moderators can only see their analytics through the dashboard entity

**Comment by JohnPCarroll** [comment]
Test Passed. Can only see their own tables via the dashboard. Can the Analytics Tab be removed as it serves no purpose for a moderator

**Comment by damienderoistecso** [comment]
> Test Passed. Can only see their own tables via the dashboard. Can the Analytics Tab be removed as it serves no purpose for a moderator

@JohnPCarroll Analytics tab should not be available to moderators. Is this the case?

**Comment by damienderoistecso** [comment]
Analytics now removed from menu for moderators
@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Test passed
