### ISSUE TITLE
[BUG] Error thrown when user attempts to dowload an XLSX file with more than 1048576 rows

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#378]
When a user attempts to download an XLSX dataset with more than the maximum allowed number of rows (1048576) an error is thrown. This should instead be handled at the front end and the back end.

**Comment by neilfromcork** [comment]
Error with appropriate message returned when the limit is exceeded. New entry in global config - dataset.xlsx-threshold

**Comment by damienderoistecso** [comment]
@neilfromcork move from global config to static

**Comment by neilfromcork** [comment]
Ready for test in TEST

**Comment by JohnPCarroll** [comment]
Test passed in TEST Environment
