### ISSUE TITLE
[BUG] Intermittent row locked error when trying to extend session

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#379]
For an externally logged in user, when attempting to extend the session time in the database, an error occurs because the row is locked.

**Comment by neilfromcork** [comment]
Fixed in DEV

**Comment by damienderoistecso** [comment]
@neilfromcork include c# transaction

**Comment by neilfromcork** [comment]
Try..catch moved from sp to c#  code
Ready for test in TEST

**Comment by damienderoistecso** [comment]
@lorenzobruni to review

**Comment by lorenzobruni** [comment]
Code amended to enforce a Snapshot Isolation also on Read Base Template
@neilfromcork to run some tests

**Comment by neilfromcork** [comment]
@lorenzobruni - looks ok in testing so far.

**Comment by neilfromcork** [comment]
Issue seems to be resolved in TEST
