### ISSUE TITLE
Include unit in statistic option title in table select

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#380]
Currently when you hover over an option in the statistic dimension of the table selection, the unit is not displayed. This would be useful in the case of long labels where the unit is not visible in the select

![image](https://user-images.githubusercontent.com/53211688/108840536-67326200-75ce-11eb-8da7-70bef8b36ac5.png)

Now, when you hover over a statistic, the unit is displayed  

![image](https://user-images.githubusercontent.com/53211688/108840902-e162e680-75ce-11eb-84eb-a6033947f664.png)

**Comment by damienderoistecso** [comment]
@liamie ready for testing

**Comment by liamie** [comment]
Seems to be displaying correctly for table select and related, including release view data and chart statistic select.
Also appears correct in other languages.
