### ISSUE TITLE
Extent table widgets to include responsive option

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#382]
Allow an optional toggle to include the responsive option to datatables. 

It's enabled by default and if turned to false, then the table get a horizontal scroll instead to allow for viewing when the table width overflows it's container

**Comment by damienderoistecso** [comment]
@liamie ready for testing

**Comment by liamie** [comment]
Seems to be correct. If a row is to long the  remainder is available by clicking the entry. Can the list of additional columns be formatted and aligned  similar to the front end, to clearly distinguish between title and content.

In widget
![image](https://user-images.githubusercontent.com/55874862/109143730-4269f600-7758-11eb-8ad5-16b3fbade9da.png)

In frontend
![image](https://user-images.githubusercontent.com/55874862/109144132-b4dad600-7758-11eb-9bbd-4222d5e52cae.png)

**Comment by damienderoistecso** [comment]
@liamie In PxStat we use bootstrap which give it the format as per your second screenshot. For the widgets, we render with the default datatables look and feel as the widgets could be used in any environment with or without bootstrap. The widget will render using bootstrap if the HTML page that the widget is embedded in already has bootstrap.
