### ISSUE TITLE
Index monitor for defragmentation[ENHANCEMENT] 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#384]
Index Monitor for defragmentation

**Comment by liamie** [comment]
On dev now

**Comment by damienderoistecso** [comment]
@liamie can you tell us the name of the api for the read please?

**Comment by CHanamy57** [comment]
@liamie fragmentation spelled as "fragmentaion" in API

**Comment by liamie** [comment]
@CHanamy57 Should be correct there now

**Comment by CHanamy57** [comment]
Database Entity ready for test

**Comment by liamie** [comment]
@CHanamy57
This message appears after the successful reorganize for both the individual table and the all table options
![image](https://user-images.githubusercontent.com/55874862/110925167-c4424d80-831a-11eb-9a67-e60ede3c5ab6.png)

However the tables list is not actually reloaded unless the reload button is clicked.

1. Should the success message be reorganized rather than reloaded 
2.  Should the table/index list  be updated on a successful reorganize to reflect the new figures

**Comment by damienderoistecso** [comment]
@CHanamy57 

Can we change the confirm messages to the following

For the overall reorganise : "<p>You are about to reorganise all indices for all tables. </p><p>Confirm to continue, or Cancel.</p>"

**Comment by damienderoistecso** [comment]
@CHanamy57  Can we change the confirm messages to the following

For the overall reorganise : You are about to reorganise all indices for all tables. Confirm to continue, or Cancel

For the table reorganise create a dynamic message : You are about to reorganise all indices for the table {0} Confirm to continue, or Cancel

Once either reorganise is successful you can display a generic success message like "Reorganise successful" and then simply reload the entity to re-draw the updated database read

**Comment by CHanamy57** [comment]
Updated Confirm & Success messages
ReDraw bug fix

Ready for test

**Comment by damienderoistecso** [comment]
@liamie Can you test the issue you raised in #390

**Comment by liamie** [comment]
Issue seems to be cleared now.
