### ISSUE TITLE
[BUG] Checking for duplicate item in dimensions bug

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#385]
**Describe the bug**
In build create, if you try and add a variable with the code "pop" is was causing the validation of that dimension to fail due to the variable being called "pop" as this is a function name in javascript also

**Comment by damienderoistecso** [comment]
Fixed in dev

@liamie ready for test

**Comment by liamie** [comment]
This seems to be correct now. Tested for STATISTIC,PERIOD and CLASSIFICATION also
