### ISSUE TITLE
[BUG] Slow return of individual data items in CTM01

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#389]
CTM01 (5m records) - individual records take a few minutes to return once selected

**Comment by JohnPCarroll** [comment]
Test passed in DEV and TEST.  Took around 12 seconds in Test and 20 in DEV

**Comment by neilfromcork** [comment]
@lorenzobruni - amended data delete job to include index re-org as the next step. Added some logging and "execute as owner". Looks ok for data update, also tested ok for two simultaneous updates.

**Comment by neilfromcork** [comment]
Indexes changed in TD_DATA and TM_DATA_CELL
sp rewritten to move where clause to the join
Awaiting patch to enable OPTION(USE HINT('ENABLE_PARALLEL_PLAN_PREFERENCE')) to force parallel processing
