### ISSUE TITLE
[BUG] px file. Decimal value different on output to Input file

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#39]
**Describe the bug**
A px file which contains decimal and Precision which are different should contain the lowest value in the decimal. EG EY003.px had DECIMAL=0; and PRECISION("Statistic","Percentage change 2011-2016")=1; on input and has DECIMAL=1; and PRECISION("Statistic","Percentage change 2011-2016")=1;

**To Reproduce**
1. Go to releases
2. Click on EY003
3.  View source 
4.  View Data and download

**Comment by neilfromcork** [comment]
Fix in Dev.

**Comment by damienderoistecso** [comment]
Duplicate of https://github.com/CSOIreland/PxStat/issues/46
