### ISSUE TITLE
[ENHANCEMENT] Make PxStat database agnostic - with reference to PostgreSQL

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#391]
It should be possible to use a different database for PxStat without requiring an extensive re-write of PxStat. 

Notes from investigations:

- If migrating to Amazon Web Services, AWS provide a very useful tool, i.e. SCT (Schema Conversion Tool)
-  SCT will only migrate the database as a structure. If data needs to be migrated, that must be done seperately (Use a tool like SSIS)
- PostgreSQL is highly case sensitive. This can normally be changed by creating a new Collation and changing the entry for the database in the pg_database table.. However AWS does not allow the pg_database table to be altered except by the pgadmin user (equivalent to sysadmin in SQL Server) which doesn't appear to be available for AWS users.. If we were to migrate the existing database without changing the collation, we would need to be much more careful about testing etc.
- SCT will convert all Stored Procedures to PostgreSQL stored procedures. However PostgreSQL works better if data retrieval sp's are converted to Functions. This must be done manually.
- A specific API ADO needs to be created for PostgreSQL (and any other database that needs to be used). I would recommend that both the new ADO and the SQL Server specific ADO extend the same interface.
- PxStat should not refer to either the new or existing ADO, rather it should only reference the interface
- PxStat should not create its own ADO, rather the we should use the principal of Dependency Injection to supply it with the appropriate implementation of the ADO Interface. A factory class should be created for situations where an appropriate ADO needs to be obtained.
- PostgreSQL functions and sp's must be called with the parameters in the same order as the sp's and functions. Because this is not required in SQL server ADO.Net, sequences are not always in the correct order. For this to work in the new ADO we would need to query the pg_get_function_identity_arguments function first in order to map the parameters.
- Bulk load is not inherently supported in PostgreSQL. However an implementation exists in github at https://github.com/neisbut/Npgsql.Bulk
- The Always Encrypted columns would need to be explicitly encrypted and unencrypted. Support would need to be built into the ADO
- It would be possible to prepare PxStat for database neutrality without necessarily creating a new version of the ADO

**Comment by liamie** [comment]
Ground work completed
