### ISSUE TITLE
[ENHANCEMENT] Update DATABASE STATISTIC after INDEX REORGANIZE 

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#393]
Database statistic should be updated after a reorganize in order to enable the execution plan to take advantage of it.

**Comment by neilfromcork** [comment]
Deployed in TEST - ready for test. An entry is made in the Logging table after database statistics are updated

**Comment by damienderoistecso** [comment]
Client side updated and tested
