### ISSUE TITLE
Add "Themes" to navigation above Subjects

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#394]
### Client Side Changes
Create a new entity under Manage called "Themes"
Allow for the reading, creation, updating and deleting of themes.
Themes cannot be deleted if they have associated subjects.

Update the subjects entity to make each subjects a sibling of a theme.
In the subjects table, add a column to display it's parent theme.
In the update of subjects, allow the ability to change the parent theme.
When creating a subject, you must assign a parent theme.

In the browse menu, add a new layer for Themes

### Server side changes
Create new entity for the creating of Themes. This should be more or less the exact same as the existing subjects entity with the same rules and API's
In the subject entity, the read, create and update API's will have to be updated to reflect the new linkage to Themes.
"PxStat.System.Navigation.Navigation_API.Read" will have to be update to reflect the new structure

**Comment by neilfromcork** [comment]
Sever side complete

**Comment by damienderoistecso** [comment]
Client side update

Ready for testing

@JohnPCarroll @liamie a full regression test of Products and Subjects should be conducted along with Themes as the addition of Themes had an effect on both subjects and products

**Comment by liamie** [comment]
Theme name don't wrap in the browse column seem to wrap fine else where in the manage section etc.
As per example if the list was longer the whole page would be blotted out.
![image](https://user-images.githubusercontent.com/55874862/112608732-9547d380-8e12-11eb-94e4-5effa9f9e9e4.png)

**Comment by damienderoistecso** [comment]
> @damienderoistecso Theme name don't wrap in the browse column seem to wrap fine else where in the manage section etc.
> As per example if the list was longer the whole page would be blotted out.
> ![image](https://user-images.githubusercontent.com/55874862/112608732-9547d380-8e12-11eb-94e4-5effa9f9e9e4.png)

Fixed in dev @liamie ready for testing

**Comment by JohnPCarroll** [comment]
This should be Titled Update Theme
![image](https://user-images.githubusercontent.com/44975474/112646756-b83cac80-8e3f-11eb-9829-5dd6549eb3d2.png)

**Comment by JohnPCarroll** [comment]
For each row in the column "No Subjects"  can it be updated so that you can open up the relevant subjects  page. This currently applies to the Subjects page which allow you access the relevant Products page.

**Comment by damienderoistecso** [comment]
> This should be Titled Update Theme
> ![image](https://user-images.githubusercontent.com/44975474/112646756-b83cac80-8e3f-11eb-9829-5dd6549eb3d2.png)

Fixed in dev

@JohnPCarroll ready for test

**Comment by damienderoistecso** [comment]
> For each row in the column "No Subjects" can it be updated so that you can open up the relevant subjects page. This currently applies to the Subjects page which allow you access the relevant Products page.

Unlike products, there is now subjects page per theme. All subjects are displayed on a single datatable so it would be impossible to bring you directly to the relevant subject.

**Comment by JohnPCarroll** [comment]
Subjects not in Alpha order on Browse Section of Data page 
![image](https://user-images.githubusercontent.com/44975474/112832486-4b1e5680-908d-11eb-860b-30159242028e.png)

Subjects not in Alpha order where the drop down option is available including Manage Products, Keywords Subjects and Products and Releases Update Navigation. They appear to be running in Date Creation order
![image](https://user-images.githubusercontent.com/44975474/112832902-df88b900-908d-11eb-8b1b-c495a6dd8af0.png)

**Comment by neilfromcork** [comment]
Subjects now sorted by Subject Name @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Test passed for order of subjects in Browse section of data page.
Subjects not in alpha order in drop down options

**Comment by liamie** [comment]
Language translations required for Theme, titles and buttons also.
e.g. 
![image](https://user-images.githubusercontent.com/55874862/113733889-c36ec280-96f2-11eb-9c85-39af3ed6220f.png)

**Comment by damienderoistecso** [comment]
> Language translations required for Theme, titles and buttons also.
> e.g.
> ![image](https://user-images.githubusercontent.com/55874862/113733889-c36ec280-96f2-11eb-9c85-39af3ed6220f.png)

We are awaiting translations for this from the Irish office. If we don't have them, the system defaults to English

**Comment by damienderoistecso** [comment]
> Test passed for title in Update Theme
> Test passed for order of subjects in Browse section of data page.
> Subjects not in alpha order in drop down options

@neilfromcork Can you look at the order of subjects returned from "PxStat.System.Navigation.Subject_API.Read"

**Comment by neilfromcork** [comment]
Subjects now in alpha order in drop down of Manage Subjects page @damienderoistecso

**Comment by damienderoistecso** [comment]
Client looks OK to me now. 

@JohnPCarroll ready for test
