### ISSUE TITLE
[ENHANCEMENT] Add ability mark a classification variable as an "eliminator" variable

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#395]
### Client Side
In build create & update, allow users to select one variable if they wish to mark as the "eliminator" variable from each classification.

### Server side
In build create & update, include this "elimination" variable details in Px file
In the JSON-stat output, include the elimination variable details in the extension properties
Consider should the elimination variables be included in the "About" sheet in the XLSX output

**Comment by damienderoistecso** [comment]
@neilfromcork in addition to above, I presume "PxStat.Data.Cube_API.ReadMetaCollection" should also contain elimination details in it's extension

**Comment by damienderoistecso** [comment]
Client side updated and committed

Ready for testing once @neilfromcork gives the OK in terms validation on the server

**Comment by neilfromcork** [comment]
Server side complete for:
- Build Update
- Build Create
- Import
- Read data
Ready for test in DEV

**Comment by damienderoistecso** [comment]
@neilfromcork "PxStat.Build.Build_API.Read" isn't returning the correct elimination details in the extension. Input source contains elimination in px file but all elimination properties in JSON-stat extension set to null

**Comment by JohnPCarroll** [comment]
When a Dual language px file called JCEY037( English and Irish ) is used in the Build create and update option, The English Language is used in the Irish Elimination section of the Gaeilge Tab. The Irish Language should be used as is done in the Classification section.

![image](https://user-images.githubusercontent.com/44975474/113872751-10629f80-97ac-11eb-83ae-b9565d06dcf5.png)

**Comment by damienderoistecso** [comment]
> When a Dual language px file called JCEY037( English and Irish ) is used in the Build create and update option, The English Language is used in the Irish Elimination section of the Gaeilge Tab. The Irish Language should be used as is done in the Classification section.
> 
> ![image](https://user-images.githubusercontent.com/44975474/113872751-10629f80-97ac-11eb-83ae-b9565d06dcf5.png)

This is not in the Irish tab. It is outside of the tabs. As elimination is identified by codes only, we always use the default language to display the label of the elimination code

**Comment by JohnPCarroll** [comment]
The Build Create and Update are correct for Duel Language The px file created/updated contains the ELIMINATION Details.

One question if a classification has one variable only should it be allowed for Elimination ? For example classifications containing State only.

**Comment by damienderoistecso** [comment]
> The Build Create and Update are correct for Duel Language The px file created/updated contains the ELIMINATION Details.
> 
> One question if a classification has one variable only should it be allowed for Elimination ? For example classifications containing State only.

I would say there is no need to restrict elimination where only one variable exists. The selection of elimination is always at the desecration of the user and a logical elimination should always be chosen. I would argue that there should never be a classification with only one variable, why breakdown something by one!

**Comment by JohnPCarroll** [comment]
The build create and Update are correct for Single Language. The px file created/updated contains the ELIMINATION Details.

**Comment by JohnPCarroll** [comment]
The elimination extension is included in JSON-Stat 2.0 ( extract only )
	"extension": {
		"matrix": "JCE1054",
		"reasons": [],
		"language": {
			"code": "en",
			"name": "English"
		},
		"elimination": {
			"C02684V03251": "02",
			"C02800V03468": "100300"
		},

**Comment by neilfromcork** [comment]
Elimination now showing in Read - Fixed in DEV, ready for test

**Comment by JohnPCarroll** [comment]
Build Create fails when a new table is created 
The elimination section is not populated when you select a classification from the Search Classification results page.
![image](https://user-images.githubusercontent.com/44975474/114550228-ddac2180-9c59-11eb-9ff8-1a08b81d2094.png)

**Comment by JohnPCarroll** [comment]
Test passed for Elimination details to be shown in the Build Update if they exist on the px file.

**Comment by damienderoistecso** [comment]
I can include the elimination for a period added via search

@neilfromcork Do you think you could extend "PxStat.Data.Classification_API.Read" to give the details if any of the elimination variable if it exists?

**Comment by liamie** [comment]
In build create if Clear Dimensions button is used the Elimination section is unaffected and the delete buttons and reset options break as the classifications in Eliminator section cannot be deleted
![image](https://user-images.githubusercontent.com/55874862/114559097-49df5300-9c63-11eb-99aa-fcdac11bd32f.png)

**Comment by JohnPCarroll** [comment]
Build update issue when Elimination section when reset button used. Values do not revert to initial value
Was 
![image](https://user-images.githubusercontent.com/44975474/114563501-5c5b8b80-9c67-11eb-864d-ab84308e5049.png)

Amended to
![image](https://user-images.githubusercontent.com/44975474/114563590-7301e280-9c67-11eb-8802-989c2d52a359.png)

Selected Reset Button and the new value in elimination remains. Should revert to initial value
![image](https://user-images.githubusercontent.com/44975474/114563804-a6447180-9c67-11eb-90e1-9912521bc427.png)

**Comment by damienderoistecso** [comment]
> In build create if Clear Dimensions button is used the Elimination section is unaffected and the delete buttons and reset options break as the classifications in Eliminator section cannot be deleted
> ![image](https://user-images.githubusercontent.com/55874862/114559097-49df5300-9c63-11eb-99aa-fcdac11bd32f.png)

@liamie This issue should be resolved now in dev

**Comment by damienderoistecso** [comment]
> Build update issue when Elimination section when reset button used. Values do not revert to initial value
> Was
> ![image](https://user-images.githubusercontent.com/44975474/114563501-5c5b8b80-9c67-11eb-864d-ab84308e5049.png)
> 
> Amended to
> ![image](https://user-images.githubusercontent.com/44975474/114563590-7301e280-9c67-11eb-8802-989c2d52a359.png)
> 
> Selected Reset Button and the new value in elimination remains. Should revert to initial value
> ![image](https://user-images.githubusercontent.com/44975474/114563804-a6447180-9c67-11eb-90e1-9912521bc427.png)

@JohnPCarroll fixed in dev ready for test

**Comment by liamie** [comment]
The ELIMINATOR Keyword should appear in the PX File Format Recommended KEYWORD order while PXSTAT import seems to  recognise and implement Eliminators in their current order the other readers eg. PC-AXIS need to have the associated VALUES/Variables declared before the ELIMINATOR in order to be recognised correctly. Declaring the Eliminator beforehand means it  may not be used.

**Comment by JohnPCarroll** [comment]
Test passed for Build Update Elimination reset. Initial values are reverted to when Reset Button used

**Comment by neilfromcork** [comment]
Server side complete - @damienderoistecso  can you check?

**Comment by neilfromcork** [comment]
Self re-assigned for px file ordering as outlined by @liamie

**Comment by neilfromcork** [comment]
Position of ELIMINATION tag in PX file re-ordered to comply with px recommendations @liamie

**Comment by damienderoistecso** [comment]
Client side fully complete

@liamie now if you search for a classification and if the one you select to use has an elimination already set, this gets inherited. You can search for classification C03397V04089 in dev to test this

**Comment by liamie** [comment]
Position of ELIMINATION seems to work now correctly for loading.
In the PX generated file Second Language seems to be correct as it is the value not code used for ELIMINATION and so needs translation for each language however when this is displayed Elimination section of the create or update only the English appears.
![image](https://user-images.githubusercontent.com/55874862/114744857-0873a400-9d46-11eb-8769-709032429548.png)
As noted the PX file now seems to reflect the correct language when saved it is just not displayed on the front end.

Note: while PX file format produced appears to be correct now its function is not utilised in PXSTAT
we do not generate a YES/NO option and our default for front end is still no value chosen is "all" not the ELIMINATION value listed in the file

**Comment by damienderoistecso** [comment]
> Position of ELIMINATION seems to work now correctly for loading.
> In the PX generated file Second Language seems to be correct as it is the value not code used for ELIMINATION and so needs translation for each language however when this is displayed Elimination section of the create or update only the English appears.
> ![image](https://user-images.githubusercontent.com/55874862/114744857-0873a400-9d46-11eb-8769-709032429548.png)
> As noted the PX file now seems to reflect the correct language when saved it is just not displayed on the front end.
> 
> Note: while PX file format produced appears to be correct now its function is not utilised in PXSTAT
> we do not generate a YES/NO option and our default for front end is still no value chosen is "all" not the ELIMINATION value listed in the file

As elimination is code based, we always display the elimination deatils in the default language and outside of the language dimension tabs. We will look at utilising the functionality in the next release and in future visualisation projects

**Comment by damienderoistecso** [comment]
@JohnPCarroll @liamie can you confirm if there are any further observations/issue and if not are we happy to mark as tested?

**Comment by neilfromcork** [comment]
@liamie @damienderoistecso  - FYI - If a PX file contains YES or NO in the elimination, it will be ignored for import, build, etc

**Comment by JohnPCarroll** [comment]
Test passed for px files with or without elimination Keywords. These are px files created or updated via the Build Create and Update options. It applies to Single and Dual languages tables
