### ISSUE TITLE
[ENHANCEMENT] Highlight multidimensional pivoting feature better on the front end

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#397]
Multidimensional pivoting is available through the XLSX selection download. Highlight this feature better for the front end users  who are used to this functionality from Statbank but are not aware that it is still available in PxStat through the XLSX download.

**Comment by liamie** [comment]
New published items now give error when accessed 
On Data Page
Last updated tables click a table published today 31/03 error occurs
![image](https://user-images.githubusercontent.com/55874862/113131054-9fa00e00-9214-11eb-9e4f-d001a0e8a95d.png)

**Comment by liamie** [comment]
Pivoting information link and how to now available in advanced pivoting  option.
