### ISSUE TITLE
[BUG] Dashboard Awaiting response displays invalid date

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#4]
**Describe the bug**
Dashboard Awaiting response displays invalid date

**To Reproduce**
When you open the awaiting response card in the dashboard, the publish dates for certain requests display as invalid date.  This should be blank.

**Expected behavior**
Should display empty string if date is null from server

**Screenshots**
![image](https://user-images.githubusercontent.com/53211688/71174235-a04da480-225c-11ea-8fd8-c610b1632f95.png)

**Additional context**
Check across site for this issue with moment

**Comment by RoseHayes** [comment]
This has been amended to check for nulls and replace with empty string. The rest of the application has also been reviewed to add a check where ever a date is passed to moment.

**Comment by lorenzobruni** [comment]
Issue to be re-opened as it is not yet deployed.

**Comment by lorenzobruni** [comment]
@JohnPCarroll please test this as it was closed by mistake
