### ISSUE TITLE
[ENHANCEMENT] Use elimination variables in view data entity

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#401]
In the table selection view, per select a variable if it is marked as the elimination variable for that classification.

Preselect the latest time point

**Comment by liamie** [comment]
ignore testing
![image](https://user-images.githubusercontent.com/55874862/113018289-4aaeba00-9178-11eb-8436-5f2e7adf7c6c.png)

**Comment by liamie** [comment]
Unrequired
