### ISSUE TITLE
[ENHANCEMENT] Add list of Dimension to the PxStat.Data.Cube_API.ReadCollection API

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#403]
**_Logged on behalf of end-user request_**

Hello,
We have been working with CSO data in 2019 when CSO tables were provided by StatBank. Back then the Table Of Contents of all available tables (toc) downloaded using the R-package was very helpful resource to navigate thousands of available tables. 
 
With switching over to PxStat the contents of the TOC has changed – it no longer include the “dimensions” of the tables (which is a very helpful detail). 
 
Below is the side-by-side comparison of the previous (StatBank) and the new (PxStat) Table of Contents:
![image](https://user-images.githubusercontent.com/53212047/113282622-1570ac00-92df-11eb-9444-df6719b85017.png)

Dimensions (or tags) are visible on the web-page:

![image](https://user-images.githubusercontent.com/53212047/113282752-47820e00-92df-11eb-8398-055c05383ad3.png)
Is there a way to download the Table of Contents that would include the “dimensions” (“tags”)? May be we are missing some parameters in the call to a procedure in R-package?

## Describe the solution
* Amend the API `PxStat.Data.Cube_API.ReadCollection` to include the list of Dimensions - no variables.
* Amend the R package to read and display the list of Dimensions in another column (ie. coma separated)

**Comment by neilfromcork** [comment]
Fixed in DEV - Ready for test

**Comment by damienderoistecso** [comment]
@liamie this can be tested using the RESTfull API

**Comment by liamie** [comment]
Now has an ID section that contains
Period
STATISTIC
List of Classification Codes

Label and alternate web sources reflect language chosen
