### ISSUE TITLE
[BUG] Unexpected error when downloading alternative language XLSX file format

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#404]
**Describe the bug**
Unexpected error when downloading alternative language XLSX file format
![image](https://user-images.githubusercontent.com/55874862/113315704-78753980-9305-11eb-98b4-021f041e41d7.png)

**To Reproduce**
1. Go to matrix with two languages eg. EY041 
2. Click on '.download and choose XLSX format or button in advanced pivot 
3. See error
Other formats seem fine and also fine if the default (English) XLXS format is downloaded

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test.

Perhaps we need a regression test of other language functionality?

**Comment by liamie** [comment]
This error is cleared now.
