### ISSUE TITLE
[BUG] In ReadMetaCollection only the id for the time dimension is shown

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#405]
In ReadMetaCollection only the id for the time dimension is shown

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by damienderoistecso** [comment]
@liamie Can you test this via postman ("PxStat.Data.Cube_API.ReadMetaCollection") as it can't be tested on the browser. All dimensions should be included

**Comment by liamie** [comment]
ID section now contains
Period
STATISTIC
List of Classification Codes
