### ISSUE TITLE
[BUG] Strange char before CSV output in API response

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#407]
There is a strange char at the beginning of the CSV body within the API response.
When saving the output the char disappear... but it's weird...

@neilfromcork can you please check where it comes from?
Thank

![image](https://user-images.githubusercontent.com/53212047/114170442-dd92e580-992a-11eb-9c58-9bfc772cac0c.png)

**Comment by neilfromcork** [comment]
That's the BOM (Byte Order Mark). We have to insert this at the start of CSV files in order to signal to the client application that it should use utf-8 encoding.

**Comment by lorenzobruni** [comment]
Perfect, thanks!
