### ISSUE TITLE
[ENHANCEMENT] Improve CSV/XLSX max size error handling

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#409]
# Client Side
@damienderoistecso 
For both CSV and XLSX formats. Check if the number of rows exceeds the maximum limit set in the `config.global`.
If so then display an information notice (to be defined).

# Server Side
@neilfromcork 
For both CSV and XLSX formats. Check if the number of rows exceeds the maximum limit set in the `config.global`.
If so then return simplified error message (to be defined)

**Comment by neilfromcork** [comment]
Server side complete

**Comment by damienderoistecso** [comment]
Ready for testing

**Comment by JohnPCarroll** [comment]
Test passed if number of rows requested > set number in config.global. Information message displayed
Test passed if number of rows requested < set number in config.global.  output file created.

**Comment by liamie** [comment]
when data row count = 1048576 download no message is displayed,  error occurs when downloading xlxs format also last row data is lost if csv is opened in excel
![image](https://user-images.githubusercontent.com/55874862/114895936-cd39a980-9e07-11eb-8e28-763fa4078abc.png)

I believe we need to reduce our current max limit by one to and total in messages accordingly as part of our file generation for csv/xlsx creates a header row and thus uses one of the max limit as standard

**Comment by neilfromcork** [comment]
Limit reduced by 1 for xlsx and csv - Ready for test

**Comment by liamie** [comment]
CSV and XLSX files download and open correctly on file sizes equal to and below new MAX 
Warning message informs correctly on attempt to download number of records above above the MAX
