### ISSUE TITLE
[BUG] 500 Internal Server Error - Max XLSX limit exeeded for RESTful and PxAPIv1

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#410]
Review the error handling when the max XLSX size is passed for the RESTful nd PxAPIv1 APIs

**Comment by neilfromcork** [comment]
@lorenzobruni - can we have a look at the IIS error settings? This problem only occurs when the application is deployed in IIS.

 See: https://docs.microsoft.com/en-us/iis/configuration/system.webServer/httpErrors/

**Comment by neilfromcork** [comment]
HttpError messages updated in PxStat code

**Comment by neilfromcork** [comment]
@lorenzobruni - trace back svn logs to see where this stands

**Comment by lorenzobruni** [comment]
Duplicate of #409
