### ISSUE TITLE
[BUG] Unexpected error appearing in Delete Signoff 

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#411]
**Describe the bug**
When you try to delete a release an error appears in the sign off. I was using Table JCE1054 version 1.1

![image](https://user-images.githubusercontent.com/44975474/114849516-bd09d600-9dd7-11eb-8994-2924c61687c8.png)

**Comment by damienderoistecso** [comment]
Duplicate of #388
