### ISSUE TITLE
[ENHANCEMENT] Change Natural sorting of values in datatable

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#413]
**Describe the solution you'd like**
Update custom sorting of datatable values so that confidential values are sorted before zero values

Sync this enhancement with the widget library

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for test Values should now sort better with confidential values placed before zero vales. Issue before was trying to sort and see the highest value where you had many confidential values

**Comment by lorenzobruni** [comment]
Requires synching with PxWidget https://github.com/CSOIreland/PxWidget
