### ISSUE TITLE
[ENHANCEMENT] Improve CSV error handling in create/update

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#414]
**Describe the solution you'd like**
Give clearer error messages in create/update for errors in CSV files so users can better identify issues

**Comment by damienderoistecso** [comment]
@JohnPCarroll If data CSV in update contains parsing errors (e.g. a row with less values than it should), errors are now displayed in modal, replacing generic invalid CSV message

**Comment by JohnPCarroll** [comment]
Test fails in the Build update Option. It  Appears to be incorrectly counting the rows on the csv table. Rest of details are correct 
![image](https://user-images.githubusercontent.com/44975474/115245221-9d96e400-a11c-11eb-96bd-01de2c2b6c8e.png)
