### ISSUE TITLE
[BUG] Single Apostrophe in Notes appearing as codes in XLSX format

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#419]
**Describe the bug**
 Single Apostrophe in Notes appearing as codes in XLSX format

in XLXS 
![image](https://user-images.githubusercontent.com/55874862/115541889-8fb99e00-a297-11eb-8850-0a25bb16f837.png)

Appears fine in px NOTE="As part of the RPPI's continuous
and json seems ok also
**To Reproduce**
Download a file with a single  Apostrophe in XLSX format
e.g HPM08 on live

**Comment by neilfromcork** [comment]
Fixed in DEV

**Comment by liamie** [comment]
Still occurring on VSA01 in Dev

**Comment by neilfromcork** [comment]
Not still occurring. Cache just needed to be flushed.

**Comment by liamie** [comment]
Cleared now. Apostrophe appears fine now.
