### ISSUE TITLE
[BUG] Disable delete copyright button if copyright used in tables

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#420]
**Describe the bug**
Currently, the delete copyright button remains enabled on client even if the copyright is used in tables. Server does not allow it to be deleted but the client should still disable the button

**Comment by damienderoistecso** [comment]
Fix in dev

@liamie ready for testing

**Comment by liamie** [comment]
The delete copyright button is now disabled if used in tables. It is enabled correctly if the copyright is not associated with any table.
