### ISSUE TITLE
Client side config file[QUERY] 

### ISSUE THREAD

**Issue by Chriz-ONeill** [CSOIreland/PxStat#421]
Code blocks for downloaded code

Can I just check if there is a small issue with the client side config file. On checking the file in VS code without making any change straight after download, VS Code is showing a small error: Expected comma or closing bracejson(518)

Am I right in thinking this is as simple as adding another closing brace? 

Thanks

<img width="773" alt="config" src="https://user-images.githubusercontent.com/69847527/116403406-6cf23100-a825-11eb-9daf-b79dc6f9cb35.PNG">

**Comment by liamie** [comment]
I believe this has been resolved. Thank you.
