### ISSUE TITLE
[ENHANCEMENT] Add GeoJSON entity to PxStat

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#423]
Build GeoJOSN entity in PxStat with ability to add, update, edit and delete GeoJSON objects.

Provide RESTfull API to read GeoJSON data from repository for use in tables to display geospatial data on a map

Update build create/update to select the appropriate maps and insert the RESTfull API endpoint into PX files

**Comment by neilfromcork** [comment]
APIs created

**Comment by neilfromcork** [comment]
API amendments completed:

- Geometry validation (Can't mix polygons/multi polygons with points)
- Validation applied to Build and Import
- ReadDataByMap - null output amended

**Comment by neilfromcork** [comment]
ReadDataByMap - null output amended - rolled back

**Comment by neilfromcork** [comment]
Server changes complete

**Comment by damienderoistecso** [comment]
Client side changes complete

**Comment by liamie** [comment]
@neilfromcork If a px file has two or more map entities for the same classification it passes validation for create, update and import
As discussed there should only be one map allowed per classification in a valid file and so should be picked up in validation.

Note: Only the first map entry seems to be used/retained in the create/update tools but for clarity I think it should still be part of the validation.

**Comment by liamie** [comment]
@damienderoistecso text on import error message goes out of bounds when map file does not exist.
![image](https://user-images.githubusercontent.com/55874862/120204530-d6000680-c220-11eb-81b4-01c3e12c2e95.png)

**Comment by neilfromcork** [comment]
Validation extended to allow maximum only one map per classification

**Comment by damienderoistecso** [comment]
> @damienderoistecso text on import error message goes out of bounds when map file does not exist.
> ![image](https://user-images.githubusercontent.com/55874862/120204530-d6000680-c220-11eb-81b4-01c3e12c2e95.png)
> 
> may just be unbroken text line too long rather than map specific

@lorenzobruni I think we can solve this issue by adding the bootstrap class "overflow-auto" to the `<li>` when we list errors from the api.ajax.jsonrpc function. When I tested in using the inspector it outputs like this which is much better and allows the user to properly read the error with the help of a scroll bar when needed

![image](https://user-images.githubusercontent.com/53211688/120209992-3134f780-c227-11eb-8246-6b066101344c.png)
![image](https://user-images.githubusercontent.com/53211688/120210026-3b56f600-c227-11eb-916a-1a215aca6f3f.png)

**Comment by liamie** [comment]
@damienderoistecso @neilfromcork Currently the add map validation in System > Maps passes if the features contain a properties tag it doesn't confirm that there are actually named properties in that tag so if any/all features have empty properties the dropdowns for assigning properties are empty. As we have no means of manually assigning a property validation should probably ensure we have at least one property for the dropdowns.

"type": "Feature","properties": { },

![image](https://user-images.githubusercontent.com/55874862/120292108-e913e480-c2bb-11eb-9f73-88612b1c99aa.png)

**Comment by liamie** [comment]
> Validation of PX file extended to allow maximum only one map per classification

This seems resolved, now correctly reporting error with inconsistent map data

**Comment by damienderoistecso** [comment]
> @damienderoistecso @neilfromcork Currently the add map validation in System > Maps passes if the features contain a properties tag it doesn't confirm that there are actually named properties in that tag so if any/all features have empty properties the dropdowns for assigning properties are empty. As we have no means of manually assigning a property validation should probably ensure we have at least one property for the dropdowns.
> However if properties are listed in the first feature but not in some of the subsequent features the drop down is populated but the map wont load just hangs on the loading bars
> 
> "type": "Feature","properties": { },
> 
> ![image](https://user-images.githubusercontent.com/55874862/120292108-e913e480-c2bb-11eb-9f73-88612b1c99aa.png)

Client updated to validate properties during "Set Properties" step

@liamie ready for testing

**Comment by liamie** [comment]
@damienderoistecso "Set Properties" button not disabled after first press so everytime click "Set Properties" an additional english field is added.
![image](https://user-images.githubusercontent.com/55874862/120320159-c4c70080-c2d9-11eb-8a23-0f558bac78bd.png)

**Comment by neilfromcork** [comment]
_"Currently the add map validation in System > Maps passes if the features contain a properties tag it doesn't confirm that there are actually named properties in that tag so if any/all features have empty properties the dropdowns for assigning properties are empty. As we have no means of manually assigning a property validation should probably ensure we have at least one property for the dropdowns.
However if properties are listed in the first feature but not in some of the subsequent features the drop down is populated but the map wont load just hangs on the loading bars"_
 
From a map validation point of view, this is correct. GeoMap allows anything in the properties object, hence we to validate this as a GeoJson file, we don't concern ourselves with the contents of the properties object.

**Comment by damienderoistecso** [comment]
> @damienderoistecso "Set Properties" button not disabled after first press so everytime click "Set Properties" an additional english field is added.
> ![image](https://user-images.githubusercontent.com/55874862/120320159-c4c70080-c2d9-11eb-8a23-0f558bac78bd.png)
> 
> Similar occurs for multi language
> ![image](https://user-images.githubusercontent.com/55874862/121360179-1a2f8d00-c92c-11eb-89db-7a78381b0572.png)

Fixed in dev @liamie ready for testing

**Comment by liamie** [comment]
> > @damienderoistecso "Set Properties" button not disabled after first press so everytime click "Set Properties" an additional english field is added.
> > ![image](https://user-images.githubusercontent.com/55874862/120320159-c4c70080-c2d9-11eb-8a23-0f558bac78bd.png)
> > Similar occurs for multi language
> > ![image](https://user-images.githubusercontent.com/55874862/121360179-1a2f8d00-c92c-11eb-89db-7a78381b0572.png)
> 
> Fixed in dev @liamie ready for testing

This aspect is now corrected, the Set Properties button cannot be activated multiple times now.

**Comment by liamie** [comment]
Possible conflict between validation rules
![image](https://user-images.githubusercontent.com/55874862/122946027-ed8a6500-d370-11eb-8215-99be70aded53.png)
this error is flagged in create but if the same map link as used in the import file is readded then it will pass through all other validation for import and publishing stages.

**Comment by damienderoistecso** [comment]
Fixed in dev @liamie ready for test

**Comment by liamie** [comment]
> Possible conflict between validation rules
> ![image](https://user-images.githubusercontent.com/55874862/122946027-ed8a6500-d370-11eb-8215-99be70aded53.png)
> this error is flagged in create but if the same map link as used in the create/import file is readded then it will pass through all other validation for import and publishing stages.

This issue appears to be resolved now, no longer producing error so no need to keep readding the map again

**Comment by JohnPCarroll** [comment]
The Build update fails when map included. Table used E2003. This is a single language table.
When you add a map with duel languages the following error message appears
![image](https://user-images.githubusercontent.com/44975474/123077452-f8e19d00-d411-11eb-8088-4a4fb915d944.png)

The build create works correctly

**Comment by neilfromcork** [comment]
Elimination issue fixed in dev - please retest @JohnPCarroll

**Comment by liamie** [comment]
@damienderoistecso in system> Maps the table count and attached tables for geomaps seems to have been reset to 0 for all and no longer incrementing or listing for new attachments.
![image](https://user-images.githubusercontent.com/55874862/123131536-ad48e680-d445-11eb-8e4f-681a377aa04c.png)
some of these have tables attached should not be all 0

**Comment by JohnPCarroll** [comment]
Map Widgets not working. 
Table E2003. This table has a status of "Work in Progress". Nothing is shown when the downloaded widget is used
Table E2003JC. This table has a status of "Live".  The title is shown but no map when the downloaded widget is used.

**Comment by damienderoistecso** [comment]
> @damienderoistecso in system> Maps the table count and attached tables for geomaps seems to have been reset to 0 for all and no longer incrementing or listing for new table attachments.
> ![image](https://user-images.githubusercontent.com/55874862/123131536-ad48e680-d445-11eb-8e4f-681a377aa04c.png)
> some of these have tables attached should not be all 0
> also modal page when link attached no longer has any tables for any entry
> ![image](https://user-images.githubusercontent.com/55874862/123131948-192b4f00-d446-11eb-9e9e-f0b08b17e113.png)

@neilfromcork Can you look at this. "TableCount" always returns zero from "PxStat.Data.GeoMap_API.ReadCollection"

**Comment by neilfromcork** [comment]
@damienderoistecso  - That should be ok now

**Comment by JohnPCarroll** [comment]
Map not displayed.
Table E2003JCNULL. This table contains no values for counties Kilkenny and Leitrim.

**Comment by damienderoistecso** [comment]
> Map Widgets not working.
> Table E2003. This table has a status of "Work in Progress". Nothing is shown when the downloaded widget is used
> Table E2003JC. This table has a status of "Live". The title is shown but no map when the downloaded widget is used.

@JohnPCarroll fixed in dev, ready for test, update both widget code and client code to test

**Comment by JohnPCarroll** [comment]
PNG issue. When you download a map the png output is not very clear as the colors in the map match the background color ( white). Example taken form E2003JCZERO

Selection

![image](https://user-images.githubusercontent.com/44975474/123253326-4713a080-d4e5-11eb-8709-f445cd8cc395.png)

PNG Output

![image](https://user-images.githubusercontent.com/44975474/123253650-978afe00-d4e5-11eb-9c4a-64cc1f82e181.png)

**Comment by JohnPCarroll** [comment]
Map Widget not working for Table E2003. This table has a status of "Work in Progress". 

Map Widgets working for Table E2003JC. This table has a status of "Live". The only issue I have is that you do not know what the map details refer to eg. Time period, Statistical indicator.

**Comment by damienderoistecso** [comment]
> Map not displayed.
> Table E2003JCNULL. This table contains no values for counties Kilkenny and Leitrim.

@JohnPCarroll  This issue should be fixed. Update widget code

**Comment by damienderoistecso** [comment]
> @damienderoistecso - That should be ok now

Might still be issue with "PxStat.Data.Matrix_API.ReadByGeoMap", always returns null

**Comment by JohnPCarroll** [comment]
Map displayed for Table E2003JCNULL. This table contains no values for counties Kilkenny and Leitrim.

**Comment by liamie** [comment]
> > @damienderoistecso - That should be ok now
> 
> @neilfromcork Might still be issue with "PxStat.Data.Matrix_API.ReadByGeoMap", always returns null
@damienderoistecso @neilfromcork Maybe related to this but currently maps do not seem to have deletion protection if attached to an existing file so if the front end delete button is purposefully/accidently made activate the map entry can be deleted as if it had 0 tables attached.

**Comment by neilfromcork** [comment]
@liamie - bug found and fixed related to this, can you check this issue again? Thanks

**Comment by damienderoistecso** [comment]
> E2003

@JohnPCarroll Can you test this now please. Update both client and widget folder from SVN

**Comment by liamie** [comment]
> > > @damienderoistecso - That should be ok now
> > 
> > 
> > @neilfromcork Might still be issue with "PxStat.Data.Matrix_API.ReadByGeoMap", always returns null
> > @damienderoistecso @neilfromcork Maybe related to this but currently maps do not seem to have deletion protection if attached to an existing file so if the front end delete button is purposefully/accidently made activate the map entry can be deleted as if it had 0 tables attached.
> > This results in an oops! message on the tables pages that had these now deleted maps attached.
> > ![image](https://user-images.githubusercontent.com/55874862/123390275-a1b70600-d592-11eb-89a2-239da4813264.png)

This appears to be resolved now. Table names are appearing and deletion with existing connection is protected now

**Comment by JohnPCarroll** [comment]
Map Widget working for tables has a status of "Work in Progress".
