### ISSUE TITLE
[ENHANCEMENT] Make adding a reason mandatory publishing a table

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#424]
**Describe the solution you'd like**
Ensure a reason is added to a release before any request to publish is initiated.

Make this requirement configurable in the global config so it may not be mandatory

**Comment by neilfromcork** [comment]
Completed on Server side. Config on global.config "workflow.release.reason-required":true

**Comment by liamie** [comment]
Leave is now mandatory before publish, dialog appears to inform,

Note: There is an implication that comments on reasons can be updated at any stage not just work in progress as the text box can be altered and typed in, however this is not the case as update button is disabled once moved from work in progress. I think the text box state should be frozen along with the update button for clarity.
![image](https://user-images.githubusercontent.com/55874862/119630490-e706dd00-be06-11eb-9117-083b435d7fd5.png)

**Comment by damienderoistecso** [comment]
> Leave is now mandatory before publish, dialog appears to inform,
> 
> Note: There is an implication that comments on reasons can be updated at any stage not just work in progress as the text box can be altered and typed in, however this is not the case as update button is disabled once moved from work in progress. I think the text box state should be frozen along with the update button for clarity.
> ![image](https://user-images.githubusercontent.com/55874862/119630490-e706dd00-be06-11eb-9117-083b435d7fd5.png)

@liamie I have implemented a fix for this, can you test please

**Comment by liamie** [comment]
text screen does not allow edits now once past work in progress.

Note: slight usability issue if you close up the text area by using the small stroked lines at bottom right of POWERED BY TINY //
you can't seem to undo it unless you major reset the whole page. cancel and reopen the modal doesn't reset and  even switching to a different matrix doesn't reset the modal. Need to go to a different section such as DATA and then back to releases for the modal to reset the comments view. Seems to apply to all the tiny text boxes in modals as public comment modal is affected the same.
![image](https://user-images.githubusercontent.com/55874862/119690809-eb9cb700-be41-11eb-964c-ba81e05ad68e.png)

![image](https://user-images.githubusercontent.com/55874862/119689594-e428de00-be40-11eb-8801-a4eef50d9ce3.png)

**Comment by damienderoistecso** [comment]
text screen does not allow edits now once past work in progress.

@liamie can you test this issue now please

**Comment by damienderoistecso** [comment]
@liamie I set min_height: 100, when we initiate the tinymce so that the user can no longer reduce the height to such an extent that they can not expand it again. Should be applied across all the application. Can you test

**Comment by liamie** [comment]
Seems to be resolved now.

**Comment by damienderoistecso** [comment]
@liamie can you re-test this please. I forgot to allow for the fact that this requirement is configurable from the global config

**Comment by liamie** [comment]
global config changes seem to correct.
