### ISSUE TITLE
[ENHANCEMENT] Add Area Chart to chart widgets

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#425]
Add area chart to available chart widget types

https://www.chartjs.org/docs/2.9.4/charts/area.html

**Comment by damienderoistecso** [comment]
Client updated. 

@liamie @JohnPCarroll can you have a quick check of the other charts to make sure nothing broke with them

**Comment by liamie** [comment]
Other charts appear un affected by the changes

**Comment by JohnPCarroll** [comment]
Test passed. Other charts are not affected
