### ISSUE TITLE
Database Update[QUERY] 

### ISSUE THREAD

**Issue by Chriz-ONeill** [CSOIreland/PxStat#426]
Timeout error when trying to update database through version 3.5.1

**Query**
When trying to update from version 3.4.0 to 3.6.1, on running the database script we encountered an issue where an error was thrown up regarding a timeout for the time taken as shown in the screengrab.

To try to get round this we took the 3.5.1 version from GitHub and ran that, where we received the same error message, however on attempting to run 3.6.1 again it all appeared to work fine, would anyone be able to shed any light on what may have been going wrong?

Thank you. 

![InkedSQL Error_LI](https://user-images.githubusercontent.com/69847527/117144516-eb148180-ada9-11eb-8a96-279ad34c3c15.jpg)

**Comment by Chriz-ONeill** [comment]
To add....

We also had an issue where the script (while running database changes under 3.5.1) seemed to be trying to create "IX_TDT_OPTIMISER" and "IX_DTC_OPTIMISER". The indexes we seem to have under td_data and tm_data_cell are clustered although the script was attempting to recreate variables as non-clustered?

Is this an error as we should have ended up with new indexes of a non-clustered type?

**Comment by liamie** [comment]
Database structure has been altered which should eliminate this particular issue
