### ISSUE TITLE
[BUG] Dashboard Pending Live displaying multiple workflow requests for the same table

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#427]
Table EAP13 is displayed in the Pending Live section of the Dashboard twice.

A workflow request for EAP13 was made by the Approver with the incorrect publication date selected. 
I rejected the request and the Approver sent through another with the correct date and I sign-off on it.
The Pending Live section of the Dashboard now shows the table listed twice with both publication dates.
However, on the Releases page for the table, the workflow is listed correctly.

![Dashboard Bug 1](https://user-images.githubusercontent.com/59689411/118626112-7b978c80-b7c2-11eb-850a-b4e8b1005a9a.PNG)
![Dashboard Bug 2](https://user-images.githubusercontent.com/59689411/118626133-805c4080-b7c2-11eb-8305-57491b2f92cb.PNG)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. This bug only occured where the two proposed Release Date/Time values were different

**Comment by JohnPCarroll** [comment]
In the Workflow I select the Publish option, enter details and ADD the following error message appears 
![image](https://user-images.githubusercontent.com/44975474/118968527-edf3a280-b963-11eb-8c9f-61bdfd444c40.png)

This message would imply that the PX File is incorrect. This is not true. 
The reason the Message appears is because the Reason to Publish section was not filled.  The message should be more clear.

**Comment by damienderoistecso** [comment]
> In the Workflow I select the Publish option, enter details and ADD the following error message appears
> ![image](https://user-images.githubusercontent.com/44975474/118968527-edf3a280-b963-11eb-8c9f-61bdfd444c40.png)
> 
> This message would imply that the PX File is incorrect. This is not true.
> The reason the Message appears is because the Reason to Publish section was not filled. The message should be more clear.

@neilfromcork  also implemented a new enhancement on the server to enforce a reason to be added before a request to publish is initiated. I haven't implemented this on the client yet so this is why the error is showing.

**Comment by JohnPCarroll** [comment]
Test Passed for Pending Live on Dashboard. Appears once only
