### ISSUE TITLE
[BUG] Duplicate tables appear on Analytics

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#428]
In some cases, a duplicate table name appears on Analytics

**Comment by neilfromcork** [comment]
Fixed in DEV, ready for test.

**Comment by JohnPCarroll** [comment]
These tables may not be duplicates as the Titles were updated.  
The update in DEV is not correct. The table I used was LRW07.
Steps Taken
1. I uploaded the previous Live version in dev and accessed it twice. The analytics were correct as it stated 2 users.  
2. I uploaded the Current live version in dev and accessed it once. The analytics were incorrect as it stated 1 users.  It ignored the previous version which it should not as it was in the relevant time frame.

Both versions are available on DEV.

**Comment by neilfromcork** [comment]
Restored the ability to view previous versions where name, product subject etc are different. This will result in duplicates as technically they are different data. We can discuss further depending on what the business view of this is. @JohnPCarroll
