### ISSUE TITLE
[ENHANCEMENT] Create configuration to switch on and off AD user access to OpenAccess PxStat

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#429]
Currently PxStat OpenAccess allows AD users to login externally. Create a config item to switch this ability on and off. Ensure that it is consistent across all APIs (e.g. for amending 2FA, etc)

**Comment by damienderoistecso** [comment]
Client side will have to reflect this change also

**Comment by damienderoistecso** [comment]
Client side updated. No longer option to reset/update 2FA for AD users if disabled in the global config

**Comment by neilfromcork** [comment]
Server side updated ready for test. Ideally this requires a full regression test of external login functions.

**Comment by neilfromcork** [comment]
No testing for the moment - some current issues need to be dealt with.

**Comment by neilfromcork** [comment]
Ready for test

**Comment by JohnPCarroll** [comment]
Issue when AD user.  Added a user as a Power User.. The application sent an email to the person in relation to "setup your 2FA"

**Comment by neilfromcork** [comment]
Created a fix to prevent the email being sent if AD access is not configured

**Comment by damienderoistecso** [comment]
@JohnPCarroll Can you confirm if this is OK now?

**Comment by JohnPCarroll** [comment]
Emails no longer sent for AD user
