### ISSUE TITLE
[BUG] Read format from anonymous user

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#43]
**Describe the bug**
When an anonymous user browses that data entity, they get an error as they can't call "PxStat.System.Settings.Format_API.Read"

**To Reproduce**
Browse data as anonymous user  

**Expected behavior**
 Anonymous user has access to "PxStat.System.Settings.Format_API.Read"

**Comment by neilfromcork** [comment]
Fix in dev

**Comment by damienderoistecso** [comment]
Updated api endpoint to public for all "PxStat.System.Settings.Format_API.Read"

@JohnPCarroll ready for testing

**Comment by lorenzobruni** [comment]
Test pass with anonymous user
