### ISSUE TITLE
[BUG] Email addresses that are currently shown to an AD user can be used to create a local user

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#430]
Email addresses that are currently shown to an AD user can be used to create a local user. This needs to be forbidden in order to avoid dual local/AD users

**Comment by neilfromcork** [comment]
Fixed in DEV, ready for test

**Comment by neilfromcork** [comment]
@liamie note change of title of issue

**Comment by liamie** [comment]
Email addresses assigned to a current CSO AD account cannot be used to create Local Accounts.

**Comment by JohnPCarroll** [comment]
Test passed. If an AD user no local account is created using you CSO Email
