### ISSUE TITLE
[BUG] Mandatory Keywords can be deleted

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#431]
**Describe the bug**
The front end can be manipulated to allow for the deletion of mandatory keywords

**To Reproduce**
Keywords > Subjects or
Keywords > Products
enable the delete button on front end (disabled by default for front end and press
![image](https://user-images.githubusercontent.com/55874862/120773577-612b1600-c519-11eb-9162-c4857a159a51.png)

**Expected behavior**
Mandatory keywords should remain protected

**Additional context**
provide a protective lock on mandatory keywords to prevent deletion

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test
