### ISSUE TITLE
[ENHANCEMENT] Handle locked accounts on client side

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#433]
**Describe the solution you'd like**
If a users account is locked, render the navigation menu as if they are unauthenticated users, but display a warning message where their name should appear if they were not locked

**Comment by damienderoistecso** [comment]
@liamie ready for testing

**Comment by liamie** [comment]
Account locked indicator appears for AD user after refresh.
Local users treated like a standard unlogged in user.
For both additional menu items removed after page refresh.
