### ISSUE TITLE
[BUG] Cannot add local user to a group

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#435]
@damienderoistecso **Describe the bug**
When trying to assign a local user to a group an error message appears and user is not added. AD users can be added

**To Reproduce**
1. Go to Manage Groups
2. Click on any group
3. Click Add Member
4. Choose a Local user in the dropdown
5. See error

**Expected behavior**
User should be add as per AD user

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/123088922-3b10db80-d41e-11eb-9095-2860215314df.png)

**Comment by damienderoistecso** [comment]
@neilfromcork Can you check this from your end. Error is being returned from the server.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Local User can now be added and removed correctly.
