### ISSUE TITLE
[BUG] Snapshot isolation update conflict error with deleted and reinstated local user

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#439]
For local users the following error occurs when they e.g. view a table in Releases :

 Exception has been thrown by the target of an invocation. ---> System.Data.SqlClient.SqlException: Snapshot isolation transaction aborted due to update conflict. You cannot use snapshot isolation to access table 'dbo.TD_LOGIN' directly or indirectly in database 'pxstat.live' to update, delete, or insert the row that has been modified or deleted by another transaction. Retry the transaction or change the isolation level for the update/delete statement.

**Comment by neilfromcork** [comment]
Title changed to reflect this does not only occur with reinstated local users

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Please contact me if/when you need the dev environment changed to local login only (no AD)

**Comment by JohnPCarroll** [comment]
test passed for the following
1. Delete and import of table at the same time
2. Import and delete of table at the same time

**Comment by liamie** [comment]
Tested with local user 
Delete and import of table at the same time no error appeared
Import and delete of table at the same time no error appeared

**Comment by lorenzobruni** [comment]
Great, thanks!
I will add the Test label and reassign to me then. Cheers
