### ISSUE TITLE
[BUG] PX formatting can cause newline characters in JSON-stat output

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#441]
A PX file with misaligned TIMEVAL data caused newline characters to appear on the JSON stat output.
Example file attached.
[BPQ26_4_0_20210627T160638.px.txt](https://github.com/CSOIreland/PxStat/files/6840377/BPQ26_4_0_20210627T160638.px.txt)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test.

**Comment by neilfromcork** [comment]
Amended to ensure a px file fails validation if its TIMEVAL is not one of the standard values (e.g. TLIST(A1) etc)

**Comment by JohnPCarroll** [comment]
Test passed. 
1. The px file fails validation if its TIMEVAL is not one of the standard values (e.g. TLIST(A1) etc)
