### ISSUE TITLE
[BUG] Incorrect restful url in JSON-stat output hrefs

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#443]
RESTful urls in JSON-stat output are missing a / character

**Comment by JohnPCarroll** [comment]
Test passed.

**Comment by neilfromcork** [comment]
@JohnPCarroll , @lorenzobruni @liamie - Collection seems to have correct url formation - you may check for yourselves also.

**Comment by lorenzobruni** [comment]
This fix requires the Cache to be flushed. Go to System >> Cache >> Flush.
