### ISSUE TITLE
[ENHANCEMENT] Special character cleansing to be added to  manage>Add subject & manage>Add Product

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#445]
Currently "Add subject" and "Add Product" allows special characters such as " quotes which can then be passed into a px file causing it to break. Unless these characters are specifically required they should be cleansed as per other text fields.

**Comment by neilfromcork** [comment]
Fixed in DEV on server side. May need front end intervention as well.

**Comment by neilfromcork** [comment]
Fix reversed pending workshop on character cleansing @liamie
