### ISSUE TITLE
[BUG] Creates failing

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#448]
Build create fails when you press the Create button

**Comment by neilfromcork** [comment]
Fixed in DEV. Requires an emergency release. Please test multi-language, also test update and upload. @lorenzobruni @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Test passed for table for one and two languages. I created tables, updated tables with the data and imported them. All works correctly.

**Comment by neilfromcork** [comment]
Needs to be tested as a new build from scratch

**Comment by JohnPCarroll** [comment]
Test passed using Single and Duel Languages tables I tested the Build Create, Build Update and Imported the tables. I viewed the data via the Table , Chart and Map options and all is correct
