### ISSUE TITLE
[ENHANCEMENT] Allow data selection download when you get threshold warning

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#45]
**Describe the solution you'd like**
When you get a hard or soft threshold warning when viewing data selection, allow the user to download the data without having to view the data on screen first

@JohnPCarroll ready for testing

**Comment by damienderoistecso** [comment]
Updated to close modal after downloading

**Comment by damienderoistecso** [comment]
Fixed issue with modal size on releases entity, 

Fixed other bugs

@JohnPCarroll ready for testing

**Comment by damienderoistecso** [comment]
Fixed issue with canceling modal in releases, fixed issue with duplicate formats types in dropdown

@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test failed due to Duplicate listing of Download Results appearing.
Select PX 2013 from download results, then View data and re-select download results where duplicate listing appears
