### ISSUE TITLE
[ENHANCEMENT] Implement Cookie Link for CHART and MAP

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#451]
Implement a quick link like for tables to jump straight to some content.

**Comment by lorenzobruni** [comment]
@JohnPCarroll you can test this by replacing the keyword "table" with "chart" or "map" (if applicable).
ie.

-  [https://dev-data.cso.ie/carrollj/4.0.0/client/table/TEM20](https://dev-data.cso.ie/carrollj/4.0.0/client/table/TEM20)
-  [https://dev-data.cso.ie/carrollj/4.0.0/client/chart/TEM20](https://dev-data.cso.ie/carrollj/4.0.0/client/chart/TEM20)

**Comment by lorenzobruni** [comment]
Please run an update in 4.0.0.
Thanks

**Comment by JohnPCarroll** [comment]
Test passed for Table, Chart and Map. Used Table E2003JC

**Comment by liamie** [comment]
Appears that if Tables are accessed through some other means rather than the quick link described  above eg via the Browse menu the Table tab/page appears blank on first entry 
![image](https://user-images.githubusercontent.com/55874862/128871945-a4ef7611-6e85-4aa9-bb1d-aa1e5caa9d03.png)
It does appear correctly again if click on the chart tab and then return to the table tab on the page
![image](https://user-images.githubusercontent.com/55874862/128872740-1177acde-7b7c-4d0b-af1f-0dc132ab3e6c.png)

**Comment by damienderoistecso** [comment]
> Appears that if Tables are accessed through some other means rather than the quick link described above eg via the Browse menu the Table tab/page appears blank on first entry
> ![image](https://user-images.githubusercontent.com/55874862/128871945-a4ef7611-6e85-4aa9-bb1d-aa1e5caa9d03.png)
> It does appear correctly again if click on the chart tab and then return to the table tab on the page
> ![image](https://user-images.githubusercontent.com/55874862/128872740-1177acde-7b7c-4d0b-af1f-0dc132ab3e6c.png)

This should be resolved now @liamie ready for testing

**Comment by liamie** [comment]
This seems correct now for the direct link and the other methods for reaching the table page load first time.

NB: The link in the bottom right hand corner of the of the html generated widget page always links to the table page even if the chart or map widget is used.

**Comment by damienderoistecso** [comment]
> This seems correct now for the direct link and the other methods for reaching the table page load first time.
> 
> NB: The link in the bottom right hand corner of the of the html generated widget page always links to the table page even if the chart or map widget is used.

I think that's OK Liam as the link under the chart is for the purposes of accessing the source data, which is essentially the data viewed as a table
