### ISSUE TITLE
[ENHANCEMENT] Allow redundant columns to be removed from table widget

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#455]
For the table widgets, if there are columns which contain all the same variables, give the option to remove these columns by way of a toggle.

If "Remove redundant columns" is set to true, all redundant columns are removed from the widget, giving a simpler table. It's then up to the user of the widget to accurately describe the table using their own table title wherever they are using the widget.

**Comment by damienderoistecso** [comment]
@liamie ready for testing

**Comment by damienderoistecso** [comment]
@liamie issue with pivoted columns should be fixed now

**Comment by liamie** [comment]
This seems to be functioning correctly now as described.
