### ISSUE TITLE
[BUG] Map Widget option label incorrect

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#456]
The include-border option label has brackets surrounding
![image](https://user-images.githubusercontent.com/55874862/131653609-f84fd58a-0ffb-4e63-8257-9140395e7b95.png)

Live and Dev affected

**Comment by damienderoistecso** [comment]
Renames label to "Borders" and added to dictionary

**Comment by liamie** [comment]
Appears correct now. NB. Borders on Irish translation also, taken will be corrected as with other translations.
