### ISSUE TITLE
[ENHANCEMENT] Set min zoom on map widget and disable panning outside the map bounds

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#457]
When rendering the map widgets, set a min zoom to stop the user zooming out beyong the geoJSON map.

Also, if a user pans beyond the bounds of the geoJSON map, return them to the map

**Comment by damienderoistecso** [comment]
@liamie ready for testing, update widget code first

**Comment by liamie** [comment]
This seems to be functionally working correctly now bouncing the view back and limit on zoom, however the bounds of the map area seems to include a good portion of sea and the UK meaning that at some zoom settings you can still have a whole region view of non relevant map with no data. Is there a means to tighten the map box/return zone  to just Ireland. If possible as well a snap to button(or similar) for a center of Ireland or data section chosen eg Munster.
