### ISSUE TITLE
[ENHANCEMENT] Print modal, hide backdrop & back to top icon

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#462]
When viewing a modal and then printing it, hide the dark backdrop and back to top icon

**Comment by damienderoistecso** [comment]
@liamie ready for testing

**Comment by liamie** [comment]
Back to top icon still appearing in prints

**Comment by liamie** [comment]
Also in Analytics the print of the modal for a table view takes a considerable time and then shows a couple of hundred pages with only the top few the actual analytics and the rest blank pages with just the back to top icon.  
![image](https://user-images.githubusercontent.com/55874862/133997122-e1fc10fc-db60-4334-b7b3-a86f9ea99f1c.png)
