### ISSUE TITLE
[ENHANCEMENT] Mobile search results layout

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#47]
**Describe the solution you'd like**
Better responsive layout for search results

**Comment by damienderoistecso** [comment]
Added response classes to search results

@JohnPCarroll ready for testing

**Comment by lorenzobruni** [comment]
Code update to sync the Search Results list with the Table Header.
Test passed with @JohnPCarroll 

![image](https://user-images.githubusercontent.com/53212047/75181002-35758980-5735-11ea-9a68-4550178267b6.png)

![image](https://user-images.githubusercontent.com/53212047/75181035-46be9600-5735-11ea-830e-deede015b53e.png)
