### ISSUE TITLE
[BUG] Data loading slow intermittently

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#482]
Users report slow progress in data table load

**Comment by neilfromcork** [comment]
Modifications done for delete entities stored procedures

**Comment by neilfromcork** [comment]
Remove transactions from the bulk upload @neilfromcork

**Comment by JohnPCarroll** [comment]
Tested in the dev environment
I loaded the px file for Table HPM02 which contains just over 1.6 Million rows. This table took 25 minutes to load due to locking of 2 database tables. The tables were TD_DATA and TM_DATA_CELL.  
[HPM02..px.txt](https://github.com/CSOIreland/PxStat/files/7544985/HPM02.px.txt)

**Comment by neilfromcork** [comment]
Are these suspensions or locks? 

I tried loading this table twice, but it loaded reasonably efficiently in both cases. However we are getting a number of PAGEIOLOCK_EX messages during the load and the subsequent delete. The message is defined as:

 "Occurs when a task is waiting on a latch for a buffer that is in an I/O request. The latch request is in Exclusive mode. Long waits may indicate problems with the disk subsystem"

If anybody spots a slow load load in DEV, can you take note of any suspension  (or lock) messages in the Activity Monitor?

**Comment by neilfromcork** [comment]
@liamie has confirmed that the messages referred to exclusive locks on TD_DATA and TM_DATA_CELL

**Comment by neilfromcork** [comment]
Two tests run:
1. Load data while a delete is in progress - Getting frequent LCK_M_IX warnings ( "Occurs when a task is waiting to acquire an Intent Exclusive (IX) lock."). Loaded in about 10 minutes.
2. Load data while another large load is in progress. Similar to above, frequent LCK_M_IX warnings. Loaded in about 10 minutes.

**Comment by damienderoistecso** [comment]
Updated unitsPerSecond for "PxStat.Data.Matrix_API.Create" in the config to get a more accurate progress bar for importing pxfiles. We have allowed a buffer of 20% to ensure the job finished before the bar hits 100%

@JohnPCarroll @liamie can ye test this
