### ISSUE TITLE
[ENHANCEMENT] Allow Firebase authentication

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#483]
Allow Firebase authentication so that users may subscribe via Google, Facebook etc

**Comment by neilfromcork** [comment]
Subscriber management APIs deployed to DEV

**Comment by liamie** [comment]
Can't set alternative language unless logged in.
The language selection only seems to work now if logged in.
Should be able to chose available language whether logged in or not. 
Defaults back to english if irish chosen and not looged in.

**Comment by liamie** [comment]
In User profile > developer > regenerate API key
Typo in success message 

![image](https://user-images.githubusercontent.com/55874862/158575465-621a3527-2c1b-4423-b712-b4e2caa2e46f.png)

Not sure about the Translate.... bit but should be New key generated not New ket generated

**Comment by liamie** [comment]
Github signed in user being reprompted to login with Google account

Signed in as a github verified account > went to Profile > Developer > regenerate Api code 
![image](https://user-images.githubusercontent.com/55874862/158590727-21f9d17b-6906-4b16-900b-04e50d832526.png)

autorisation failed message
retried and was asked to verify with a google account

**Comment by damienderoistecso** [comment]
> In User profile > developer > regenerate API key Typo in success message
> 
> ![image](https://user-images.githubusercontent.com/55874862/158575465-621a3527-2c1b-4423-b712-b4e2caa2e46f.png)
> 
> Not sure about the Translate.... bit but should be New key generated not New ket generated

Correct wording added to dictionary @liamie

**Comment by damienderoistecso** [comment]
> Github signed in user being reprompted to login with Google account
> 
> Signed in as a github verified account > went to Profile > Developer > regenerate Api code ![image](https://user-images.githubusercontent.com/55874862/158590727-21f9d17b-6906-4b16-900b-04e50d832526.png)
> 
> autorisation failed message retried and was asked to verify with a google account
> 
> Also the regenerate Api code button seems to be failing on autorisation a high percent of the time no matter how logged in

Fixed in test @liamie

**Comment by liamie** [comment]
![cleaninvalid](https://user-images.githubusercontent.com/55874862/158630686-ac9e47db-c184-41a5-9f37-42875b29e098.png)

Github subscribers all appearing as invalid user in the subscriber list

**Comment by damienderoistecso** [comment]
Issue with language 

> Can't set alternative language unless logged in. The language selection only seems to work now if logged in. Should be able to chose available language whether logged in or not. Defaults back to english if irish chosen and not looged in.

Fixed in test @liamie

**Comment by liamie** [comment]
Issue with language

Can't set alternative language unless logged in. The language selection only seems to work now if logged in. Should be able to chose available language whether logged in or not. Defaults back to english if irish chosen and not looged in.

Fixed in test @liamie

This is corrected now

**Comment by liamie** [comment]
[](https://user-images.githubusercontent.com/55874862/158630686-ac9e47db-c184-41a5-9f37-42875b29e098.png)cleaninvalid
Github subscribers all appearing as invalid user in the subscriber list

This is corrected now

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/160788707-4e348f9b-6358-492b-87db-3e36c2dc8d83.png)

sometimes user login name can appear blank for email subscribers, same in manage>subscriber display

**Comment by liamie** [comment]
sign up>name section allows html tags which then can affect login user name (e.g. allow appear blank)

**Comment by damienderoistecso** [comment]
> sign up>name section allows html tags which then can affect login user name (e.g. allow appear blank)

Fixed in test @liamie

**Comment by liamie** [comment]
Most html seems removed now.
Some symbols remain such as @ are we allowing this?
Also long sign up names allow the layout to shift so text and buttons can become illegible
![image](https://user-images.githubusercontent.com/55874862/160850891-9b769a2e-6c50-4b9e-b572-2ac7f8acab7d.png)
