### ISSUE TITLE
[BUG] Double entries appearing in Pending Live list

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#487]
If a publish request is rejected by an approver and the amended table is later approved by a different user then there will be a double entry while the release is in the Pending Live dashboard

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
Test passes. I Loaded a table in EV.  I rejected its approval at sign off and then Declan approved its sign off. The table only appears only one in Pending Live.
