### ISSUE TITLE
[BUG] Hashed Classification code created when classification code=classification value

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#49]
**Describe the bug**
In a px file, if the classification code in the domain is the same as the classification name, then a default style classification code is used rather than the px classification code in the domain

**Comment by neilfromcork** [comment]
[CEN1.20200117T100107.px.txt](https://github.com/CSOIreland/PxStat/files/4076884/CEN1.20200117T100107.px.txt)

Fix complete - please retest. Bug originally showed up in Build - ReadTemplate

**Comment by JohnPCarroll** [comment]
Test Successful for Build Import and Update options.
The test is for DOMAIN("Classification")="Classification"; where they are both the same

**Comment by lorenzobruni** [comment]
@JohnPCarroll 
Can you please test also to create a new simple PX file having Classification Code and Classification Value identical?

Thanks
