### ISSUE TITLE
[BUG] Pivot not reset to default values with Reset button

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#490]
**Describe the bug**
You select a pivot option and view the data. The pivot option chosen remains if you select other details from the table 

**To Reproduce**
1.  Select data 
2. Select pivot option other than none
3. View data
4. Press the Reset button and then the View button
5. The data will be displayed with the Pivot option previously selected and not the default one as shown by the button

**Expected behavior**
The default output shown be shown as per the pivot button

**Comment by damienderoistecso** [comment]
Fixed in dev

@JohnPCarroll ready for test

**Comment by JohnPCarroll** [comment]
Test passed in Dev
