### ISSUE TITLE
[BUG] NoHtmlStrip attribute of Sanitizer does not work because Cleanser filtering happens before Sanitizer

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#493]
**To Reproduce**
I added the attribute NoStripHtml to both the headerTemplate and footerTemplate fields of my DTO as they both use html code in their values:

        /// <summary>
        /// Header template
        /// </summary>
        [NoHtmlStrip]
        public string HeaderTemplate { get; set; } = Configuration_BSO.GetCustomConfig(ConfigType.server, "printOptions.headerTemplate");

        /// <summary>
        /// Footer template
        /// </summary>
        [NoHtmlStrip]
        public string FooterTemplate { get; set; } = Configuration_BSO.GetCustomConfig(ConfigType.server, "printOptions.footerTemplate");

But the DTO is cleansed before being sanitized in the code, so, for example, if the footerTemplate in the request was:

`<span class=pageNumber></span>/<span class=totalPages></span>
`

after the sanitization it became

/

**Expected behavior**
The footerTemplate field should still contain the html code

**Comment by JohnPCarroll** [comment]
Tested via the PDF engine
