### ISSUE TITLE
[ENHANCEMENT] Create channels and allow users to subscribe to channels

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#495]
Create channels for the purposes of allowing users to receive notifications specific to the channels they are subscribed to.

Initially, channels will be business and technical

On the client side, allow users to subscribe or unsubscribe to a channel when they create an account and also through their profile modal.

Allow power users and admins to send channel notifications through a channel entity

**Comment by liamie** [comment]
Channel Subscription options not available to AD Users

**Comment by liamie** [comment]
Channel mails being sent to users whether subscribed to channels or not
even if not subscribed to channel the channel mail arrives

**Comment by liamie** [comment]
Language mails sent to users even if not set to that language

**Comment by liamie** [comment]
Channels all send via technical even if different radio button chosen

**Comment by liamie** [comment]
This is corrected now. Correct channel and language sent to. 

** Note: Database only management of channels
