### ISSUE TITLE
[ENHANCEMENT] Allow users to save queries for tables, charts and maps

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#496]
Allow users to save a query for returning a table, chart or map.

Once a users creates a map, chart or map, give them the option to save the query so they can easily run again without having to build their selection. Allow them to save the query with either fixed or fluid time selected.

A new view will have to be created for the user to view a list of their saved queries and run them

**Comment by damienderoistecso** [comment]
Duplicate of #494

**Comment by JohnPCarroll** [comment]
Column chart issue

1. You select years for the x-axis and then the relevant Series Details.
The chart looks like
![153893483-9de2028c-347b-41d1-b723-d65fe01057dc](https://user-images.githubusercontent.com/44975474/154024825-71fef41e-dca9-4d8a-b45d-5fc25736fa5f.png)

2.  You then use the Save Query button and the chart is saved.

3.  When you view it via the Save Queries option the x-axis details are in reverse which is incorrect
![153893927-60fdd7bc-37e5-472d-a8ba-e0d31f375144](https://user-images.githubusercontent.com/44975474/154024947-d197f1b5-a6cf-4a27-b2dc-f0ba0b242346.png)

4.  The details on the save query chart should equal what on the table chart

**Comment by JohnPCarroll** [comment]
The Bar charts are encountering the same issue as the column charts

Table
![153894026-2086ecd6-5304-47c8-8b34-caee06564325](https://user-images.githubusercontent.com/44975474/154025141-7fc4a36d-9b60-4220-8109-74c384f2a54a.png)

Saved Query
![153894071-7bd134b8-db49-4841-ba9e-df5d594984ea](https://user-images.githubusercontent.com/44975474/154025232-ab4cf875-5a8a-4a1b-9414-1942160b0430.png)

**Comment by liamie** [comment]
The save query tagname box allows some html symbols to be used and so affect the success message as below the name test is a link to cso website
![image](https://user-images.githubusercontent.com/55874862/154025987-c3b79720-feff-4d8d-b63d-8110736b1217.png)
![image](https://user-images.githubusercontent.com/55874862/154027230-8b83e598-730b-4a1e-97c2-2484e6834ce5.png)

the scrubbing seems to be only done after the success message so some symbols removed then and the actual save query list seems plain text. Normal restrictions should apply

**Comment by JohnPCarroll** [comment]
Pie Chart issue with Save Query 

Steps to do this.
1. Create a Bar chart
2. Select the Reset button 
3. Create a Pie chart using a different Statistic
4. Save the chart using the Save Query Button. 
5. The pie chart will contain the details for the pie and Bar chart
![image](https://user-images.githubusercontent.com/44975474/154043638-9bf8141d-5840-49b7-8d7e-1c5a9a662357.png)

6. The inner chart should not exist

**Comment by JohnPCarroll** [comment]
The Doughnut has bar chart selection and not the Doughnut selection. Similar to Pie Chart above

**Comment by damienderoistecso** [comment]
> The Doughnut has a bar chart selection and not the Doughnut selection. Similar to Pie Chart above

Fixed in test @JohnPCarroll ready for testing

**Comment by liamie** [comment]
Pivoted tables can break the bounds of saved queries

Use save query on a pivoted table result

Go to the saved query tab

Display the saved query 

![image](https://user-images.githubusercontent.com/55874862/154048661-72177e35-2b13-4ee3-9f3b-4d0294826032.png)

**Comment by JohnPCarroll** [comment]
The Mixed Column/Line chart is saved in reverse order
![image](https://user-images.githubusercontent.com/44975474/154058213-fddc669d-76e9-42be-9828-f66259aa5664.png)

**Comment by JohnPCarroll** [comment]
The doughnut Chart widget download displays years in reverse order.

Chart on the page
![image](https://user-images.githubusercontent.com/44975474/154260141-3165ce69-e336-4ff0-b951-5168b2597a15.png)


Chart widget download
![image](https://user-images.githubusercontent.com/44975474/154259947-d098d10f-b64f-4ea3-81a0-ff2feca4799f.png)

**Comment by JohnPCarroll** [comment]
The Polar Area widget chart is displaying years in reverse order. Should run 2013 to 2020 not 2020 to 2013

![image](https://user-images.githubusercontent.com/44975474/154264325-860e9087-f9b2-413e-8b02-7e9f2f84ab01.png)

**Comment by JohnPCarroll** [comment]
Issue with date time format on Charts,, maps and widget download
The date format is correct but the time is working on a 12 hour clock. It should operate on a 24 hour clock.

The time is 16:42.04
![image](https://user-images.githubusercontent.com/44975474/154455339-b2d245c7-df0b-4608-b30c-16a8c317e307.png)
 
The time is 04:42;04 which is incorrect.
![image](https://user-images.githubusercontent.com/44975474/154455549-b0717a65-6926-4b2e-99b8-11b4a1298305.png)

**Comment by JohnPCarroll** [comment]
Save Query  :- delete an entry with the same Multi User access. 
For user 1 the delete is correct but an incorrect message is appearing when you try to delete as user 2.
This has occurred for other options in the past and was resolved.

**Comment by damienderoistecso** [comment]
> The Bar charts are encountering the same issue as the column charts
> 
> Table ![153894026-2086ecd6-5304-47c8-8b34-caee06564325](https://user-images.githubusercontent.com/44975474/154025141-7fc4a36d-9b60-4220-8109-74c384f2a54a.png)
> 
> Saved Query ![153894071-7bd134b8-db49-4841-ba9e-df5d594984ea](https://user-images.githubusercontent.com/44975474/154025232-ab4cf875-5a8a-4a1b-9414-1942160b0430.png)

@JohnPCarroll fixed in test

**Comment by damienderoistecso** [comment]
> Issue with date time format on Charts,, maps and widget download The date format is correct but the time is working on a 12 hour clock. It should operate on a 24 hour clock.
> 
> The time is 16:42.04 ![image](https://user-images.githubusercontent.com/44975474/154455339-b2d245c7-df0b-4608-b30c-16a8c317e307.png)
> 
> The time is 04:42;04 which is incorrect. ![image](https://user-images.githubusercontent.com/44975474/154455549-b0717a65-6926-4b2e-99b8-11b4a1298305.png)

@JohnPCarroll fixed in test

**Comment by JohnPCarroll** [comment]
Column and Bar charts re tested for time order using table LMARA02 
The saved charts are correct when all time periods are selected  
The saved charts are in reserve order if only some years selected which is incorrect

**Comment by damienderoistecso** [comment]
> Column and Bar charts re tested for time order using table LMARA02 The saved charts are correct when all time periods are selected The saved charts are in reserve order if only some years selected which is incorrect

@JohnPCarroll fixed in test

**Comment by liamie** [comment]
Save Query button appearing in work in progress table/chart view data
![image](https://user-images.githubusercontent.com/55874862/155103917-4c79a39a-c9f8-44a5-9b37-968a20b394ed.png)
![image](https://user-images.githubusercontent.com/55874862/155104275-e2fcb351-5688-464b-b053-0c13987d534b.png)
Should option be available for work in progress?

**Comment by damienderoistecso** [comment]
> Save Query button appearing in work in progress table/chart view data ![image](https://user-images.githubusercontent.com/55874862/155103917-4c79a39a-c9f8-44a5-9b37-968a20b394ed.png) ![image](https://user-images.githubusercontent.com/55874862/155104275-e2fcb351-5688-464b-b053-0c13987d534b.png) Should option be available for work in progress?

Fixed in test @liamie

**Comment by JohnPCarroll** [comment]
Test passed for Saved Charts using selected years only. Table Used LMARA02

**Comment by JohnPCarroll** [comment]
> > Column and Bar charts re tested for time order using table LMARA02 The saved charts are correct when all time periods are selected The saved charts are in reserve order if only some years selected which is incorrect
> 
> @JohnPCarroll fixed in test
Test passed for Saved Charts using selected years only. Table Used LMARA02

**Comment by JohnPCarroll** [comment]
> Pie

Test passed for Pie and Doughnut charts.  They also have the correct time order

**Comment by JohnPCarroll** [comment]
> The Mixed Column/Line chart is saved in reverse order ![image](https://user-images.githubusercontent.com/44975474/154058213-fddc669d-76e9-42be-9828-f66259aa5664.png)

Test passed. Saved in correct order

**Comment by JohnPCarroll** [comment]
> Polar Area chart saved displays details in reverse years.
> 
> Chart displayed
> 
> ![image](https://user-images.githubusercontent.com/44975474/154060537-9ac6916c-c3b1-415d-a7d7-2422ecccf873.png)
> 
> Image Saved
> 
> ![image](https://user-images.githubusercontent.com/44975474/154060425-eddcbee9-b5fb-416c-b17c-6e3b5e1113ed.png)

Test passed. Now displayed in correct order

**Comment by JohnPCarroll** [comment]
> The doughnut Chart widget download displays years in reverse order.
> 
> Chart on the page ![image](https://user-images.githubusercontent.com/44975474/154260141-3165ce69-e336-4ff0-b951-5168b2597a15.png)
> 
> Chart widget download ![image](https://user-images.githubusercontent.com/44975474/154259947-d098d10f-b64f-4ea3-81a0-ff2feca4799f.png)

Test passed. Years in correct order

**Comment by JohnPCarroll** [comment]
> The Polar Area widget chart is displaying years in reverse order. Should run 2013 to 2020 not 2020 to 2013
> 
> ![image](https://user-images.githubusercontent.com/44975474/154264325-860e9087-f9b2-413e-8b02-7e9f2f84ab01.png)

Test passed. Years in correct order

**Comment by JohnPCarroll** [comment]
Saved Query Popup Issue with Fluid Time Toggle Button not resetting

Default popup is
 
![image](https://user-images.githubusercontent.com/44975474/155526523-96f81e8d-c1d7-4222-ad44-bf62d2c3679c.png)

Set to false as it was required

![image](https://user-images.githubusercontent.com/44975474/155526650-dabfc4f1-f007-4581-a6e2-07800b82b426.png)

It does not matter whether you save or cancel the false value remains if you do not exit the Matrix. It affects both tables and charts and a mxx of both
![image](https://user-images.githubusercontent.com/44975474/155526851-f3b34ee6-826d-4bbc-a848-3d902945cc80.png)

**Comment by JohnPCarroll** [comment]
Save Query and Saved Queries Fluid Time Issue. The Fluid time can be incorrectly appear as true when false was requested.

In Save query popup set the Fluid Time to false and close

![image](https://user-images.githubusercontent.com/44975474/155544469-706e400e-5dfd-4338-b56b-f6a859e5b551.png)

Then Save a query 

![image](https://user-images.githubusercontent.com/44975474/155544593-3e85b469-0a5c-412a-92cc-142c1a9d7a8f.png)

The details on the Saved Queries page has fluid time set to True when it Should be False
![image](https://user-images.githubusercontent.com/44975474/155544904-60e32ff7-5aca-4ef1-ae2f-a6af433f8a98.png)

This may be liked to the Button reset issue noted above

**Comment by damienderoistecso** [comment]
Issue with fluid time for saved queries not correct fixed in test

@JohnPCarroll

**Comment by JohnPCarroll** [comment]
Saved Queries issue with maps
I am getting the Leave Site Message when I select the Save Button and cannot save it

![image](https://user-images.githubusercontent.com/44975474/156358949-f4316f9c-f12c-48e6-9363-cb4441cb001b.png)

**Comment by JohnPCarroll** [comment]
Saved Queries issue with Maps following saving a chart
You save a chart and then save a Map
The saved query for the map is a chart and not a map

![image](https://user-images.githubusercontent.com/44975474/156359688-4dcf3ec8-de74-45ad-b8e4-a4499f18acab.png)

**Comment by damienderoistecso** [comment]
> Saved Queries issue with Maps following saving a chart You save a chart and then save a Map The saved query for the map is a chart and not a map
> 
> ![image](https://user-images.githubusercontent.com/44975474/156359688-4dcf3ec8-de74-45ad-b8e4-a4499f18acab.png)

Issues with saving map queries should be fixed in test @JohnPCarroll

**Comment by JohnPCarroll** [comment]
> Saved Queries issue with maps I am getting the Leave Site Message when I select the Save Button and cannot save it
> 
> ![image](https://user-images.githubusercontent.com/44975474/156358949-f4316f9c-f12c-48e6-9363-cb4441cb001b.png)

Test passed

**Comment by JohnPCarroll** [comment]
> > Saved Queries issue with Maps following saving a chart You save a chart and then save a Map The saved query for the map is a chart and not a map
> > ![image](https://user-images.githubusercontent.com/44975474/156359688-4dcf3ec8-de74-45ad-b8e4-a4499f18acab.png)
> 
> Issues with saving map queries should be fixed in test @JohnPCarroll

Test Passed

**Comment by damiancosmoschapman** [comment]
Added a fix for deleting a saved query that does not exist in the database to return a failure rather than a success response.

**Comment by damiancosmoschapman** [comment]
> Added a fix for deleting a saved query that does not exist in the database to return a failure rather than a success response.

**Comment by liamie** [comment]
Table Queries created and printed only show Saved Queries in heading for all

![image](https://user-images.githubusercontent.com/55874862/160598761-221969b1-d8d1-4e5a-847c-9e56c09e0926.png)

Should this be table/ query nickname or combination of both

**Comment by damiancosmoschapman** [comment]
@damienderoistecso , @CHanamy57 , I'm not sure if this is a backend issue but if it is, can you please let me know?

**Comment by damienderoistecso** [comment]
> Table Queries created and printed only show Saved Queries in heading for all
> 
> ![image](https://user-images.githubusercontent.com/55874862/160598761-221969b1-d8d1-4e5a-847c-9e56c09e0926.png)
> 
> Should this be table/ query nickname or combination of both

Fixed and test in test
