### ISSUE TITLE
[ENHANCEMENT] Allow users to choose fluid or fixed time for widgets

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#497]
allow users to build widgets using fluid time or fixed time.

If the user chooses fluid time, the position of their timepoints will always remain the same, even if more timepoints get added to the data.

**Comment by damienderoistecso** [comment]
@liamie ready for testing

**Comment by liamie** [comment]
This seems to be working correctly as intended. Labels/Buttons for this widget process now seems to be correct also in charts and tables.
