### ISSUE TITLE
Remove default sort of the results table in PxStat[ENHANCEMENT] 

### ISSUE THREAD

**Issue by Elainehoward** [CSOIreland/PxStat#499]
Hi all,

Would it be possible to remove the default sort of the results table by the first column?  At the moment the Statistic column is in alphabetical order on the results table.

Thanks
Elaine

**Comment by liamie** [comment]
By default the results are now ordered in statistic code order on results page. Note however if the sort columns arrows are used on the results page this will apply to statistic name alphabetical order as per before
