### ISSUE TITLE
[BUG] Duplicate entry in list of releases

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#50]
**Describe the bug**
If a matrix title for the same code differs over releases, there will be a duplicate entry in the Code List.

**Comment by neilfromcork** [comment]
Fix in dev

**Comment by damienderoistecso** [comment]
Removed tool tip from read matrix lookup, removed language parameter when calling          "PxStat.Data.Matrix_API.ReadCodeList",
 @JohnPCarroll ready for testing
