### ISSUE TITLE
Add option to download Statistics in Build/Create [ENHANCEMENT] 

### ISSUE THREAD

**Issue by Elainehoward** [CSOIreland/PxStat#500]
Hi all,

Can we have a option to download the statistics in the Build/Create?  This would allows us to change the order of the statistic without having to delete all the existing statistics that may be in a table.  This happens if a section require changes to be made to an existing table.

Thanks
Elaine

**Comment by damienderoistecso** [comment]
Fixed in dev 

@liamie ready for testing

**Comment by liamie** [comment]
If there is no statistic the download button is stall active but downloads a completely blank file with the table_statistic filename which then throws up an error if try to upload, would it be better to disable button and inform if just going to produce an invalid file that may be confused with correct versions

**Comment by liamie** [comment]
Different languages are downloaded on separate tabs however the exact same filename is used for the downloaded statistics regardless of language, this may lead to confusion may want to incorporate language into part of the filename to distinguish easier for reuploading

**Comment by damienderoistecso** [comment]
Fixed in dev

@liamie ready for testing
