### ISSUE TITLE
[ENHANCEMENT] Remove language dropdown if only one language

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#502]
If there is only one language in the system, remove redundant language dropdown select

**Comment by damienderoistecso** [comment]
Fixed in dev

@liamie ready for testing

**Comment by liamie** [comment]
During testing for this. It appears now if a language is created and then chosen from the dropdown after refresh it reverts back to the default language as expected, if no internationalization dictionary json file exists.  But this then keeps looping trying to find a json file with the language code in the client.

**Comment by liamie** [comment]
The logged in name button and login button (if no one is logged in) keep a straight line on the right hand side as if expecting the dropdown to be there with its rounding on the right to complete the rounded look. These should probably be rounded corners like everything else if no drop down there.
![image](https://user-images.githubusercontent.com/55874862/152507945-5c802ba0-acb6-4dcf-8ee1-6ec5b7449aee.png)

**Comment by damienderoistecso** [comment]
> During testing for this. It appears now if a language is created and then chosen from the dropdown after refresh it reverts back to the default language as expected, if no internationalization dictionary json file exists. But this then keeps looping trying to find a json file with the language code in the client.

resolved by enhancement #509

**Comment by damienderoistecso** [comment]
> The logged in name button and login button (if no one is logged in) keep a straight line on the right hand side as if expecting the dropdown to be there with its rounding on the right to complete the rounded look. These should probably be rounded corners like everything else if no drop down there. ![image](https://user-images.githubusercontent.com/55874862/152507945-5c802ba0-acb6-4dcf-8ee1-6ec5b7449aee.png)

Fixed in dev @liamie ready for testing

**Comment by liamie** [comment]
Remaining button edges after dropdown removed seem to be correct now.

**Comment by liamie** [comment]
Appears to be correct now for one language.
