### ISSUE TITLE
[ENHANCEMENT] Ability to chose to not try and connect to an active directory to avoid error message when one isn't connected

### ISSUE THREAD

**Issue by 1556953** [CSOIreland/PxStat#505]
When not connected to an AD and using local users only, a daily error is received in the log to notify of invalid AD configuration. It would be useful to be able to flag that no AD is there to avoid this error
![image](https://user-images.githubusercontent.com/60383775/151177190-d05373ad-0e00-4f3c-956a-adf6c68fb9c3.png)

**Comment by liamie** [comment]
Option available now.
