### ISSUE TITLE
OSM broken link map tile layer message appears when adding a new map to the map list

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#506]
**Describe the bug**
OSM broken link map tile layer message appears when adding a new map to the map list

**To Reproduce**
1. Go to system -> maps 
2. Click on add button and upload map json file
3. Scroll down to set properties
4. After setting dropdowns click view map
5. error message appears in background tiles

**Expected behavior**
blank base tiles

**Comment by damienderoistecso** [comment]
OSM layer updated
Fixed in test 
@liamie ready for test

**Comment by liamie** [comment]
Message no longer appearing tile appears correct.
