### ISSUE TITLE
[ENHANCEMENT] Add NltWidget to PxStat.Security.Analytic_API.ReadReadTimeline

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#507]
Bring PxStat.Security.Analytic_API.ReadReadTimeline in line with PxStat.Security.Analytic_API.ReadRead by including NltWidget in the output

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test @damienderoistecso

**Comment by damienderoistecso** [comment]
Duplicate of #466
