### ISSUE TITLE
[ENHANCEMENT] Only allow new languages if dictionary exists

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#509]
When you attempt to add a new language to the system, you should only be able to do so if you have first created the dictionary for the language in the correct location

also, when a language is being deleted, any user that has this language set as their preference should have their preference reverted to the default language

**Comment by neilfromcork** [comment]
The existing matrix language check in Language_API.Delete has been extended to also test if the language is in use for accounts or subscribers. This is ready for test

**Comment by damienderoistecso** [comment]
Client side updated

@liamie ready for testing

**Comment by liamie** [comment]
The language>create api still allows a language to be created and so the problem persists?

**Comment by neilfromcork** [comment]
API now requires the dictionary to be in place before a language can be created

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/152984852-edbbcefa-8ed5-4b34-aba8-4c07444b4d87.png)
Is coming up on client side even if language file exists in client
