### ISSUE TITLE
[BUG] Invalid Source displayed when Import option used in Build/Create

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#51]
**Describe the bug**
When you import a px file containing a source we currently do not include, it is shown on screen as Central Statistics Office, Ireland

**Comment by damienderoistecso** [comment]
If invalid copyright in imported px file, user forced to select valid copyright

@JohnPCarroll ready for testing

**Comment by damienderoistecso** [comment]
Fixed closing confirm modal in releases entity, fixed issue with repeating formats in dropdown

@JohnPCarroll ready for testing
