### ISSUE TITLE
[BUG] Bar chart. Delete Button is removed when series selected is viewed

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#517]
The delete button on a series selected is removed when the View button is selected. This does not happen on the Line and Column Charts. 

**Expected behavior**
The delete button should not be removed and remain active

**Comment by liamie** [comment]
The Add Series Button also disappears on bar charts at the view stage present on Column
![image](https://user-images.githubusercontent.com/55874862/154957237-f7c569b4-752a-4dfd-ada7-2eb56a583f4d.png)

**Comment by damienderoistecso** [comment]
fixed in test @JohnPCarroll @liamie
