### ISSUE TITLE
[BUG] Radar Charts.  There is missing text

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#519]
**Describe the bug**
1. The first section is missing a title and an active box has no text beside it

![image](https://user-images.githubusercontent.com/44975474/154064599-d1269cfb-59b4-4f12-a04f-7f1270f1bc75.png)

2. The Series 1 section has a Y-Axis non active dropdown. Why is this required ?

![image](https://user-images.githubusercontent.com/44975474/154064833-8fa9020f-9d45-4f33-a357-d6ffa6a6bb2a.png)

3. The options section X-Axis Max No. of Steps. Is this required as it appears to make no difference

![image](https://user-images.githubusercontent.com/44975474/154065160-c30ed10f-beb0-4450-82ed-fca5926b8b6f.png)

**Comment by damienderoistecso** [comment]
fixed in test @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Test passed for Part 1 and Part 3
