### ISSUE TITLE
[BUG] Chart Widget toggle buttons not resetting

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#520]
In the Widget section you set the toggle buttons to false for one or more options. It does not reset if you require another type of chart widget for the same Table

Default values
![image](https://user-images.githubusercontent.com/44975474/154236774-3648fdfb-f731-4570-b152-5f97ebae9c81.png)

Set to false

![image](https://user-images.githubusercontent.com/44975474/154236882-32d6733f-2aa9-4681-92f2-218c1e5a362d.png)

Initial appearance on new chart type selection

![image](https://user-images.githubusercontent.com/44975474/154237090-2833850a-b224-4298-8f26-173f6532c605.png)

The widget Toggle buttons should be set to True  for next chart type required for the same table.

**Comment by damienderoistecso** [comment]
fixed in test

@JohnPCarroll please test from data entity and also from releases (WIP & live)

**Comment by JohnPCarroll** [comment]
Test passed for the Widget toggle Buttons in the Data Entity and Release (WIP and Live ).
