### ISSUE TITLE
Auto scale being ignored for bar horizontal bar charts

### ISSUE THREAD

**Issue by Elainehoward** [CSOIreland/PxStat#521]
Hi all,

When we try to create a bar chart in PxStat the AutoScale option doesn't seem to be working.  

Thanks
Elaine

**Comment by damienderoistecso** [comment]
Begin at zero was being applied to the wrong axes for horizontal bar charts 
Fixed in test @JohnPCarroll @liamie @DeclanBuckley

**Comment by liamie** [comment]
Auto scaling now along the horizontal axis for barcharts
