### ISSUE TITLE
[BUG] Analytics not showing correct values

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#522]
Live Environment
The Table total is not correct. It appears to be not including the BOTS number.
![image](https://user-images.githubusercontent.com/44975474/154664668-85d6eb7f-0254-4a63-9559-2722d879be1e.png)

The summary Total is correct as it includes BOTS, M2M and Users

![image](https://user-images.githubusercontent.com/44975474/154664965-74efe81f-6feb-465d-8e7b-527afbd984dc.png)

**Comment by neilfromcork** [comment]
Rule changed to ensure if BOT then all other categories are overruled
