### ISSUE TITLE
[ENHANCEMENT] Allow sorting of widget charts by value

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#523]
For bar, line or column charts, where you have one series, allow the user to order the variables by value

**Comment by liamie** [comment]
using stacked percentage and sort by value together could cause confusion as to ordering is done by value but no visual clue as to whether this is correct as the displayed percentage is 100% for all
Would it be better to disable sort by value for stacked percentage 
![image](https://user-images.githubusercontent.com/55874862/156362339-fa9a5b0c-6226-41f4-8a61-6bee268f0ea6.png)

**Comment by damienderoistecso** [comment]
Fixed in test @liamie

**Comment by liamie** [comment]
sort by value and stacked percentage clear now
