### ISSUE TITLE
[BUG] Using filter allows it to appear cells selected are greater than cells available and that classifications can appear to be be picked more than once

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#524]
**Describe the bug**
Using filter allows it to appear cells selected are greater than cells available and that classifications can appear to be be picked more than once
![image](https://user-images.githubusercontent.com/55874862/156156372-7256e65e-a3cc-472e-9634-2e50b5e2c94c.png)

**To Reproduce**
1. Go to Table
2. Click on a selection of classifications, use filter and even if that is already in the list it can be reselected

**Expected behavior**
Show correct cells selected count

**Comment by damienderoistecso** [comment]
Fixed in test @liamie

**Comment by liamie** [comment]
Filter option now only displays items not already selected so  only once on list now and does not exceed cells available with cells selected.
