### ISSUE TITLE
[BUG] Choosing certain sections of data drops product value details producing an error in comparing data and expected values

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#525]
**Describe the bug**
Choosing certain sections of data drops product value details producing an error in comparing data and expected values

![image](https://user-images.githubusercontent.com/55874862/156200643-29ed1750-a748-478d-86b1-9249591cbe15.png)

**To Reproduce**
1. Go to Table eg PCA14
2. Choose starting classifications  27115080 to 27123205

when download px file it won't correctly upload and the product value for the  27.12.32.05 code is missing
if the above  block of classifications is included and so the data for the file reads as to large if try to import
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by neilfromcork** [comment]
The px file downloaded from "Download Source" doesn't validate on pxstat (and crashes PxWin). The issue here is perhaps how did it pass validation first time?

**Comment by neilfromcork** [comment]
Should this issue be closed?
