### ISSUE TITLE
[ENHANCEMENT] Improve clarity of Dual Axis requiring second series

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#526]
Currently if a single series is chosen and the setting for dual axis is picked  the side not chosen only shows a default  value scale.

This should not be possible as it could lead to confusion.
![image](https://user-images.githubusercontent.com/55874862/156382432-a22c950d-2fac-4028-9752-b356680af2e3.png)

**Comment by damienderoistecso** [comment]
Error now shown if dual axis selected with only one series

Ready for testing @liamie

**Comment by liamie** [comment]
Appropriate error message now appears if only one series is chosen with dual axis

Note: still possible to double/overstack one axis, but that's a usage issue
