### ISSUE TITLE
[BUG] Product details not appearing on update Product

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#527]
When you click to update a Product the details do not appear every time.

![image](https://user-images.githubusercontent.com/44975474/156744085-baebc3b7-9b5c-4102-a15f-f06e818f1283.png)

**Comment by damienderoistecso** [comment]
Fixed in test @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Test passed in test environment
