### ISSUE TITLE
[BUG] CSV Downloads in compare releases do not recognise Codes

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#530]
**Describe the bug**
In other areas if codes is chosen the csv download includes codes but in compare releases it is the un coded csv that down loads regardless of whether codes is active or not 
![image](https://user-images.githubusercontent.com/55874862/157209538-d6e56f06-37d5-4911-a45a-38de39126d74.png)

**To Reproduce**
1. Go to 'compare release'
2. Click on 'codes button' set  to true
3. Download CSV
4. Codes are not included in CSV

**Expected behavior**
Codes should be included in CSV if display codes is chosen

**Comment by damienderoistecso** [comment]
As this export comes from the datatable library rather than an API, it is much more complex to include, exclude codes from the export.

If there is a strong case from the business areas to includes/exclude codes we can look at implementing this but for now I don;t think it's worth the effort
