### ISSUE TITLE
[BUG] When Update Navigation is used on a published table the table remains on the previous product page as well as the new 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#531]
**Describe the bug**
Products https://test-data.cso.ie/product/testpro
and https://test-data.cso.ie/product/code1 both contain the same table LMAKM01

**To Reproduce**
1. Go to release page 
2. Click on update navigation
3. Change product
4. Recheck the links

**Expected behavior**
table to display only on the current product page

**Comment by neilfromcork** [comment]
@liamie - I can't replicate this. When I update navigation on the release page to change the product, it remains changed.

**Comment by neilfromcork** [comment]
@liamie - I found an issue and deployed a fix into test. Can you retry?

**Comment by liamie** [comment]
May be related but when using manage products to change the subject there is a similar delay/ misstep of the location of tables.

![image](https://user-images.githubusercontent.com/55874862/157461514-0030b6bb-f572-43bf-8292-51580c631643.png)

Note the different breadcrumb old location  to the theme drop down new location of these tables

**Comment by liamie** [comment]
> 

the first part seems corrected now, the product pages reflect updated locations rather than appearing in both

**Comment by neilfromcork** [comment]
Cache flush extended to subject update api

**Comment by neilfromcork** [comment]
Code updated to clear the individual caches for matrix codes and release codes for ReadDataset, ReadPreDataset, ReadMetadata and ReadPreMetadata @damienderoistecso @liamie

**Comment by liamie** [comment]
@neilfromcork @damienderoistecso reopened this as the table linking from last updated tables part of home page does not seem to be fixed by this.

**Comment by liamie** [comment]
seems correct now
