### ISSUE TITLE
[BUG] Colours repeat after 10 series rather than 20 in charts

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#534]
**Describe the bug**
Colours for charts repeat after 10 series this should not occur until 20
![image](https://user-images.githubusercontent.com/55874862/158365016-042c91e2-75c5-4509-8b43-297daa7b951f.png)

**To Reproduce**
1. Go to '.chart'
2. create more than 10 series
4. See colours start to repeat

**Expected behavior**
Colours should be distinct until 20

**Comment by damienderoistecso** [comment]
Fixed in test @liamie
