### ISSUE TITLE
[BUG] Issue with Last Updated Tables list 

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#537]
The Last updated Tables list is not working if you select a from date or last 7 or last 30 days post using the pivot option on a table.

1. Go to a table and select data 
2. View the data
3.  Pivot the data
4. Go to Data Page
5. Select the last 30 days and the last updated tables are not shown.

**Expected behavior**
Relevant data displayed

**Comment by liamie** [comment]
This also seems to occur from releases > view data> and similar pivot

**Comment by damienderoistecso** [comment]
Issue is caused when for some reason, the code enters a column render function from a previous rendered datatable and find an undefined variable there

Patch put in place to check for that variable first, if it does not exists return null from the render function

@JohnPCarroll ready for test
