### ISSUE TITLE
[BUG] Charts can be created with no series

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#538]
**Describe the bug**
Charts can be published with no series. Normally the view button is inactive by default or produces an error when pressed containing information on what series is missing elements and no chart is created until these are corrected.

**To Reproduce**
1. Go to a column chart
2. Setup the x-axis
3. delete the series there by default ( also occurs if delete created series after view first) 
4. Press view See chart with no series

**Expected behavior**
View button should be inactive/produce error until a valid series is created

**Comment by liamie** [comment]
same for any of the charts with the delete series option

**Comment by damienderoistecso** [comment]
fixed in test @liamie

**Comment by liamie** [comment]
Seems correct now
