### ISSUE TITLE
[BUG] Sorting of Values column on data results table

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#54]
**Describe the bug**
Incorrect sorting of values column on data results table

**To Reproduce**
In a table with values of over a thousand, sort by values

**Expected behavior**
Correct sorting of values

**Screenshots**
![image](https://user-images.githubusercontent.com/53211688/72795557-c7214100-3c35-11ea-9ca1-f52bbfb65c19.png)

**Comment by damienderoistecso** [comment]
Added override for natural sorting

@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test Successful
