### ISSUE TITLE
[ENHANCEMENT] Visibility of available maps for moderators/power users

### ISSUE THREAD

**Issue by CSOIrelandTechnology** [CSOIreland/PxStat#541]
Have ability for moderators to see what maps are available. Currently, the only way for moderators or power users to see what maps are loaded into the system is to view them through the create/update entities.

**Comment by damienderoistecso** [comment]
@neilfromcork 
Can the following privilege's be applied to the following API's

"PxStat.Data.GeoLayer_API.Read" - All privilege types
"PxStat.Data.GeoLayer_API.Create" - Administrators only
"PxStat.Data.GeoLayer_API.Update" -  Administrators only
"PxStat.Data.GeoLayer_API.Delete" -  Administrators only

"PxStat.Data.GeoMap_API.ReadCollection" - All privilege types
"PxStat.Data.GeoMap_API.Validate" - Administrators only
 "PxStat.Data.GeoMap_API.Create"- Administrators only
"PxStat.Data.GeoMap_API.Delete"- Administrators only
"PxStat.Data.GeoMap_API.Update"- Administrators only
"PxStat.Data.Matrix_API.ReadByGeoMap"- Power users and Administrators

**Comment by damienderoistecso** [comment]
Moved map entity from system to build

Client side changes complete

**Comment by damiancosmoschapman** [comment]
Server side changes complete.

**Comment by liamie** [comment]
Map tables not visible for power user
seems to be permission on PxStat.Data.Matrix_API.ReadByGeoMap

**Comment by damiancosmoschapman** [comment]
Changed "PxStat.Data.Matrix_API.ReadByGeoMap"- Power users and Administrators to
Power users or Administrators.

Please retest.

**Comment by liamie** [comment]
This seems to be correct now.
