### ISSUE TITLE
[BUG] < and > symbols removed from Title when PX goes through Update

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#545]
The table title is "Wind, Maximum Gale Gust (>33.5 Knots)"
When brought into the Update the > was still visible but once the new PX file was generated the > was missing form the title.
Before -
DESCRIPTION="Wind, Maximum Gale Gust (>33.5 Knots)";
TITLE="Wind, Maximum Gale Gust (>33.5 Knots)";
CONTENTS="Wind, Maximum Gale Gust (>33.5 Knots)";
UNITS="Knots";
STUB="STATISTIC","Month";
HEADING="Meteorological Weather Station";
CONTVARIABLE="STATISTIC";
VALUES("STATISTIC")="Wind, Maximum Gale Gust (>33.5 Knots)";

After -
DESCRIPTION="Wind, Maximum Gale Gust (33.5 Knots)";
TITLE="Wind, Maximum Gale Gust (33.5 Knots)";
CONTENTS="Wind, Maximum Gale Gust (33.5 Knots)";
UNITS="Knots";
STUB="STATISTIC","Month";
HEADING="Meteorological Weather Station";
CONTVARIABLE="STATISTIC";
VALUES("STATISTIC")="Wind, Maximum Gale Gust (>33.5 Knots)";

**Comment by damienderoistecso** [comment]
Update and create are both affected by this bug

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. For Build, another problems was the Title was being taken from the Contents rather than the Title field in the px file. This has been rectified.
