### ISSUE TITLE
[ENHANCEMENT] Can a True/False indicator be included in each field of the Comparison Report

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#546]
We use the Comparison Report when approving every publication request for a table. We need to check if there have been Amendments and Additions to ensure the correct Reason to Publish codes have been selected.

However, if the table is large (greater then 1 million rows I think) a pop-up warns that the Comparison Report may slow down your machine or not run -
![Compare Release Large File Warning](https://user-images.githubusercontent.com/59689411/162239602-74c94ac2-74bd-43e3-8b16-b1515ac62012.PNG)

If the Report is still requested a blank Comparison Report is created -
![Comparison Report Blank](https://user-images.githubusercontent.com/59689411/162242981-e7574219-bd66-4db9-9c70-cb2c97f89b1c.PNG)

Is it possible to a include a feature to indicate if any Amendments, Additions or Deletions were present in the report? In these circumstances it is understandable that it may not be possible to list them, but it would be very useful to know if any were present at all.
Thanks.

**Comment by liamie** [comment]
If the comparison warning message is continued from only the results available are given.
