### ISSUE TITLE
Notes in Excel appearing as generic collections call [BUG] 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#548]
In the excel Table Note field :
System.Collections.Generic.List`1[System.String]

Appears instead of note/blank if no note

**Comment by liamie** [comment]
In Excel Codes for products that are numeric only appear on the right of the code field text appears on the left and 
if numeric leading zeros are removed on codes so 01 appears as 1

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
This Seems to be correct now
