### ISSUE TITLE
[BUG] Statistic replaced by Matrix Title in dev

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#549]
In the Development Environment : The Title has replaced the word Statistic.

When you view the Matrix Details the Title is used instead of the word Statistic

The word Statistic should be used

![image](https://user-images.githubusercontent.com/44975474/165270246-5bd67895-4a42-446a-8eaa-c5970ed815d9.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Incorrect capitalisation on the Label leaves difficulty distinguishing between Statistic and STATISCIC
CPA01 on live
![image](https://user-images.githubusercontent.com/55874862/165480433-b7354a2a-6b36-47b8-81aa-ce49936d25c2.png)

LMCPA01 in dev
![image](https://user-images.githubusercontent.com/55874862/165480001-b7a522f5-f744-4485-8dfc-15f55bcf79a4.png)


CPA05 on live
![image](https://user-images.githubusercontent.com/55874862/165480850-6626ba05-7f9c-473a-a3a5-0861768deac8.png)

LMCPA05 in Dev
![image](https://user-images.githubusercontent.com/55874862/165481840-a84e2d1c-46da-4eff-8697-a7f07acbad82.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - for new uploads
