### ISSUE TITLE
[BUG] In Excel the Pivoted page does not contain the correct data DEV

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#553]
**Describe the bug**
Table used RAA01. I downloaded the  table using the option XLSX 2007. The Statistic is mot ticked or included in the Rows

**Expected behavior**
The Pivoted page should contain the data in the same format as live 

![image](https://user-images.githubusercontent.com/44975474/165764035-f56cbbc2-83a9-45f8-90f0-271983dee018.png)

![image](https://user-images.githubusercontent.com/44975474/165764125-b59f4b88-bb00-403e-a129-3b3e5c519747.png)

The dev output is incorrect

![image](https://user-images.githubusercontent.com/44975474/165764247-5fff860f-94bf-4a68-84cf-0c90d4e1b3d6.png)

![image](https://user-images.githubusercontent.com/44975474/165764310-51cab624-1a41-439f-9930-6ed877a90f53.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test.

**Comment by JohnPCarroll** [comment]
Test passed
