### ISSUE TITLE
[BUG] Browse option not displaying a list of tables for a product in DEV

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#554]
**Describe the bug**
When you select a product the list of tables are not displayed on the page. A no data found message is shown

**To Reproduce**
1. Go to the Data page
2. Click on Browse 
3. Click on a Theme followed by Subject followed by Product. 
4. I created new ones for each on dev.

**Expected behavior**
The relevant tables associated with the Product shown be shown.

**Screenshots**
Message shown is 
![image](https://user-images.githubusercontent.com/44975474/165939435-fec7564d-5688-4062-91b8-63cba361c43c.png)

**Comment by JohnPCarroll** [comment]
The same issue arises if you use 
![image](https://user-images.githubusercontent.com/44975474/165940122-0a98ac19-ddb6-4a9e-adc8-6d5043d0285c.png)

at table or product Level

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by JohnPCarroll** [comment]
> 

Test Passed once tables reloaded

**Comment by JohnPCarroll** [comment]
> The same issue arises if you use ![image](https://user-images.githubusercontent.com/44975474/165940122-0a98ac19-ddb6-4a9e-adc8-6d5043d0285c.png)
> 
> at table or product Level

Teat passed once tables reloaded
