### ISSUE TITLE
[BUG] Dual Language files give error during import

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#555]
**Describe the bug**

**To Reproduce**
1. Go to  Build>Import
2. Import a dual language file 
3. Validation works correctly 
4.  When click file import button error appears
5. See error

![image](https://user-images.githubusercontent.com/55874862/166468746-213d43c7-d61f-4b50-835a-8f0da00058c1.png)

**Expected behavior**
Import file correctly

**Additional context**
Validation for the file passes correctly its only on import

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Dual language files seem to be importing correctly now.
