### ISSUE TITLE
[BUG] Import states there unable to continue due to workflow in progress but no workflow exists

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#560]
**Describe the bug**
Import states there unable to continue due to workflow in progress but no workflow exists

**To Reproduce**
1. Go to build import 
2. Go to import copy px file C0111 can be obtained by dowloding from source of current C0001 in dev
3. Validates correct but on file import
![image](https://user-images.githubusercontent.com/55874862/166707572-cff9215e-14e5-4a9f-9eb5-b48a808b80de.png)

**Expected behavior**
Message should only appear if workflow present

**Comment by neilfromcork** [comment]
There is a pending WIP but it appears to only exist in an Irish language version. Was this related to a failed import? @liamie

**Comment by liamie** [comment]
closed invalid
