### ISSUE TITLE
[BUG] Client requests data in English even when the user has changed preference to Irish. 

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#561]
Client requests data in English even when the user has changed preference to Irish. 

This occurs for WIP and Live under the Releases tab
Also appears when viewing the data and metadata in Comparison

**Comment by neilfromcork** [comment]
@damienderoistecso - This is ok under the Data tab, occurs under the Releases tab

**Comment by damienderoistecso** [comment]
The returned data language is not defined by the interface language preference. It is defined by whatever the user selects from the language dropdown in the source panel
