### ISSUE TITLE
[ENHANCEMENT] Map widget new features

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#562]
- Allow users to choose mode, q for quantile, e for equidistant, k for k-means

**Comment by damienderoistecso** [comment]
Allow base maps to be configurable through the snippet code by way of constants in Pxstat

**Comment by damienderoistecso** [comment]
Change starting scale color from "whitesmoke" to "antiquewhite" for a better contrast for low value features

**Comment by damienderoistecso** [comment]
@liamie ready for test. Client needs to point to dev widget code for testing

**Comment by liamie** [comment]
options in dropdown appearing clipped 
![image](https://user-images.githubusercontent.com/55874862/186447748-5c1c35a9-5b77-4bc4-9155-0c9135a72c54.png)

**Comment by damienderoistecso** [comment]
> options in dropdown appearing clipped in some screen sizes ![image](https://user-images.githubusercontent.com/55874862/186447748-5c1c35a9-5b77-4bc4-9155-0c9135a72c54.png)

Fixed in dev @liamie ready for testing

**Comment by liamie** [comment]
selection box is now displayed in full where possible.
