### ISSUE TITLE
[BUG] Existing table data displayed as 0 instead of double dots in new DEV

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#563]
**Describe the bug**
Table used TDM04. Where a value is NULL it should be displayed as a double dot and not as 0.

**Screenshots**
Table TDM04 already on database. The data is incorrect
![image](https://user-images.githubusercontent.com/44975474/167666868-4dc0ff92-0967-42ff-86dc-3c070821f197.png)

Table TDM04JC ( same details as TDM04 ) Loaded 10/05/22. The data is correct

![image](https://user-images.githubusercontent.com/44975474/167667020-183b31de-f7da-4099-8f58-3ce7e55151e9.png)

**Comment by liamie** [comment]
This seems to be corrected now with new database update old data and new imports show ..

**Comment by JohnPCarroll** [comment]
Test passed for Current Matrices and New Matrices loaded. This applies to this with single or Multiple Statistics
