### ISSUE TITLE
[BUG] Decimals places not getting displayed for tables with 1 statistic in new DEV

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#564]
**Describe the bug**
Table used G0316
Tables with one Statistic and where the values contain decimals are getting rounded so no decimals are displayed

**Expected behavior**
Values containing decimals should be displayed as per the requirements in the PX File

**Screenshots**
Live Table with correct data

![image](https://user-images.githubusercontent.com/44975474/167822712-b6f4f50d-901d-4e16-a1cf-8851bd0efb2a.png)

The Live px file. Please note DECIMALS value 
[G0316.20220511T100529.px.txt](https://github.com/CSOIreland/PxStat/files/8668802/G0316.20220511T100529.px.txt)

Dev environment containing incorrect data

![image](https://user-images.githubusercontent.com/44975474/167822878-b1b8a57a-d759-472e-9478-998c257fea66.png)

The Dev px file. Please note DECIMALS value 
[G0316.20220511T100520.px.txt](https://github.com/CSOIreland/PxStat/files/8668807/G0316.20220511T100520.px.txt)

**Comment by damiancosmoschapman** [comment]
I think the table used is incorrect. I think it should be G0316 rather than S0316.

I tested, using Developer tools in Chrome and the PxStat API returns the correct decimal values in the response (see below)  @JohnPCarroll, Could this be an issue with the front end?:

`{
   "jsonrpc":"2.0",
   "result":{
      "class":"dataset",
      "dimension":{
         "STATISTIC":{
            "category":{
               "index":[
                  "G0316"
               ],
               "label":{
                  "G0316":"Suicide mortality rate"
               },
               "unit":{
                  "G0316":{
                     "decimals":0,
                     "label":"No. per 1000 Pop.",
                     "position":"end"
                  }
               }
            },
            "label":"STATISTIC"
         },
         "TLIST(A1)":{
            "category":{
               "index":[
                  "2014",
                  "2015",
                  "2016"
               ],
               "label":{
                  "2014":"2014",
                  "2015":"2015",
                  "2016":"2016"
               }
            },
            "label":"Year"
         },
         "C03171V03833":{
            "category":{
               "index":[
                  "-",
                  "A",
                  "010",
                  "021",
                  "022",
                  "023",
                  "024",
                  "030",
                  "040",
                  "050",
                  "060",
                  "070",
                  "080",
                  "090",
                  "100",
                  "110",
                  "120",
                  "B",
                  "130",
                  "141",
                  "142",
                  "150",
                  "161",
                  "162",
                  "170",
                  "171",
                  "172",
                  "181",
                  "182",
                  "C",
                  "191",
                  "192",
                  "200",
                  "210",
                  "220",
                  "230",
                  "D",
                  "240",
                  "250",
                  "260",
                  "IE11",
                  "IE12",
                  "IE13",
                  "IE21",
                  "IE22",
                  "IE23",
                  "IE24",
                  "IE25"
               ],
               "label":{
                  "-":"State",
                  "A":"Leinster",
                  "010":"Carlow",
                  "021":"Dublin City",
                  "022":"South Dublin",
                  "023":"Fingal",
                  "024":"Dun Laoghaire-Rathdown",
                  "030":"Kildare",
                  "040":"Kilkenny",
                  "050":"Laois",
                  "060":"Longford",
                  "070":"Louth",
                  "080":"Meath",
                  "090":"Offaly",
                  "100":"Westmeath",
                  "110":"Wexford",
                  "120":"Wicklow",
                  "B":"Munster",
                  "130":"Clare",
                  "141":"Cork City",
                  "142":"Cork County",
                  "150":"Kerry",
                  "161":"Limerick City",
                  "162":"Limerick County",
                  "170":"Tipperary",
                  "171":"North Tipperary",
                  "172":"South Tipperary",
                  "181":"Waterford City",
                  "182":"Waterford County",
                  "C":"Connacht",
                  "191":"Galway City",
                  "192":"Galway County",
                  "200":"Leitrim",
                  "210":"Mayo",
                  "220":"Roscommon",
                  "230":"Sligo",
                  "D":"Ulster (part of)",
                  "240":"Cavan",
                  "250":"Donegal",
                  "260":"Monaghan",
                  "IE11":"Border",
                  "IE12":"Midland",
                  "IE13":"West",
                  "IE21":"Dublin",
                  "IE22":"Mid-East",
                  "IE23":"Mid-West",
                  "IE24":"South-East",
                  "IE25":"South-West"
               }
            },
            "label":"Area of Residence"
         },
         "C02199V02655":{
            "category":{
               "index":[
                  "-",
                  "1",
                  "2"
               ],
               "label":{
                  "-":"Both sexes",
                  "1":"Male",
                  "2":"Female"
               }
            },
            "label":"Sex"
         }
      },
      "extension":{
         "matrix":"G0316",
         "reasons":[
            
         ],
         "language":{
            "code":"en",
            "name":"English"
         },
         "elimination":{
            "C03171V03833":null,
            "C02199V02655":null
         },
         "contact":{
            "name":"Kevin McCormack",
            "email":"Kevin.McCormack@cso.ie",
            "phone":"(+353) 21 453 5603"
         },
         "subject":{
            "code":40,
            "value":"Sustainable Development Goals"
         },
         "product":{
            "code":"SDG3",
            "value":"Goal 3 - Good Health and Well-Being"
         },
         "official":true,
         "copyright":{
            "name":"Central Statistics Office, Ireland",
            "code":"CSO",
            "href":"https://www.cso.ie/"
         },
         "exceptional":false,
         "reservation":false,
         "archive":false,
         "experimental":false,
         "analytical":false
      },
      "href":"https://dev-ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/G0316/PX/2013/en",
      "id":[
         "STATISTIC",
         "TLIST(A1)",
         "C03171V03833",
         "C02199V02655"
      ],
      "label":"Suicide mortality rate",
      "link":{
         "alternate":[
            {
               "type":"text/csv",
               "href":"https://dev-ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/G0316/CSV/1.0/en"
            },
            {
               "type":"application/json",
               "href":"https://dev-ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/G0316/JSON-stat/2.0/en"
            },
            {
               "type":"application/json",
               "href":"https://dev-ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/G0316/JSON-stat/1.0/en"
            },
            {
               "type":"application/base64",
               "href":"https://dev-ws.cso.ie/public/api.restful/PxStat.Data.Cube_API.ReadDataset/G0316/XLSX/2007/en"
            }
         ]
      },
      "note":[
         "For more information, please go to the[url=https://www.cso.ie/en/statistics/unsustainabledevelopmentgoals/] statistical release page[/url] on our website."
      ],
      "role":{
         "metric":[
            "STATISTIC"
         ],
         "time":[
            "TLIST(A1)"
         ]
      },
      "size":[
         1,
         3,
         48,
         3
      ],
      "updated":"2020-12-01T11:00:00.000Z",
      "value":[
         10.5,
         17.4,
         3.7,
         0.0,
         0.0,
         0.0,
         0.16,
         0.18,
         0.15,
         0.08,
         0.13,
         0.03,
         0.08,
         0.12,
         0.04,
         0.04,
         0.07,
         0.01,
         0.03,
         0.07,
         0.0,
         0.13,
         0.25,
         0.02,
         0.12,
         0.17,
         0.08,
         0.04,
         0.05,
         0.02,
         0.1,
         0.2,
         0.0,
         0.09,
         0.13,
         0.05,
         0.09,
         0.16,
         0.02,
         0.1,
         0.2,
         0.0,
         0.08,
         0.16,
         0.0,
         0.18,
         0.3,
         0.05,
         0.09,
         0.16,
         0.03,
         0.0,
         0.0,
         0.0,
         0.15,
         0.27,
         0.02,
         0.13,
         0.19,
         0.08,
         0.11,
         0.17,
         0.04,
         0.16,
         0.26,
         0.07,
         0.27,
         0.4,
         0.14,
         0.07,
         0.1,
         0.03,
         0.0,
         0.0,
         0.0,
         0.1,
         0.2,
         0.0,
         0.13,
         0.22,
         0.04,
         0.02,
         0.04,
         0.0,
         0.18,
         0.35,
         0.0,
         0.0,
         0.0,
         0.0,
         0.15,
         0.2,
         0.11,
         0.14,
         0.24,
         0.03,
         0.1,
         0.19,
         0.0,
         0.15,
         0.23,
         0.06,
         0.19,
         0.31,
         0.06,
         0.09,
         0.13,
         0.06,
         0.0,
         0.0,
         0.0,
         0.17,
         0.25,
         0.08,
         0.1,
         0.15,
         0.04,
         0.17,
         0.3,
         0.03,
         0.11,
         0.18,
         0.05,
         0.08,
         0.14,
         0.01,
         0.15,
         0.24,
         0.06,
         0.06,
         0.1,
         0.02,
         0.11,
         0.19,
         0.02,
         0.13,
         0.22,
         0.04,
         0.14,
         0.23,
         0.06,
         0.12,
         0.19,
         0.05,
         9.1,
         14.5,
         3.8,
         0.0,
         0.0,
         0.0,
         0.11,
         0.14,
         0.07,
         0.05,
         0.08,
         0.03,
         0.04,
         0.06,
         0.01,
         0.04,
         0.08,
         0.0,
         0.01,
         0.01,
         0.0,
         0.09,
         0.15,
         0.04,
         0.14,
         0.17,
         0.11,
         0.11,
         0.17,
         0.06,
         0.1,
         0.2,
         0.0,
         0.08,
         0.13,
         0.03,
         0.12,
         0.16,
         0.08,
         0.1,
         0.21,
         0.0,
         0.07,
         0.09,
         0.05,
         0.13,
         0.22,
         0.04,
         0.12,
         0.19,
         0.04,
         0.0,
         0.0,
         0.0,
         0.14,
         0.23,
         0.05,
         0.12,
         0.22,
         0.01,
         0.11,
         0.17,
         0.05,
         0.12,
         0.2,
         0.04,
         0.11,
         0.1,
         0.12,
         0.14,
         0.21,
         0.07,
         0.0,
         0.0,
         0.0,
         0.12,
         0.21,
         0.03,
         0.15,
         0.21,
         0.09,
         0.06,
         0.13,
         0.0,
         0.09,
         0.18,
         0.0,
         0.0,
         0.0,
         0.0,
         0.09,
         0.16,
         0.03,
         0.13,
         0.21,
         0.04,
         0.11,
         0.21,
         0.0,
         0.1,
         0.15,
         0.04,
         0.15,
         0.29,
         0.0,
         0.09,
         0.09,
         0.09,
         0.0,
         0.0,
         0.0,
         0.1,
         0.16,
         0.03,
         0.15,
         0.2,
         0.1,
         0.09,
         0.17,
         0.0,
         0.11,
         0.16,
         0.06,
         0.09,
         0.16,
         0.03,
         0.11,
         0.19,
         0.03,
         0.04,
         0.06,
         0.01,
         0.11,
         0.17,
         0.05,
         0.13,
         0.2,
         0.06,
         0.12,
         0.19,
         0.06,
         0.11,
         0.18,
         0.04,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0,
         0.0
      ],
      "version":"2.0"
   },
   "id":"361801203"
}`

**Comment by JohnPCarroll** [comment]
This appears to be linked to DECIMALS and PRECISION in the px file. 
For 1 statistic no PRECISION exists in the px file and the application should accept the DECIMALS value but does not.  the Live environment accepts the DECIMALS value

**Comment by JohnPCarroll** [comment]
Test passed as values are appearing correct when px file is uploaded or already exists. Checked table G0316

**Comment by JohnPCarroll** [comment]
The downloading with DECIMALS and PRECISION issue for one statistic still exists.

**Comment by damiancosmoschapman** [comment]
Can you please retest when you get a chance?

**Comment by neilfromcork** [comment]
The formatting of the decimals for the data is fixed now. To test dwonload G0316 in PX format and the data values should be shown correct to two decimal places.

**Comment by JohnPCarroll** [comment]
Test Passed
