### ISSUE TITLE
[BUG]  Pivoting in Dev causes download Excel to fail

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#567]
**Describe the bug**
 Pivoting in Dev causes download Excel to fail

**To Reproduce**
Steps to reproduce the behavior: in Dev
1. Go to table
2. Click on view 
3. Set pivot by statistic
4. See error when try download excel XLSX file

![image](https://user-images.githubusercontent.com/55874862/167874762-43ae45a9-4fa0-41c2-af2e-e77d7481d586.png)

**Expected behavior**
Download excel file

**Additional context**
Occurs in normal table view and releases view data

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test
