### ISSUE TITLE
[BUG] Search does not appear to be working for new published Uploads

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#568]
**Describe the bug**
[BUG] Search does not appear to be working for new published Uploads in dev

**To Reproduce**
1. Go to Data page
2. Click on search bar
3. Use a new published matrix eg LMMSA02
4. See image below

**Expected behavior**
matrix appear in results section

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/168049561-228a5bfe-10ac-403c-941c-aaf163ce19c1.png)

the original copy database files seem to be searchable and releases select seems ok
![image](https://user-images.githubusercontent.com/55874862/168050287-a5f6ba76-4914-40e9-b4e5-92e728674eb7.png)

![image](https://user-images.githubusercontent.com/55874862/168050527-a8887e4c-403f-4223-b82e-8f36a23f9721.png)

**Comment by liamie** [comment]
Also seems to be issue for new files not appearing in Breadcrumbs to  product pages and the browse options
![image](https://user-images.githubusercontent.com/55874862/168054468-22e22cd1-5f3b-42a3-b064-22b99f172276.png)

**Comment by JohnPCarroll** [comment]
Table TDM04JC not appearing on table list for 
![image](https://user-images.githubusercontent.com/44975474/168055759-abef6655-617f-461b-94c1-4d84abb16c8e.png)

**Comment by liamie** [comment]
Also pages share links not working for new publish pages is working for previous published pages

**Comment by liamie** [comment]
This seems to be corrected now for new files in search, product/page links and breadcrumbs.
