### ISSUE TITLE
[BUG] The Chart widget output contains the word 'Invalid Date' in the Release if used from a WIP Matrix

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#569]
**Describe the bug**
The publication is Housing Assistance Payment (HAP) Properties by Local Electoral Area 2021 published on the 4th May 2022
Because the Matrix is not live no date is available to be shown and the words Invalid Date are used instead.
The Matrix used is HAP10

**To Reproduce**
1. Go to Release in PxStat and Select the Matrix required
2. Create the chart and download the widget
3. Insert into the Release

**Expected behavior**
The words should not appear.

**Screenshots**
Taken from the Publication 
![image](https://user-images.githubusercontent.com/44975474/168273004-4dd237c8-7129-4255-a759-29fee4fc780b.png)

Taken from PxStat ( WIP Matrix in current DEV )

![number_of_hap_properties 1652440846405](https://user-images.githubusercontent.com/44975474/168273242-e79ac098-4543-4a2c-beb1-34f321f9c761.png)

**Comment by damienderoistecso** [comment]
Fixed in dev

**Comment by JohnPCarroll** [comment]
Test Passed
