### ISSUE TITLE
[BUG] Compare Release fails if data is deleted in new dev

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#570]
**Describe the bug**
If you compare using a px file with time periods removed it fails

**To Reproduce**
1. Go to releases 
2. Use table RSM05
3. Click on Compare Release 
![image](https://user-images.githubusercontent.com/44975474/168624941-059c3387-7d58-4b63-847a-67b8723f1b5c.png)

**Expected behavior**
The data deleted should be shown

**Comment by neilfromcork** [comment]
Fixed in DEV

**Comment by JohnPCarroll** [comment]
Test passed
