### ISSUE TITLE
[BUG] Px file output contains timeval based on values instead of codes 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#574]
**Describe the bug**
Px file output contains timeval based on values instead of codes

**To Reproduce**
1. Go to RSM03 or LMRSM03(newly uploaded and published) on dev
2. Click on download px
3. Compare to same  PX download on RSM03 on live

on dev
TIMEVAL("Month")=TLIST(M1),"2005M01","2005M02" etc... values

on live
TIMEVAL("Month")=TLIST(M1),"200501","200502","200503" etc ... codes

**Expected behavior**
both to use the same codes for time val as source file 

**Additional context**
May just be a side effect of the new process but px files seem to now have an additional listed code block for the classification field for the codes that happen to also be timeval where before the timeval was the code block

eg in new px dev download 
CODES("Month")="200501","200502","200503","200504","200505","200506","200507","200508","200509","200510","200511","200512","200601","200602",
"200603","200604","200605","200606","200607","200608","200609","200610","200611","200612","200701","200702","200703","200704","200705","200706",
"200707","200708","200709","200710","200711","200712","200801","200802","200803","200804","200805","200806","200807","200808","200809","200810",
"200811","200812","200901","200902","200903","200904","200905","200906","200907","200908","200909","200910","200911","200912","201001","201002",
"201003","201004","201005","201006","201007","201008","201009","201010","201011","201012","201101","201102","201103","201104","201105","201106",
"201107","201108","201109","201110","201111","201112","201201","201202","201203","201204","201205","201206","201207","201208","201209","201210",
"201211","201212","201301","201302","201303","201304","201305","201306","201307","201308","201309","201310","201311","201312","201401","201402",
"201403","201404","201405","201406","201407","201408","201409","201410","201411","201412","201501","201502","201503","201504","201505","201506",
"201507","201508","201509","201510","201511","201512","201601","201602","201603","201604","201605","201606","201607","201608","201609","201610",
"201611","201612";

appears in addition to the incorrect  TIMEVAL("Month")=TLIST(M1),"2005M01","2005M02" etc... values

in live it is only
TIMEVAL("Month")=TLIST(M1),"200501","200502","200503" etc ... codes
no additional 
CODES("Month")="200501","200502", etc. block ie the codes were contained by TIMEVAL only

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test
