### ISSUE TITLE
[BUG] Different ReadDataset queries returning different responses

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#577]
**Describe the bug**
Depending on how you construct your query, the response from "PxStat.Data.Cube_API.ReadDataset" is different for what should return the same values

Query 1: Return empty value array

```
{
    "class": "query",
    "id": ["C03738V04487", "C03737V04485", "C03786V04535"],
    "dimension": {
        "C03738V04487": {
            "category": {
                "index": ["M", "F", "B"]
            }
        },
        "C03737V04485": {
            "category": {
                "index": []
            }
        },
        "C03786V04535": {
            "category": {
                "index": ["2AE196291F2F13A3E055000000000001"]
            }
        }
    },
    "extension": {
        "pivot": null,
        "codes": false,
        "language": {
            "code": "en"
        },
        "format": {
            "type": "JSON-stat",
            "version": "2.0"
        },
        "matrix": "SAP2016T1T1AED"
    },
    "version": "2.0"
}
```
Query 2: Returns wrong response

`{
    "class": "query",
    "id": ["C03738V04487", "C03786V04535"],
    "dimension": {
        "C03738V04487": {
            "category": {
                "index": ["M", "F", "B"]
            }
        },
        "C03786V04535": {
            "category": {
                "index": ["2AE196291F2F13A3E055000000000001"]
            }
        }
    },
    "extension": {
        "pivot": null,
        "codes": false,
        "language": {
            "code": "en"
        },
        "format": {
            "type": "JSON-stat",
            "version": "2.0"
        },
        "matrix": "SAP2016T1T1AED"
    },
    "version": "2.0"
}
` 

Query 3: Correct response
`{
    "class": "query",
    "id": ["C03786V04535"],
    "dimension": {
        "C03786V04535": {
            "category": {
                "index": ["2AE196291F2F13A3E055000000000001"]
            }
        }
    },
    "extension": {
        "pivot": null,
        "codes": false,
        "language": {
            "code": "en"
        },
        "format": {
            "type": "JSON-stat",
            "version": "2.0"
        },
        "matrix": "SAP2016T1T1AED"
    },
    "version": "2.0"
}
`

**Comment by neilfromcork** [comment]
Fixed in 5.0.0
