### ISSUE TITLE
[BUG] PxStat.Data.Cube_API.ReadDataset query containing redundant id item

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#578]
**Describe the bug**
In your payload for "PxStat.Data.Cube_API.ReadDataset" if the id property contains a dimension id but this is not contained in your dimension object, no response returned

![image](https://user-images.githubusercontent.com/53211688/170069893-52c97406-de11-4fa9-b2b5-f11034d09941.png)

**Comment by neilfromcork** [comment]
Fixed in 5.0.0

**Comment by liamie** [comment]
Correct now as described by example.
