### ISSUE TITLE
[BUG] ReadDataset API does not work when the isoLanguageCode parameter is omitted

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#580]
**Describe the bug**
In the latest version when you call the ReadDataset API without the isoLanguageCode parameter it does not work. In the previous version of the API the call without the isoLanguageCode parameter worked.

**To Reproduce**
1. Go to {{host}}/public/api.restful/PxStat.Data.Cube_API.ReadDataset/IIA14/JSON-stat/2.0/
2. A 500 server error is generated. if you go to {{host}}/public/api.restful/PxStat.Data.Cube_API.ReadDataset/IIA14/JSON-stat/2.0/en
the API works

**Expected behavior**
The API with or without the en parameter should return the same data with no errors

**Comment by neilfromcork** [comment]
Fixed in DEV, ready for test. I've included an excel file with a list of minimum test cases as the RESTful capability was rewritten as part of this fix.
[TestCases for restful etc.xlsx](https://github.com/CSOIreland/PxStat/files/8831370/TestCases.for.restful.etc.xlsx)

**Comment by liamie** [comment]
**(Host)**/public/api.restful/PxStat.Data.Cube_API.ReadDataset/LMIIA14/JSON-stat/2.0
works fine
However 
**(Host)**/public/api.restful/PxStat.Data.Cube_API.ReadDataset/LMIIA14/JSON-stat/2.0/
fails
The trailing slash seems to make a difference to the result

**Comment by liamie** [comment]
Seems to be correct now
