### ISSUE TITLE
[ENHANCEMENT] Remove date from all widgets created from tables that are not yet live

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#583]
Widgets created from WIP, awaiting response, awaiting sign-off don't display a date while widgets created from pending live do. 

This can lead to inconsistent widgets on a single page if they were created at different stages in a workflow,

For consistency, only widgets created form a live release should contain a date.

**Comment by liamie** [comment]
Date seems to be cleared now from widget at all prelive stages.

Note: date still appears in the pending live view of charts and the download image for the view.
