### ISSUE TITLE
[BUG] Reasons missing from "PxStat.Data.Cube_API.ReadMetadata"

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#584]
Reasons are not included in the JSONstat for "PxStat.Data.Cube_API.ReadMetadata"

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by damienderoistecso** [comment]
@liamie Can you test this

**Comment by damienderoistecso** [comment]
> re opened as now reasons appearing twice?

@neilfromcork It appears as if ReadMetadata is correct and returns the reasons as they should be but ReadDataset returns the same reason twice in the same reasons array in the extension

**Comment by liamie** [comment]
Reasons appearing once and only once now
