### ISSUE TITLE
[BUG] Data_Matrix_ReadPeriodByRelease and Data_Matrix_ReadStatisticByRelease referencing old data structure

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#590]
Data_Matrix_ReadPeriodByRelease and Data_Matrix_ReadStatisticByRelease referencing old data structure. This can cause some keywords not to be included for search.

**Comment by neilfromcork** [comment]
This bug might not have obvious implications. To check, load a dataset via postman and make sure data is returned in Keyword_Release_BSO_CreateMandatory.cs lines 74 and 106.

**Comment by liamie** [comment]
Seems to be correct now tested with CompleteNewValue
