### ISSUE TITLE
[BUG] csv uploads can introduce unwanted whitespace / tabs etc. into entities of build create and update

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#591]
**Describe the bug**
csv uploads can introduce unwanted whitespace / tabs etc. into entities of build create and update

**To Reproduce**
1. Go to build create
2.  Add properties and click build dimensions
3.  Add a statistic using csv upload
4.  If the csv file contains extra whitespace in name etc. this is carried into the created file
5. click create to see in px file

**Expected behavior**
csv files should be cleansed/trimmed where possible the same as the fields if manually entering data

**Comment by damienderoistecso** [comment]
Fixed in dev

@liamie  ready for testing

**Comment by liamie** [comment]
fields added via csv uploads are now trimmed start and end for whitespaces similar to manual added fields
