### ISSUE TITLE
[ENHANCEMENT] Allow HEAD request versions of RESTful and PxApi requests

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#594]
Http HEAD requests will enable data.gov.ie to test if data exists without returning it.

**Comment by neilfromcork** [comment]
Ready for test

**Comment by neilfromcork** [comment]
This is correct as far as I know

**Comment by liamie** [comment]
Correct to stated requirement as discussed.

**Comment by neilfromcork** [comment]
New bug caused by trace fix. Fixed in DEV - ready for test

**Comment by liamie** [comment]
get and head returning same status response now
