### ISSUE TITLE
[BUG]  Reorganise Indexes fails unexpectedly

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#596]
**Describe the bug**
Reorganise Indexes fails unexpectedly

**To Reproduce**
1. On Dev go to 'System -> Database'
2. Click on 'Re-organise' Button
3. Confirm on pop up screen 
4. See unexpected error message

**Expected behavior**
Indexes Reorganised

**Comment by neilfromcork** [comment]
Powershell script did not create the DataMatrixUpdateIndexes_pxstat.dev job.

This can be checked when we deploy 5.2.0 into TEST @lorenzobruni @damiancosmoschapman @liamie
