### ISSUE TITLE
[QUERY] Alignment of documented and current api responses

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#598]
**Topic**
Due to recent changes some documented and current api responses seem to slightly misaligned 

**Query**
Misalignments of out puts will be listed below. So decisions to update documentation or re adjust api can be made.

**Comment by liamie** [comment]
**Method:** `PxStat.Data.Compare_API.ReadPreviousRelease`
Documented
| Name | Type |  Description  |
| :--- | :--- |  :--- | 
|`PreviousRlsCode` |String  | Code of the Previous Release Code |

Actual

| Name | Type |  Description  |
| :--- | :--- |  :--- | 
|`Result` |Int  | Code of the Previous Release Code |

**Comment by liamie** [comment]
**Method:** `PxStat.Data.Matrix_API.Read`
Documented

**Return:** `Array` [ `Object` ]

| Name | Type |  Description  |
| :--- | :--- |  :--- | 
|`MtrCode`|String | Matrix Identifier |
|`MtrTitle`     | String| Matrix Title |
|`MtrNote`     |String | Matrix Note |
|`MtrOfficialFlag`     |Boolean | Matrix Official Flag |
|`MtrInput`     | String| Matrix data content |
|`CcnUsernameCreate`     |String | AD username that created the Matrix |
|`DtgCreateDatetime`     |DateTime | Date and time of Matrix creation |
|`CcnUsernameUpdate`     |String |AD username that most recently updated the Matrix|
|`DtgUpdateDatetime`     |DateTime | Date and time of the most recent Matrix update |
|`RlsCode`     |Int |Release code  |
|`RlsVersion`     |Int |Release version  |
|`RlsRevision`     |Int |Release revision  |
|`RlsLiveFlag`     |Boolean |Live flag indicator  |
|`RlsLiveDatetimeFrom`     | DateTime|Start date and time of Release  |
|`RlsLiveDatetimeTo`     |DateTime | End date and time of Release |
|`RlsDependencyFlag`     |Boolean | Dependency Flag indicator  |
|`RlsEmergencyFlag`     |Boolean |Emergency Flag indicator  |
|`RlsReservationFlag`     |Boolean |Reservation Flag indicator  |
|`RlsArchiveFlag`     |Boolean |Archive Flag indicator  |
|`RlsAnalyticalFlag`     |Boolean |Analytical Flag indicator  |
|`RlsAlertFlag`     | Boolean|Alert Flag indicator  |
|`LngIsoCode`     | String|ISO Language code of Matrix  |
|`LngIsoName`     | String|Name of the Language of the Matrix  |
|`CprValue`     | String|Copyright value  |
|`CprCode`     |String |Copyright code  |
|`FrqValue`     |String |Frequency value  |
|`FrqCode`     |String |Frequency code  |
|`FrmType`     |String |Format type  |
|`FrmVersion`     |String |Format version  |
|`GrpCode`     |String |Group code  |
|`GrpName`     |String |Group name |
|`GrpContactName`     |String | Group contact name |
|`GrpContactPhone`     |String | Group contact phone number |
|`GrpContactEmail`     |String | Group contact email |
|`CmmCode`     |Int | Comment code |
|`CmmValue`     |String | Comment value |
|`SbjCode`     | Int|Subject code  |
|`SbjValue`     | String|Subject value  |
|`PrcCode`     |Int  |Product code |
|`PrcValue`     | String|Product value  |#

Actual

| Name | Type |  Description  |
| :--- | :--- |  :--- | 
|`MtrCode`|String | Matrix Identifier |
|`MtrTitle`     | String| Matrix Title |
|`MtrNote`     |String | Matrix Note |
|`MtrOfficialFlag`     |Boolean | Matrix Official Flag |
|`MtrInput`     | String| Matrix data content |
|`MtrId`     | Int| Matrix Id | Additional to documented|
|`CcnUsernameCreate`     |String | AD username that created the Matrix |
|`DtgCreateDatetime`     |DateTime | Date and time of Matrix creation |
|`CcnUsernameUpdate`     |String |AD username that most recently updated the Matrix|
|`DtgUpdateDatetime`     |DateTime | Date and time of the most recent Matrix update |
|`RlsCode`     |Int |Release code  |
|`RlsVersion`     |Int |Release version  |
|`RlsRevision`     |Int |Release revision  |
|`RlsLiveFlag`     |Boolean |Live flag indicator  |
|`RlsLiveDatetimeFrom`     | DateTime|Start date and time of Release  |
|`RlsLiveDatetimeTo`     |DateTime | End date and time of Release |
|`RlsExceptionalFlag`     |Boolean | Exceptional Flag indicator  |
|`RlsReservationFlag`     |Boolean |Reservation Flag indicator  |
|`RlsArchiveFlag`     |Boolean |Archive Flag indicator  |
|`RlsAnalyticalFlag`     |Boolean |Analytical Flag indicator  |
|`RlsExperimentalFlag`     |Boolean |Experimental Flag indicator  |
|`LngIsoCode`     | String|ISO Language code of Matrix  |
|`LngIsoName`     | String|Name of the Language of the Matrix  |
|`CprValue`     | String|Copyright value  |
|`CprCode`     |String |Copyright code  |
|`CprUrl`     |String |Copyright Url  | Additional to documented|
|`FrqValue`     |String |Frequency value  |
|`FrqCode`     |String |Frequency code  |
|`FrmType`     |String |Format type  |
|`FrmVersion`     |String |Format version  |
|`GrpCode`     |String |Group code  |
|`GrpName`     |String |Group name |
|`GrpContactName`     |String | Group contact name |
|`GrpContactPhone`     |String | Group contact phone number |
|`GrpContactEmail`     |String | Group contact email |
|`CmmCode`     |Int | Comment code |
|`CmmValue`     |String | Comment value |
|`SbjCode`     | Int|Subject code  |
|`SbjValue`     | String|Subject value  |
|`PrcCode`     |Int  |Product code |
|`PrcValue`     | String|Product value  |#

**Comment by liamie** [comment]
**Method:** `PxStat.Data.Matrix_API.ReadHistory`

| Name | Type |  Description  |
| :--- | :--- |  :--- | 
|`RlsCode`     |Int |Release code  |
|`RlsLiveDatetimeFrom`     | DateTime|Start date and time of Release  |
|`RlsLiveDatetimeTo`     |DateTime | End date and time of Release |
|`RlsVersion`     |Int |Release version  |
|`RlsRevision`     |Int |Release revision  |
|`GrpCode`     |String |Group code  |
|`GrpName`     |String |Group name |
|`CcnUsername`     |String | Username |
|`CreateDateTime`     |DateTime | Date and time of creation |
|`MtrTitle`     |String|Matrix title* |
|`RqsValue`     |String|Request Value |
|`RqsCode`     |String|Request Code |
|`RspValue`     |String|Response Value |
|`RspCode`     |String|Response Code |
|`SgnValue`     |String|Signoff Value |
|`SgnCode`     |String|Signoff Code |


| Name | Type |  Description  | Difference  |
| :--- | :--- |  :--- | :--- | 
|`MtrCode`     |String |Matrix code  |
|`RlsCode`     |Int |Release code  |
|`RlsLiveDatetimeFrom`     | DateTime|Start date and time of Release  |
|`RlsLiveDatetimeTo`     |DateTime | End date and time of Release |
|`RlsVersion`     |Int |Release version  |
|`RlsRevision`     |Int |Release revision  |
|`GrpCode`     |String |Group code  |
|`GrpName`     |String |Group name |
|`CcnUsername`     |String | Username |
|`CreateDateTime`     |DateTime | Date and time of creation |
|`MtrTitle`     |String|Matrix title* |
|`RqsValue`     |String|Request Value |
|`RqsCode`     |String|Request Code |
|`RspValue`     |String|Response Value |
|`RspCode`     |String|Response Code |
|`SgnValue`     |String|Signoff Value |
|`SgnCode`     |String|Signoff Code |

**Comment by liamie** [comment]
Documented

**Return:** `Array` [ `Object` ]

| Name | Type |  Description  |
| :--- | :--- |  :--- | 
|`MtrCode` |String  | Code of the Matrix associated with this Release |
|`RlsCode` | Int  | Release code |
|`RlsAlertFlag` | Boolean |Flag to indicate an Alert  |
|`RlsAnalyticalFlag` | Boolean |Flag to indicate Analytical |
|`RlsArchiveFlag` | Boolean |Flag to indicate Archive |
|`RlsLiveFlag` | Boolean | Indicates this is a Live Release |
|`RlsLiveDatetimeTo` |Datetime | End of Release period  |
|`RlsReservationFlag` |Boolean |Flag to indicate Reservation |
|`RlsRevision` | Int  |Release Revision |
|`RlsVersion` | Int | Release Version |
|`RlsExceptionalFlag` |Boolean | Flag to indicate an Exceptional Release |
|`RlsLiveDatetimeFrom` | Datetime |  Start of Release period|
|`MtrTitle` | String| Matrix title|
|`RqsCode` | String| Request Code|
|`RqsValue` | String| Request Value|
|`RspCode` | String| Response Code|
|`RspValue` | String| Response Value|
|`SgnCode` | String| Signoff Code|
|`SgnValue` | String| Signoff Value|

<hr>

Actual

**Return:** `Array` [ `Object` ]

| Name | Type |  Description  | Difference  |
| :--- | :--- |  :--- |  :--- | 
|`MtrCode` |String  | Code of the Matrix associated with this Release |
|`RlsCode` | Int  | Release code |
|`RlsAnalyticalFlag` | Boolean |Flag to indicate Analytical |
|`RlsArchiveFlag` | Boolean |Flag to indicate Archive |
|`RlsExperimentalFlag` | Boolean |Flag to indicate Experimental | Additional to documented |
|`RlsLiveFlag` | Boolean | Indicates this is a Live Release |
|`RlsLiveDatetimeTo` |Datetime | End of Release period  |
|`RlsReservationFlag` |Boolean |Flag to indicate Reservation |
|`RlsVersion` | Int | Release Version |
|`RlsRevision` | Int  |Release Revision |
|`RlsExceptionalFlag` |Boolean | Flag to indicate an Exceptional Release |
|`RlsLiveDatetimeFrom` | Datetime |  Start of Release period|
|`MtrTitle` | String| Matrix title|
|`RqsValue` | String| Request Value|
|`RqsCode` | String| Request Code|
|`RspValue` | String| Response Value|
|`RspCode` | String| Response Code|
|`SgnValue` | String| Signoff Value|
|`SgnCode` | String| Signoff Code|

**Comment by liamie** [comment]
currently unchanged

**Comment by damiancosmoschapman** [comment]
Strange, I made the changes and saved them but they seem to have reverted so I made the changes again. Should be good for retest now.

**Comment by liamie** [comment]
APIs and documented more aligned now
