### ISSUE TITLE
[BUG]  Restful PxStat.Data.Cube_API.ReadMetadata returns blank

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#599]
**Describe the bug**

**To Reproduce**
1. Try url (host)/public/api.restful/PxStat.Data.Cube_API.ReadMetadata/EHA04/en
2. See blank response

**Expected behavior**
should be same as the jsonrpc response
Return: Metadata in JSON-stat format for live table

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Also test 1. A non existent dataset should return a 404 and 2. PreMetadata version of this call (for WIP datasets)

**Comment by liamie** [comment]
Metadata now displayed for live datasets only
