### ISSUE TITLE
[BUG] Margin top missing from time and time span pills 

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#60]
**Describe the bug**
In responsive mode, time and time span pills in latest releases and table selection page are missing margin top

**Expected behavior**

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/53211688/73258352-6b1e6580-41bd-11ea-9fb5-2fe387770ce4.png)

![image](https://user-images.githubusercontent.com/53211688/73262832-0a942600-41c7-11ea-9676-8785c30d3515.png)

**Comment by damienderoistecso** [comment]
Added margin in HTML

@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test successful
