### ISSUE TITLE
[BUG] All classification variables counts in Build search classification listed as 0

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#601]
**Describe the bug**
All classification variables counts in Build search classification listed as 0

**To Reproduce**
1. Go to 'Build -> Create'
2. Set up or import properties Click on 'Build Dimensions'
3. Scroll down to 'Classifications'
4. Search Classifications using  a search term or classification code

![image](https://user-images.githubusercontent.com/55874862/175493688-1405714b-6fcf-4d1c-bf7e-402f14debdeb.png)

**Expected behavior**
Correct count of Variables to be visible so easier to match right classification otherwise its a redundant column I think

Note if you click on a code the right no of entries appears in the description below
![image](https://user-images.githubusercontent.com/55874862/175495003-ad6fb972-69fe-4c3e-9884-8accd55e027d.png)
and if use is clicked the correct variable count shows in the classifications section
![image](https://user-images.githubusercontent.com/55874862/175495370-1312096f-2907-448c-b9cc-ff76dbacc20a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/175493688-1405714b-6fcf-4d1c-bf7e-402f14debdeb.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
count displayed now
