### ISSUE TITLE
[BUG] Link For google firebase in privacy section is broken.

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#602]
**Describe the bug**
Link For google firebase in privacy section is broken.

**To Reproduce**
1. Go to 'Privacy' link at bottom of the page
2. Click on it
3. On the modal that appears click the google firebase link
4.
![image](https://user-images.githubusercontent.com/55874862/177294821-dce60dc7-d70a-4400-9858-01b3370963d4.png)

5. See error
![image](https://user-images.githubusercontent.com/55874862/177290597-90c40999-de67-4c60-b950-aa7a313ff71c.png)
**Expected behavior**
connect to goolgle firebase website

**Additional context**
Live and Dev affected

**Comment by damienderoistecso** [comment]
Ready for testing

**Comment by liamie** [comment]
Link now points to a current google firebase site
