### ISSUE TITLE
[BUG] Analytics: Titles with special characters (>) breaking Table Codes in CSV

### ISSUE THREAD

**Issue by CHanamy57** [CSOIreland/PxStat#607]
When downloading CSV of Analytics, Table titles including characters such as **<** and **>** are removed by **C_APP_REGEX_NOHTML** and unwanted html appears in Table title of the CSV

Reproduce:
1. In Analytics, find table with **>** character in title, ie; MTM04
2. Download CSV & open in Ecxel

![analytics](https://user-images.githubusercontent.com/55976631/179013587-9b6e32e2-cb87-48dc-a863-901d9f52b154.JPG)

![analytics2](https://user-images.githubusercontent.com/55976631/179013616-9f018dad-89ca-4164-8533-b6a37a9457ff.JPG)

**Comment by liamie** [comment]
May be related to #463

**Comment by liamie** [comment]
This is producing a correct csv/excel file now for analytics, however the human readable displays on the front end and tool tips are now showing code rather than greater than sign in correctly.
see #635 for images

**Comment by liamie** [comment]
This is now occurring again in it's original manner  due to the greater than sign resolution in #635.
The csv download is breaking at the first > sign in the text of title

**Comment by liamie** [comment]
Corrected for csv download with new format.
