### ISSUE TITLE
[QUERY] Clarification on Language error message 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#609]
**Topic**
Error message Clarification

**Query**
If the requirement is exactly 2 characters length should the language error message state this directly rather than using between 2 and 2

![image](https://user-images.githubusercontent.com/55874862/182876709-f3326f27-6a1b-4a3c-9d10-aefbc2923ca5.png)

**Comment by damiancosmoschapman** [comment]
This is fixed now. The error should now read: PX Schema: the keyword LANGUAGE must have a length of 2 char(s).

**Comment by liamie** [comment]
This is the response now for default English. Needs adding to other languages.
