### ISSUE TITLE
[BUG] Validation of MtrNote refuses newlines

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#61]
**Describe the bug**
The validator for Build Update mistakes a newline character for a quote and refuses validation

**Comment by neilfromcork** [comment]
Fixed in dev

**Comment by damienderoistecso** [comment]
Working for build update, but not build create
@neilfromcork

**Comment by neilfromcork** [comment]
Fixed for Create as well

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
test successful
