### ISSUE TITLE
[ENHANCEMENT] Refactor build for consistency and performance

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#610]
Refactor build for consistency and performance

For the client side, reduce payload of data in update and parse new reduced report structure

**Comment by neilfromcork** [comment]
Server side ready for test

**Comment by liamie** [comment]
Build Import Inconsistency between live and dev 
In current live semicolons aren't stripped from units on import
In Dev these are now stripped on import
so for the same file import different create results are produced
Dev
![image](https://user-images.githubusercontent.com/55874862/183602808-dc8b9d26-d025-428a-89e4-6154336eb35c.png)

Live
![image](https://user-images.githubusercontent.com/55874862/183602418-2e49dbe0-6f7b-4fb7-9c2a-20d6ac48bb5d.png)

ALSO 
a semicolon in Unit is allowed through by live to create the blank file but produces and error on the current DEV
![image](https://user-images.githubusercontent.com/55874862/183603456-50e74f5f-9a92-4998-b642-0797740e2866.png)

**Comment by liamie** [comment]
Imported files handle empty quoted notes differently.
when a file is brought into work In Progress if the Note in the source file only contains quotes i.e  NOTE="";
the note appears as "" in Dev but totally blank in Live and carries through the same to the published table
Dev
![image](https://user-images.githubusercontent.com/55874862/183616828-4eb3f6ea-58a9-4a0f-8179-ccd708719ba3.png)

Live
![image](https://user-images.githubusercontent.com/55874862/183617054-a9fb107a-2e8b-4e79-b205-7533a9a37cec.png)

**Comment by liamie** [comment]
Seasonally adjusted statistics with format TABLENAMES1 rather than TABLENAMEC01 not picked up
The number of cells is miscounted due to non standard format of seasonal adjusted figures not being picked up as statistic I suspect. 
E.g. MIM04 

Affected:
Build Import 
Build Create Import
Build Update

Gives message
![image](https://user-images.githubusercontent.com/55874862/183642514-634adb4b-c505-4b40-bd63-ac15a09b071b.png)

**Comment by liamie** [comment]
If TimeVal is missing 

Build Create and 
Build Update 
do not show dimension options and regardless of frequency chosen validate just loops back to the prompt screen.
![image](https://user-images.githubusercontent.com/55874862/183698042-0ff8c837-d23a-4768-83ac-cc841ee8c358.png)


Works fine for build import
![image](https://user-images.githubusercontent.com/55874862/183698504-15994061-94fb-46ef-9a2e-ac7fdfb90dd3.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Build Update not adding default values as default.

If a new time period is added to Build Update of a px file the values are defaulted to null/blank "" rather than double dots ".."
So the file won't create as default.

**Comment by liamie** [comment]
> 

This issue seems to be corrected now
