### ISSUE TITLE
[BUG]  information not found info message going to releases

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#611]
**Describe the bug**
information not found info message going to releases

**To Reproduce**
1.  Import file
2. Go to 'Releases'
3. Click on 'release number'

Note: Occurs for not just recent uploaded

**Expected behavior**
View the file

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/182882237-ffab3ea7-2e1d-4a52-9689-bf57563bb81a.png)

**Comment by damiancosmoschapman** [comment]
This issue was caused by a mistake by me in changing the stored procedure for reading releases. I have reverted the change now and retested and found no issues. Apologies for any inconvenience caused.

**Comment by liamie** [comment]
Seems cleared now
