### ISSUE TITLE
Imported files handle quoted notes differently.

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#616]
Imported files handle empty quoted notes differently.
when a file is brought into work In Progress if the Note in the source file only contains quotes i.e  NOTE="";
the note appears as "" in Dev but totally blank in Live and carries through the same to the published table
Dev
![image](https://user-images.githubusercontent.com/55874862/183616828-4eb3f6ea-58a9-4a0f-8179-ccd708719ba3.png)

Live
![image](https://user-images.githubusercontent.com/55874862/183617054-a9fb107a-2e8b-4e79-b205-7533a9a37cec.png)

Update: This is occurring for non empty notes also the quote marks are not stripped from the string
![image](https://user-images.githubusercontent.com/55874862/183665761-27577e95-447f-4811-9a40-8e5620592ca7.png)

_Originally posted by @liamie in https://github.com/CSOIreland/PxStat/issues/610#issuecomment-1209150580_

**Comment by liamie** [comment]
This seems to be correct now, quotes not appearing in footnote.

**Comment by liamie** [comment]
Seems to be reoccurring now so reopened

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Quotes not added to notes now
