### ISSUE TITLE
[BUG] Downloaded CSV with ".." data not consistent between Live and dev

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#618]
**Describe the bug**
[BUG] Downloaded CSV with ".." data not consistent between Live and dev

**To Reproduce**
1. Go to a table with ".." data 
2. Click on download csv
3. Open resulting csv file

In live these are denoted as "" in the csv
In Dev these are denoted as ""..""  double quotes, double dots, double quotes

**Expected behavior**
Constant between the two 

**Screenshots**
AJM01 in live
![image](https://user-images.githubusercontent.com/55874862/184139924-efbf4449-e76c-4deb-b6f2-f9975d52768b.png)

LMAJM01 in Dev
image pending

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
.. data in csv now appearing as blanks for both live and dev now

**Comment by liamie** [comment]
Reopened as reoccuring
in csv and excel 
"".."" rather than "" in csv and excel downloads
on dev when download
![image](https://user-images.githubusercontent.com/55874862/190631954-0f3cd7f3-f485-4f60-b62f-82acb9868f57.png)

in live same data
![image](https://user-images.githubusercontent.com/55874862/190632607-9b6ebc86-abf1-498b-b375-90c2785f0949.png)

**Comment by liamie** [comment]
Json data also affected
live is null
dev is ".."

**Comment by liamie** [comment]
download of px files also affected

live has ".."
dev has "".."" additional encompassing set of double quotes

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test. Please note this was a problem with upload, so previously uploaded data will still be affected.
