### ISSUE TITLE
[BUG] Delete of live dataset deletes the dataset rather than setting it to historical

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#62]
**Describe the bug**
If a live release exists and we  delete it, the release disappears from the browser and any subsequent WIPs stay there with their release number.

**Expected behavior**
The release should stay on the screen as a historical release. It should be possible to compare a WIP against it.

**Comment by neilfromcork** [comment]
Fixed in Dev - for retest

**Comment by JohnPCarroll** [comment]
test successful
