### ISSUE TITLE
[ENHANCEMENT]  Include Name of Map in Build Map Details

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#621]
**Is your feature request related to a problem? Please describe.**
Map Name does not appear on Map details info box

**Describe the solution you'd like**
The Name of the Map to appear in the Map Details modal 

**Describe alternatives you've considered**
The Name of the Map to appear either in the  body similar to update maps modal or in the header like the view maps(eye symbol) or tables modal all on the same row

**Comment by damienderoistecso** [comment]
Map name is now displayed in the more detail modal for both the map list table in build/maps and also in the map list table that is used when adding a map in the create or update

**Comment by damienderoistecso** [comment]
@liamie ready for test

**Comment by liamie** [comment]
Is corrected in modals now
however the link in the map section of create/update appears as undefined rather than details
correct previous
![image](https://user-images.githubusercontent.com/55874862/185094838-b3fd0801-17f5-4135-98c3-36e52b0eb39e.png)

incorrect now
![image](https://user-images.githubusercontent.com/55874862/185095567-33c86174-c052-47f2-a959-9ee7eb6a1372.png)
