### ISSUE TITLE
The Saved Queries menu is missing for Moderators[BUG] 

### ISSUE THREAD

**Issue by colmanflynn** [CSOIreland/PxStat#622]
Queries can be saved by Moderators but they don't have any way of accessing them afterwards.
Here is an image of the navigation available to Moderators. The Saved queries menu should be between Data and Dashboard -
![Moderator Menu](https://user-images.githubusercontent.com/59689411/185104913-f721c78e-66bc-4bc8-9940-3526fb9c0fe4.PNG)

Power Users and external users (once an account is created) can access them without issue.

**Comment by damienderoistecso** [comment]
Fixed in dev

@liamie ready for test

**Comment by liamie** [comment]
Saved queries is present now on moderators menu
