### ISSUE TITLE
[BUG] Build error when certain words are included in NOTES 

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#624]
From NISRA:

We’ve some across a strange issue with the notes in PxStat.  We had a user yesterday report that every time he tried to create a Px file he got an Exception Error  “Server or Network Error. Please try again”. We couldn’t find anything in the logs and there were no other reports of issues so we tried to recreate using the exact information that he was inputting. It turned out it was the notes section that was causing the problem so by process of removing words we found that there was an issue with the term Northern Ireland Maternity System (NIMATS). The use of “System” and “(NIMATS)” side by side caused the exception error, if one of these words was removed or a word put between them the exception error didn’t occur. I thought maybe the term “System (NIMATS)” meant something in Px files as I’ve tried the word system followed by other letter combinations and it works ok, but I can’t find anything online.  This may be a one off but I thought it was worth letting you know in case you come across the same issue down the line.

**Comment by liamie** [comment]
closed as invalid
