### ISSUE TITLE
[BUG] Local Authenticated users not showing up in Trace

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#625]
Locally authenticated users are showing up in trace as Anonymous instead of their user id

**Comment by neilfromcork** [comment]
This is really #504

**Comment by neilfromcork** [comment]
Original problem fixed . However AD users are not traced on deployed version (works ok in Postman)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Complete as per specified
