### ISSUE TITLE
[ENHANCEMENT] Add ability to associate tables with another product

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#628]
Allow tables to be associated with one or more products that are not their main navigation.

These tables will appear below any archived tables when you land on a product listing page.

The management of associated products will be done through the releases entity alongside the management of the main navigation

**Comment by damienderoistecso** [comment]
@liamie Management of associated tables through the release entity ready for testing

**Comment by liamie** [comment]
Column Name/Dictionary  missing from 
![image](https://user-images.githubusercontent.com/55874862/186131261-a3526acc-f6d7-45a4-b973-7872c773f6d4.png)

**Comment by liamie** [comment]
Associations are not removed or altered when the Navigation is changed so Navigation and duplicate Association can occur if navigation is changed to one of the existing Associations.

**Comment by damienderoistecso** [comment]
> Associations are not removed or altered when the Navigation is changed so Navigation and duplicate Association can occur if navigation is changed to one of the existing Associations.

We can handle this scenario through a change to the "PxStat.Data.Release_API.UpdateProduct" API. When this API runs, we can check if the "PrcCode" passed as an input parameter is already an associated table. If it is, then we delete this association automatically before updating the core product.

**Comment by damiancosmoschapman** [comment]
This should be fixed now. There was an update made to the stored procedure associated with the "PxStat.Data.Release_API.UpdateProduct to check if the "PrcCode" passed as an input parameter is already an associated table. If it is, then this association is deleted automatically before updating the core product. Please retest.

**Comment by liamie** [comment]
Associated products that are not on the core navigation of any table can be deleted even after been associated to a table. If associated with a table should a product be undeletable as with core products or if it is able to be deleted should the associations also be auto removed to avoid orphan product associations.

**Comment by liamie** [comment]
This seems to be correct now bar tidying up after product detion

**Comment by damiancosmoschapman** [comment]
@liamie, Yes, this is a WIP and I will re-assign this issue back to you when this functionality is implemented and deployed to dev.

**Comment by damiancosmoschapman** [comment]
I have updated the System_Navigation_Product_Delete stored procedure to delete a Release Product association in the TM_RELEASE-PRODUCT table when a Product is deleted using the Navigation API. Please test when you get a chance.

**Comment by liamie** [comment]
> I have updated the System_Navigation_Product_Delete stored procedure to delete a Release Product association in the TM_RELEASE_PRODUCT table when a Product is deleted using the Navigation API. Please test when you get a chance.

Associated products on existing tables now deleted if product is removed from manage>products

**Comment by liamie** [comment]
> Column Name/Dictionary missing from product link ![image](https://user-images.githubusercontent.com/55874862/186131261-a3526acc-f6d7-45a4-b973-7872c773f6d4.png)

Column Heading appears correct now

**Comment by liamie** [comment]
> 

This element is still outstanding

**Comment by damiancosmoschapman** [comment]
This is fixed now.

**Comment by damiancosmoschapman** [comment]
This is fixed now.

**Comment by liamie** [comment]
This is now in line with current navigation rules

**Comment by liamie** [comment]
Association button is not greyed out when move from one work in progress to another.
If the association button is active in one wip and you use a link to switch to a different wip the button remains active even if no navigation is set in the new wip.
