### ISSUE TITLE
[BUG] Spurious data point being picked up if the semi colon is on the next line after the DATA in a px file

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#629]
Additional blank data point being picked up if the semi colon is on the next line after the DATA in a px file, e.g. 

DATA=
77.8 91.7 93.6 104.0 114.4 117.3 
108.8 106.7 113.5 107.7 112.1 107.7 
147.6 143.1 164.3 159.8 151.1 157.7 
;

**Comment by liamie** [comment]
Extra data point no longer added
