### ISSUE TITLE
[BUG] Set focus to search on mobile

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#63]
**Describe the bug**
When the focus is set automatically to the search input, the keyboard pops us always on a mobile

**To Reproduce**
On a mobile device, launch the application

**Expected behavior**
Focus is not set to the search input to prevent keyboard always showing on mobile device

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for testing

**Comment by lorenzobruni** [comment]
Test passed
