### ISSUE TITLE
[ENHANCEMENT] Remove strict validation for maps

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#630]
When adding a map to a classification in create/update, remove strict validation.

Allow maps to be added, even if variables in the classification are not contained in the GeoJSON.

For the server side, remove all validation. On the client side, use the same validation, but only to display a report to the user to show them the variables not found in the GeoJSON. They can then confirm if they wish to add the map based on the report.

**Comment by neilfromcork** [comment]
Question - Apart from the connection between variables and features, it is necessary to validate that a map exists before uploading a px file. But is this a requirement at the Build stage as well? @damienderoistecso

**Comment by damienderoistecso** [comment]
> 

I would say yes, we should always check for the existence of the resource whenever we are attaching it to a classification

**Comment by damienderoistecso** [comment]
@neilfromcork New validation applied to create but not update. No rush applying this to update, I can simply add manually in the px file to proceed with my changes to displaying the data

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by damienderoistecso** [comment]
Client side all updated and committed 

@liamie ready for testing

**Comment by liamie** [comment]
Random maps can now be added to px files
