### ISSUE TITLE
[ENHANCEMENT] Default sorting of table results base on newest timepoint first

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#631]
For both the PxStat interface and widgets, apply a default sorting by the time column with the most recent time point first by default.

To do this correctly and preserve the order of the statistics dimension, we remove the ability to sort by the statistic column completely

**Comment by damienderoistecso** [comment]
@liamie ready for test

**Comment by liamie** [comment]
Saved queries save the order from the original results not adjusted order from results at point of pressing save query

if you run a query the results are in a particular order
if you use the order arrows to adjust the order of the result such as reverse the time order and then save the query it is still the order as per the original query that is retained is this correct or should the save query reflect the order at the time the save query was made.
adjustments to the displayed results after the original query are not reflected in saved query is this correct should save query just preserve the original query ran or should it reflect the current screen order of the results when pressed.

displayed order when saved query was pressed
![image](https://user-images.githubusercontent.com/55874862/186913645-511e1439-e5b3-4c2d-8945-f56d8dad3b1e.png)

saved query result 
![image](https://user-images.githubusercontent.com/55874862/186912854-820f652c-28ff-4250-b146-fd09bba630c4.png)

**Comment by damienderoistecso** [comment]
> Saved queries save the order from the original results not adjusted order from results at point of pressing save query
> 
> if you run a query the results are in a particular order if you use the order arrows to adjust the order of the result such as reverse the time order and then save the query it is still the order as per the original query that is retained is this correct or should the save query reflect the order at the time the save query was made. adjustments to the displayed results after the original query are not reflected in saved query is this correct should save query just preserve the original query ran or should it reflect the current screen order of the results when pressed.
> 
> displayed order when saved query was pressed ![image](https://user-images.githubusercontent.com/55874862/186913645-511e1439-e5b3-4c2d-8945-f56d8dad3b1e.png)
> 
> saved query result ![image](https://user-images.githubusercontent.com/55874862/186912854-820f652c-28ff-4250-b146-fd09bba630c4.png)

Fixed in dev

@liamie ready for testing
