### ISSUE TITLE
[ENHANCEMENT] Allow option of line chart to have straight and curved lines

### ISSUE THREAD

**Issue by Elainehoward** [CSOIreland/PxStat#633]
Hi Damien,  

In the chart widget the line chart is showing a curved line, can we have the option of having a straight line?

Thanks
Elaine

**Comment by damienderoistecso** [comment]
Toggle now under options for line of mixed charts to switch between curved and straight lines

@liamie ready for testing

**Comment by damienderoistecso** [comment]
> Line and mixed chart now have option to toggle between straight and curved lines. This affects all lines and so is curved or straight lines not a mix of both curved and straight on the one chart. Is this correct?

Yes, the intention is that all lines on the chart will be either curved or straight.

**Comment by liamie** [comment]
This appears to be correct as described so. Tested for saved queries and in releases as well as live table.
