### ISSUE TITLE
[BUG] More than / greater than symbols incorrectly stripped from variable labels in create

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#635]
When you add a classification in create, more than / greater than symbols are being incorrectly stripped from variable labels in the px output

**Comment by neilfromcork** [comment]
Fixed in dev - awaiting publish

**Comment by neilfromcork** [comment]
Issue with <> fixed in DEV

**Comment by neilfromcork** [comment]
We need to review this. It is demonstrably possible to do a cross site scripting attack by including scripts in e.g. the NOTES field of a px file.

**Comment by neilfromcork** [comment]
Using new sanitizer library. Symbols are replaced with &gt; and &lt; etc. Ok in html, px and csv. XLSX could be a problem. Need to workshop this to devise an optimum strategy.

**Comment by liamie** [comment]
Files with greater than sign in title are now appearing with code rather than human readable.
in data/last updated tables
![image](https://user-images.githubusercontent.com/55874862/190649939-9af67c2f-c4fe-4613-ada2-725fd83b37f6.png)
in analytics

**Comment by liamie** [comment]
issues #463 and #607 may also be resolved with an optimum strategy but should at least be factored.

**Comment by neilfromcork** [comment]
Rule to be applied:
1. HTML tag to strip the tag but to retain the body
2. HTML script gets stripped in full
3. from isolated <> to &gt; &lt; and BACK to <>

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Greater than signs are now retained in classifications.
