### ISSUE TITLE
[BUG]  When an association is updated, the navigation search API is still returning the old cached result

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#636]
**Describe the bug**
When an association is updated, the navigation search API is still returning the old cached result. It may be that when an association is updated, this should invalidate the cache or something to that affect.

**To Reproduce**
1. Update an association
2. Call the Navigation Search API
3. The updated association is not shown in the response of the Navigation Search API

**Expected behavior**
The updated association should be shown in the response of the Navigation Search API

**Comment by damiancosmoschapman** [comment]
This should be fixed now.

**Comment by liamie** [comment]
The Matrix is appearing in the new navigation when association changed

**Comment by liamie** [comment]
Association button is not greyed out when move from one work in progress to another.
If the association button is activeon one wip and you use a link to switch to a different wip the button remains active even if no navigation is set in the new wip.
