### ISSUE TITLE
[BUG]  Attempting to delete Work in progress produces an unexpected error

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#637]
**Describe the bug**
Attempting to delete Work in progress produces an unexpected error

**To Reproduce**
1. Go to any work in progress
2. Choose delete on workflow and go through steps for approval
3. When get to sign off

**Expected behavior**
Be able to delete as requested

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/190367016-c39f31ad-ea04-49db-92fb-5473b5fa0522.png)

E.g. WIP for SPP02 on dev

**Comment by DeclanBuckley** [comment]
This error also occurs when I create a  product and try to delete it afterwards.

**Comment by damiancosmoschapman** [comment]
This should be fixed now. To test I was able to sign off on the WIP for SPP02 on dev.

**Comment by liamie** [comment]
Error still occurring for delete of product.

**Comment by damiancosmoschapman** [comment]
The product deletion is fixed now.

**Comment by liamie** [comment]
Products can be created/deleted error free now
