### ISSUE TITLE
[BUG] Import of file can fail but seems to leave a shadow release that means file cannot be reimported/corrected

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#638]
**Describe the bug**
[BUG] Import of file can fail but seems to leave a shadow release that means file cannot be reimported/corrected

**To Reproduce**
Does not always occur/may have specific circumstances
1. Import a file and publish
2. Import file again to create a new release gave an unspecified error and no wip created
3. When try to reimport file giving message that release is in use however there is no wip release listed as did not import

**Expected behavior**
If release not fully imported clear to allow a new correct import of px file

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/190396739-f3113783-1020-420f-ba2a-71bec1933acd.png)

**Additional context**
e.g. LMSPP04 on dev

**Comment by damiancosmoschapman** [comment]
I was able to reproduce this issue when investigating #628. After fixing #628 I was not able to reproduce this issue. so it looks like #628 may have fixed this issue. Please retest with a few different tables containing none, one and multiple table associations to make sure that the error is not reproducible.

**Comment by liamie** [comment]
This seems to be resolved now. Marking as such.
