### ISSUE TITLE
[BUG]  Create Parser on dev and Live do not match

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#639]
**Describe the bug**
  Create Parser on dev and Live do not match
Some files can import on create  on Live but fail on the parse of Dev
**To Reproduce**
1. Go to build> create and attempt to import a source px for TAQ01
2. Click on Parse
3. See error
4. Imports fine on live

**Expected behavior**
Consistent parse input between live and dev
**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/191206830-27d83320-b587-4c50-8d03-38df71d1386c.png)

**Comment by liamie** [comment]
Same occurs on build>update
But does pass the parser on build>import

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Allowing same files as live in now.
