### ISSUE TITLE
[BUG] Email validation rules

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#64]
**Is your feature request related to a problem? Please describe.**
Update email validation to follow specification here https://www.jochentopf.com/email/chars.html 

Email addresses username should only allow 

- a-z
- A-Z
- 0-9
- -
- _
- +
- .

@JohnPCarroll ready for testing

**Comment by lorenzobruni** [comment]
Client Side passed, Server side is missing the `+`

**Comment by lorenzobruni** [comment]
Test passed
