### ISSUE TITLE
[BUG]  Search returns multiple copies of the same table 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#641]
**Describe the bug**
Search returns multiple copies of the same table 

**To Reproduce**
Steps to reproduce the behavior in dev
1. Do a search for Transport
2. Limit the view by properties for easier viewing

**Expected behavior**
A single example of each table in the search

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/191245065-b5aa7d09-88ad-48c4-8606-0640901e8caf.png)

**Comment by liamie** [comment]
Duplication still occuring

**Comment by damiancosmoschapman** [comment]
The issue happened again because the application was redeployed and didn't include my fix so I redeployed again with my fix. It should be working now.

**Comment by liamie** [comment]
working correctly now
