### ISSUE TITLE
[BUG]  Build >Update >Download CSV gives different headers

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#642]
**Describe the bug**

**To Reproduce**
1. Go to Build> Update, import a file  
2. Click on Download CSV
3. Set labels and unit to true and download
4. Compare headings between live and dev

**Expected behavior**
Consistent headings

**Additional context**
sample matrix TAQ01 in live
![image](https://user-images.githubusercontent.com/55874862/191269957-2d23e552-8b12-46f5-9abc-40d89817b2d0.png)

"STATISTIC","STATISTIC - Statistic","TLIST(Q1)","TLIST(Q1) - Quarter","C02935V03550","C02935V03550 - Airports in Ireland","UNIT","VALUE"

sample matrix TAQ01 in dev 
![image](https://user-images.githubusercontent.com/55874862/191270367-3688a85c-3245-49e5-9fb2-a5bdce8f99dd.png)

"STATISTIC CODE","Statistic","TLIST(Q1)","Quarter","C02935V03550","Airports in Ireland","UNIT","VALUE"

**Comment by neilfromcork** [comment]
Fixed in DEV -ready for test

**Comment by liamie** [comment]
Headings seem to match now

**Comment by liamie** [comment]
Re opened as this is reoccuring now. 
Example RBA01 in live
code false
![image](https://user-images.githubusercontent.com/55874862/192525100-0d6fdd3e-e064-47ce-8166-83b813bbd5b8.png)

with code true
![image](https://user-images.githubusercontent.com/55874862/192524542-26ab69f6-ce08-48b8-868f-0051ae4e7d31.png)

In Dev
code false
![image](https://user-images.githubusercontent.com/55874862/192525266-043714b2-1db6-4d69-945e-1155c633557c.png)

with code true
![image](https://user-images.githubusercontent.com/55874862/192524727-bf21901b-8c05-455f-a524-b8a03baf3b43.png)

**Comment by neilfromcork** [comment]
Code=false means only labels are shown for each dimension
Code=true means code, then code plus '-' plus label, for each dimension

**Comment by neilfromcork** [comment]
Fixed in DEV -ready for test

**Comment by liamie** [comment]
Seems to be correct now.
