### ISSUE TITLE
[BUG]  Build>Create dropping notes on create PX file

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#643]
**Describe the bug**
in dev
[BUG]  Build>Create dropping notes on create PX file

**To Reproduce**
1. Go to Build>Create
2. Import file for template or build own dimensions
3. Click create > PX at bottom

Even if notes are present in the notes field no notes are created in the PX file

Should retain the notes in the notes field

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
note seems to be fine now however in live when notex gets import it gets converted to note with the same contents as the original notex

in dev currently the notex is dropped and a blank note is created i.e. the contents are not carried over

**Comment by neilfromcork** [comment]
NOTEX behaviour amended - ready for test

**Comment by liamie** [comment]
Create correct now.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Seems to be correct now
