### ISSUE TITLE
[BUG] Sort on Month Indicator label before view or download sorts alphabetically but view and downloads are in correct order

### ISSUE THREAD

**Issue by DeclanBuckley** [CSOIreland/PxStat#644]
An issue with sorting on live and test - I have imported an the latest version of CPM01 from live into test. The previous version of this and other tables had values of 2002M01, 2002M02 etc for month values. These have been changed to 2022 January, 2022 February etc. If you view the table and the values for the Month statistic they look fine . If you click on the sort for the Month statistic with the new values they get reordered alphabetically so you then get 2022 April, 2002 August, 2022 December, 2022 February etc.

**Comment by DeclanBuckley** [comment]
Downloading the file the data comes out in the correct order on the px file.

**Comment by damienderoistecso** [comment]
Fixed in dev @DeclanBuckley ready for testing

**Comment by DeclanBuckley** [comment]
Ok. Thanks.
