### ISSUE TITLE
[ENHANCEMENT] Allow custom widget titles

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#645]
Allow users to create custom widget titles instead of using the table title if title is set to true.

**Comment by damienderoistecso** [comment]
@liamie chart custom title ready for testing

**Comment by damienderoistecso** [comment]
@liamie custom table title ready for testing. Update of widget code required for this

**Comment by damienderoistecso** [comment]
@liamie custom map title ready for testing.

**Comment by liamie** [comment]
In Pie charts
If title is false series name is also not shown as well as no title 
If title is true Header Title appears below the Series name is this correct?
![image](https://user-images.githubusercontent.com/55874862/192550479-653971d6-4661-4e3b-bd70-7307e187df65.png)

**Comment by damienderoistecso** [comment]
Fixed in dev

**Comment by liamie** [comment]
Title now top if used.

**Comment by liamie** [comment]
Reset on chart resets the title of widget back to default.
Reset on table does not reset the title.
There is no reset on map.
So for table and map you have to leave the matrix page for it to rest.
Is this correct?

**Comment by damienderoistecso** [comment]
> Reset on chart resets the title of widget back to default. Reset on table does not reset the title. There is no reset on map. So for table and map you have to leave the matrix page for it to reset. Is this correct?

Yes, this behavior is correct for tables and maps.

**Comment by liamie** [comment]
Seems to be working as described
