### ISSUE TITLE
[BUG] Local Users names are not shown when added to groups

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#646]
**Describe the bug**
Local Users names are not shown when added to groups

**To Reproduce**
1. Go to 'Manage Users'
2. Add a local user 
3. Name is not displayed.
4. This is also not displayed in update user modal of group subsequently

**Expected behavior**
Name should appear in name section

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/192264911-092f991f-56e5-4b18-9491-8eeda3bab59f.png)
![image](https://user-images.githubusercontent.com/55874862/192265155-91a4403e-e07a-47aa-bd83-383059f658c8.png)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Name appears correct now
