### ISSUE TITLE
[QUERY] Is dev aligned with live for what automated emails are produced for an approver?

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#647]
**Topic**
Workflow automated emails

**Query**
 Is dev aligned with live for what automated emails are produced for an approver?
At what stages of the workflow should automated emails be produced currently?

**Comment by neilfromcork** [comment]
Workflow emails should be produced at Request (to the approver), Response (to the signoff) and Signoff (to the moderators)
