### ISSUE TITLE
[BUG] Notes split over multiple lines in PX file handled differently between live and dev

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#649]
**Describe the bug**
Notes split over multiple lines in PX file handled differently between live and dev

**To Reproduce**
1. Go to Build>Create
2. Import file with notes over more than one line.
3. Observe quotes still in notes

occurs for create, update and build import(viewed in releases)

**Expected behavior**
Alignment of notes

**Screenshots**
section in PX file
![image](https://user-images.githubusercontent.com/55874862/192510331-538060a8-a7da-4c38-af75-898134ad7b76.png)

result live
![image](https://user-images.githubusercontent.com/55874862/192510798-635de220-99f7-44b8-8663-f148ae0d65ea.png)

result dev
![image](https://user-images.githubusercontent.com/55874862/192510571-b0b032c6-b7fb-4f27-a760-aaf34f1dcdb1.png)

**Comment by neilfromcork** [comment]
Manual parser is including the internal quotation marks as literal values in the upload

**Comment by damiancosmoschapman** [comment]
Please test.

**Comment by liamie** [comment]
Seems to be correct now
