### ISSUE TITLE
[BUG]  Build Create in Dev generating &amp; instead of &

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#652]
**Describe the bug**
Build Create in Dev generating &amp; instead of &

**To Reproduce**
1. In build create live the PX file generated produces & in the px when there is an & sign 
2.  In build create dev the PX file generated produces &amp; in the px when there is an & sign 
3. eg in classification for Procedure in table DHA58 if used as import source for build>create

**Expected behavior**
consistent create px file 

*use edit to read as apparently githhub auto converts for &.amp;

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by neilfromcork** [comment]
Additional change to ensure that all html codes will be translated and not just the ones we specifically nominate

**Comment by liamie** [comment]
Seems to be correct now
