### ISSUE TITLE
[BUG] Import Validation error on new Pulse Survey tables

### ISSUE THREAD

**Issue by DeclanBuckley** [CSOIreland/PxStat#653]
I have tried to import some of the just released Pulse Surveys - spending time outdoors into 5.2.0 but get errors. I added the Group OLOD, and the subject Pulse Survey and Product OLOD Pulse Survey Our Lives Outdoors under the Theme Themed Publications. When I try to import a px file and validate it I get an error. e.g. the following error for OLOD70.px. I get similar errors forOLOD68.px and OLOD69.px
![errorolod70](https://user-images.githubusercontent.com/44837351/193276247-b6d014ef-1b20-4a10-baa4-4107bfde023d.png)

**Comment by damiancosmoschapman** [comment]
Please retest.

**Comment by DeclanBuckley** [comment]
I have successfully been able to validate and import OLOD68 and OLOD70 now in the updated 5.2.0 code.
