### ISSUE TITLE
[BUG] Add Request button is not greyed out when move from one work in progress to another.

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#654]
**Describe the bug**
Add Request button is not greyed out when move from one work in progress to another.
If the Add Request  button is active in one wip and you use a link to switch to a different wip the button remains active even if no action in the select drop down is set in the new wip.

**To Reproduce**
1. Go to a work in proress
2. Click on 'Publish' in Workflow Request Type dropdown
3. switch to different WIP
4. See Add Request button is highlighted even though nothing selected in the Workflow Request Type dropdown

**Expected behavior**
Add Request deactivated until Workflow Request Type dropdown is chosen

**Comment by damienderoistecso** [comment]
Fixed in dev @liamie ready for testing

**Comment by liamie** [comment]
Correct now for Add Request button
