### ISSUE TITLE
[BUG] Precision being removed by test build update/ build create

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#656]
**Describe the bug**
 Precision being removed by test build update/ build create

**To Reproduce**
1. Download source for ACA03 on live
2. Put through build update/build create
3. Precision information lines removed 

**Expected behavior**
Precision information retained

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/194310559-f69a9dd7-a978-4cb0-98ca-f2c59301a8dd.png)

**Additional context**
May be applying the precision to the PX file data rather than just maintaining the precision meta lines and leaving Data intact

**Comment by neilfromcork** [comment]
This file doesn't show precisions because all precisions are 1. Therefore it's more efficient to just display the decimals as 1
