### ISSUE TITLE
[BUG] When Manage/Subscriber is selected it is returning invalid users

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#657]
**Describe the bug**

When Manage/Subscriber is selected it is returning invalid users

**To Reproduce**
1. Select Manage/Subscribers
2. See Invalid User for some of the subscriber rows

**Expected behavior**
Invalid User subscriber rows should not be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/85613974/194851344-38a11788-13c8-489b-8de8-43689529d8df.png)

**Additional context**

**Comment by damiancosmoschapman** [comment]
I have deployed a fix to dev. 

To test: 

1. Flush the cache.
2. Add a new user email address using the Firebase console for the PxStat-Dev project.
3. Verify that the new user is added using Manage/Subscribers.
4. Flush the cache.
5. Remove the new user email address using the Firebase console for the PxStat-Dev project.
6. Verify that the new user is removed using Manage/Subscribers.
7. Verify that there are no Invalid users.

If you need any help adding and removing users using the Firebase console, please let me know.

**Comment by liamie** [comment]
No Invalid users showing now.
