### ISSUE TITLE
[BUG] Incorrect y-axis labels on charts

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#658]
In some cases, when a series in a chart has decimal places, the y-axis label is incorrect. 

![image](https://user-images.githubusercontent.com/53211688/194899646-d04ee60f-7894-4221-ada2-3dc0904a3372.png)

This images shows a value of 3.515 but it appears above a line on the y-axis with a label of 4

**Comment by liamie** [comment]
This seems to be correct now for decimals.
