### ISSUE TITLE
[BUG] Analytics CSV download showing incorrect headers

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#668]
Analytics CSV download showing database codes instead of labels

**Comment by damienderoistecso** [comment]
![image](https://user-images.githubusercontent.com/53211688/197145335-56553f10-cead-4332-bcbc-df9815bd2f09.png)

**Comment by liamie** [comment]
Columns now returned to previous with additional title added.

**Comment by neilfromcork** [comment]
Label field now has Label added, removed from code field
Ready for test in DEV
