### ISSUE TITLE
[BUG] Mail server unavailable issue

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#67]
**Describe the bug**
When the mail server is down, you can't progress the workflow

**Expected behavior**
Allow the workflow to continue even when the mail server is down

**Comment by neilfromcork** [comment]
Temporary fix in place to ignore mail issue if it occurs and complete the Request/Response/Rollback
@damienderoistecso

**Comment by lorenzobruni** [comment]
Complete fix will be deployed together with the changes required for the parent bug https://github.com/CSOIreland/PxStat/issues/72

**Keep this bug open until the parent bug is resolved.**

**Comment by lorenzobruni** [comment]
@JohnPCarroll can you please test this one ASAP? Thanks

**Comment by JohnPCarroll** [comment]
Test successful
