### ISSUE TITLE
[ENHANCEMENT] Change Server-Side entity ReleaseAudit to TableAudit

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#679]
* Change the Entity name `ReleaseAudit` to `TableAudit ` for consistency with Client-Side interface.
* Change the DB Stored Procedure `Report_Release_Audit.sql` to `Report_TableAudit.sql`

**Comment by damiancosmoschapman** [comment]
Server side is completed now. Client side needs to be completed before testing. Assigning to @CHanamy57 to complete client side.

**Comment by CHanamy57** [comment]
Client side change completed - ready for test
