### ISSUE TITLE
[BUG] Buttons note resetting post Map viewing

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#68]
**Describe the bug**
When you view a map relating to a table and select the Data buttons the codes Reset and View all buttons are incorrectly displayed
**To Reproduce**
Used Table NEA06

**Expected behavior**
Buttons should default to correct position before map button selected

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test passed
