### ISSUE TITLE
[ENHANCEMENT] Update TITLE property in PX file to include more information

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#682]
For example, in Statistics Sweden there is a matrix NV1701AF 
[NV1701AF.txt](https://github.com/CSOIreland/PxStat/files/10033381/NV1701AF.txt)

This file has the properties:

TITLE="Number of establishments by region, type of establishment and year";
CONTENTS="Number of establishments";
HEADING="year";
VALUES("region")="Greater Stockholm";
VALUES("type of establishment")="Hotels";

where TITLE is a combination of the CONTENT, VALUES and HEADING properties which is more informative.

The TITLE property in the generated PX file in PxStat, at present, has the same value as the contents property i.e.

For NV1701AF:

TITLE="Number of establishments";
CONTENTS="Number of establishments";

The TITLE property would be more informative if it was:

TITLE="Number of establishments - region,type of establishment and year";

**Comment by damiancosmoschapman** [comment]
To test e.g.

dimensions: dim1, dim2 and year
year values are 2018 and 2022
CONTENTS="This is a test"

The title would be:

TITLE="This is a test - dim1,dim2 and year - 2018,2022"

**Comment by liamie** [comment]
Layout seems correct as per new start and end years description rather than individual years chosen.
