### ISSUE TITLE
[ENHANCEMENT] Classification / Variable ordering is lost on Build Create

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#69]
If a dataset is created from Build, the output PX orders the classifications and variables by code. The user should be allowed to preserve the required classification/variable order. (From Digital Comms)

**Comment by neilfromcork** [comment]
Implemented  in DEV, for retest

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test successful
