### ISSUE TITLE
[SECURITY] 

### ISSUE THREAD

**Issue by frzyb** [CSOIreland/PxStat#698]
**Describe the vulnerability**
A clear and concise description of what the vulnerability is.

**N.B.** Do no report or attach sensitive information such as `password` or `IP address`. Mask any sensitive information in the attachments. Any sensitive information can be shared in private following the initial report.

**Tiers affected**
Identify (if possible) the specific tier affected by the vulnerability:
- Client
- Server
- Cache
- DB

**Comment by liamie** [comment]
No details provided.
