### ISSUE TITLE
[ENHANCEMENT] Enhance JSON-stat collection to include metadata

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#7]
**Is your feature request related to a problem? Please describe.**
Add metadata to collection to differentiate similar table titles.

**Describe the solution you'd like**
Collection will display metadata and the latest releases table will display dimension pills.

**Comment by neilfromcork** [comment]
Collection object updated in the API. Ready for test

**Comment by damienderoistecso** [comment]
Updated datatable to include metadata

**Comment by damienderoistecso** [comment]
Fixed bug with delete all

**Comment by damienderoistecso** [comment]
@neilfromcork please review order of classifications to match search results

**Comment by neilfromcork** [comment]
This is not a Collections issue. New issue raised #29
