### ISSUE TITLE
[ENHANCEMENT] Update regex for matrix name

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#702]
At present the application will only allow alphanumeric characters for a matrix name.

Some statistical organizations use underscores in their matrix names. 
This enhancement will change the regex to also allow underscore characters in matrix names

**Comment by liamie** [comment]
Underscores can now be used in matrix names.

**Comment by liamie** [comment]
Regex resolved. Matrix name blocked at initial build/create and import now
