### ISSUE TITLE
[BUG] JSON-RPC Invalid Schema

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#72]
The present JSON-RPC schema refers to the wrong `data` property rather than `result`.
Also, the `error.data` should be available for extensive error notification. 

This bug can be fixed across Client and Server code following the closure of the parent bug https://github.com/CSOIreland/Server-API-Library/issues/1 under the **Server-Side-Library** repository.

#### Please note this issue must be resolved in isolation, under his own milestone.

**Comment by lorenzobruni** [comment]
Entities to regression-test:
* **Navigation Bar** 
* **Data**

**Comment by JohnPCarroll** [comment]
Navigation bar failure
![image](https://user-images.githubusercontent.com/44975474/73921652-a7d61500-48bf-11ea-8d28-7d1e42c7e24a.png)

**Comment by neilfromcork** [comment]
Change made to Matrix_API for this issue

**Comment by JohnPCarroll** [comment]
Map option failure. When map selected no map shown and goes into a loop
![image](https://user-images.githubusercontent.com/44975474/73922460-19fb2980-48c1-11ea-9301-2e043db8c922.png)

**Comment by lorenzobruni** [comment]
> Navigation bar failure
> ![image](https://user-images.githubusercontent.com/44975474/73921652-a7d61500-48bf-11ea-8d28-7d1e42c7e24a.png)

@JohnPCarroll FIXED

**Comment by lorenzobruni** [comment]
> Map option failure. When map selected no map shown and goes into a loop
> ![image](https://user-images.githubusercontent.com/44975474/73922460-19fb2980-48c1-11ea-9301-2e043db8c922.png)

@JohnPCarroll FIXED

**Comment by liamie** [comment]
> Entities to regression-test:
> 
> * **Navigation Bar**
> * **Data**

Passed

**Comment by JohnPCarroll** [comment]
Test passed for Navigation bar and Data

**Comment by lorenzobruni** [comment]
Entities to regression-test:
* **Analytic**

**Comment by JohnPCarroll** [comment]
Unable to Download a PNG Image
![image](https://user-images.githubusercontent.com/44975474/73926573-c3ddb480-48c7-11ea-86db-aa87eb219138.png)

**Comment by liamie** [comment]
> Entities to regression-test:
> 
> * **Analytic**

![image](https://user-images.githubusercontent.com/55874862/73926570-c3451e00-48c7-11ea-875b-7a72f6ea6d40.png)
 when trying to view fullscreen of table language chart

**Comment by JohnPCarroll** [comment]
if you select "print chart" and cancel the requests an error occurs
![image](https://user-images.githubusercontent.com/44975474/73926864-41a1c000-48c8-11ea-835d-5ddd5035ffb1.png)

**Comment by JohnPCarroll** [comment]
If you select print an error occurs
![image](https://user-images.githubusercontent.com/44975474/73927086-a6f5b100-48c8-11ea-884a-c813383c269c.png)

**Comment by lorenzobruni** [comment]
@JohnPCarroll and @liamie 
All the issues reported above about the **Analytic** entity  were generated by the same problem.
Can you please update, reload the application (Ctrl + F5) and test it again? Thanks

FYI, we also upgrade to HighCharts version 8.0.0 (latest stable).

**Comment by JohnPCarroll** [comment]
Test passed for the **Analytic** entity issues in relation to the download and print options noted above

**Comment by liamie** [comment]
> Entities to regression-test:
> 
> * **Analytic**

![image](https://user-images.githubusercontent.com/55874862/73944761-0795e580-48eb-11ea-964a-d22df1faf1c2.png)

when using three dots to print or right click and print

**Comment by liamie** [comment]
> Entities to regression-test:
> 
> * **Analytic**
![image](https://user-images.githubusercontent.com/55874862/73946494-ea164b00-48ed-11ea-9e5a-8412a93fb873.png)

debugger left

**Comment by lorenzobruni** [comment]
> > Entities to regression-test:
> > 
> > * **Analytic**
> >   ![image](https://user-images.githubusercontent.com/55874862/73946494-ea164b00-48ed-11ea-9e5a-8412a93fb873.png)
> 
> debugger left

FIXED

**Comment by lorenzobruni** [comment]
> > Entities to regression-test:
> > 
> > * **Analytic**
> 
> ![image](https://user-images.githubusercontent.com/55874862/73944761-0795e580-48eb-11ea-964a-d22df1faf1c2.png)
> 
> when using three dots to print or right click and print

FIXED (FYI, this was a Chrome related bug... but it should look fine now)

**Comment by liamie** [comment]
> > Entities to regression-test:
> > 
> > * **Analytic**
> 
> ![image](https://user-images.githubusercontent.com/55874862/73944761-0795e580-48eb-11ea-964a-d22df1faf1c2.png)
> 
> when using three dots to print or right click and print

This no longer produces error

**Comment by liamie** [comment]
> Entities to regression-test:
> 
> * **Analytic**

Passed

**Comment by lorenzobruni** [comment]
Entities to regression-test:
* **Dashboard**

**Comment by liamie** [comment]
> Entities to regression-test:
> 
> * **Dashboard**
on dashboard page load
![image](https://user-images.githubusercontent.com/55874862/73957041-b5aa8b00-48fd-11ea-9d60-d5c16b463014.png)

**Comment by liamie** [comment]
No releases appearing in live releases and detached from rest of collapseable modals

![image](https://user-images.githubusercontent.com/55874862/73957542-64e76200-48fe-11ea-978b-2080038387c7.png)

**Comment by lorenzobruni** [comment]
> > Entities to regression-test:
> > 
> > * **Dashboard**
> >   on dashboard page load
> >   ![image](https://user-images.githubusercontent.com/55874862/73957041-b5aa8b00-48fd-11ea-9d60-d5c16b463014.png)

FIXED

**Comment by lorenzobruni** [comment]
> No releases appearing in live releases and detached from rest of collapseable modals
> 
> ![image](https://user-images.githubusercontent.com/55874862/73957542-64e76200-48fe-11ea-978b-2080038387c7.png)

FIXED

**Comment by JohnPCarroll** [comment]
error with analytics link in live release section
![image](https://user-images.githubusercontent.com/44975474/73959146-d7f1d800-4900-11ea-9526-64a651fd2435.png)

**Comment by lorenzobruni** [comment]
> error with analytics link in live release section
> ![image](https://user-images.githubusercontent.com/44975474/73959146-d7f1d800-4900-11ea-9526-64a651fd2435.png)

FIXED

**Comment by JohnPCarroll** [comment]
Test passed for error with analytics link in live release section

**Comment by lorenzobruni** [comment]
Entity ready to regress-test
* **Release**

**Comment by liamie** [comment]
> Entities to regression-test:
> 
> * **Dashboard**
Passed

**Comment by liamie** [comment]
> Entity ready to regress-test
> 
> * **Release**

![image](https://user-images.githubusercontent.com/55874862/73961181-0329f680-4904-11ea-8630-75a66f66f297.png)

clicking on a table in main window after search
or on table in right hand panels

**Comment by JohnPCarroll** [comment]
Configuration Reason - update fails
![image](https://user-images.githubusercontent.com/44975474/74037694-b8b58200-49b6-11ea-8f88-d58885f708cf.png)

**Comment by JohnPCarroll** [comment]
Configuration Language - Update link to display popup page not working
![image](https://user-images.githubusercontent.com/44975474/74038032-632da500-49b7-11ea-8ac1-42f24c7ddd6c.png)

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/74038018-5e68f100-49b7-11ea-9b24-f0e7d2cabcc6.png)

Languages when click on a language iso code on left column

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/74038782-9de40d00-49b8-11ea-8a58-0ff79b9a26e1.png)

when adding a reason with same ID as previous maybe unrelated but should be more informative then just error

**Comment by lorenzobruni** [comment]
RELEASE + CONFIGURATION entities fixed.
Can you please give another round of testing?

Thanks

**Comment by JohnPCarroll** [comment]
Test passed for all Configuration entities

**Comment by JohnPCarroll** [comment]
Test failed for Release entity. Source window missing

**Comment by lorenzobruni** [comment]
> Test failed for Release entity. Source window missing

Release - Source FIXED
Please retest.

**Comment by JohnPCarroll** [comment]
Test failed for Release entity source window. The Compare button is not active if wip and live version exist. The came applies to live and historical or any other combinations

**Comment by lorenzobruni** [comment]
> Test failed for Release entity source window. The Compare button is not active if wip and live version exist. The came applies to live and historical or any other combinations

Fixed, please retest.

**Comment by liamie** [comment]
> > Test failed for Release entity source window. The Compare button is not active if wip and live version exist. The came applies to live and historical or any other combinations
> 
> Fixed, please retest.

Button now clickable

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/74346754-f3992a80-4da7-11ea-91e8-af0269794c3f.png)

when download csv and when close the download status bar

**Comment by JohnPCarroll** [comment]
Test passed for Compare button on Source window of Release Entity.
Tested Wip V Live, Wip V historical, Live V Histrical and Historical V Historical

**Comment by lorenzobruni** [comment]
All the Entities in the **Manage** section are ready to test. Thanks

**Comment by liamie** [comment]
> All the Entities in the **Manage** section are ready to test. Thanks

![image](https://user-images.githubusercontent.com/55874862/74352742-dc126f80-4db0-11ea-8ba5-e2c12d49a1b2.png)

clicking Add Member button on groups page.
Pop up does not appear

**Comment by liamie** [comment]
> All the Entities in the **Manage** section are ready to test. Thanks

![image](https://user-images.githubusercontent.com/55874862/74353704-38c25a00-4db2-11ea-99e4-dccddac40c2d.png)

when trying to Edit an existing Group in Manage>Groups

**Comment by lorenzobruni** [comment]
> > All the Entities in the **Manage** section are ready to test. Thanks
> 
> ![image](https://user-images.githubusercontent.com/55874862/74352742-dc126f80-4db0-11ea-8ba5-e2c12d49a1b2.png)
> 
> clicking Add Member button on Manage>Groups page.
> Pop up does not appear

FIXED ready to retest

**Comment by liamie** [comment]
> > > All the Entities in the **Manage** section are ready to test. Thanks
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/55874862/74352742-dc126f80-4db0-11ea-8ba5-e2c12d49a1b2.png)
> > clicking Add Member button on Manage>Groups page.
> > Pop up does not appear
> 
> FIXED ready to retest

Popup now appears however

![image](https://user-images.githubusercontent.com/55874862/74360341-c99e3300-4dbc-11ea-8817-56d12d61e321.png)

occurs when trying to add a user that already exists.
And screen locks and fades out with the below error behind 
![image](https://user-images.githubusercontent.com/55874862/74360513-1c77ea80-4dbd-11ea-8f6c-fa6c1534543b.png)

**Comment by liamie** [comment]
> > > > All the Entities in the **Manage** section are ready to test. Thanks
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/55874862/74352742-dc126f80-4db0-11ea-8ba5-e2c12d49a1b2.png)
> > > clicking Add Member button on Manage>Groups page.
> > > Pop up does not appear
> > 
> > 
> > FIXED ready to retest
> 
> Popup now appears correctly however
> 
> ![image](https://user-images.githubusercontent.com/55874862/74360341-c99e3300-4dbc-11ea-8817-56d12d61e321.png)
> 
> occurs when trying to add a user that already exists.
> And screen locks and fades out with the below error behind
> ![image](https://user-images.githubusercontent.com/55874862/74360513-1c77ea80-4dbd-11ea-8f6c-fa6c1534543b.png)

Error now appearing correctly and can close
![image](https://user-images.githubusercontent.com/55874862/74362486-b68d6200-4dc0-11ea-9ca1-0048bfd84d6e.png)

**Comment by lorenzobruni** [comment]
## Nothing outstanding from here before.
Testing of the Menage entities still in progress...

**Comment by neilfromcork** [comment]
Validation fail on Group Update has been fixed. Please retest.   @liamie , @JohnPCarroll

**Comment by liamie** [comment]
> Validation fail on Group Update has been fixed. Please retest. @liamie , @JohnPCarroll

Update in line with create now. All good.

**Comment by JohnPCarroll** [comment]
Test passed for group update

**Comment by lorenzobruni** [comment]
Are all the entities under **MANAGE** cleared?
Just double checking before moving to the next one. Thanks!

**Comment by lorenzobruni** [comment]
All entities under **Keyword** ready to re-test.

**Comment by liamie** [comment]
> Are all the entities under **MANAGE** cleared?
> Just double checking before moving to the next one. Thanks!

Yes

**Comment by liamie** [comment]
> All entities under **Keyword** ready to re-test.

Seems Correct

**Comment by lorenzobruni** [comment]
Error modal enhanced with Copy to Clipboard.
Please test.
![image](https://user-images.githubusercontent.com/53212047/74522267-c87f1a00-4f12-11ea-986a-86750b417fd1.png)

**Comment by liamie** [comment]
> Error modal enhanced with Copy to Clipboard.
> Please test.
> ![image](https://user-images.githubusercontent.com/53212047/74522267-c87f1a00-4f12-11ea-986a-86750b417fd1.png)

Copy to clipboard is appearing and works when paste to notepad

**Comment by lorenzobruni** [comment]
All entities under **Build** ready to test.

**Comment by liamie** [comment]
> Error modal enhanced with Copy to Clipboard.
> Please test.
> ![image](https://user-images.githubusercontent.com/53212047/74522267-c87f1a00-4f12-11ea-986a-86750b417fd1.png)

![image](https://user-images.githubusercontent.com/55874862/74550321-1dd61e00-4f49-11ea-8222-1782aee502d0.png)

when using Build>Create with multiple languages Click Create button

**Comment by lorenzobruni** [comment]
> > Error modal enhanced with Copy to Clipboard.
> > Please test.
> > ![image](https://user-images.githubusercontent.com/53212047/74522267-c87f1a00-4f12-11ea-986a-86750b417fd1.png)
> 
> ![image](https://user-images.githubusercontent.com/55874862/74550321-1dd61e00-4f49-11ea-8222-1782aee502d0.png)
> 
> when using Build>Create with multiple languages Dimensions section Click Create button
> Won't allow to copy to clipboard

Problems fixed, please re-test?

**Comment by JohnPCarroll** [comment]
Test passed for all Keywords options - Subjects, Products and Releases

**Comment by JohnPCarroll** [comment]
Build/ Create Option. Should the language be stated in the Confirm deletions messages instead of the language code ? 
![image](https://user-images.githubusercontent.com/44975474/74643000-eb583b00-516b-11ea-9e26-e72abc80ed43.png)

**Comment by JohnPCarroll** [comment]
Build/Create Options -  Error downloading Templates
![image](https://user-images.githubusercontent.com/44975474/74643650-fc557c00-516c-11ea-8b31-2a905f3540ea.png)

**Comment by JohnPCarroll** [comment]
Build/Create Options - Imported duel language table and added Classification for English only. No error messages displayed
![image](https://user-images.githubusercontent.com/44975474/74645612-2a888b00-5170-11ea-8e54-de0fd148c340.png)

**Comment by JohnPCarroll** [comment]
Build Update option - Same download template errors as Create option

**Comment by lorenzobruni** [comment]
> Build/ Create Option. Should the language be stated in the Confirm deletions messages instead of the language code ?
> ![image](https://user-images.githubusercontent.com/44975474/74643000-eb583b00-516b-11ea-9e26-e72abc80ed43.png)

Fixed, ready to retest

**Comment by lorenzobruni** [comment]
> Build/Create Options - Imported duel language table and added Classification for English only. No error messages displayed
> ![image](https://user-images.githubusercontent.com/44975474/74645612-2a888b00-5170-11ea-8e54-de0fd148c340.png)

Fixed, please retest

**Comment by JohnPCarroll** [comment]
Test passed for Build/Create Option in relation to adding Classification for English only on Duel Language Table

**Comment by JohnPCarroll** [comment]
Email Error sometimes.
This happens if you update an alert and then access the email option
![image](https://user-images.githubusercontent.com/44975474/74728719-2c6b5080-523b-11ea-9e5a-aaa5fbd1f6d1.png)

**Comment by JohnPCarroll** [comment]
Test passed for Build/ Create Option. Language now stated in the Confirm deletions messages

**Comment by JohnPCarroll** [comment]
Build/ Create import option. Error deleting time Periods.
![image](https://user-images.githubusercontent.com/44975474/74733765-ee732a00-5244-11ea-82a0-4c49d7604bba.png)

**Comment by lorenzobruni** [comment]
> Build/ Create import option. Error deleting time Periods.
> ![image](https://user-images.githubusercontent.com/44975474/74733765-ee732a00-5244-11ea-82a0-4c49d7604bba.png)

Fixed. Please note to retest also the results into the Comparison.

**Comment by lorenzobruni** [comment]
Test passed by @JohnPCarroll
