### ISSUE TITLE
[BUG] Footnote containing line breaks looses the line breaks when the Matrix is updated

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#733]
**To Reproduce**
Do a Build/Import and the Footnote line breaks are not preserved.

**Expected behavior**
The line breaks should not be removed

**Comment by damiancosmoschapman** [comment]
To test use

[CPM15_31_1_20230216T150254.txt](https://github.com/CSOIreland/PxStat/files/10758216/CPM15_31_1_20230216T150254.txt)

Do a Build/Import and the Footnote should preserve the line breaks.

**Comment by damiancosmoschapman** [comment]
Reopening as still reproducible in 5.5.0 production

**Comment by liamie** [comment]
Works now as described. Pre and post line breaks to the  main note body are trimmed automatically by build create/update.
