### ISSUE TITLE
Analytics title appearance [BUG] 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#74]
Analytics appearance
hits title displaying as [hits-over-time] in brackets on popup details screen

After choosing a table by double clicking on the Analytics screen, on the screen that pops up

**Screenshots**
![image](https://user-images.githubusercontent.com/55874862/73956065-4bddb180-48fc-11ea-9f56-9217ca35a084.png)

**Comment by damienderoistecso** [comment]
@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test passed
