### ISSUE TITLE
[ENHANCEMENT] Update the ReleaseProduct APIs to associate a Product with a Release that doesn't have a core Product already

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#742]

**Comment by damiancosmoschapman** [comment]
Changes to Associated tables APIs to not check for a Product to be associated with a Release

1. PxStat.Data.ReleaseProductAssociation_API.Create to asscoiate a Release with a Product without the Release having a core Product

2. PxStat.System.Navigation.Product_API.Delete to not delete a Product if it has Associated Tables

3. PxStat.System.Navigation.Product_API.Read - Add MtrAssociatedCount to response

4. PxStat.Data.Matrix_API.ReadByProduct - Add optional parameter to read Associated Tables i.e. bool AssociatedOnly

5. PxStat.System.Navigation.Navigation_API.Read - Add live Associated Tables in the PrcReleaseCount to response

**Comment by lorenzobruni** [comment]
Implemented and tested
