### ISSUE TITLE
Official Statistics symbol not ordering [BUG] 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#75]
**Describe the bug**
Official Statistics symbol not ordering in Dashboard -> Live releases

**To Reproduce**
1. Dashboard -> Live releases
2. Click on arrows for ordering on Official Statistics column

No order changed

**Expected behavior**
Expected different symbols to order differently

![image](https://user-images.githubusercontent.com/55874862/73960100-34a1c280-4902-11ea-9efa-2d4e5f9eba09.png)

**Comment by damienderoistecso** [comment]
Update column to type: "natural",
@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test Passed
