### ISSUE TITLE
[ENHANCEMENT] Add period sorting to PxStat Build Import, Create and Update

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#750]
1. Build update - new periods, already sorting - (Nothing to change)

2. Build update - no new periods no sorting currently - (C# should sort periods)

3. Build create - no sorting - (C# should sort periods)

4. Build import - no sorting - (C# should sort periods)

5. Output generation - no sorting - (Nothing to change)

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test
