### ISSUE TITLE
[BUG] API can be used to set a non existing product to release even if live which can leave null product and affect navigation

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#753]
**Describe the bug**
PxStat.Data.Release_API.UpdateProduct
API can be used to set a non existing product to release even if live which can leave null product and affect navigation and make subject/product not set
**To Reproduce**
1. Use the  PxStat.Data.Release_API.UpdateProduct api  but replace PrcCode with an ID that does not exist
2. Success message appears. This should not be the case

**Expected behavior**
Protect from adding a nonexistent product 

**Screenshots**
in release page (on dev)
<img width="361" alt="liveprodnotset" src="https://user-images.githubusercontent.com/55874862/234635343-b9ed4d2c-6f1c-46be-be49-5f96cb0e4c94.PNG">

in front tble data (on dev)
<img width="376" alt="missingprod" src="https://user-images.githubusercontent.com/55874862/234637685-59aa4ea9-2442-4559-89f2-14e8a9de0967.PNG">

Additional
an invalid release code in same API results in a null pointer exception.

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by liamie** [comment]
Application error now thrown correctly and unchanged if invalid
