### ISSUE TITLE
[ENHANCEMENT] Create the option of PxAPIv1 Get Url with fluid time

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#754]
Extend the PxAPIv1 to handle fluid time. Allow users option of selecting specific time points, top time points or fluid time points. Fluid time points refers to specific positions in the time dimension.

**Comment by neilfromcork** [comment]
Server side complete

**Comment by neilfromcork** [comment]
Amended server side to allow no query and empty variables
