### ISSUE TITLE
[BUG] Fix output of APIs error message when the APIs throw a Format exception

### ISSUE THREAD

**Issue by damiancosmoschapman** [CSOIreland/PxStat#757]
**Describe the bug**
At present when the APIs throw a format exception it logs the format exception message but it does not return the format message to the API but a generic message instead i.e. "API Schema violated. Please review the syntax of your API request.

**To Reproduce**
1. Rename [MAN05101.txt](https://github.com/CSOIreland/PxStat/files/11344605/MAN05101.txt) from .txt to .px
2. Add 
SOURCE="Statistics Iceland"
3. Import the PX file
4. The API returns the error: API Schema violated. Please review the syntax of your API request.

**Expected behavior**
The API should return the more descriptive error: PX Schema: the keyword "SOURCE" has not been found for the language "en".
**Screenshots**

**Additional context**

**Comment by liamie** [comment]
Correct error being returned now.
