### ISSUE TITLE
[BUG] In workflow, the cache gets flushed before the database transaction is committed which can cause cache issues

### ISSUE THREAD

**Issue by damianCosmos** [CSOIreland/PxStat#763]
**Describe the bug**
The issue can be caused by an API, to read the dataset, being called, between when the cache is flushed and the workflow database transaction in progress, but has not been committed yet. This can cause the cache to have an incorrect time to live for the dataset which can impact the release date of the dataset.

This is very difficult to test and it is probably best to test by verifying that all of the existing workflow functionality still works as expected.

**Comment by liamie** [comment]
Workflows appear to be unaffected
