### ISSUE TITLE
Language Option on Listing Page

### ISSUE THREAD

**Issue by Elainehoward** [CSOIreland/PxStat#764]
Hi all,

There is only one language option showing up on the listing page when two options (English & Irish) available.
![bug](https://github.com/CSOIreland/PxStat/assets/59655582/fe88dcb4-563b-4ac5-ad9b-0dc4be61ffa3)

Can you have a look at this? 

Thanks
Elaine

**Comment by neilfromcork** [comment]
A list of datasets per language could be done as a report rather than on the core application
