### ISSUE TITLE
[BUG] If a dual language matrix is favourited double entries are put into the favourite  table list

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#767]
**Describe the bug**
If a dual language matrix is favourited double entries are put into the favourite  table list

**To Reproduce**
1. Go to a matrix with multiple languages
2. Click on add to favourites
3. See error

**Expected behavior**
Only one entry per Matrix

**Screenshots**
![image](https://github.com/CSOIreland/PxStat/assets/55874862/2bac3929-e475-4c74-a207-9ea032b9decf)

**Additional context**

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test
