### ISSUE TITLE
[BUG] Contact details update

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#77]
**Describe the bug**
If group details are updated, the cached JSONstat data does not get updated.

**Expected behavior**
When you update a group, any matrix associated with that group gets it's cache flushed

**Comment by neilfromcork** [comment]
Fixed in dev - for retest

**Comment by lorenzobruni** [comment]
The RegEx for the Contact Phone has been fixed as well. 
`^(\(\+\d{1,3}\) \d+ \d+ \d+)$`

**Comment by lorenzobruni** [comment]
Test passed on behalf of @JohnPCarroll
