### ISSUE TITLE
[ENHANCEMENT]  Threshold warning for map creation

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#778]
**Is your feature request related to a problem? Please describe.**
 Threshold warning for map creation to waarn user if the geomap is a large size

**Describe the solution you'd like**
A clear warning message to the user to inform them

**Comment by CHanamy57** [comment]
Enhancement made in dev:
Warning message suggesting to simplify GeoJSON file appears when attempting to upload file over 3MB.

**Comment by liamie** [comment]
Threshold message appears now.
Note: Can be size issues in browser before reaching threshold test if file is very large.
