### ISSUE TITLE
[ENHANCEMENT] Analytics performance improvements  

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#779]
**Is your feature request related to a problem? Please describe.**
 Analytics performance improvements to enhance the speed and functionality of the analytics

**Describe the solution you'd like**
Modifications to the date pickers and dashboard api calls to facilitate the analytics improvements

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test

**Comment by neilfromcork** [comment]
Fixed in TEST
