### ISSUE TITLE
[BUG] Geo role in JSONstat

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#78]
**Describe the bug**
Geo role in JSONstat contains dimension label instead of code

**Expected behavior**
Geo role should contain code

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/53211688/74045198-3e8bfa00-49c4-11ea-8cb6-09f18331f26f.png)

**Comment by neilfromcork** [comment]
Fixed in dev @damienderoistecso

**Comment by JohnPCarroll** [comment]
Test Passed

**Comment by neilfromcork** [comment]
Client side may need to be checked.

**Comment by damienderoistecso** [comment]
Updated create-update to read new JSON-stat

@JohnPCarroll ready for testing

**Comment by JohnPCarroll** [comment]
Test passed
