### ISSUE TITLE
[BUG] Rollback of live causes rolled back release to stay live

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#79]
**Describe the bug**
Rollback of live causes rolled back release to stay live

**To Reproduce**
1.Rollback live to historical

**Expected behavior**
Rolled back release goes to WIP, historical goes to live

**Comment by neilfromcork** [comment]
Fix in dev - for retest

**Comment by JohnPCarroll** [comment]
Test passed for rolling back live. The Historical goes live and the live is Work in progress. 
A further issue arises in this situation.
1. You start with a Live and two historical.
2. You rollback the live and you now have one work in progress, one live and one historical.
3. You then rollback the live and you end up with two work in progress and one live. This is incorrect You should end up with one work in progress and one live.

**Comment by neilfromcork** [comment]
Modified in DEV to fix the double rollback case. If a live is rolled back then any subsequent WIP is deleted. For retest @JohnPCarroll

**Comment by JohnPCarroll** [comment]
Test passed
