### ISSUE TITLE
[ENHANCEMENT] Make link to WIP widgets queries fixed to selected variables

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#797]
When you create a widget from a WIP and you select all variables from a dimension, if the dataset gets updates with new variable, the widget automatically gets this new variable.

This is not ideal when you want a "point in time" widget so now the variables regardless of how many are selected in each dimension will be be explicitly asked for in the query.

**Comment by liamie** [comment]
all time points are individually listed
