### ISSUE TITLE
[ENHANCEMENT] Define Modals for Printing in Isolation

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#80]
Define Modals for Printing in Isolation

**Comment by lorenzobruni** [comment]
When printing a page with an active Modal, everything grayed-out in the background WILL NOT be printed. 
This apply across all system.

See example of an active Modal.

![image](https://user-images.githubusercontent.com/53212047/77116345-f4b51b80-6a27-11ea-9f23-b5ab3d6dac16.png)

See example of the print preview of the active Modal.

![image](https://user-images.githubusercontent.com/53212047/77116466-262de700-6a28-11ea-8f1a-a95746a2d2e5.png)

**Comment by damienderoistecso** [comment]
@JohnPCarroll @liamie ready for testing.

**Comment by liamie** [comment]
@damienderoistecso error and confirmation messages appear as blank sheet only not the contents of modal

**Comment by damienderoistecso** [comment]
@liamie code update so now if api modals are launched, the page prints as normal. If app modals are launched, they are printed in isolation as if they were a separate page
