### ISSUE TITLE
[BUG] Downloaded pivot xlsx variables sorted alphabetically

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#800]
Where a field has a "LABEL" text added to it and is part of a pivot, the variables of that dimension are sorted alphabetically rather than by dimension order in the downloaded xlsx pivot table.

**Comment by neilfromcork** [comment]
Fix deployed to TEST

**Comment by neilfromcork** [comment]
Fix deployed to TEST

**Comment by liamie** [comment]
Variables no longer sorted alphabetically
