### ISSUE TITLE
[BUG] Browse/Search by product limited to 100 entries but number of Matrixes in products can exceed this

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#802]
**Describe the bug**
Browse/Search by product limited to 100 entries but number of Matrixes in products can exceed this

**To Reproduce**
1. Go to '.Browse on left hand side'
2. Click on 'Census > Census 2022 > [Summary Results]     (https://data.cso.ie/product/C2022SR)
3.  Only 100 matrix shown even though 120 listed 

**Expected behavior**
All shown for that product without limit including associated tables

**Additional context**
Also affects direct linking to products and using the breadcrumb

**Comment by neilfromcork** [comment]
Fixed in TEST

**Comment by liamie** [comment]
Seems corrected now
