### ISSUE TITLE
Downloading on the Comparison Report Screen

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#81]
![image](https://user-images.githubusercontent.com/55874862/74346754-f3992a80-4da7-11ea-91e8-af0269794c3f.png)

on Comparison Report screen when download csv intermittently and when close the download status bar

_Originally posted by @liamie in https://github.com/CSOIreland/PxStat/issues/72#issuecomment-585245369_

**Comment by liamie** [comment]
> ![image](https://user-images.githubusercontent.com/55874862/74346754-f3992a80-4da7-11ea-91e8-af0269794c3f.png)
> 
> on Comparison Report screen when download csv intermittently and when close the download status bar
> 
> _Originally posted by @liamie in [#72 (comment)](https://github.com/CSOIreland/PxStat/issues/72#issuecomment-585245369)_

Same problem also occurs on Manage > Tracing

![image](https://user-images.githubusercontent.com/55874862/74355791-38778e00-4db5-11ea-8fe8-e9f5f3f6c0b6.png)

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/74518912-936fc900-4f0c-11ea-84c6-9bfbc3dc21da.png)

Same problem occurs if try to download results button on View Data screen or the  large selection confirm message.
![image](https://user-images.githubusercontent.com/55874862/74519130-1133d480-4f0d-11ea-93b3-5938a297982c.png)

**Comment by liamie** [comment]
![image](https://user-images.githubusercontent.com/55874862/74545870-84efd480-4f41-11ea-9818-5a69ac37f374.png)

Also occurs on Build>Update buttons at bottom after loading a px file

                         Download CSV Template
                         Download CSV Data
                         Update


Seems to be to do with the tray (becomes tab if you use show all button) created by downloading as it is the first download to open tray and then reoccurs when tray is closed for all subsequent downloads.

**Comment by lorenzobruni** [comment]
Fixed, ready to test

**Comment by JohnPCarroll** [comment]
Test Passed
