### ISSUE TITLE
[BUG] Analytical flag not appearing on search result screens and in product listings 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#810]
**Describe the bug**
Analytical flag not appearing on search result screens and in product listings 

**To Reproduce**
1. Go to 'search'
2. Search by keyword 
3. See other symbols as appropriate

**Expected behavior**
Analytical symbol flag should appear where applicable similar to map, official statistic etc.

**Screenshots**
![image](https://github.com/CSOIreland/PxStat/assets/55874862/5f4278e6-af08-4807-96e5-857da5f10b73)

**Comment by neilfromcork** [comment]
Fixed in client dev
