### ISSUE TITLE
[BUG} For all Pyramid charts the x and y axis labels are being reversed.

### ISSUE THREAD

**Issue by DisseminationNI** [CSOIreland/PxStat#817]
For all chart type, Pyramid - the X and Y axis are reversed.

When the public are completing their desired options under the 'Chart' tab, type 'Pyramid' , it appears when you view your 
chart, the X and Y axis are not correct they have been reversed and show the opposite of what was chosen.

See links to screenshots below 

https://github.com/CSOIreland/PxStat/assets/90850128/fdab21f0-d009-4b8d-8cb9-80eedf3dd4c3
https://github.com/CSOIreland/PxStat/assets/90850128/7189c1b5-9240-4e6e-a63b-de193f49421f
https://github.com/CSOIreland/PxStat/assets/90850128/d8921200-9141-416d-ac0e-c9a94c1f0b70

**Comment by liamie** [comment]
X and Y axis are now correct
