### ISSUE TITLE
[BUG] Time Value not identifying latest year if data uploaded is in descending order 

### ISSUE THREAD

**Issue by DisseminationNI** [CSOIreland/PxStat#818]
If a file is uploaded in descending date order 
The summary displays correctly in the latest tables view 
![image](https://github.com/CSOIreland/PxStat/assets/90850128/bc28ad4e-20b7-4b43-b2d0-138d024db444)

but when you click into the table the time period is reversed

![image](https://github.com/CSOIreland/PxStat/assets/90850128/23d6d74c-31a0-4222-b7c9-fb8f78dc86ce)

This is resulting in any dashboards using the widget updating with the earliest years data instead of the latest

**Comment by liamie** [comment]
Time pill appears correct on tables now.
