### ISSUE TITLE
[BUG] Classification Pill order can shift on Last Updated Tables list depending on dates chosen

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#837]
**Describe the bug**
Classification Pill order can shift on Last Updated Tables list depending on dates chosen

**To Reproduce**
1. Go to data/home page from Last 7 days
2. Note pill order on tables listed 
3. Alter date to a custom date
4. See some pill orders may have shifted

**Expected behavior**
Classification pill order to remain consistent for a table regardless of date to align with matrix page once clicked into.

**Screenshots**
<img width="637" alt="pill order 1" src="https://github.com/CSOIreland/PxStat/assets/55874862/60e1871f-765d-40d6-984b-e180d5a9e7fa">
<img width="651" alt="pill order 2" src="https://github.com/CSOIreland/PxStat/assets/55874862/b0c71ab7-37d7-4656-8d13-5d4b43ea0c29">

Additional Context:
This seems to only occur on the last updated tables. Product page and individual Matrix page seem to remain consistent.

**Comment by neilfromcork** [comment]
Unable to reproduce

**Comment by liamie** [comment]
Closed unless can be reproduced may have been a timing/cache issue.
