### ISSUE TITLE
Can create or delete a language without the language list updating [BUG] 

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#84]
When you create or delete a language the drop down on top right does not update automatically

The language isn't on the dropdown until a refresh occurs.

This can lead to unexpected errors when you try to access some areas Releases and Configuration>Releases,  Manage>Alerts
with a language that was deleted but is still retained in the drop down

![image](https://user-images.githubusercontent.com/55874862/74524596-434a3400-4f17-11ea-9edb-4b27efca570d.png)

**Comment by lorenzobruni** [comment]
Languages are system settings defined at the root level by an Admin only.
Their change is reflecting globally, and refreshing the page of the Admin wont help other users who are logged in.

Also, deleting a Language is a critical Admin job, so this is not a common issue.

Thanks for reporting anyway :-)
