### ISSUE TITLE
[BUG] Filename incorrect when Source is downloaded

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#85]
When you are in the Release page and you select the "Download Source" button. The output created does not contain the table code.

**Comment by lorenzobruni** [comment]
Fixed

**Comment by JohnPCarroll** [comment]
Teat failed.
Output file now contains .px twice at the end eg  AHM04_2_0_20200128T140108.px.px
When downloaded elsewhere it is AHM04.20200218T090253.px

**Comment by lorenzobruni** [comment]
Fixed

**Comment by JohnPCarroll** [comment]
Test Passed
