### ISSUE TITLE
[BUG] Build/Update option. Title updated but not fully reflected in updated Px file

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#850]
**Describe the bug**
Build Update not updating content with title changes

**To Reproduce**
1. Go to build update 
2. Import a px file 
3. Change title 
4. Click Update file 
5.  Title and Description updated but content remains unchanged

**Expected behavior**
The DESCRIPTION, TITLE AND CONTENTS should all update

**Additional context**
Similar to
[BUG] Build/Update option. Title updated but not fully reflected in updated Px file #175

**Comment by neilfromcork** [comment]
Fixed in DEV - ready for test
