### ISSUE TITLE
[ENHANCEMENT] Sort results from various api's

### ISSUE THREAD

**Issue by damienderoistecso** [CSOIreland/PxStat#853]
Sort the results from the following api's 

"PxStat.System.Settings.Copyright_API.Read" by "CprValue" 

"PxStat.Data.GeoLayer_API.Read" by "GlrName"

"PxStat.Data.GeoMap_API.ReadCollection" by "GmpName"

Make copyright drop down in create/update select2

**Comment by neilfromcork** [comment]
Fixed in DEV, ready for test
