### ISSUE TITLE
[BUG] Build/Import option - Incorrect Auto Generation of Statistical Codes for Multi Language tables

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#86]
**Describe the bug**
Currently if a Table has one statistic the code is auto generated for each language. This code must be the same at the default language.

![image](https://user-images.githubusercontent.com/44975474/74726102-cbda1480-5236-11ea-98b0-beba07c41d9f.png)

[E3002.txt](https://github.com/CSOIreland/PxStat/files/4218569/E3002.txt)

**Comment by neilfromcork** [comment]
Fixed in dev. For retest.

**Comment by JohnPCarroll** [comment]
Test passed
