### ISSUE TITLE
[BUG] Email Error sometimes.

### ISSUE THREAD

**Issue by JohnPCarroll** [CSOIreland/PxStat#87]
Email Error sometimes.
This happens if you update an alert and then access the email option
![image](https://user-images.githubusercontent.com/44975474/74728719-2c6b5080-523b-11ea-9e5a-aaa5fbd1f6d1.png)

_Originally posted by @JohnPCarroll in https://github.com/CSOIreland/PxStat/issues/72#issuecomment-587395868_

**Comment by lorenzobruni** [comment]
@JohnPCarroll we have upgraded the TinyMCE library, can you please try again?
Thanks

**Comment by JohnPCarroll** [comment]
Test fails. 
If you add or update an alert all is OK. If you cancel an alert update the error occurs

**Comment by lorenzobruni** [comment]
Fixed by initiating the tinyMCE before running the form validation in the Email entity.
Test passed on behalf of @JohnPCarroll
