### ISSUE TITLE
[ENHANCEMENT] Add XLSX (Open Excel) output format

### ISSUE THREAD

**Issue by lorenzobruni** [CSOIreland/PxStat#91]
**Is your feature request related to a problem? Please describe.**
Allow to downlaod XLSX (Open Excel) output format

**Additional context**
Sample of Excel spreadsheet
[template.xlsx](https://github.com/CSOIreland/PxStat/files/4245651/template.xlsx)
 format (look&feel)

**Comment by neilfromcork** [comment]
Complete on server side

**Comment by lorenzobruni** [comment]
Release to Milestone 2.1.0 postponed. 
2.1.0.sql script is missing the XLSX 2007 format and the Datamodel.sql and Datamodel.xml still need to be amended.**

@neilfromcork can you please add the new format in the above 3 files for the next Milestone 2.2.0? Thanks

**Comment by neilfromcork** [comment]
Script changes complete for Datamodel.sql and 2.1.0.sql. Changes not required in Datamodel.xml?

**Comment by lorenzobruni** [comment]
@neilfromcork 
There is a list of static entries in the Datamodel.xml to update with the XLSX type and version under the TS_FORMAT table.
Could you find it? Thanks

**Comment by neilfromcork** [comment]
Done, check when convenient. XLSX entry added to datamodel.sql also.

**Comment by damienderoistecso** [comment]
@lorenzobruni ready for testing

**Comment by lorenzobruni** [comment]
script 2.2.0 and datamodel updated.
To be tested during deployment
