### ISSUE TITLE
[BUG] Large datasets hang in Build Update (NISRA) 

### ISSUE THREAD

**Issue by neilfromcork** [CSOIreland/PxStat#93]
**Describe the bug**
A Build Update of approx 88,000 records caused the system to hang

[MYESA.20200225T140225.px.txt](https://github.com/CSOIreland/PxStat/files/4275800/MYESA.20200225T140225.px.txt)

[MYESA.20200212T150201.template.csv.txt](https://github.com/CSOIreland/PxStat/files/4275802/MYESA.20200212T150201.template.csv.txt)

**Comment by neilfromcork** [comment]
Fixed -  ready for test in dev

**Comment by JohnPCarroll** [comment]
Test Passed
