### ISSUE TITLE
[BUG] If a file is sent to awaiting response is rejected the status returns to work in progress but no longer appears in either the dashboard or the right hand side of build

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#94]
**Describe the bug**
If a file is sent to awaiting response is rejected the status returns to work in progress but no longer appears in either the dashboard or the right hand side of build

**To Reproduce**
1. Upload a new table 
2. Request publish
3. Reject in awaiting response
4. No longer appears in either the awaiting response or work in progress lists

**Expected behavior**
When the status is reverted would expect to see in relevant list but it appears in none

**Comment by liamie** [comment]
Seems to also occur if awaiting signoff  is rejected.  Won't reappear on the lists until status is at least awaiting response

**Comment by neilfromcork** [comment]
Should be ok now - ready for retest

**Comment by liamie** [comment]
This seems correct now
