### ISSUE TITLE
[BUG] When upload a two language matrix the file appears twice in dashboard and work in progress panel

### ISSUE THREAD

**Issue by liamie** [CSOIreland/PxStat#98]
![image](https://user-images.githubusercontent.com/55874862/75994410-d95bf380-5ef2-11ea-8976-06630c972b30.png)

It is fine in the English environment language 
It appears twice in the Irish environment language

**Comment by neilfromcork** [comment]
Fix completed - for retest

**Comment by liamie** [comment]
This seems correct now one entry in Irish environment language also
